packages/nitro-protocol/contracts/ForceMove.sol, packages/nitro-protocol/test/contracts/ForceMove/forceMove.test.ts
While writing the TLA+ spec for the new protocol, I discovered that `forceMove` currently lets you overwrite existing challenges with the same turn number.
=> Fix force move

.circleci/config.yml
This combines the circleci four jobs into one job.
- `ensure-updated-lockfiles` was redundant, since the only step it ran, `yarn --frozen-lockfile`, is included in other jobs
- restoring the cache, and running `yarn --frozen-lockfile` takes about 40 seconds. So, combing the three remaining jobs into one job saves 80 seconds.
I don't see much benefit in having separate jobs for building, linting, and testing. If there's no benefit, we might as well save ourselves at least 160s per pull request (once on the PR, and once on the merge into master).
=> Faster circle runs

.circleci/config.yml
Subfolder `node_modules` were not being persisted across jobs which meant thing like `packages/*/node_modules/.bin/truffle` were not being found.
=> Persist subfolder node_modules inside workspace

packages/wallet/package.json, packages/wallet/src/utils/contract-utils.ts
With the #17 PR we made sure `yarn test:ci` passed, but `yarn test` is actually not passing. This is because the tests attempt to read from files which are not there at the moment.
=> Fix the 'yarn test' command in the wallet

packages/jest-gas-reporter/tsconfig.json, packages/nitro-protocol/tsconfig.json, packages/wallet/tsconfig.json
Gives us some nice features inside VS Code such as Jump To Source:
=> Use TypeScript references in wallet and nitro-protocol

yarn.lock
Apparently somewhere down the line, the latest merged PRs didn't commit the updated `yarn.lock`. This PR rectifies that.
=> [monorepo] Updates yarn.lock

renovate.json
Ignore yarn as the circleCI image doesn't have the latest version.
=> Ignore Yarn in Renovate

packages/wallet/bin/start-ganache.js, packages/wallet/src/contract-tests/test-utils.ts, packages/wallet/src/contract-tests/transactions.test.ts, packages/wallet/src/utils/contract-utils.ts
Gets etherlime working with the fixed `CHAIN_NETWORK_ID` and change `getLibraryAddress` to be a sync method.
This allows us to treat contract addresses as constants as we were before.
=> [Wallet] - Etherlime fixed network id

.circleci/config.yml, package.json, packages/jest-gas-reporter/package.json, packages/nitro-protocol/package.json
Since `packageA` is linked to `packageB` when `packageA` depends on `packageB`, some of the current build process is needed for tests to run in `packageA`. An example of this is the `wallet` package depending on `nitro-protocol`.
However, some of the build process is not needed to run tests, such as `build:webpack` in the `wallet` package. This script takes over 30s on my laptop. The goal of running `yarn build:webpack` in a circleci build is to make sure that the current changes don't break the app in a way not covered by our test suite.
This PR separates the build commands required by dependencies from commands building the project for production. The former go in `prepare`, and are run in the `prepare` job on circle. The latter go in `build:ci`, and go into the `build` job on circle. …
=> Separate build process in circle

packages/nitro-protocol/package.json, packages/nitro-protocol/tsconfig.json
This has been helpful for me while writing transactions tests.
~It also makes `nitro-protocol` only export `.ts` files.~
=> Add sourceMap to nitro-protocol

packages/nitro-protocol/src/index.ts, packages/nitro-protocol/src/transactions.ts, packages/nitro-protocol/test/src/transactions.test.ts, packages/wallet/src/contract-tests/test-utils.ts, packages/wallet/src/contract-tests/transactions.test.ts, packages/wallet/src/redux/protocols/dispute/responder/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/dispute/responder/reducer.ts, packages/wallet/src/utils/nitro-converter.ts, packages/wallet/src/utils/transaction-generator.ts
Gets the tests passing for `respondWithMoveTransaction` based transactions in `transactions.test.ts` and updates relevant reducers.
I reuse the `Commitment` object and make it an argument into the transaction generator for `respondWithMoveTransaction`.
=> Support respondWithMoveTransaction transactions

.circleci/config.yml, package.json
The `build` circle job never seems to be rate-limiting, so adding `yarn lint:ci` to it won't slow down the workflow, but will save ~20s of container time.
In addition, if `HEAD` was already lint-checked, I believe we only have to lint-check packages that have changed based on the staged changes.
=> Linting improvements

packages/nitro-protocol/contracts/AssetHolder.sol, packages/nitro-protocol/contracts/ERC20AssetHolder.sol, packages/nitro-protocol/contracts/ETHAssetHolder.sol, packages/nitro-protocol/contracts/Outcome.sol, packages/nitro-protocol/contracts/interfaces/IAssetHolder.sol, packages/nitro-protocol/contracts/test/TESTAssetHolder.sol, packages/nitro-protocol/docs/adjudicator/state-format.md, packages/nitro-protocol/docs/asset-holder/claim.md, packages/nitro-protocol/docs/asset-holder/deposit.md, packages/nitro-protocol/docs/asset-holder/outcomes.md, packages/nitro-protocol/docs/asset-holder/set-outcome.md, packages/nitro-protocol/docs/asset-holder/transfer.md, packages/nitro-protocol/test/contracts/AssetHolder/claimAll.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/isExternalDestination.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts, packages/nitro-protocol/test/contracts/examples/SingleAssetPayments/validTransition.test.ts, packages/nitro-protocol/test/test-helpers.ts
This PR attempts to reduce potential confusion around `address`, `channelId`, `ExternalAddress`. 
Since `address` is a core ethereum concept, let us no longer use that term to describe other data types.  This means no more `channel address` or `external address`.
A `destination` is the beneficiary of a channel stipulated in the outcome of a nitro channel. It can either be a `channelId` or an `ExternalDestination`. 
External destinations are converted back into `addresses` by AssetHolder contracts during payouts.
=> Replace External Address with External Destination

packages/nitro-protocol/contracts/AssetHolder.sol, packages/nitro-protocol/contracts/ERC20AssetHolder.sol, packages/nitro-protocol/contracts/ETHAssetHolder.sol, packages/nitro-protocol/contracts/Outcome.sol, packages/nitro-protocol/contracts/interfaces/IAssetHolder.sol, packages/nitro-protocol/contracts/test/TESTAssetHolder.sol, packages/nitro-protocol/docs/adjudicator/state-format.md, packages/nitro-protocol/docs/asset-holder/claim.md, packages/nitro-protocol/docs/asset-holder/deposit.md, packages/nitro-protocol/docs/asset-holder/outcomes.md, packages/nitro-protocol/docs/asset-holder/set-outcome.md, packages/nitro-protocol/docs/asset-holder/transfer.md, packages/nitro-protocol/test/contracts/AssetHolder/claimAll.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/isExternalAddress.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/isExternalDestination.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts, packages/nitro-protocol/test/contracts/examples/SingleAssetPayments/validTransition.test.ts, packages/nitro-protocol/test/test-helpers.ts, packages/wallet/src/contract-tests/transactions.test.ts, packages/wallet/src/utils/transaction-generator.ts
Addressing an inconsistency noticed in #175 (see https://github.com/statechannels/monorepo/pull/175#issuecomment-538711824).
=> Change padding of external addresses in AssetHolder to left-pad

packages/web3torrent/src/clients/web3torrent-client.ts, packages/web3torrent/src/components/torrent-info/TorrentInfo.tsx, packages/web3torrent/src/pages/download/Download.tsx, packages/web3torrent/src/types.ts
When merged, this PR will improve the magnet link parsing, and generation:
The sharing link will now have this structure (we assume that the trackers are always the same, so I hard coded them so that the sharing link is shorter):
http://localhost:3000/download/magnet#magnet:?xt=urn%3Abtih%3A148c62a7f7845c91e7d16ca9be85de6fbaed3a1f&dn=test.zip&xl=1398978&cost=0
Where 
- **xt** is the id of the torrent 
- **dn** is the name of the torrent/file
- **xl** is the length (size) of the torrent
and **cost**... well.. that's kind of obvious.
=> [Web3Torrent] improve magnetURI generation & parsing

packages/nitro-protocol/contracts/AssetHolder.sol
This method is unused (and a carbon copy of one that *is* used in the ForceMove contract).
=> Remove _recoverSigner() from AssetHolder contract

packages/web3torrent/src/components/torrent-info/TorrentInfo.test.tsx, packages/web3torrent/src/components/torrent-info/TorrentInfo.tsx, packages/web3torrent/src/components/torrent-info/download-info/DownloadInfo.test.tsx, packages/web3torrent/src/components/torrent-info/download-info/DownloadInfo.tsx, packages/web3torrent/src/components/torrent-info/download-info/progress-bar/ProgressBar.scss, packages/web3torrent/src/components/torrent-info/download-info/progress-bar/ProgressBar.test.tsx, packages/web3torrent/src/components/torrent-info/download-info/progress-bar/ProgressBar.tsx, packages/web3torrent/src/components/torrent-info/download-link/DownloadLink.test.tsx, packages/web3torrent/src/components/torrent-info/download-link/DownloadLink.tsx, packages/web3torrent/src/components/torrent-info/magnet-link-button/MagnetLinkButton.test.tsx, packages/web3torrent/src/components/torrent-info/magnet-link-button/MagnetLinkButton.tsx, packages/web3torrent/src/components/torrent-info/upload-info/UploadInfo.test.tsx, packages/web3torrent/src/components/torrent-info/upload-info/UploadInfo.tsx, packages/web3torrent/src/types.ts, packages/web3torrent/src/utils/test-utils.ts, packages/web3torrent/src/utils/torrent-status-checker.test.ts, packages/web3torrent/src/utils/torrent-status-checker.ts
So... what started as a simple change (the first commit, a couple of lines), ended up as a refactor with 17 files affected :-P.
- Replaces the share button with an anchor link. See #241 for more details.
- Moves the cancel button from the progress bar into a page level button (#246 ).
- And most of all, refactors several components into their own files, and fixes a lot of things that @joelalejandro had commented that could be improved, this will pave the way for me tomorrow to work on the routing improvements, and implementing #245.
closes #241
closes #246 
affects #245
=> [Web3Torrent] TorrentInfoComponent Refactoring - Buttons Improvements

packages/embedded-wallet/public/wallet.js
Contributes to #254.
This will attempt to load assets by scanning the Embedded Wallet's asset manifest. If it fails, it'll skip preloading and resume normal usage.
=> [embedded-wallet] Adds asset preloader

packages/embedded-wallet/src/dialogs/budget-allocation/BudgetAllocation.test.tsx, packages/embedded-wallet/src/dialogs/budget-allocation/BudgetAllocation.tsx, packages/embedded-wallet/src/ui/chevron/Chevron.module.css, packages/embedded-wallet/src/ui/chevron/Chevron.test.tsx, packages/embedded-wallet/src/ui/chevron/Chevron.tsx, packages/embedded-wallet/src/ui/expandable/Expandable.module.css, packages/embedded-wallet/src/ui/expandable/Expandable.test.tsx, packages/embedded-wallet/src/ui/expandable/Expandable.tsx, packages/embedded-wallet/src/ui/index.ts
Resolves #265.
Adds `Chevron` and `Expandable` components, with its corresponding tests.
**Initial view**
**Expanded view**
=> [embedded-wallet] Implements simplified Budget Allocation view

packages/channel-provider/package.json, packages/channel-provider/tsconfig.json, packages/embedded-wallet/package.json, packages/web3torrent/package.json, yarn.lock
We're not publishing packages automatically in CI, so the deploy preview for Web3Torrent got broken due to a non-published package reference. 
This problem made the checks fail in #293 and #294.
Once we merge this PR, the ones mentioned above should be mergeable again.
Also resolves #303.
=> [embedded-wallet] [web3torrent] Use channel-provider@0.0.3

.gitignore, packages/nitro-protocol/.yarnrc, packages/nitro-protocol/package.json, packages/nitro-protocol/website/package.json, packages/nitro-protocol/yarn.lock
Coupled with a change to our netlify config (see below), this will allow website builds to be triggered only when files have changed in the `nitro-protocol` package (including for PRs), as well as cutting the build time roughly to a quarter of what it was (decoupling it from the building of other packages). 
Closes #259 (although any change to the package triggers a build, rather than just the contracts or docs).
=> [nitro-protocol] Introduce website:deploy script

netlify.toml
This should prevent any netlify sites that are linked to the root of the monorepo from triggering builds unless there is one or more changes across the
- `channel-provider`
- `web3torrent`
- `embedded-wallet`
packages.
=> [monorepo] Prevent unnecessary netlify builds

packages/nitro-protocol/package.json, packages/nitro-protocol/solidoc.json, yarn.lock
Our fork of `solidoc` has been updated to join relative paths for our contracts with a URL for our repo properly.  This PR pulls in those changes and exposes a `repoUrl` as required.
Will fix broken links labelled "View Source" on e.g. https://nitro-protocol.netlify.com/docs/natspec/iforcemove .
=> [nitro-protocol] Fix broken links on docs website

.circleci/config.yml, packages/hub/package.json, packages/hub/src/utilities/contracts.ts, packages/hub/src/wallet/db/seeds/1_rules.ts, packages/hub/src/wallet/utilities/blockchain.ts, yarn.lock
- Add postgres to CircleCi.
- Enable existing hub tests that do not rely on the outdated Nitro Adjudicator.
=> [hub] Enable tests that do not interact with contracts

netlify-ignore.sh, netlify.toml, packages/nitro-protocol/yarn.lock
This change enables any netlify site to target the base directory of the monorepo (which makes dependency installation smoother), but also to skip a build based on changes to a `TARGET_PACKAGE` env variable.
=> [monorepo] Add netlify-ignore script

.yarnrc, yarn.lock
To avoid conflicts like this:
```
<<<<<<< HEAD
resolved "https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.0.0.tgz#06e2ab19bdb535385559aabb5ba59729482800f8"
=======
resolved "https://registry.yarnpkg.com/@babel/code-frame/-/code-frame-7.0.0.tgz#06e2ab19bdb535385559aabb5ba59729482800f8"
>>>>>>> Remove rps references from the hub
```
=> Set registry to npmjs

packages/hub/package.json, yarn.lock
Removes the node-jq dependency from the hub as it's not being used anywhere (both by a quick search that I did on the repository and by @kerzhner [comments on Slack](https://statechannels.slack.com/archives/CMPHW40R0/p1572642456094200?thread_ts=1572636024.092500&cid=CMPHW40R0)).
The installation was failing, as reported in #336, this PR fixes that.
close #336
=> [Hub] Remove node-jq dependency from Hub

packages/hub/src/hub/handlers/handle-wallet-message.ts, packages/wallet/notes/actions.md, packages/wallet/notes/channel-opening.md, packages/wallet/notes/indirect-funding-proposal.md, packages/wallet/notes/protocol-conventions.md, packages/wallet/src/communication/actions.ts, packages/wallet/src/contract-tests/eth-asset-holder-events.test.ts, packages/wallet/src/redux/__tests__/helpers.ts, packages/wallet/src/redux/__tests__/state-helpers.ts, packages/wallet/src/redux/channel-store/channel-state/__tests__/index.ts, packages/wallet/src/redux/channel-store/channel-state/states.ts, packages/wallet/src/redux/channel-store/reducer.ts, packages/wallet/src/redux/protocols/advance-channel/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/advance-channel/actions.ts, packages/wallet/src/redux/protocols/advance-channel/reducer.ts, packages/wallet/src/redux/protocols/consensus-update/actions.ts, packages/wallet/src/redux/protocols/consensus-update/readme.md, packages/wallet/src/redux/protocols/consensus-update/reducer.ts, packages/wallet/src/redux/protocols/direct-funding/actions.ts, packages/wallet/src/redux/protocols/direct-funding/readme.md, packages/wallet/src/redux/protocols/dispute/challenger/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/dispute/challenger/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/dispute/challenger/readme.md, packages/wallet/src/redux/protocols/reducer-helpers.ts, packages/wallet/src/redux/protocols/virtual-funding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/virtual-funding/__tests__/scenarios.ts, packages/wallet/src/redux/sagas/__tests__/challenge-watcher.test.ts, packages/wallet/src/redux/sagas/__tests__/message-listener.test.ts, packages/wallet/src/redux/sagas/message-listener.ts, packages/wallet/src/utils/transaction-generator.ts
Updates `CommitmentsReceived` to `SignedStatesReceived` and updates comments that still refer to commitments.
=> [engine] Clean up remaining commitment references

packages/wallet/src/redux/sagas/adjudicator-state-updater.ts, packages/wallet/src/utils/contract-utils.ts
Fixes #420.
I've disabled a saga that has not been updated to work against the nitro protocol and changed how we load the `deployment-map.json` so we don't use `fs` in the browser.
=> [wallet] Fix on load error

packages/devtools/.prettierrc.js, packages/devtools/src/utils/network-setup.ts, packages/nitro-protocol/.prettierrc.js
Updates prettier config to set line length to 100 for `dev-tools` and `nitro-protocol` packages.
=> Format line length

packages/app-wallet-interface/source/index.html.md
More changes to the JSON-RPC interface. In particular:
* Begins to define some errors
* Adds a `messageQueued` event, for when the wallet wants the app to relay a message
* Adds a `pushMessage` method, for when the app receives a relayed message, and needs to send it to the wallet
* Adds the `closeChannel` method
* Adds a `getAddresses` method, for the app to request one or more signing addresses from the wallet
=> More JSON-RPC API changes

netlify.toml
This should mean that our sites *always* build from the latest code on master after a PR is merged.
Deploy-preview builds for PRs themselves will still be skipped if packages have not changed.
=> [monorepo] Disable custom netlify configuration in production

netlify-ignore.sh
Currently, we look for changes between a commit and its parent to decide whether to skip a build on netlify (as per [their suggestion](https://docs.netlify.com/configure-builds/file-based-configuration/#ignore-builds)). However, if you push a stack of commits and freshest one does not make changes in the target package, this means no deploy-preview will be built for your PR. 
After this change, deploy-preview (read 'PR') builds will be skipped based on a comparison between a commit and the tip of origin/master. Production builds (where comparing to origin/master would never yield any changes) will be unaffected since they do not trigger this script.
=> [monorepo] Do not netlify-ignore if changes made w.r.t master

packages/app-wallet-interface/source/index.html.md
Since I don't think we can actually verify `appData` and `appDefintion`(besides checking that there's a contract deployed at `appDefintion` I've changes those errors.
I've also added a `state transition` error on `joinChannel` as we can call `validTransition` once we have 2 states.
Also I've changed the numbering to reserve 100 error codes per a method. This allows us to introduce error codes for methods without messing with the rest.
=> [api] Update Errors

packages/wallet/package.json, packages/wallet/src/redux/__tests__/selectors.test.ts, packages/wallet/src/redux/__tests__/state-helpers.ts, packages/wallet/src/redux/actions.ts, packages/wallet/src/redux/channel-store/channel-state/__tests__/index.ts, packages/wallet/src/redux/channel-store/channel-state/states.ts, packages/wallet/src/redux/channel-store/channel-state/valid-transition.ts, packages/wallet/src/redux/channel-store/reducer.ts, packages/wallet/src/redux/protocols/actions.ts, packages/wallet/src/redux/protocols/advance-channel/reducer.ts, packages/wallet/src/redux/protocols/application/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/application/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/application/reducer.ts, packages/wallet/src/redux/protocols/application/states.ts, packages/wallet/src/redux/protocols/reducer-helpers.ts, packages/wallet/src/redux/reducer.ts, packages/wallet/src/redux/sagas/__tests__/message-handler.test.ts, packages/wallet/src/redux/sagas/__tests__/message-sender.test.ts, packages/wallet/src/redux/sagas/message-handler.ts, packages/wallet/src/redux/sagas/message-sender.ts, packages/wallet/src/redux/selectors.ts, packages/wallet/src/redux/state.ts, packages/wallet/src/utils/json-rpc-utils.ts, yarn.lock
Fixes #435. Fixes #462.
Implements the `Create Channel` Api Call (https://deploy-preview-427--app-wallet-interface.netlify.com/#create-channel)
Currently `CreateChannel` does not send a message to the opponent so they know a channel has been created. That will be handled under #470.
=> [wallet] Implement Create Channel API Call 

packages/app-wallet-interface/source/index.html.md
Switches the `amount` to be a hex string and adds the error codes based on https://github.com/statechannels/monorepo/pull/458
=> [api] - Switch amount to Hex and add Error Codes

readme.md
We do not use it anymore, so we can remove it.
=> Remove renovate status badge

packages/wallet/src/redux/actions.ts, packages/wallet/src/redux/sagas/__tests__/message-handler.test.ts, packages/wallet/src/redux/sagas/message-handler.ts, packages/wallet/src/redux/sagas/message-sender.ts
Fixes #436 
Adds support for the Join Channel api call.
Currently it updates the application protocol with the next state and returns success.
=> [wallet] Add Join Channel API

packages/hub/src/hub/handlers/__test__/handle-ongoing-process-action.test.ts, packages/hub/src/hub/handlers/handle-new-process-action.ts, packages/hub/src/hub/handlers/handle-ongoing-process-action.ts, packages/hub/src/test/test-constants.ts, packages/hub/src/test/test_data.ts, packages/hub/src/wallet/adjudicator-watcher/__chain-test__/adjudicator-watcher.test.ts, packages/hub/src/wallet/db/migrations/20191111110900_allocations.ts, packages/hub/src/wallet/db/queries/__test__/channels.test.ts, packages/hub/src/wallet/db/queries/channels.ts, packages/hub/src/wallet/db/seeds/2_allocator_channels_seed.ts, packages/hub/src/wallet/db/seeds/3_wallet_processes.ts, packages/hub/src/wallet/models/__test__/channelState.test.ts, packages/hub/src/wallet/models/channelState.ts, packages/hub/src/wallet/models/outcome.ts, packages/hub/src/wallet/services/__test__/channelManager.test.ts, packages/hub/src/wallet/services/__test__/ledgerChannelManager.test.ts, packages/hub/src/wallet/utilities/outcome.ts
Most important changes are in `packages/hub/src/wallet/utilities/outcome.ts`.
This PR: 
- tests converting a guarantor channel state stored in postgres to an object.
- opportunistically renames snake_case functions and constants to camelCase.
=> [hub] Further support for guarantees

packages/rps/config/jest/jest.config.js
If you try to load jest-gas-reporter when ganache isn't running, you get weird errors like:
```
Error: invalid response - 0
at exports.XMLHttpRequest.request.onreadystatechange (~/magmo/monorepo/node_modules/ethers/utils/web.js:84:29)
```
We shouldn't need ganache (or jest-gas-reporter) when running app-only tests.
=> Don't use jest-gas-reporter when testing app

packages/nitro-protocol/package.json
We shouldn't need this anymore with the new shared contracts infrastructure.
=> Remove deploy step in nitro-protocol local tests

.gitignore
Seems like `env.ts` doesn't actually use `.env.local` files, it uses `.env.{NODE_ENV}.local` files...
https://github.com/statechannels/monorepo/blob/bfc0b0240a6dfca146f0107bf616f8e2963af83b/packages/devtools/src/config/env.ts#L13:L13
I use `USE_NATIVE_SOLC` to make compilation times 10 faster (see #86) so I need this.
=> Ignore local environment files

netlify-ignore.sh
Netlify does not seem to have upstream branches, meaning we cannot do a `git diff` to, e.g. `origin/master` .
Solution: add the remote and fetch as a part of our custom script.
=> Fix netlify error

packages/rps/src/utils/channel-client.ts
There are a lot of types defined in the channel client, which end up being a lot of information to process. This PR attempts to simplify the types and their relationships, e.g. by using less inheritance.
=> Changes to channel client

packages/wallet/config/jest/jest.contracts.config.js, packages/wallet/src/setupContractTests.ts, packages/wallet/src/setupTests.ts
Mocks out some contract-utils to allow tests to pass when the `ganache-deployer` isn't running.
=> [Wallet] Allow tests to run without requiring ganache

packages/wallet/src/redux/actions.ts, packages/wallet/src/redux/sagas/__tests__/message-handler.test.ts, packages/wallet/src/redux/sagas/__tests__/message-sender.test.ts, packages/wallet/src/redux/sagas/message-handler.ts, packages/wallet/src/redux/sagas/message-sender.ts, packages/wallet/src/utils/json-rpc-utils.ts
Send a message to the opponent's wallet when joining a channel. This allows your opponent to continue funding.
=> [wallet] Send Message to opponent's wallet when joining a channel

packages/ganache-deployer/.eslintignore, packages/ganache-deployer/.eslintrc.js, packages/ganache-deployer/.prettierignore, packages/ganache-deployer/package.json, packages/ganache-deployer/src/index.ts, packages/ganache-deployer/tslint.json
This PR replaces TSLint with ESlint in Ganache Deployer.
TSLint is deprecated.
The rules can be changed.
What does everyone think?
=> [ganache-deployer] Replace TSLint with ESlint in Ganache Deployer

packages/nitro-protocol/src/contract/consensus-app.ts, packages/nitro-protocol/src/contract/force-move-app.ts, packages/wallet/src/redux/channel-store/channel-state/valid-transition.ts
Due to #537 the wallet cannot load in the browser. This PR comments out the `pure-evm` usage so the wallet loads properly.
Once #537 is resolved this should be reverted.
=> [wallet/nitro-protocol] Comment out pure-evm use

packages/wallet/src/redux/sagas/message-sender.ts, packages/wallet/src/utils/json-rpc-utils.ts
Fixes the `CreateChannel`/`UpdateChannel` response failing the json schema validation.
=> [wallet] Fix Invalid Outgoing Message

packages/nitro-protocol/src/contract/consensus-app.ts, packages/nitro-protocol/src/contract/force-move-app.ts, packages/rps/package.json, packages/wallet/config/paths.js, packages/wallet/config/webpack.config.js, packages/wallet/package.json, packages/wallet/src/redux/channel-store/channel-state/valid-transition.ts, patches/pure-evm+0.1.2.patch, yarn.lock
Uses `/* WebpackMode: "eager" */` to load the module which is an instantly resolved promise.
I did nothing to address the `readFileSync` call yet; I have not been able to see that error since when I run `yarn start` in `@statechannels/wallet` I see #544 and no dev server starts. Also because of the linting, the comment for `webpackMode` is forced to start with a capitalized `W`. I'm not sure if this breaks it or not, because I cannot get the dev server to start. Also while working on this I noticed we should probably do #543.
=> Update pure-evm loading strategy

packages/hub/src/hub/handlers/__test__/handle-ongoing-process-action.test.ts, packages/hub/src/test/test_data.ts, packages/hub/src/wallet/__test__/wallet.test.ts, packages/hub/src/wallet/db/queries/__test__/channels.test.ts, packages/hub/src/wallet/db/queries/channels.ts, packages/hub/src/wallet/db/queries/getCurrentState.ts, packages/hub/src/wallet/db/seeds/2_allocator_channels_seed.ts, packages/hub/src/wallet/models/__test__/channelState.test.ts, packages/hub/src/wallet/services/__test__/channelManager.test.ts, packages/hub/src/wallet/services/__test__/ledgerChannelManager.test.ts
Fixes https://github.com/statechannels/monorepo/issues/547.
Upper case constants remain in snake case.
=> Hub: rename variables from snake_case to camelCase

packages/rps/src/redux/message-service/channel-updated-listener.ts, packages/rps/src/redux/message-service/message-queued-listener.ts
Turns out that if you do this:
```ts
const channel = eventChannel(rpsChannelClient.onMessageQueued, buffers.fixed(10))
```
you just get the `onMessagedQueued` function, and *not* the `onMessageQueued` function in the context of the `rpsChannelClient`. We need to do this instead:
```ts
const subscribe = emit => rpsChannelClient.onMessageQueued(emit);
const channel = eventChannel(subscribe, buffers.fixed(10));
```
=> Fix listeners

packages/wallet/src/redux/actions.ts, packages/wallet/src/redux/adjudicator-state/reducer.ts, packages/wallet/src/redux/sagas/adjudicator-state-updater.ts, packages/wallet/src/utils/contract-utils.ts
We do not have the luxury of on-chain data availability for our channel states (i.e., outcome, isFinalized, etc) anymore. The only piece of on-chain data we have is the current block number, which we will need to implement a different kind of saga / state updater for.
=> Update comments about the adjudicatorStateUpdater

packages/ganache-deployer/src/deployer.ts, packages/wallet/src/contract-tests/eth-asset-holder-events.test.ts, packages/wallet/src/contract-tests/transactions.test.ts, packages/wallet/src/utils/transaction-generator.ts
This was causing some tests to be skipped unnecessarily.
=> Fix ganache-deployer's set adjudicator address for asset holder contracts

packages/wallet/src/redux/sagas/adjudicator-watcher.ts
Is this needed @lalexgap? It seems like the "process event actions" are getting dispatched many more times than need be. Also, two of them were being dispatched in the "event actions" helper function anyway.
=> Remove redundant action dispatching

yarn.lock
[This commit](https://github.com/LimeChain/ethers.js/commit/13c82e89991c3cbe81c51d1ceec453a43dbb4415) fixed a types issue, but for some reason our `yarn` is using an older commit even though the `package.json` of `etherlime-lib` references `master` of `LimeChain/ethers.js`.
If anyone knows how to fix this permanently let me know, because I fixed this last week but it came back somehow.
=> Change LimeChain/ethers github resolution

.circleci/config.yml
As far as I can tell, we don't need to be caching the `.git` folder across workflows on CircleCI. This was probably from copying the config from Counterfactual which may, at one point, have fetched the last git commit hash to do something inside the config.
=> Remove .git folder per-workflow cache

packages/ganache-deployer/src/deployer.ts, packages/nitro-protocol/contracts/test/TESTAssetHolder.sol, packages/nitro-protocol/contracts/test/TESTAssetHolder2.sol, packages/nitro-protocol/test/contracts/NitroAdjudicator/pushOutcome.test.ts
Hey @geoknee I noticed that the `pushOutcome.test.ts` tests were failing with an `Only the NitroAdjudicator is authorized` error occurring. I realized this must have happened because I recently changed `ganache-deployer` to deploy `ETHAssetHolder` and `ERC20AssetHolder` with the real `NitroAdjudicator` contract as the `AdjudicatorAddress` argument (see https://github.com/statechannels/monorepo/pull/583). However this is problematic because the tests relied on those two asset holders allowing the `TESTNitroAdjudicator` as the `AdjudicatorAddress`.
Anyway three things:
1. I don't know how the CI did not catch this.
2. I tried adding the `constructor` from `ETHAssetHolder` to `TESTAssetHolder` and re-writing the tests (as you can see in this PR) but I am now seeing a `revert` on tests 1 and …
=> Attempt to fix pushOutcome test

packages/wallet/config/webpack.config.js
This seems highly unnecessary.
=> Remove tslint checker on WebPack

packages/wallet/config/webpack.config.js, packages/wallet/package.json, packages/wallet/src/json-rpc-validation/validator.ts, packages/wallet/tsconfig.json
In order to use dynamic imports, we need to use the `import(...)` syntax. TypeScript doesn't know how to handle this with `commonjs`, so we need to use `esnext`.
In order to use WebAssembly in the browser we need to use dynamic imports.
In order to use `pure-evm`, we need to use WebAssembly, which means we need dynamic imports.
The integration tests use `ts-node`, which uses Node.js, which can't handle ES modules. See https://github.com/TypeStrong/ts-node/issues/436.
So, I need to use `commonjs` for the `puppeteer/funding.ts` test script. Note that this is _just_ for the test script, which launches a browser, which runs the webpack output, which was built from the TypeScript source compiled using `esnext`.
=> Switch wallet tsconfig to use esnext module

packages/hub/package.json
We got rid of these on all other packages but the `hub` has this still because it was added recently.
=> Remove lint checks on test command on hub

package.json
This ensures CI tests run for dependencies of a package that is changed in addition to that package.
=> Run CI tests only for changed packages and dependencies

packages/wallet/config/jest/jest.config.js, packages/wallet/config/polyfills.js
Using the `globals` field in the jest config was the wrong approach for providing `window.PureEVM` in the jest tests for the `wallet`. Instead, this should have been a polyfill provided to `setupTests`. This fixed that.
=> [wallet] Use correct polyfill technique for wallet jest tests

.gitignore
This file is produced by packages with `composite` set to `true` in their `tsconfig`. It helps make builds go faster. See [here](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-4.html#composite-projects) for more.
=> Ignore tsconfig.tsbuildinfo

packages/devtools/src/config/env.ts, packages/devtools/tsconfig.json
When I updated the monorepo `tsconfig` earlier this year I mentioned I would later go through each child package and try to merge any duplicate or unneeded keys to minimize complexity. Devtools was added later, so just doing this now.
=> Update tsconfig.json of devtools

packages/channel-provider/package.json, packages/devtools/package.json, packages/embedded-wallet/package.json, packages/hub/package.json, packages/jest-gas-reporter/package.json, packages/nitro-protocol/package.json, packages/rps/package.json, packages/wallet/package.json, packages/wallet/tsconfig.json, packages/web3torrent/package.json, yarn.lock
Andrew and I noticed that the linting precommit hook wasn't working as expected, so I investigated. Turns out some packages did not have it set at all (i.e., `rps` and `hub`) and others had it set incorrectly (wrong regex to search for staged files). Also, it was implemented incorrectly in the first place in most cases, as if there _were_ a staged filed to be linted, it would run `yarn lint:check` which usually linted _every_ file and not just the sole changed one.
=> Fix issues with lint-staged in various packages

packages/wallet/src/redux/sagas/__tests__/message-sender.test.ts, packages/wallet/src/redux/sagas/message-sender.ts, packages/wallet/src/redux/selectors.ts
Fixes #645 
Sets the `funding` array on the API response for `UpdateState`. Currently only supports ETH.
=> [Wallet] Return funding array from API

packages/wallet/src/json-rpc-validation/schema/notification.json, packages/wallet/src/redux/sagas/__tests__/display-sender.test.ts, packages/wallet/src/redux/sagas/display-sender.ts
Fixes #444 
This will allow the `ChannelProvider` to show/hide the wallet appropriately.
=> [wallet] Send out json-rpc notifications for hiding/showing the wallet

packages/wallet/package.json
These `typings` were being added by `TypeSync` when running `yarn`.
=> Add missing types to satifsy typesync

.vscode/settings.json
For me, this was affecting files in the `wallet` folder while I had open the `monorepo` as a root folder in my workspace. It was applying the `bracketSpacing: true` rule in particular every time I hit save.
Turning this flag off fixed the issue.
=> Turn off formatOnSave

packages/hub/config/env.js, packages/hub/package.json, packages/hub/src/hub/server.ts, packages/hub/src/start-dev-server.ts, yarn.lock
- migrate away from the depricated `magmo-devtools` dependency.
- do not populate environment variables in the hub application. Expect the environment variables to be populated before application start.
=> Hub: env vars

packages/wallet/puppeteer/__tests__/funding.test.ts, packages/wallet/puppeteer/__tests__/state-updating.test.ts, packages/wallet/puppeteer/__tests__/update-state.test.ts, packages/wallet/puppeteer/helpers.ts, packages/wallet/src/redux/channel-store/channel-state/states.ts, packages/wallet/src/redux/sagas/messaging/__tests__/message-handler.test.ts, packages/wallet/src/redux/sagas/messaging/__tests__/message-sender.test.ts, packages/wallet/src/redux/sagas/messaging/message-handler.ts, packages/wallet/src/redux/sagas/messaging/message-sender.ts, packages/wallet/src/redux/sagas/messaging/outgoing-api-actions.ts, packages/wallet/src/redux/selectors.ts, packages/wallet/src/utils/json-rpc-utils.ts
Fixes #661 
Updates the wallet to send a state to the opponent's wallet when calling `UpdateState`. The opponent's wallet will dispatch a `ChannelUpdated` notification so the `app` knows about the new state.
Also added an integration test for updating states.
=> [wallet] Send state to opponent when calling UpdateState

.eslintrc.js, packages/hub/.eslintrc.js, packages/hub/package.json, packages/jest-gas-reporter/.eslintrc.js, packages/wallet/.eslintrc.js
Adds a shared `.eslintrc.js` in the monorepo root.
=> [monorepo] Shared .eslintrc.js

packages/hub/.env.test, packages/hub/readme.md, packages/hub/src/db-admin/knexfile.ts
Fixes https://github.com/statechannels/monorepo/issues/693.
`knexfile` is executed both as a `ts` file (through ts-node) and as a compiled `js` file. With this PR, `knexfile` references migrations files that match the execution environment.
=> [hub] use migrations based on location of knexfile

packages/wallet/src/redux/sagas/ganache-miner.ts
The Ganache miner saga was previously failing when using a shared ganache instance, since it tries to use `GANACHE_PORT` to create a provider.
It has been updated to use `getProvider` from `contract-utils`.
=> [wallet] Fix Ganache Miner to not fail when using Shared ganache

packages/wallet/src/redux/sagas/ganache-miner.ts, packages/wallet/src/redux/sagas/messaging/__tests__/message-handler.test.ts, packages/wallet/src/redux/sagas/messaging/__tests__/message-sender.test.ts, packages/wallet/src/redux/sagas/messaging/message-handler.ts, packages/wallet/src/redux/sagas/messaging/message-sender.ts, packages/wallet/src/redux/sagas/messaging/outgoing-api-actions.ts
Fixes #722. Fixes two issues that were stopping RPS from exchanging moves:
- The `recipient` and `sender` were swapped when sending a ChannelUpdated message to your opponent.
- When a `pushMessage` was called with a `ChannelUpdated` message it was not returning success, so `channel-client` would timeout and retry 5 times, messing up the state.
=> [wallet] Allow RPS to properly exchange states

.circleci/config.yml
If a job on `master` fails, then #sc-general-chat Slack channel receives a notification mentioning the @devs user group.
=> Add circle failure slack notifications

packages/wallet/puppeteer/helpers.ts
Hopefully this addresses #721. Instead of waiting 1 second for the wallet to load, we now wait until `DOMContentLoaded` is fired when accessing the wallet page.
=> [build] Wait for wallet page to load in puppeteer

packages/rps/src/redux/login/saga.ts, packages/rps/src/redux/metamask/saga.ts
Fixes #718.
Uses `window.ethereum.enable` when available instead of `web3.eth.getAccounts` as this seemed to just return an empty array when using firefox and metamask.
=> [rps] Use window.ethereum if available

packages/devtools/README.md, packages/devtools/package.json, packages/hub/readme.md, packages/jest-gas-reporter/package.json, packages/nitro-protocol/docs/forcemove-and-nitro/force-move.md, packages/nitro-protocol/package.json
Lots of ♥ for Magmo but links were pointing to incorrect places 😅
This fixes usages of Magmo in files such as package.json and READMEs.
There are still a few links pointing to places that don't have a corresponding file in StateChannels
Closes #533
=> [monorepo] chore: Remove usages of Magmo in files

packages/hub/env.js, packages/hub/readme.md, packages/wallet/config/env.js, packages/wallet/src/constants.ts
With this PR:
- we can define `HUB_ADDRESS` and `HUB_PRIVATE_KEY` once in the root of the monorepo.
- have a clearer readme on starting the hub.
=> Hub: state channel address configuration

packages/channel-client/src/channel-client.ts, packages/channel-client/src/index.ts, packages/rps/src/redux/auto-opponent/__tests__/auto-opponent.test.ts, packages/rps/src/redux/auto-opponent/auto-opponent.ts, packages/rps/src/redux/game/__tests__/player-a.test.ts, packages/rps/src/redux/game/__tests__/player-b.test.ts, packages/rps/src/redux/store.ts, packages/rps/src/utils/__tests__/rps-channel-client.test.ts, packages/rps/src/utils/rps-channel-client.ts
Closes #713 .
This PR undisables these tests, which were set to "skip" recently. 
1. The auto-opponent and test use the `FakeChannelClient`
2. The test for `RPSChannelClient` class mocks up a `ChannelClient` and does not assert anything that requires the underlying provider to exist (for example, an event being emitted). It also expands the test coverage to 
👀 Additional modifications to non-test code:
- A wrapper `Client` will not spawn the underlying `Client`: it must be passed in, instead (makes testing via mocks far easier)
- (related) Channel Client's `enable` method no longer does anything.
- Encoding mismatch fixed (uncovered by new testing approach).
- Wrapper client's `pushMessage` method passes through (i.e. returns) the return value of the inner class instance's `pushMessage`
=> [rps] Resintate tests

.vscode/settings.json
- allows vscode eslint plugin pickup settings file correctly
=> [rps][wallet] Mirror vscode settings for packages migrated to eslint

packages/rps/src/gateways/firebase.ts, packages/rps/src/redux/login/actions.ts, packages/rps/src/redux/login/saga.ts, packages/rps/src/redux/metamask/actions.ts, packages/rps/src/redux/metamask/reducer.ts, packages/rps/src/redux/metamask/saga.ts
As per [recommendation](https://gist.github.com/rekmarks/d318677c8fc89e5f7a2f526e00a0768a#file-newprovider-js-L71-L73), metamask will not pop up until the user has confirmed they want to use the app. 
Note that metamask will remember the approval for a connection to `localhost` (or `rps.com`) and therefore will not re-prompt next time unless you delete the connection.
I also disabled persistence for firebase auth, which was causing any user who had previously logged in to be bumped straight past the homepage to the "Name / Twitter Handle" modal without clicking anything.
References
---
See https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1102.md
=> [rps] Improve user login / metamask enable experience

.circleci/config.yml, packages/nitro-protocol/package.json
`tsc` is much, much faster on the second run. This PR caches `packages/*/lib` after running `yarn prepare`.
=> Cache `lib` directories in circle

packages/channel-client/package.json, packages/channel-client/src/fake-channel-client.ts, packages/channel-client/tests/fake-channel-client.test.ts, packages/rps/package.json
The `test:ci` was missing from the original PR that introduced the `FakeChannelClient`.
=> [channel-client] Run FakeChannelClient tests in CI

packages/wallet-specs/src/ChannelStoreEntry.ts, packages/wallet-specs/src/protocols/advance-channel/protocol.ts, packages/wallet-specs/src/protocols/conclude-channel/protocol.ts, packages/wallet-specs/src/protocols/create-channel/protocol.ts, packages/wallet-specs/src/protocols/create-null-channel/protocol.ts, packages/wallet-specs/src/protocols/direct-funding/protocol.ts, packages/wallet-specs/src/protocols/ledger-defunding/protocol.ts, packages/wallet-specs/src/protocols/ledger-funding/protocol.ts, packages/wallet-specs/src/protocols/partial-withdrawal/protocol.ts, packages/wallet-specs/src/protocols/virtual-defunding-as-leaf/protocol.ts, packages/wallet-specs/src/protocols/virtual-fund-as-hub/protocol.ts, packages/wallet-specs/src/protocols/virtual-funding/protocol.ts, packages/wallet-specs/src/protocols/wallet/protocol.ts, packages/wallet-specs/src/store.ts
- An array of signed states is stored, rather than two arrays of supported and unsupported signed states
- Some getter functions are removed from the store; the channel's store entry can instead expose these getters or alternatives.
=> Wallet store cleanup

packages/nitro-protocol/docs/forcemove-and-nitro/asset-holder.md, packages/nitro-protocol/docs/forcemove-and-nitro/force-move.md, packages/nitro-protocol/docs/state-channels/quick-start.md
Fixes most of the broken links found by https://www.brokenlinkcheck.com/
Outstanding ones are the links to the source files for the imported openzeppelin contracts, which require a bit more thought to fix.
=> [nitro] Fix broken links in website

packages/wallet-specs/src/ChannelStoreEntry.ts, packages/wallet-specs/src/protocols/advance-channel/protocol.ts, packages/wallet-specs/src/protocols/support-state/protocol.ts
Some protocols were still relying on `latestSupportState` to return `undefined` instead of throwing an error. I've added a `hasSupportedState` so protocols that aren't sure if a state is supported yet can check that before trying to access it.
=> Fix protocols crashing when there is no supported state

packages/hub/readme.md
Modifying the hub readme with Heroku commands that worked for me. Of note is that instructions now point to the new `statechannels-hub-staging` heroku app that belongs to the `statechannels` Heroku team.
=> Hub: update heroku + docker readme

packages/hub/.env.development, packages/hub/src/db-config.ts, packages/hub/src/wallet/db/connection.ts
The environment variables were not being loaded for some reason when I ran `yarn hub:start:dev` unless I did this.
=> [hub] Fix hub:start:dev

packages/e2e-tests/puppeteer/helpers.ts, packages/rps/src/redux/game/saga.ts, packages/wallet/src/redux/protocols/virtual-funding/reducer.ts
It turns out #823 caused a regression that was undetected by the integration tests since `window.ethereum.selectedAddress` was `undefined`. This meant `address` and `outcomeAddress` were the same value.
However, in production they will be different.
This means we need to update the virtual funding protocols to be OK with this scenario, or revert that PR, or just change the default value to address of the ephemeral signing key temporarily.
This is where the virtual funding gets stuck now:
=> Add ethereum.selectedAddress to puppeteer environment

packages/rps/src/utils/rps-channel-client.ts, packages/wallet/src/redux/protocols/virtual-funding/reducer.ts
Fixes two main issues:
- The joint channel was not being properly constructed with 3 participants. This would cause defunding to behave improperly later.
- The participants being passed into `createChannel` had their `destination` set to their `signingAddress`.
=> Fix Wallet Funding issues

packages/wallet-specs/jest.config.js, packages/wallet-specs/src/__tests__/allocateToTarget.test.ts, packages/wallet-specs/src/calculations.ts, packages/wallet-specs/src/index.ts, packages/wallet-specs/src/protocols/funding/__tests__/funding.test.ts, packages/wallet-specs/src/protocols/ledger-funding/protocol.ts
In addition to the main event, this PR introduces a unit test for a complicated bit of logic around ledger-funding. I think that these kinds of tests are more useful than copying over the "if we receive this action in this state we move to that state" tests from the redux wallet.
=> Properly update ledger outcome in ledger-funding

packages/rps/.env.production
This variable is needed for the UI to pickup the target network id. Previously, this was not being overwritten and so took on some default value for `ganache`.
There might be a more elegant fix that removes the redundancy with `TARGET_NETWORK` (which has the network namesting), but at least this change should un-break the deployed app.
=> [rps] Overwrite CHAIN_NETWORK_ID in production

packages/hub/package.json, packages/hub/tsconfig.json
`hub` was not using [build mode](https://www.typescriptlang.org/docs/handbook/project-references.html#build-mode-for-typescript), now it is. Also added the `nitro-protocol` reference.
=> [hub] Use TypeScript references correctly in hub

packages/rps/src/components/InsufficientFunds.tsx, packages/rps/src/components/Resigned.tsx
Minimal change that removes confusion for the user (since they already withdrew by this point). 
There is still arguably one more state / screen than there should be -- the user 
- has no warning from the *app* when opponent resigns or funds are depleted
- has to click *twice* to get back to the lobby after the wallet has wrapped up the channel.
I have kept that the way it is here, because I anticipate a future PR moving the `client.closeChannel()` call one state down, so that the app *does* give a warning, and there is one confirmatory click *before* the wallet takes over, and one afterwards.
=> [rps] 'Withdraw' button simply 'OK' button

packages/rps/contracts/RockPaperScissors.sol, packages/rps/src/contract-tests/rock-paper-scissors.test.ts
This PR 
- upgrades test script to output gas information
- adds a test case specifying an attack where player A can increase their payout if they win (test fails on existing contract)
- refactors the contract to fix this case (test passes), and increase clarity around "stake" and "winnings" etc
- ^ negligible changes in gas cost (see below)
Gas before:
Returns true on RoundAccepted -> Reveal; B won:
66335 gas
Returns true on RoundAccepted -> Reveal; A won:
66282 gas
Returns true on RoundAccepted -> Reveal; Draw:
65960 gas
Gas after: 
Returns true on RoundAccepted -> Reveal; B won:
66431 gas (+96)
Returns true on RoundAccepted -> Reveal; A won:
66360 gas (+78)
Returns true on RoundAccepted -> Reveal; Draw:
65670 gas (-290)
=> [rps] Fix security bug and refactor for clarity

.circleci/config.yml, package.json, packages/nitro-protocol/package.json, packages/rps/package.json, packages/wallet/package.json, yarn.lock
Adding a release job to circle that builds + deploys static sites to netlify. For now, only `nitro-protocol` docs, `wallet`, and `rps` are deployed. Once this PR is merged in, continuous integration will be turned off in the netlify console. The reasons to migrate static site builds and deploys to Circle are:
- Netlify CI is expensive. Our monthly budget is around $200 (which is more than CircleCI).
- Static site build and deploy instructions are defined in code (config.yml) as opposed to in Netlify console.
- Circle is faster since `yarn install` is only run once for all site builds + deploys. On Netlify, `yarn install` is run once per each static site build + deploy.
=> Build and deploy netlify sites from circle

packages/wallet-specs/src/index.ts, packages/wallet-specs/src/protocols/depositing/protocol.ts, packages/wallet-specs/src/protocols/direct-funding/protocol.ts, packages/wallet-specs/src/protocols/ledger-funding/protocol.ts, packages/wallet-specs/src/runtime.ts
I believe this PR gets direct funding working with the exception that it gets the holdings from an object called `chain` imported from `index.ts`. This should be updated based on the store's `getHoldings` method from `ag/xstate-deposit`. Since that branch has merged `ags/xstate-direct-funding` into it, the cleanest thing is to merge `ags/xstate-direct-funding` into master as is, and fix the state of affairs by branching off of `ag/xstate-deposit`.
=> Direct funding

package.json
In order to address [@geoknee comment](https://github.com/statechannels/monorepo/pull/856#discussion_r367328106), `--since` flag was added to Netlify build and release commands. The issue is that when a PR is merged into master, Netlify build and release are skipped. On PR merge into `master`, the correct action is to release static sites to production.
For now, turning on Netlify build and release for every CI run. This will generate lots of Deploy Previews. But I am not aware that this will cause any issues.
=> Build and release to Netlify on every CI run

package.json
On Linux Alpine, `yarn` uses `sh` (as opposed to `bash`) to execute subshell commands. `[[ ]]` and `==` are not valid.
=> Switch to single bracket syntax in package.json

package.json
We get an out of memory error on circle under current config. 
On this branch I will try a few different configs that avoid the error while keeping the duration as short as possble.
Tests in the `wallet` package take the most time (typically 6mins).
For all tests:
Concurrency = 2: 9mins
Concurrency = 4: 6 mins
=> [monorepo] Set concurrency for lerna to 4

packages/nitro-protocol/contracts/ForceMove.sol, packages/nitro-protocol/docs/forcemove-and-nitro/force-move.md, packages/nitro-protocol/test/contracts/ForceMove/respond.test.ts
The bug disallowed `respond`ing to a challenge when the challenge state was the final post fund setup in the round, since the core protocol `validTransition` would erroneously judge the response state to be a setup state, and then require the `appData` to not change.
Hint: the test is for a 3 participant channel, so the example is when `turnNumRecord=5`.
=> [nitro] Fix error in definition of setup phase

packages/e2e-tests/puppeteer/__tests__/rps.test.ts, packages/e2e-tests/puppeteer/helpers.ts, packages/e2e-tests/puppeteer/scripts/rps.ts, packages/rps/src/redux/auto-opponent/__tests__/auto-opponent.test.ts, packages/rps/src/redux/game/__tests__/player-a.test.ts, packages/rps/src/redux/game/__tests__/player-b.test.ts, packages/rps/src/redux/game/saga.ts, packages/rps/src/redux/open-games/saga.ts
Three fixes: 
- Because most of the `rps` sagas `take` every action, there were hacks in place to prevent performing some tasks multiple times: in this case a mutex to track if Player A had joined a game. This mutex was never getting reset. The new approach is to do away with the mutex, and only join a game when a "join game" action was dispatched. 
- Some tasks (e.g. opening a channel) were only executed when the `channelState` was "empty". The new approach is to clear out the `channelState` when the game is over. 
Closes #778 .
(and, unrelated to this issue)
- In some scenarios the metamask address never gets injected, leading to runtime errors down the line. The new approach is to wait for the metamask address to exist before progressing with the game.
=> [rps] Allow multiple serial games

.circleci/config.yml
These are the rate-limiting steps in most builds. In my very unscientific comparison:
- `"large"` saves ~30 seconds on `yarn install`
- `"large"` saves ~20 seconds on `yarn test:ci` with concurrent tests
- `lerna run test:ci --parallel` is slower than `lerna run test:ci --concurrency 4 --no-sort`
So, we might save 30-60s by spending a bit more money on circle credits.
Other things, like restoring the cache or persisting/restoring a workspace, seem to take a pretty variable amount of time.
=> 💸 💸  Set resource_class to "large" in test and prepare 💸 💸

packages/nitro-protocol/src/contract/transaction-creators/force-move.ts, packages/nitro-protocol/src/transactions.ts, packages/nitro-protocol/test/contracts/ForceMove/_validSignatures.test.ts, packages/nitro-protocol/test/contracts/ForceMove/forceMove.test.ts
It was previously using a broken `createSignatureArguments` helper -- this is now altered to rip the signatures out of an array of `SignedStates`, and re-order them by participant (as is required by the contract code). 
This PR also increases test coverage such that tests would fail without the above fix (namely, when the array of states submitted does not begin with one owned by participant 0). 
Some scope for DRYing out the new tests.
=> [nitro] Fix and test forceMove transaction generator

packages/xstate-wallet/package.json, packages/xstate-wallet/webpack-build.config.js, yarn.lock
Fixes the `yarn build` command in `xstate-wallet` and adds a `build:ci` command to build `xstate-wallet` on CI.
=> Fix build command

packages/hub/package.json, packages/hub/src/test/test-constants.ts, packages/hub/src/types.ts, packages/hub/src/wallet/db/queries/channels.ts, packages/hub/src/wallet/index.ts, packages/hub/src/wallet/models/allocation.ts, packages/hub/src/wallet/models/channel.ts, packages/hub/src/wallet/models/channelHoldings.ts, packages/hub/src/wallet/models/channelState.ts, packages/hub/src/wallet/models/outcome.ts, packages/hub/src/wallet/models/rule.ts, packages/hub/src/wallet/services/__test__/depositManager.test.ts, packages/hub/src/wallet/services/applicationManager.ts, packages/hub/src/wallet/services/asset-holder-watcher.ts, packages/hub/src/wallet/services/blockchain.ts, packages/hub/src/wallet/services/index.ts, packages/rps/package.json, packages/rps/src/components/NavigationBar.tsx, packages/rps/src/components/OpenGameCard.tsx, packages/tic-tac-toe/package.json, packages/wallet/package.json, packages/wallet/src/redux/protocols/withdrawing/__tests__/scenarios.ts, packages/xstate-wallet/package.json, yarn.lock
I tried upgrading to Node 12.7.0 and hit an issue related [to this Github issue](https://github.com/ethereum/web3.js/issues/2913). I don't think we even need `scrypt` since we don't need `web3`... so removing these.
=> [monorepo] Remove fmg-core and web3 dependencies

packages/wallet-protocols/src/store.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/workflow-manager.ts, packages/xstate-wallet/src/workflows/application.ts
After changes to `ChannelUpdated` in  #907  the xstate wallet wasn't functioning correctly and `rps` would get stuck on funding. 
This PR gets the `xstate-wallet` back to the point that `rps` can be funded/played.
=> Get XState Wallet working

packages/rps/package.json, packages/rps/src/index.tsx, yarn.lock
This PR sets up Sentry for RPS.
I created an Org called state-channels.
In Sentry settings I set it up so that it only logs errors from this url:
`https://rps.statechannels.org`
=> [RPS] Add Sentry.io Error Tracking and Monitoring

.circleci/config.yml
Every build is red now because of this. Builds should not be failing because of an unrelated issue, so we should disable this test in circle, fix the test, and then re-enable it.
=> Disable integration test in circle

packages/e2e-tests/puppeteer/__tests__/rps.test.ts, packages/rps/src/redux/game/saga.ts, packages/wallet/src/redux/sagas/messaging/message-handler.ts
I had been trying to make it the case that when you finish a challenge, the state can be updated despite the wallet process being in an `Application.WaitForDispute` state. This ended up causing race conditions not visible when testing against a fast local ganache network, but noticeable on Ropsten.
This PR gets rid of that feature, so if you want to continue a channel after a challenge, you need to click "Ok" on both prompts.
=> Improve reliability of rps challenging scenario

packages/e2e-tests/puppeteer/helpers.ts, packages/nitro-protocol/src/contract/challenge.ts, packages/rps/src/core/channel-state.ts, packages/rps/src/redux/game/saga.ts, packages/wallet/src/redux/channel-store/reducer.ts, packages/wallet/src/redux/protocols/application/reducer.ts, packages/wallet/src/redux/protocols/dispute/challenger/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/dispute/challenger/reducer.ts, packages/wallet/src/redux/protocols/dispute/responder/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/dispute/responder/reducer.ts, packages/wallet/src/redux/protocols/reducer-helpers.ts, packages/wallet/src/redux/sagas/messaging/message-handler.ts
Variations include:
- A challenges B, B responds and B clicks OK first
- A challenges B, B responds and A clicks OK first
- B challenges A, A responds and A clicks OK first
- B challenges A, A responds and B clicks OK first
And for each one of the above:
- A challenges and B responds before noticing the on-chain challenge 
- B challenges and A responds before noticing the on-chain challenge
=> [rps, wallet] Handle challenging in various variations of rps state changes

package.json, yarn.lock
Running typesync _only_ alters `package.json`, adding values such as `@types/foo` if it finds `foo` as a dependency. As such, any nontrivial change (that does not have `yarn` run afterwards) is just going to cause everyone who bases work from that commit to regenerate `yarn.lock`.
This fix isn't particularly nice, so open to alternative suggestions (such as not having tyepsync be  part of `prepare` at all...).
=> [monorepo] Run yarn install immediately after typesync

packages/client-api-schema/schema/notification.json, packages/client-api-schema/schema/push-message.json, packages/client-api-schema/schema/request.json
Currently json-schema-to-typescript doesn't support `const` in json schemas, so some interfaces being generated were invalid. I've just switched to `enum:["bla"]` which is functionally the same as `const`.
There is a PR to fix this but it hasn't been touched in a while unfortunately: https://github.com/bcherny/json-schema-to-typescript/pull/264
It looks like some of the interfaces we're generating are still not valid (like `Notification`) but I haven't investigated the cause.
=> Avoid using const in json schemas

packages/wallet-protocols/.eslintrc.js, packages/wallet-protocols/src/ChannelStoreEntry.ts, packages/wallet-protocols/src/__tests__/allocateToTarget.test.ts, packages/wallet-protocols/src/__tests__/integration.test.ts, packages/wallet-protocols/src/calculations.ts, packages/wallet-protocols/src/machine-utils.ts, packages/wallet-protocols/src/protocols/advance-channel/protocol.ts, packages/wallet-protocols/src/protocols/conclude-channel/protocol.ts, packages/wallet-protocols/src/protocols/create-channel/protocol.ts, packages/wallet-protocols/src/protocols/create-null-channel/protocol.ts, packages/wallet-protocols/src/protocols/depositing/protocol.test.ts, packages/wallet-protocols/src/protocols/depositing/protocol.ts, packages/wallet-protocols/src/protocols/direct-funding/protocol.ts, packages/wallet-protocols/src/protocols/funding/protocol.ts, packages/wallet-protocols/src/protocols/funding/test.ts, packages/wallet-protocols/src/protocols/join-channel/protocol.ts, packages/wallet-protocols/src/protocols/ledger-funding/protocol.ts, packages/wallet-protocols/src/protocols/partial-withdrawal/protocol.ts, packages/wallet-protocols/src/protocols/support-state/protocol.ts, packages/wallet-protocols/src/protocols/virtual-defunding-as-leaf/protocol.ts, packages/wallet-protocols/src/protocols/wallet/protocol.ts, packages/wallet-protocols/src/store.ts
I find this sorting style to look clean and be easy to understand what a file depends on relative to external modules and local files more easily than the previous unsorted way.
=> [wallet-protocols] Add sort-imports rules to wallet-protocols

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/need-help.md
Add issue templates that help us structure the discussions, cut through the noise and push the project forward.
I added two templates. Feel free to add more if needed.
=> Add Github issue templates

packages/xstate-wallet/src/workflows/confirm-create-channel.ts
Creates the workflow that handles confirming creating and joining a channel based on https://www.notion.so/0ee12a01ea684be095ca3b38909c9399?v=282f6c575af544e88924e7a1864a7a57&p=6ba5a9b3d85d467da9bb160986f8478d.
Visualizer here: https://xstate.js.org/viz/?gist=197d65fbc5f4dfa35865da66e8a156de
It seems that the actual `confirm-create-channel` workflow actually doesn't do much and can be re-used between either joining or creating a channel.
Marking as draft so we can discuss exactly what will be handled by the workflow versus handled outside of workflows.
I also experimented with some stricter typing.
Fixes #964
=> Confirm-Create-Channel workflow

packages/hub/package.json, yarn.lock
Somehow it was missing from `hub`, causing issues seen in #955
=> [hub] Add ethers to hub

packages/xstate-wallet/.storybook/main.js, packages/xstate-wallet/package.json, packages/xstate-wallet/src/ui/application-workflow.tsx, packages/xstate-wallet/src/ui/confirm-create-channel-workflow.tsx, packages/xstate-wallet/src/ui/stories/application-workflow.stories.tsx, packages/xstate-wallet/src/ui/stories/channel-id.stories.tsx, packages/xstate-wallet/src/ui/stories/confirm-create-channel-workflow.stories.tsx, packages/xstate-wallet/src/ui/stories/helpers.tsx, packages/xstate-wallet/src/ui/stories/index.stories.tsx, packages/xstate-wallet/src/ui/wallet.tsx, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/confirm-create-channel.ts
Plus some organisation of components and stories. The buttons work!
For now application workflow and confirm-create-channel workflow treated entirely independently -- this may change soon, see #969 .
=> [xsate-wallet] Add screen for confirm-create-channel workflow

packages/hub/src/hub/server.ts, packages/rps/src/index.tsx
This prevents everyone from being alerted (emailed) when some developer gets an error locally.
=> [hub, rps] Only initialize Sentry in production environment

packages/channel-client/src/channel-client.ts, packages/channel-client/src/types.ts, packages/channel-provider/src/types.ts, packages/client-api-schema/schema/get-ethereum-selected-address.json, packages/client-api-schema/schema/request.json, packages/client-api-schema/types/index.d.ts, packages/rps/.env, packages/rps/src/__stories__/index.tsx, packages/rps/src/containers/GameContainer.tsx, packages/rps/src/containers/SiteContainer.tsx, packages/rps/src/containers/__tests__/GameContainer.test.tsx, packages/rps/src/redux/game/saga.ts, packages/rps/src/redux/message-service/firebase-inbox-listener.ts, packages/rps/src/redux/message-service/message-queued-listener.ts, packages/rps/src/redux/metamask/actions.ts, packages/rps/src/redux/metamask/reducer.ts, packages/rps/src/redux/metamask/saga.ts, packages/rps/src/redux/metamask/state.ts, packages/rps/src/redux/open-games/saga.ts, packages/rps/src/redux/store.ts, packages/rps/src/utils/__tests__/rps-channel-client.test.ts, packages/rps/src/utils/rps-channel-client.ts, packages/wallet/src/json-rpc-validation/validator.ts, packages/wallet/src/redux/sagas/messaging/__tests__/message-handler.test.ts, packages/wallet/src/redux/sagas/messaging/message-handler.ts, packages/wallet/src/redux/sagas/messaging/message-sender.ts, packages/wallet/src/redux/sagas/messaging/outgoing-api-actions.ts
Get `window.ethereum.selectedAddress` via the wallet thru new json-rpc method. 
This pattern can be replicated for `web3torrent`.
+ Some refactoring of the open game saga in `rps`.
- Thin out `rps` metamask saga in `rps` (doesn't do much)
Fixes #955
=> [wallet,rps] Do not call ethereum.enable() from rps

packages/rps/package.json, packages/wallet/package.json
We started with `rps` and `wallet` Netlify sites being released on every `master` CI run. A couple weeks ago, we decided to deploy those these packages manually via the [deploy branch](https://github.com/statechannels/monorepo/tree/deploy). This PR removes `yarn` commands that release the packages in order to:
1. Turn off release on every `master` run.
1. Allow for only one release path (through the `deploy` branch).
`rps` and `wallet` (and all other Netlify sites) are still built on every `master` run.
=> Turn off netlify release for rps and wallet

patches/pure-evm+0.1.3.patch
There's a spammy `console.log` inside `pure-evm`
=> Remove console.log from pure-evm

.circleci/config.yml
Since the integration with hub test fails pretty consistently I think we should just remove it from circleCI now.
=> Disable Integration with Hub in CircleCI

packages/wallet-protocols/src/__tests__/createAndJoinoChannel.integration.test.ts, packages/wallet-protocols/src/__tests__/data.ts, packages/wallet-protocols/src/__tests__/directFunding.integration.test.ts, packages/wallet-protocols/src/__tests__/virtualFunding.integration.test.ts, packages/wallet-protocols/src/index.ts, packages/wallet-protocols/src/machine-utils.ts, packages/wallet-protocols/src/protocols/advance-channel/protocol.ts, packages/wallet-protocols/src/protocols/conclude-channel/protocol.ts, packages/wallet-protocols/src/protocols/create-and-direct-fund/protocol.ts, packages/wallet-protocols/src/protocols/create-channel/protocol.ts, packages/wallet-protocols/src/protocols/depositing/protocol.test.ts, packages/wallet-protocols/src/protocols/depositing/protocol.ts, packages/wallet-protocols/src/protocols/direct-funding/protocol.ts, packages/wallet-protocols/src/protocols/funding/protocol.ts, packages/wallet-protocols/src/protocols/join-channel/protocol.ts, packages/wallet-protocols/src/protocols/ledger-funding/protocol.ts, packages/wallet-protocols/src/protocols/support-state/protocol.ts, packages/wallet-protocols/src/protocols/virtual-fund-as-hub/protocol.ts, packages/wallet-protocols/src/protocols/virtual-fund-as-leaf/protocol.ts, packages/wallet-protocols/src/protocols/wallet/protocol.ts, packages/wallet-protocols/src/store.ts, packages/wallet-protocols/src/temp-store.ts, packages/xstate-wallet/src/index.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/ui/stories/application-workflow.stories.tsx, packages/xstate-wallet/src/ui/stories/confirm-create-channel-workflow.stories.tsx, packages/xstate-wallet/src/workflow-manager.ts, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/confirm-create-channel.ts, packages/xstate-wallet/src/workflows/tests/application.test.ts
Renames `Store` to `ObsoleteStore` so it's clear that the old store is no longer used.
=> Rename Protocol Store to Obsolete Store

.circleci/config.yml, packages/devtools/package.json, packages/jest-gas-reporter/package.json, packages/nitro-protocol/package.json, patches/@counterfactual+cf-adjudicator-contracts+0.0.11.patch, yarn.lock
1. Downgrade `solc` npm package since our contracts still use solidity version `^0.5.13`. `openzeppelin` does not support solidity version 0.6 yet, and our contracts import `openzeppelin` contracts.
1. Maybe more controversial. Do not use native solc on CircleCI. The downside is that the prepare step is 30 seconds slower. The upside the following. With native solc (installed through apt-get in the docker image), we are not able to control what version of solc is used. As a result, every time we rebuild the docker image, we are forced to upgrade to the latest solc package.
=> Downgrade solc, do not use native solc in CI

packages/xstate-wallet/src/store/memory-channel-storage.ts, packages/xstate-wallet/src/store/memory-store.test.ts, packages/xstate-wallet/src/store/memory-store.ts, packages/xstate-wallet/src/workflows/advance-channel.ts, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/create-and-direct-fund.ts, packages/xstate-wallet/src/workflows/support-state.ts
- Reverts statechannels/monorepo#1014
- Correctly uses `signState` in ported protocols
-  Replace `Record<string, SomeType>` with `Record<string, SomeType | undefined>`, forcing users to deal with non-existing entries.
=> Revert "Revert "Store states when they arrive""

packages/rps/package.json
The `channel-provider` is used in RPS webpack config but isn't a direct dependency:
https://github.com/statechannels/monorepo/blob/master/packages/rps/config/webpack.config.js#L141
This adds `@statechannels/channel-provider` as a devDependency of `RPS`
=> [rps] Add @statechannels/channel-provider as a devDependency of RPS

packages/xstate-wallet/.vscode/launch.json, packages/xstate-wallet/src/store/memory-channel-storage.ts, packages/xstate-wallet/src/store/memory-store.test.ts, packages/xstate-wallet/src/store/memory-store.ts, packages/xstate-wallet/src/store/state-utils.ts, packages/xstate-wallet/src/store/types.ts, packages/xstate-wallet/src/store/wire-protocol.ts, packages/xstate-wallet/src/utils.ts, packages/xstate-wallet/src/utils/allocation-utils.ts, packages/xstate-wallet/src/utils/outcome.ts, packages/xstate-wallet/src/workflows/conclude-channel.ts, packages/xstate-wallet/src/workflows/index.ts, packages/xstate-wallet/src/workflows/tests/virtual-funding.test.ts, packages/xstate-wallet/src/workflows/virtualFunding.ts
This PR adds a virtual funding workflow which works, except that guarantor channels are not created (or funded), and the indirect-funding service is mocked out.
Getting this to work required several other changes:
- Some bugs caused by unsafe use of spread operators are fixed.
- `sortedByTurnNum` is renamed to add clarity, and its implementation fixed
- A `sendMessage` method is placed on the store which simply emits a "Message sent" event.
- The `channelUpdatedFeed` feed is updated to include the current entry, if it exists, as the first value
- The `'channelUpdated'` event is emitted when a state is received
=> (Partial) Virtual funding workflow

packages/web3torrent/src/clients/web3torrent-client.ts, packages/web3torrent/src/components/torrent-info/upload-info/UploadInfo.stories.tsx, packages/web3torrent/src/library/paid-streaming-extension.ts, packages/web3torrent/src/library/types.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/utils/test-utils.ts
This PR implements a buffer-based payment model for the file transfering of Web3Torrent (in which the Seeder maintains a buffer or balance of each Leecher, and answers each request accordingly, after deducing the data cost).
In this PoC, I make several assumptions:
- Each request is worth the same (which isn't true, as some requests are smaller than average).
- The Leecher always pays after being blocked, a predefined amount ($50, or 5 requests).
- The amount of funds is assumed valid (I just pass a stringified number, though I'm counting that at some point it's going to be a transaction hash to verify).
Furthermore, the UI has not been updated to reflect the changes, this change has been done at the **library** layer.
#325
=> [Web3Torrent] POC of buffer-based payment system

packages/app-wallet-interface/package.json, packages/rps/package.json, packages/rps/src/components/CreatingOpenGameModal.tsx
At the moment, the hub does not withdraw funds deposited in the asset holder. A default game buy in of 0.5 eth ends up draining hub's Ropsten funds. Decreasing the game buy in to 0.05 eth will drain hub's funds 10 times slower.
=> RPS: Decrease default round buy-in from 0.1 eth to 0.01 eth

.circleci/config.yml
- Move non sensitive CircleCi environment variables from the Circle app to `config.yml` so that non-admins can see the variables and variables are tracked in version control.
- Turn on solc native compilation now that our contracts have been upgraded to solidity 0.6.
After this PR is merged, duplicated CircleCI variables should be deleted from CircleCI app. Fixes https://github.com/statechannels/monorepo/issues/1054.
=> CircleCI environment variables

.circleci/config.yml, package.json
- Decrease lerna concurrency to 2 for `build:ci` and `build:ci:incremental`.
- Log memory usage for CircleCi build step.
=> Build job out of memory errors

packages/xstate-wallet/src/store/memory-store.ts, packages/xstate-wallet/src/tests-with-chain/chain.test.ts, packages/xstate-wallet/src/workflows/depositing.ts, packages/xstate-wallet/src/workflows/direct-funding.ts
Currently methods from the `Chain` are made available on the `Store` through proxying - for each `Chain` method, there is a method with the same name and signature on the `Store`, which calls directly through to the corresponding `Chain` method.
In separate work, I've just added three new methods to the `Chain`, and it seems a bit sub-optimal to have to add each of these to the `Store` separately. There's also a question of whether the `Store` should be providing the `Chain` at all, or whether the `Chain` should be independently passed in to any protocols that require it; the `Store` itself doesn't currently call the `Chain` directly, other than to proxy the calls through.
This PR removes the proxied methods, instead exposing a `chain` method directly on the `Store`. This should make it …
=> Expose Chain directly on the Store, instead of proxying all methods

packages/xstate-wallet/bin/generateConfigs.ts, packages/xstate-wallet/package.json
`generateConfig` is now aware of globally defined typings. Fixes:
```
➜  xstate-wallet✗ npx ts-node src/generateConfigs.ts
Saving /statechannels/monorepo/packages/xstate-wallet/src/workflows/advance-channel.config.js
⨯ Unable to compile TypeScript:
src/messaging.ts:98:22 - error TS2339: Property 'ethereum' does not exist on type 'Window & typeof globalThis'.
98         await window.ethereum.enable();
~~~~~~~~
src/messaging.ts:131:25 - error TS2339: Property 'ethereum' does not exist on type 'Window & typeof globalThis'.
131       if (typeof window.ethereum.selectedAddress === 'string') {
~~~~~~~~
src/messaging.ts:132:24 - error TS2339: Property 'ethereum' does not exist on type 'Window & typeof globalThis'.
132         resolve(window.ethereum.selectedAddress);
~~~~~~~~ …
```
=> xstate-wallet: fix generateConfig

packages/nitro-protocol/bin/compile.js, packages/rps/bin/compile.js, packages/tic-tac-toe/bin/compile.js
My `yarn prepare` script was passing, even when contracts weren't compiling due to an incorrect solidity version. This PR throws on compile error rather than logging.
=> Throw on contract compilation errors

packages/xstate-wallet/src/workflows/application.ts
Remove `assignChannelId` from JOIN_CHANNEL transition. The action is triggered on entry to the `confirmJoinChannelWorkflow`.
=> Duplicate assignChannelId action

packages/channel-client/src/channel-client.ts, packages/channel-client/src/types.ts, packages/channel-client/tests/fakes/fake-channel-provider.ts, packages/rps/src/utils/__tests__/rps-channel-client.test.ts, packages/web3torrent/src/clients/payment-channel-client.ts
I renamed the method capitalized `CloseAndWithdraw` method to follow conventions with the rest.
Some methods still ignore the return values from channel-clients, e.g., 
- ~~acceptPayment~~
- approveBudgetAndFund
It's unclear whether we should take their return values and add them to cached states.
=> Update web3torrent calls

packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/event-types.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/utils/workflow-utils.ts, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/tests/application.test.ts
Previously we converted from the `client-api-schema` types in several places: the `MessagingService`, the `ChannelWallet`, and the `ApplicationWorkflow`. This PR:
1. Pulls out the internal event types (previously defined in the `ApplicationWorkflow`) out into their own file.
2. Moves all conversion from `client-api-schema` types to internal events into the `MessagingService`
=> Move event conversion to MessagingService

packages/web3torrent/package.json, packages/web3torrent/src/library/web3torrent-lib.ts, yarn.lock
This PR tries to improve clarity around the role of the `buffer` (previously known as the `funds`, which is kept by the seeder per torrent and per leecher, and used to decide when to choke them / prompt them to pay us). 
Choices:
- The buffer should have units of "pieces" (in the near future, probably "bytes", but *not* ETH or wei)
- Conversion factor is a new constant, available to seeders and leechers and easily tuneable.
- The threshold for unchoking is when the buffer is nonzero (previously, at a positive constant called `REQUEST_RATE`)
- The number of pieces that a leecher is prepared to pay for upfront in each payment is another tuneable constant  `BUFFER_REFILL_RATE`
=> [web3t] Overhaul buffer system

packages/rps/.env
Fix a few spelling mistakes.
Also is this used? `ETH_ACCOUNT_MNENOMIC`
`Mnenomic` is not a word but I can't find usages anywhere :)
=> chore: Fix spelling mistakes

packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/integration-tests/funding.test.ts, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/tests/application.test.ts
While incorporating virtual-funding into the create-and-fund workflow, I ran into the issue of validating the app definition and data before supporting the first state. It turns out that there's no benefit to validating the first state at a later point -- the only code capable of validating the first state is the application itself. Therefore, when the app calls JOIN_CHANNEL, the wallet should assume an acceptable first state, and might as well sign it straight away.
=> Sign on join channel

packages/channel-client/tests/channel-client.test.ts
I think the current failing test on `master` was due to was one of those rare cases where tests passed both on `master` and `feature` pre-merge, there were no merge conflicts, but the merge caused the test to fail because `feature` was built against an out of date `master`.
=> [channel-client] Update new test to multi-channel pattern

packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx
If `wire` is `undefined` (because the connection dropped; browser is closed by peer for example) then the page threw an error.
=> [web3t] Handle undefined wire in web3 ChannelList

packages/xstate-wallet/.storybook/main.js, packages/xstate-wallet/src/ui/stories/application-workflow.stories.tsx, packages/xstate-wallet/src/ui/stories/confirm-create-channel-workflow.stories.tsx, packages/xstate-wallet/src/ui/stories/helpers.tsx
This gets storybook functioning in `xstate-wallet` again. Storybook was broken when we started using nested workflows.
The fix I've implemented isn't too elegant but I think it should be good enough to allow us to develop the UI using storybook.
Fixes #1114
=> Get storybook working again

packages/channel-client/src/channel-client.ts, packages/channel-client/src/types.ts, packages/channel-client/tests/fakes/fake-channel-provider.ts, packages/channel-provider/src/types.ts, packages/client-api-schema/src/generated-schema.json, packages/client-api-schema/src/types.ts, packages/rps/src/utils/__tests__/rps-channel-client.test.ts, packages/simple-hub/src/blockchain/__chain-test__/deposit.test.ts, packages/web3torrent/src/clients/payment-channel-client.ts, packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/event-types.ts, packages/xstate-wallet/src/integration-tests/create-budget.test.ts, packages/xstate-wallet/src/integration-tests/helpers.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/serde/app-messages/deserialize.ts, packages/xstate-wallet/src/serde/app-messages/serialize.ts, packages/xstate-wallet/src/store/memory-store.ts, packages/xstate-wallet/src/store/types.ts, packages/xstate-wallet/src/ui/approve-budget-and-fund-workflow.tsx, packages/xstate-wallet/src/ui/selectors.ts, packages/xstate-wallet/src/ui/stories/approve-budget-and-fund-workflow.stories.tsx, packages/xstate-wallet/src/workflows/approve-budget-and-fund.ts, packages/xstate-wallet/src/workflows/confirm-create-channel.ts, packages/xstate-wallet/src/workflows/create-budget-and-fund.ts
Adds support for budgets in the `xstate-wallet`
It adds support for the following API calls:
- `getBudget` : Returns the current budget for a `hubAddress`.
- `approveBudgetAndFund`: Starts a new workflow that asks for user approval and starts ledger funding(mocked out)
=> Basic Budgeting Functionality

packages/web3torrent/src/library/paid-streaming-extension.ts, packages/web3torrent/src/library/types.ts, packages/web3torrent/src/library/web3torrent-lib.ts
This PR should close #1148
There were quite a lot of issues that caused the issue:
- The **STOP** and **START** messages were being emitted and handled several times (on response to each blocked request). This provoked that sometimes funds were being transferred more than once. It also affected the process of jumpstarting the download and provoked several inconsistencies.
**Solutions:** 
I added a message interceptor at the wire level, that automates things, avoids message repetition at the leecher side, and adds some encapsulation to the wire.
I also added more checks in the stop() and start() methods to avoid spamming the leecher with messages, if possible.
- _The **REQUEST** interceptor implementation was horrible_, and I hate myself for leaving it as it was 'till now. It was hard to …
=> [WIP] Fix inconsistent pricing 

packages/web3torrent/src/library/client-seeding.test.ts, packages/web3torrent/src/library/web3torrent-lib.ts
Fixes https://github.com/statechannels/monorepo/issues/1099
Fake client has a very subtle bug that makes the skipped test failed and the wrong turn error we saw:
~~The bug was due to fake client sets the wrong turn number when a participant joins the channel.~~
=> Fix skipped test

packages/web3torrent/src/components/torrent-info/TorrentInfo.test.tsx, packages/web3torrent/src/components/torrent-info/TorrentInfo.tsx, packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx, packages/web3torrent/src/components/torrent-info/download-info/DownloadInfo.tsx, packages/web3torrent/src/components/torrent-info/upload-info/UploadInfo.tsx
Reflects fact that I can start uploading at any point after I start leeching, and in particular *before* I become a seeder. A seeder is someone who has the whole file.
With the existing condition in place, there's no evidence of the channels that I open to allow peers to download from me (unless I happen to be a seeder).
=> [web3t] Display UploadInfo unconditionally 

packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/library/web3torrent-lib.ts
The "spacer state" is the state channel update with `turnNum = 4`. 
It's awkward to handle, but an important inevitable consequence of the following choices: 
- unidirectional ForceMove payment channel with beneficiary in slot `0`
- vanilla ForceMove turn-taking
At the state channel layer, we should have the following sequence, with uploader as `0` and downloader as `1`:
```
0: createChannel, turnNum = 0
1: joinChannel() turnNum = 1
0: turnNum = 2
1: turnNum = 3 <<-- fake provider updates straight to here on joinChannel()
0: acceptChannelUpdate(), turnNum = 4 <<--- "spacer state"
1: makePayment(), turnNum = 5
0: acceptChannelUpdate(), turnNum = 6
...
1: makePayment(), turnNum = 2n+3
0: acceptChannelUpdate(), turnNum = 2n+4
```
According to this PR, in the web3torrent code, we do not …
=> [web3t] Clarify logic around "spacer" state

packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx, packages/web3torrent/src/library/types.ts
Currently the `DownloadInfo` component does not display the number of bytes downloaded. 
This was because 
1. TypesScript was telling me that `downloaded` was not a property on my `wire` (when actually it is). 
2. I had thought that perhaps `uploaded` would be the same as `downloaded` on a wire. But it's a duplex connection so I guess my `uploaded` is your `downloaded`. Fine.
=> [web3t] Fix downloaded = 0 in the UI

packages/simple-hub/readme.md, packages/simple-hub/src/constants.ts, packages/simple-hub/src/message/firebase-relay.ts, packages/simple-hub/src/wallet/index.ts, packages/simple-hub/src/wallet/test-helpers/index.ts
And rename constants/environment variables.
- `HUB_CHANNEL_PK`/`cHubChannelPK`: state channel private key for supporting states.
- `cHubChannelSigningAddress`: state channel public key. Never hardcoded.
- `HUB_CHAIN_PK`/`cHubChainPK`: ethereum private key used for chain transaction signing.
- `cHubChainAddress`: ethereum address. Never hardcoded.
- `HUB_PARTICIPANT_ID`/`cHubParticipantId`: state channel messaging address.
=> simple-hub: add hub participantId

packages/web3torrent/src/App.tsx, packages/web3torrent/src/library/web3torrent-lib.ts
The simple idea is to try and download the example torrent used on the webtorrent.io homepage when we enable the `WebTorrentPaidStreamingClient`. As soon as we get a WIRE event, cancel and raise a success flag. If this doesn't resolve in 3 seconds, raise a failure flag. 
We can hook this into another `ConnectionBanner` type component that informs the user: "Looks like you are behind a firewall or do not have an internet connection".
I tested this with my home WiFI on/off. 
TODO 
- test on public wifi / with typical firewall or blocked ports
- is a WIRE event enough of a signal that things should work?
Closes #1129
=> [web3t] Detect public wifi / firewall / lack of internet

packages/web3torrent/src/components/share-list/ShareList.test.tsx, packages/web3torrent/src/components/share-list/share-file/ShareFile.tsx, packages/web3torrent/src/components/torrent-info/TorrentInfo.tsx, packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx, packages/web3torrent/src/components/torrent-info/download-info/DownloadInfo.tsx, packages/web3torrent/src/components/torrent-info/upload-info/UploadInfo.test.tsx, packages/web3torrent/src/components/torrent-info/upload-info/UploadInfo.tsx, packages/web3torrent/src/utils/calculateWei.ts, packages/web3torrent/src/utils/prettyPrintWei.test.ts
This is an experiment and I'm not 100% sure if we want to do it:
Downsides: 
- increased "change blindness" (not so easy to see you are actually making payments when the numbers are big)
- rounding is not done correctly (not a big deal and definitely fixable with a bit more work).
=> [web3t] Introduce prettyPrintWei() function

packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/library/types.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/utils/test-utils.ts
Currently 
(1) I will send all `onChannelUpdated` messages messages down all wires, and
(2)The `PaymentChannelClient` will happily cache states for unknown channels.
This PR fixes both 1 and 2.
It also includes some TODOs for hub messaging (soon to be implemented)
=> [web3t] Fix messaging bug

packages/rps/src/redux/game/saga.ts
Forks the `joinChannel` call so `ChannelUpdated` event's don't get ignored while blocking on `JoinChannel` to resolve.
=> Fix player B getting stuck on game proposed

packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/ui/selectors.ts
Fixes #1235 
Currently `rps` will call `JoinChannel` any time it receives a `ChannelUpdated` event. Right now it seems that we're sending out multiple `ChannelUpdated` events (possibly related to #1237)
The `xstate-wallet` ends up creating multiple workflows for each `JoinChannel` request, ending up with multiple `Application` workflows running, causing issues with the UI.
To safeguard this I've added deterministic workflowIds for some of the events so we can detect the duplicate call and avoid starting a workflow.
Longer term:
-`RPS` should probably be more careful about making duplicate calls 
- The `xstate-wallet` should not be sending out duplicate `ChannelUpdated` events (this might be resolved by #1237?)
=> Handle duplicate Join Channel

packages/xstate-wallet/package.json, packages/xstate-wallet/src/serde/app-messages/serialize.ts, packages/xstate-wallet/src/store/channel-store-entry.ts, packages/xstate-wallet/src/store/index.ts, packages/xstate-wallet/src/store/memory-channel-storage.ts, packages/xstate-wallet/src/store/memory-store.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/store/types.ts, packages/xstate-wallet/src/ui/selectors.ts, packages/xstate-wallet/src/utils/budget-utils.ts, packages/xstate-wallet/src/workflows/approve-budget-and-fund.ts, packages/xstate-wallet/src/workflows/create-and-fund.ts, packages/xstate-wallet/src/workflows/tests/create-and-fund.test.ts, packages/xstate-wallet/src/workflows/tests/store.ts, packages/xstate-wallet/src/workflows/tests/virtual-defunding.test.ts
This adds a state `reservingFunds` before invoking the virtual-funding machine. This state invokes `reserveFunds`, which calls a new store method `reserveFunds`.
=> Add budgets to create-and-fund workflow.

packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/utils/calculateWei.ts
Fix: https://github.com/statechannels/monorepo/issues/1215
Added a fix to fall back to channel cache to calculate the download size.
Also put in a fix to handle a random crash when the channel cache is not available.
WIP: When leechers cancels the download, wire is dropped but the channel is still running.
=> web3torrent: handle dropped wires

packages/channel-client/jest.config.js, packages/channel-client/src/channel-client.ts, packages/channel-client/src/index.ts, packages/channel-client/src/types.ts, packages/channel-client/tests/channel-client.test.ts, packages/channel-client/tests/fake-channel-client.test.ts, packages/channel-client/tests/fakes/fake-channel-provider.ts, packages/channel-provider/src/channel-provider.ts, packages/channel-provider/src/types.ts, packages/channel-provider/tests/channel-provider.test.ts, packages/client-api-schema/src/generated-schema.json, packages/client-api-schema/src/types.ts, packages/rps/src/redux/message-service/firebase-inbox-listener.ts, packages/rps/src/redux/message-service/message-queued-listener.ts, packages/rps/src/utils/rps-channel-client.ts, packages/wallet/src/redux/sagas/messaging/message-handler.ts, packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/library/web3torrent-lib.ts
This work was spurred by seeing runtime errors due to unexpected types emitted from the provider, as well as discrepancy in types coming from fake vs real providers. 
I believe the second issue to be solved by this PR.
The first issue is not (and possibly cannot be) solved by tinkering with types in the provider. But we can probably diagnose the issue by doing validation of messages *from* the wallet against our schema (see #1266 ) . That work should be much easier given the greater clarity that (I hope) this PR brings to the various JSON RPC types.
=> [channel-provider/client] Add types to ChannelProvider events

packages/rps/package.json, packages/tic-tac-toe/app/services/ttt-channel-client.ts, packages/tic-tac-toe/package.json
Fixes a type import error.
An import was moved in this PR and wasn't update for TTT.
https://github.com/statechannels/monorepo/pull/1264
This also adds `@statechannels/client-api-schema` as a devDependency of RPS and TTT as they both import from this package.
=> [TTT] Fix type import errors

packages/web3torrent/package.json
Brings it into line with our other apps -- it is necessary to run this command before `yarn start`
=> [web3t] Add start:shared-ganache script to web3t

packages/channel-client/tests/fakes/fake-channel-provider.ts, packages/web3torrent/src/library/web3torrent-lib.ts
Fix error not noticed in tests due to `tic-tac-toe` error overtaking it... merged too recklessly.
=> [w3t] Patch un-enabled provider on w3t

packages/rps/package.json, packages/wallet/package.json, packages/xstate-wallet/package.json
The upside of including `build:netlify` is that CI tests that all packages hosted on netlify can be built for netlify when the package changes and on all master CI runs. The downside is that we are seeing [out-of-memory errors](https://app.circleci.com/pipelines/github/statechannels/monorepo/4464/workflows/7f137d70-7283-49b9-a440-68e22a5ba936/jobs/16026) even with concurrency set to 2.
=> Remove build:netlify from packages with manual netlify deployment

packages/xstate-wallet/src/integration-tests/approve-budget.test.ts, packages/xstate-wallet/src/integration-tests/close-withdraw.test.ts, packages/xstate-wallet/src/integration-tests/closing.test.ts, packages/xstate-wallet/src/integration-tests/helpers.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/serde/wire-format/serde.test.ts, packages/xstate-wallet/src/serde/wire-format/serialize.ts, packages/xstate-wallet/src/store/channel-store-entry.ts, packages/xstate-wallet/src/store/memory-channel-storage.ts
Currently tests will fail due to the increased checking that is being done.  Assuming the `wire-format` is correct, looks like there is some work to do ensuring messages end up being serialized in a way that is consistent with that.
=> [xstate-wallet] Validate messages in + out

package.json, yarn.lock
I periodically see errors like this when committing:
```
@statechannels/rps:   ✖ lint-staged failed due to a git error.
@statechannels/rps:   Any lost modifications can be restored from a git stash:
@statechannels/rps:     > git stash list
@statechannels/rps:     stash@{0}: On master: automatic lint-staged backup
@statechannels/rps:     > git stash pop stash@{0}
@statechannels/rps: error Command failed with exit code 1.
@statechannels/rps: info Visit https://yarnpkg.com/en/docs/cli/run for document
```
I believe others have struggled with this as well. The root cause seems to be running multiple `lint-staged` commands in parallel.
=> Run precommit hooks sequentially

packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/constants.ts, packages/web3torrent/src/library/testing/setup.js, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/tsconfig.json, packages/xstate-wallet/.env
When transitioning from the fake provider to a real wallet, channel updates are going to get significantly slower due to the burden of managing signatures. Meanwhile, web3torrent messages that do not involve the wallet will be relatively fast. 
This means that although the seeder will send the spacer state, *then* prompt the leecher to make a payment, the leecher may well respond to the prompt before the channel has been updated in their client.
=> [web3torrent] Fix possible race condition

packages/xstate-wallet/.vscode/launch.json
Great reference doc: [https://github.com/microsoft/vscode-chrome-debug](https://github.com/microsoft/vscode-chrome-debug)
- Launch chrome via `/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222 --user-data-dir=[PATH TO DIR STORING CHROME USER DATA]/chrome-debug`. Reading [this](https://github.com/microsoft/vscode-chrome-debug#cannot-connect-to-the-target-connect-econnrefused-1270019222) will clarify the command.
- Run *Attach to running wallet* in VSCode.
- Set breakpoints to your heart's content.
=> xstate-wallet: add launch config for attaching to chrome

packages/web3torrent/src/utils/calculateWei.ts
For large values (like 10 ETH) `toNumber` would overflow and throw an error.
=> Use toString instead of toNumber when calculating wei display value

packages/xstate-wallet/src/store/state-utils.ts, packages/xstate-wallet/src/store/tests/outcomes-equal.test.ts, packages/xstate-wallet/src/workflows/conclude-channel.ts
Currently this function does not understand that (e.g.)   '0x02' and '0x2' are equal.
=> [xstate-wallet] Improve outcomesEqual utility function.

packages/xstate-wallet/src/store/channel-store-entry.ts
Currently the `supported` check doesn't work correctly, resulting in no states being deleted and the GC code eating up the CPU.
This is a workaround for that until I finish more extensive refactoring/ implementing proper `supported` related functions.
See https://github.com/statechannels/monorepo/issues/1344
=> Temporarily disable GC states

.vscode/launch.json, .vscode/settings.json, packages/xstate-wallet/package.json, packages/xstate-wallet/src/chain.ts, packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/index.ts, packages/xstate-wallet/src/integration-tests/approve-budget.test.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/render.tsx, packages/xstate-wallet/src/store/index.ts, packages/xstate-wallet/src/ui/approve-budget-and-fund-workflow.tsx, packages/xstate-wallet/src/ui/enable-ethereum-workflow.tsx, packages/xstate-wallet/src/ui/stories/approve-budget-and-fund-workflow.stories.tsx, packages/xstate-wallet/src/ui/stories/confirm-create-channel-workflow.stories.tsx, packages/xstate-wallet/src/ui/wallet.tsx, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/approve-budget-and-fund.ts, packages/xstate-wallet/src/workflows/close-ledger-and-withdraw.ts, packages/xstate-wallet/src/workflows/confirm-create-channel.ts, packages/xstate-wallet/src/workflows/ethereum-enable.ts, packages/xstate-wallet/src/workflows/tests/approve-budget-and-fund.test.ts, packages/xstate-wallet/src/workflows/tests/message-service.ts, yarn.lock
This PR flattens out the approve budget workflow, so there's one top level machine that only invokes promises/observables (and not other machines). It adds the ability to view this machine, by navigating to localhost:3055, and using the xstate-devtools.
Todo in later work:
* Make the submitTransaction and deposit sub-machines re-usable
=> Refactor approve budget workflow

packages/web3torrent/package.json, packages/web3torrent/src/components/share-list/ShareList.test.tsx, packages/web3torrent/src/components/share-list/share-file/ShareFile.scss, packages/web3torrent/src/components/share-list/share-file/ShareFile.tsx, packages/web3torrent/src/constants.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/pages/welcome/Welcome.tsx
Current behaviour: There are 3 torrents on the Welcome page. Clicking on Download will connect you, via a public tracker, to any webtorrent client (bypassing state channels flow). 
With this PR: The Welcome page is now a class that wraps a bittorrent tracker client, connects to *only* our whitelisted tracker(s) (not the public ones!) and will display a torrent if it can find at least one seeder on that tracker. When clicking, you have to do the proper state-channels-enabled flow as you would when sharing a magnet link. 
Closes #1331 .
TODO:
=> [web3t] Torrents on welcome screen are *our* pre-seeded torrents

packages/xstate-wallet/src/integration-tests/closing.test.ts, packages/xstate-wallet/src/serde/wire-format/deserialize.ts, packages/xstate-wallet/src/serde/wire-format/example.ts, packages/xstate-wallet/src/serde/wire-format/serde.test.ts, packages/xstate-wallet/src/serde/wire-format/serialize.ts, packages/xstate-wallet/src/store/channel-store-entry.ts, packages/xstate-wallet/src/store/state-utils.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/store/tests/indexedDB-store.test.ts, packages/xstate-wallet/src/store/tests/memory-store.test.ts, packages/xstate-wallet/src/store/types.ts, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/close-ledger-and-withdraw.ts, packages/xstate-wallet/src/workflows/conclude-channel.ts, packages/xstate-wallet/src/workflows/support-state.ts, packages/xstate-wallet/src/workflows/tests/application.test.ts, packages/xstate-wallet/src/workflows/tests/create-and-fund.test.ts, packages/xstate-wallet/src/workflows/tests/ledger-funding.test.ts, packages/xstate-wallet/src/workflows/tests/simple-hub.ts, packages/xstate-wallet/src/workflows/tests/store.ts, packages/xstate-wallet/src/workflows/tests/virtual-defunding.test.ts, packages/xstate-wallet/src/workflows/tests/virtual-funding.test.ts, packages/xstate-wallet/src/workflows/virtual-funding-as-hub.ts, packages/xstate-wallet/src/workflows/virtual-funding-as-leaf.ts
Changes the storage of states to use a simple array and update the `support` and `supported` functions to perform an actual supported check instead of relying on the amount of signatures.
Running after this change I'm seeing less cpu usage and download speeds of `2-4MB/s`.
Fixes #1344
=> Add proper support check, refactor state storage

.circleci/config.yml, packages/e2e-tests/puppeteer/__tests__/rps.test.ts, packages/e2e-tests/puppeteer/__tests__/web3torrent.test.ts, packages/e2e-tests/puppeteer/helpers.ts, packages/e2e-tests/puppeteer/scripts/rps.ts, packages/e2e-tests/puppeteer/scripts/web3torrent.ts, packages/e2e-tests/tsconfig.json, packages/web3torrent/src/components/form/form-button/FormButton.tsx, packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx, packages/web3torrent/src/components/torrent-info/download-info/DownloadInfo.tsx, packages/web3torrent/src/components/torrent-info/magnet-link-button/MagnetLinkButton.tsx
Addresses: https://github.com/statechannels/monorepo/issues/1328
Assumption: The browser setup of web3torrent is the same as rps, so I reuse the helper functions.
=> Web3torrent: Add end-to-end tests with Puppeteer

packages/xstate-wallet/src/store/channel-store-entry.ts, packages/xstate-wallet/src/store/tests/channel-store-entry.test.ts
Fixes #1366
Adds a simplistic validTransition check when calculating the support and some basic tests.
We will probably want to replace this with a proper check at some point(#1186)
=> Add simple valid transition check in support

.circleci/config.yml, packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/integration-tests/funding.test.ts, packages/xstate-wallet/src/serde/wire-format/serialize.ts, packages/xstate-wallet/src/store/channel-store-entry.ts, packages/xstate-wallet/src/store/index.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/store/types.ts, packages/xstate-wallet/src/ui/confirm-create-channel-workflow.tsx, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/create-and-fund.ts, packages/xstate-wallet/src/workflows/tests/application.test.ts, packages/xstate-wallet/src/workflows/tests/store.ts
With these changes, I was able to virtually fund a web3torrent channel:
```
$ state-channels-monorepo
❯ yarn start:shared-ganache
$ xstate-wallet
❯ CLEAR_STORAGE_ON_START=true USE_INDEXED_DB=true  ADD_LOGS=true yarn start
$ simple-hub
❯ FIREBASE_PREFIX=web3t-andrew  NODE_ENV=development yarn hub:watch
$ web3-torrent
❯ REACT_APP_FIREBASE_PREFIX=web3t-andrew REACT_APP_AUTO_FUND_LEDGER=true yarn start
```
TODO:
`CLEAR_STORAGE_ON_START=true` and `REACT_APP_AUTO_FUND_LEDGER=true` seem to be necessary because on reload, the chain does not fetch the data from the adjudicator's current state.
=> (Mostly) budget-related fixes

packages/web3torrent/src/library/web3torrent-lib.ts
There was an issue where torrents having a size smaller than the number of requests in trust_ would get overpaid because an oversight that I made in the calculations of how much to pay.
Basically, I assumed erroneously that the initial amount of requests is always the máximum amount in trust, and I did not account for small torrents. So if I had, say, TRUST set to 4, a torrent of 30kb would pay for 4 requests minus the difference between the last piece size, and the standard request size.
This PR fixes that. And it also makes it clearer to read. And fixes a log message that for some reason was showing the balance in hexadecimal format.
=> [W3T] Fix small torrents payments with big (>1) trust overpayment

packages/simple-hub/manual-test/firebase-feeder.ts, packages/simple-hub/package.json, packages/simple-hub/src/message/firebase-relay.ts, packages/simple-hub/src/server.ts, yarn.lock
Fixes https://github.com/statechannels/monorepo/issues/1374 and removes the short-term fix of https://github.com/statechannels/monorepo/pull/1373.
[`respondToMessage`](https://github.com/statechannels/monorepo/blob/6ddd4e39affc104f982ee8848dfb97b33b458159/packages/simple-hub/src/server.ts#L26) and [`depositsToMake`](https://github.com/statechannels/monorepo/blob/6ddd4e39affc104f982ee8848dfb97b33b458159/packages/simple-hub/src/server.ts#L31) are pure functions that can throw errors. To address errors:
- delete the firebase entry as the first operation. If the firebase entry is not deleted, when `fbObservable` is re-subscribed (via `retryWhen` operator), the observable will emit the message that caused the error. This leads to an infinite loop.
- log error before re-subscribing to the …
=> simple-hub: do not crash out on errors

packages/xstate-wallet/src/index.ts, packages/xstate-wallet/src/store/store.ts
We do not have any plans for how to manage multiple private keys. Limiting the number of stored private keys to one reduces the number of things that can (and are) going wrong.
This change, in particular, will mean that the wallet will use a consistent `participantId` across sessions. This invariant lets the wallet re-use a ledger channel from the indexedDB store from a previous session.
=> Generate at most one random private key

packages/xstate-wallet/src/serde/wire-format/serialize.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/workflows/ledger-funding.ts, packages/xstate-wallet/src/workflows/tests/ledger-funding.test.ts, packages/xstate-wallet/src/workflows/tests/virtual-funding.test.ts, packages/xstate-wallet/src/workflows/virtual-funding-as-hub.ts, packages/xstate-wallet/src/workflows/virtual-funding-as-leaf.ts
While working on virtual funding puppeteer tests with @snario, we found the reason why the simple-hub was not able to read messages: during serialization, guarantee outcomes are stripped: 7c6aeb7.
This lead me to realize that the virtual-funding workflows create the guarantor channels, then move to the next step before that channel has a supported "prefund setup" state.
This PR adds a defensive "checking target" state for validating the state of the target channel when ledger funding.
Virtual funding was then fixed to account for the missing step.
=> Ledger safety + Virtual funding fix

packages/web3torrent/src/App.test.tsx, packages/web3torrent/src/App.tsx, packages/web3torrent/src/components/torrent-info/download-info/DownloadInfo.test.tsx, packages/web3torrent/src/components/torrent-info/upload-info/UploadInfo.test.tsx, packages/web3torrent/src/constants.ts, packages/web3torrent/src/library/types.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/pages/upload/Upload.tsx, packages/web3torrent/src/pages/welcome/Welcome.tsx
This PR
- adds support for secure WebSocket connections to the tracker (_wss_).
- moves the Web3TorrentClient network capability testing to the Web3TorrentClient constructor, but only for non-testing environments as this causes problems with tests.
- refactors the app component, and the welcome and upload pages.
- un-skips all the unit tests that were being skipped, and removes non-representative tests.
=> Private Tracker Deployment Preparation, Client Capability Testing improvements

packages/web3torrent/.vscode/launch.json, packages/web3torrent/src/App.tsx, packages/web3torrent/src/constants.ts
The main benefit of the refactor is that it flagged most state as unneeded. `requiredNetwork `, `canTorrent` and `showNetworkWarning` states keys are removed.
My preference is to use React function component going forward when possible.
=> web3torrent: refactor App component as a function component

packages/web3torrent/src/components/share-list/ShareList.tsx, packages/web3torrent/src/components/share-list/share-file/ShareFile.stories.tsx, packages/web3torrent/src/components/share-list/share-file/ShareFile.tsx
`ShareFile` has enough information to construct the click handler. So no need to pass the click handler as a prop.
=> web3torrent: clean up ShareFIle click handling

packages/web3torrent/src/clients/web3torrent-client.test.ts, packages/web3torrent/src/clients/web3torrent-client.ts, packages/web3torrent/src/components/torrent-info/download-link/DownloadLink.tsx, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/utils/file-saver.ts
With Torrents that consisted of several files, the naming logic in WebTorrent was not working (at least on Linux), the name of the created torrent was simply one of the files selected, which is kind of misleading for the leecher.
This PR generates a name for the torrent if the torrent has multiple files. The name consists of `"various_"+ the last 5 digits of the Date.now() + ".zip"`.
Added to that, this also sets that name to the zip file when downloaded.
=> Fix multi-file Torrents naming

packages/web3torrent/src/pages/file/File.tsx, packages/web3torrent/src/utils/torrent-status-checker.ts
- Use `function` syntax when possible. I am finding a constant that defines a function (with Typescript types sprinkled in there) pretty hard to parse. If others agree, please use `function` syntax going forward (when possible).
- `File` component has a `useContext` hook now, so we can remove `Web3TorrentContext.Consumer`. In general, I might be a good idea to minimize the logic inside jsx and instead use jsx primarily to describe UI.
=> [web3torrent] Clean up File component

packages/e2e-tests/puppeteer/__tests__/web3torrent/seed-download.test.ts, packages/e2e-tests/puppeteer/helpers.ts, packages/e2e-tests/puppeteer/scripts/web3torrent.ts, packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/workflows/conclude-channel.ts
- Add a `waitForNthState` e2e helper, and use in the test. This ensures we are testing that some data is actually being transferred
- Fixes an issue in web3torrent where the `channelCache` may be undefined when it's used
- Adds a hack to `updateChannelCache` to always set the channel cache, even when the channel is unknown (see https://github.com/statechannels/monorepo/issues/1438#issuecomment-614159943)
=> More robust integration test

packages/web3torrent/src/clients/payment-channel-client.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/tests/application.test.ts
Fixes #1438 .
We weren't assigning the `requestId` as the joiner, which meant that the `JoinChannel` response would not contain an id and thus the `channel-provider` would never resolve the `joinChannel` call.
=> Assign Request Id for joiner in application workflow

packages/e2e-tests/puppeteer/helpers.ts, packages/e2e-tests/puppeteer/scripts/web3torrent.ts, packages/xstate-wallet/src/chain.ts, packages/xstate-wallet/src/ui/enable-ethereum-workflow.tsx
based on / supersedes #1457
The integration tests were setting up `window.ethereum` and relying on specific wallet behaviour to skip the Enable Ethereum user prompt. When the `EnableEthereum` behavior changed this broke the integration tests.
This PR updates the integration tests to work with the latest changes in `EnableEthereum` and to click thru the enable ethereum prompt.
=> Get integration tests passing

packages/web3torrent/src/App.tsx, packages/web3torrent/src/constants.ts, packages/web3torrent/src/library/types.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/pages/file/File.scss, packages/web3torrent/src/pages/file/File.tsx, packages/web3torrent/src/pages/welcome/Welcome.tsx, packages/web3torrent/src/utils/checkTorrentInTracker.ts
Adds status checks for individual torrents (closes #1423 ) . The status check test consists of a separate tracker client than the one on the web3torrent client. This tracker looks up the torrent on web3torrent's tracker server, with 3 possible results:
- **Seeders found:** the tracker client had responses from the server, and was able to find an active peer. The warning is not shown at all.
- **No seeders found:** the tracker client got responses from the tracker but wasn't able to find an active peer. Might mean that the torrent doesn't have seeders, but it could also mean that the tracker is slow, or the seeder has a slow connection.
- **No connection:** there was no answer at all from the tracker server, which might mean network connections.
_Warnings don't disable any buttons or …
=> remove global network check, add initial  torrent check

packages/web3torrent/src/utils/checkTorrentInTracker.ts
should fix #1472 
To understand the change of this PR, taking a look at the [bittorrent-tracker docs](https://github.com/webtorrent/bittorrent-tracker#client) its advisable.
The previous implementation of the check was a deeper emulation of the web torrent's tracker client behaviour, but it seems that emulating that and suddenly stopping and destroying the tracker client is problematic.
So basically, what this does, is that the [tracker client waits for a couple of seconds](https://github.com/statechannels/monorepo/compare/sp/tracker-check-fix?expand=1#diff-54c06577239cf26700fa05ec63e79884R15), and then scraps the tracker server for information. This way, the tracker server gives us a more accurate response. The implementation gets simpler too.
I also added some logs for the test so it …
=> fix tracker check, add logs

packages/web3torrent/src/clients/web3torrent-client.test.ts, packages/web3torrent/src/clients/web3torrent-client.ts, packages/web3torrent/src/components/torrent-info/TorrentInfo.test.tsx, packages/web3torrent/src/components/torrent-info/download-info/DownloadInfo.stories.tsx, packages/web3torrent/src/components/torrent-info/download-info/DownloadInfo.test.tsx, packages/web3torrent/src/components/torrent-info/download-link/DownloadLink.stories.tsx, packages/web3torrent/src/components/torrent-info/download-link/DownloadLink.test.tsx, packages/web3torrent/src/components/torrent-info/upload-info/UploadInfo.stories.tsx, packages/web3torrent/src/components/torrent-info/upload-info/UploadInfo.test.tsx, packages/web3torrent/src/constants.ts, packages/web3torrent/src/pages/file/File.test.tsx, packages/web3torrent/src/pages/upload/Upload.test.tsx, packages/web3torrent/src/pages/upload/Upload.tsx, packages/web3torrent/src/types.ts, packages/web3torrent/src/utils/test-utils.ts, packages/web3torrent/src/utils/torrent-status-checker.test.ts, packages/web3torrent/src/utils/url.test.ts, packages/web3torrent/src/utils/url.ts
There are currently 4 Typescript types for torrent objects:
- `Webtorrent.Torrent` from the WebTorrent project.
- `ExtendedTorrent` used in web3torrent for additional information for the web3 extension to webtorrent.
- `Torrent` that extends `ExtendedTorrent` with `parsedTimeRemaining`, `numSeeds`, `status`, and `originalSeed` fields.
- `TorrentUI` that is used to populate React components.
I propose removing the `Torrent` type for the following reasons:
- `parsedTimeRemaining` is derived from `WebTorrent.Torrent`'s `timeRemaining` and `done`, so it does not need to be stored.
- `orginalSeed` is derived from `done` and the web3torrent client `pseAccount`, so it does not need to be stored. Same logic applies for `status`.
- `numSeeds` doesn't appear to be used anywhere in the project. …
=> [web3torrent] torrent type revamp

packages/web3torrent/src/pages/file/File.tsx, packages/web3torrent/src/utils/check-torrent-in-tracker.ts, packages/web3torrent/src/utils/checkTorrentInTracker.ts
This PR adds support for the Pino logs that @andrewgordstewart implemented last week, and reactors the checkTorrentInTracker function so that it becomes more readable.
I tried removing the entire logic behind the previous _timer_ promise, but as the tracker client is event-based, the clean up after running the function because there's a lot of possible results and you end up repeating code. 
I think that it's better to clean the function and just remove the promise race while maintaining the timer logic.
=> W3T torrent check refactor

packages/client-api-schema/src/generated-schema.json
=> Delete removed generated schema

packages/web3torrent/.storybook/web3torrent-client.mock.js, packages/web3torrent/src/components/share-list/share-file/ShareFile.stories.tsx
This PR fixes a global storybook issue where missing function, and a missing property in the mocked context was making the start-storybook script fail. And it uncomments and fixes the ShareFile story.
The bug reported in #1205 is still present though.
=> W3T Start-storybook fix

packages/xstate-wallet/src/workflows/approve-budget-and-fund.ts
Sets the application site for the ledger channel in approve budget. This addresses the error when trying to `releaseFunds` in `CloserLedgerAndWithdraw`
fixes #1500
=> Set site in approve budget

packages/channel-client/package.json, packages/channel-client/src/channel-client.ts, packages/channel-client/src/types.ts, packages/channel-client/tests/index.test.ts, packages/rps/package.json, packages/rps/src/utils/__tests__/rps-channel-client.test.ts, packages/web3torrent/package.json, packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/pages/file/File.test.tsx
The title is fairly straightforward.
This PR adds a subscribable ReplaySubject on the channelClient. This subject emits the last state to new subscribers, ensuring that no matter when the subscriber subscribes, it never loses the latest state of the channel.
See [here](https://www.learnrxjs.io/learn-rxjs/subjects) for more data about the ReplaySubject.
=> Add ReplaySubject to ChannelClient, use it on PaymentChannelClient

.circleci/Dockerfile, .circleci/README.md, .circleci/build-tag-push-docker.sh, .circleci/config.yml
Benefits:
- version pinning.
- I believe that ppa:ethereum/ethereum is Ubuntu specific, but our image is using Debian.
- I could not rebuild the image today with the ppa. Seeing:
```
> [7/8] RUN apt-get install solc --allow-unauthenticated -y:                            
#10 0.232 Reading package lists...                                                       
#10 1.014 Building dependency tree...                                                    
#10 1.179 Reading state information...                                                   
#10 1.236 Some packages could not be installed. This may mean that you have              
#10 1.236 requested an impossible situation or if you are using the unstable
#10 1.236 distribution that some required packages have not yet been created
#10 1.236 or …
```
=> Change the way solc is installed in the master docker image

.env.virtual-funding, packages/e2e-tests/puppeteer/helpers.ts, packages/rps/README.md, packages/tic-tac-toe/README.md
When using `SC_ENV=virtual-funding` and trying to run `puppeteer:dev:web3torrent` in the `e2e-tests` package, I'm not able to use it adequately because `switchNetwork` on `dappeteer` only works with 8545.
I don't think there is any benefit in using 8547 over 8545, so I propose we just change the default.
=> Change virtual-funding ganache port to 8545

packages/devtools/src/config/env.ts, packages/simple-hub/docker/simple-hub.dockerfile, packages/simple-hub/env.ts, packages/simple-hub/jest/jest.config.js, packages/simple-hub/src/server.ts, packages/simple-hub/tsconfig.json
For some reason, `tsc` compilation no longer works for the `simple-hub` package. As in, `tsc` compilation  produces no output. This PR fixes `tsc` configuration and migrates `env.js` to typescript to match devtools.
=> [simple-hub] Fix tsc

.env.circle-integration-rps, .env.circle-integration-w3t, .env.circle-integration-w3t-with-hub, .env.persistent-seeder, packages/e2e-tests/Dockerfile, packages/e2e-tests/entrypoint.sh, packages/e2e-tests/package.json, packages/e2e-tests/puppeteer/constants.ts, packages/e2e-tests/puppeteer/helpers.ts, packages/e2e-tests/puppeteer/scripts/minimal-dapp.ts, packages/e2e-tests/puppeteer/scripts/persistent-seeder.ts, packages/e2e-tests/puppeteer/scripts/web3torrent.ts, packages/e2e-tests/run-e2e.sh, yarn.lock
and associated SC_ENV, that successfully runs in a Docker container. 
Progress toward #1548 .
Instuctions
---
- `cd packages/e2e-tests`
- `docker build -t dapp . `
- `docker run -it dapp /bin/bash` to get an interactive shell inside the Docker container
- `yarn persistent-seeder` to launch web3torrent & dappeteer , upload a file and make a deposit
TODO
---
=> [e2e] Add a persistent-seeder script

packages/devtools/src/config/env.ts, packages/simple-hub/env.ts, packages/tic-tac-toe/config/env.js, packages/web3torrent/scripts/start.js, packages/xstate-wallet/config/env.js, packages/xstate-wallet/scripts/start.js
This option is not used anywhere, so I figure this keep things simple.
=> Remove monorepo arg from configureEnvVariables

.circleci/config.yml
These were needed by the legacy hub.
=> Remove unused db settings from circle config

packages/e2e-tests/puppeteer/constants.ts
I missed this when deprecating this env var in #1549
=> [e2e] Remove unused env var

packages/e2e-tests/puppeteer/scripts/web3torrent.ts
The `web3torrent.ts` script didn't get updated to use one of the etherlime accounts for puppeteer. Also, I prefer to just make running this script set up the environment as a seeder.
=> Fix puppeteer dev window for w3t

packages/xstate-wallet/package.json
⚠️ Without this PR, `xstate-wallet` release pipeline is broken. ⚠️
=> [xstate-wallet] fix release:netlify:production

packages/simple-hub/docker/simple-hub.dockerfile, packages/simple-hub/package.json
The forcing function for this work is that running `yarn add` in the docker container results in all `yarn.lock` dependencies installed (which includes all monorepo production and dev dependencies).
=> [simple-hub] add dotenv dependencies

packages/e2e-tests/puppeteer/scripts/web3torrent.ts
I am seeing this issue on production right now. I want to add some message to disambiguate this problem from other "we are stuck waiting on something" puppeteer error messages.
=> [w3t, e2e] Wait for input button to not be disabled

packages/channel-provider/src/channel-provider.ts
Currently we only log info when the wallet successfully loads. At a minimum, we should hint that we are waiting for this. 
Currently if all you see  " 'Application successfully mounted Wallet iFrame inside DOM.'" (after several seconds), it is not obvious that all-is-not-well.
We might want to actually show the user some hint of the problem, too. Right now the upload button being disabled is the only hint (but this is also the hint for being on the wrong network, which doesn't have a separate hint #1641 ). 
Suggestions for a better message are welcome.
=> [w3t] Log info about waiting for the wallet to wake up

.dockerignore, packages/e2e-tests/persistent-seeder-deployment/build-push-release.sh, packages/e2e-tests/persistent-seeder-deployment/persistent-seeder.dockerfile.dockerignore, packages/simple-hub/docker/simple-hub.dockerfile.dockerignore
This PR symlinks package specific dockerignores (for `simple-hub` and `e2e-tests`) to the monorepo general `.dockerignore`. Before this PR, monorepo `.dockerignore` was a symlink to the `simple-hub `.dockerignore`, and `e2e-test` `.dockerignore` was a lone ranger 🤠  that will not work with CircleCI deployments.
=> Create a dockerignore that works with persistent seeder

.circleci/config.yml
The job is [running out of memory](https://circle-production-customer-artifacts.s3.amazonaws.com/picard/5d85227bbc97ad5ba7cf4fb2/5eac40a9ffae755ecb225523-0-build/artifacts/netlify-stats?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200501T153939Z&X-Amz-SignedHeaders=host&X-Amz-Expires=60&X-Amz-Credential=AKIAJR3Q6CR467H7Z55A%2F20200501%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=939483a173df678f8fbefe8cb07c857e363cafd5260728d88935de58112b0329) when building `xtate-wallet` and `web3torrent` simultaneously:
=> Bump up release-netlify-production resource_class

packages/e2e-tests/puppeteer/__tests__/web3torrent/seed-download.test.ts
[This](https://app.circleci.com/pipelines/github/statechannels/monorepo/5851/workflows/bda2bf9b-7f72-4ebe-b329-ef5943bbf9f7/jobs/23177) CI job seemed to fail because the UI was not there
=> Wait for earned and paid columns to show

.circleci/config.yml, .env.circle-integration-w3t, .env.circle-integration-w3t-with-hub, .env.local-ropsten, .env.persistent-seeder, .env.production-ropsten, packages/e2e-tests/puppeteer/__tests__/web3torrent/seed-download.test.ts, packages/e2e-tests/puppeteer/__tests__/web3torrent/withdraw.test.ts, packages/e2e-tests/puppeteer/constants.ts, packages/e2e-tests/puppeteer/scripts/persistent-seeder.ts
- converts e2e tests for w3t to read in target app url via new env var 
- new circle job `e2e-test-w3t-production`
- only runs on deploy branch, and *after* apps have been redeployed
- does not start any servers of its own
- runs e2e tests (headful, dappeteer enabled) against specified environment (assumes servers are running)
Closes #1620 .
Tested against *this* branch (temporarily). Test runs and fails due to known issues.
=> [web3t] Run e2e test against deployed apps

.circleci/config.yml
=> Fix release-hub-deploy

packages/e2e-tests/puppeteer/constants.ts, packages/e2e-tests/puppeteer/helpers.ts
...and use it wherever we are waiting for a blockchain tx.
We have two e2e tests for web3torrent. Currently `withdraw.test.ts` fails when we target production https://app.circleci.com/pipelines/github/statechannels/monorepo/5927/workflows/72f3061a-0f91-47ae-8e3f-fa3739542874/jobs/23677/steps . However, this seems to be (only) because we time out waiting for ropsten. 
This PR is a hotfix for that which should get the test passing. 
`seed-download.test.ts` will still fail, this PR does nothing to help with that. 
We should probably introduce a more elegant and robust long term fix for this: currently it is difficult to tell when we are waiting for a blockchain transaction. One idea would be to wrap dappeteer's `metamask.confirmTransaction()` method with something like …
=> [e2e] Introduce TX_WAIT_TIMEOUT constant

packages/nitro-protocol/package.json, yarn.lock
For now `solidoc` errors out if the contracts are compiled with `solc =/= 0.6.1`. On circle, we use a native `solc` pinned to `0.6.1` (which matches our contracts' pragmas); but for local development we may fallback on `solcjs`, which is currently pegged to `0.6.0`.
Note that the contract compilation does not error out if the mismatched compiler is used, but the resulting artifacts cause an error in `solidoc`. 
Longer term fix might be to fix `solidoc` (which is forked by us anyway).
=> [nitro-protocol] Change solc version to 0.6.1

packages/xstate-wallet/webpack-build.config.js
Enable sourcemaps in production for xstate wallet.
It looks like web3torrent already includes sourcemaps.
=> Enable source maps in prod

packages/e2e-tests/puppeteer/__tests__/web3torrent/seed-download.test.ts
I _think_ that, were no data to be transferred during the test, it might still pass. 
Add an extra assertion to catch this.
=> [e2e, w3t] Add an assertion that something was paid

packages/xstate-wallet/src/chain.ts, packages/xstate-wallet/src/ui/approve-budget-and-fund-workflow.tsx, packages/xstate-wallet/src/ui/close-ledger-and-withdraw.tsx, packages/xstate-wallet/src/workflows/close-ledger-and-withdraw.ts
Fixes #1692 
Returns the transaction id immediately instead of waiting for it to be mined (by calling `wait()`)
=> Show transaction id after submission

packages/xstate-wallet/webpack-build.config.js
Based on https://github.com/statechannels/monorepo/pull/1696#issuecomment-624313116.
Turns off code minification which interferes with our usage of `Function.name`. [Here](https://github.com/babel/minify/issues/811) is a related issue from `babel` explaining the situation in general.
Example usage in `xstate-wallet`: https://github.com/statechannels/monorepo/blob/187dfc9dc685cccb504eb93c08e025df02e36b72/packages/xstate-wallet/src/workflows/create-and-fund.ts#L117-L121
=> [xstate-wallet] Set production xstate-wallet webpack to development mode

packages/app-wallet-interface/source/index.html.md
Following the discussion in today's standup. 
I think @andrewgordstewart / @lalexgap plans to change the behaviour in the xstate-wallet -- I think a change something like the following should accompany that. 
I think during standup we did not touch on changes to the status of the channel: e.g. to 'challenge' or 'funded'. Presumably these _should_ trigger the notification, but might not result in the turn number or the appData changing.
I think the important thing is that the application developer knows what to expect to be coming down this pipe, and which things might get swallowed by the wallet.
=> [api] Sketch out more precise description of onChannelUpdated

packages/web3torrent/src/clients/payment-channel-client.ts
Commit 312859a6094863e3e7fec92811ef2a4a299e8164 added an extra call to `EnableEthereum` on the wallet. It should have been harmless, since the wallet does a check to see if it has already been enabled (see below), but due to some kind of timing issue with how quickly MetaMask is able to provide `window.ethereum.selectedAddress`, even after a successful connection, the workflow started twice showing the UI twice, breaking our puppeteer testing scripts.
https://github.com/statechannels/monorepo/blob/d370d4efb131001bc87557a4363fced0c04994ad/packages/xstate-wallet/src/messaging.ts#L173-L181
Action item for future:
- Update the wallet to store whether or not it thinks it got a successful enable from MetaMask
=> Remove superfluous call to EnableEthereum breaking CI

packages/xstate-wallet/src/store/channel-store-entry.ts, packages/xstate-wallet/src/store/dexie-backend.ts
This makes it easier to debug https://github.com/statechannels/monorepo/issues/1693 on circle, and is progress towards https://github.com/statechannels/monorepo/issues/1711.
```
[1588789200271] ERROR (xstate-wallet/19245 on MacBook-Pro-10.local): Transaction error
error: "Transaction committed too early. See http://bit.ly/2kdckMn"
store: {
"budgets": [],
"channels": [],
"ledgers": [],
"nonces": [],
"objectives": [],
"privateKeys": [
{
"key": "0x11115FAf6f1BF263e81956F0Cc68aEc8426607cf",
"value": "0x95942b296854c97024ca3145abef8930bf329501b718c0f66d57dba596ff1318"
}
]
}
```
=> Dump store on error

packages/xstate-wallet/src/store/dexie-backend.ts
I checked in some bad code, so the example in https://github.com/statechannels/monorepo/pull/1710 was misleading.
This fixes that, and also logs a long enough slice of the callback implementation to identify which store method made the transaction.
```
[1588814673736] ERROR (xstate-wallet/4508 on MacBook-Pro-10.local): Transaction error
error: "Couldn't find the signing key for any participant in wallet."
store: {
"budgets": [],
"channels": [],
"ledgers": [],
"nonces": [],
"objectives": [],
"privateKeys": [
{
"key": "0x661b985FC2C3CC76c4DB53c8F110D084Bedf0b56",
"value": "0xdd90c4aa5138901170ebac67ef70b35e157e4e23c6ad6af9c73620a28eb69fb7"
}
]
}
callback: "() => __awaiter(this, void 0, void 0, function* () {\n            const addresses = participants.map(x => x.signingAddress);\n …
```
=> Fix store dump

packages/e2e-tests/jest.setup.ts, packages/e2e-tests/puppeteer/__tests__/web3torrent/seed-download.test.ts, packages/e2e-tests/puppeteer/__tests__/web3torrent/withdraw.test.ts, packages/e2e-tests/puppeteer/constants.ts, packages/e2e-tests/puppeteer/scripts/persistent-seeder.ts
- defaults to previous localhost 3000 and 3055
Currently there is an unnecessary wait-until-timeout situation when running e2e tests against non localhost servers.
https://app.circleci.com/pipelines/github/statechannels/monorepo/6004/workflows/d3324ad3-f0ef-4c50-ac8a-c9837e3fb706/jobs/24213/steps
=> [e2e] Wait-on reads from env vars

.circleci/config.yml
We may want to wait to merge this, until this job settles down a bit (to avoid spamming slack). 
Having said that, we don't push to deploy *all* that often, so maybe it is ok.
=> [circle] notify slack on e2e-prod failure

.circleci/config.yml
Unfortunately, I am not sure there is a way to create a notification whenever a new container is released to heroku. If a developer deploys the hub from their local machine, no notification will be sent out.
Fixes https://github.com/statechannels/monorepo/issues/1627.
=> Slack notification for hub release from circle

.env.production-ropsten, packages/simple-hub/src/server.ts
Running the hub locally with `SV_ENV=production-ropsten` sends alerts to Sentry for the production environment. With this PR, Sentry is configured using the [dyno metadata](https://devcenter.heroku.com/articles/dyno-metadata).
=> [simple-hub] remove RUNTIME_ENV

packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx
Pull property directly off the wire.
Should fix the issue where currently what is shown as a 'peer' in the UI, is actually me...
An extension to this PR would be to replace the trimmed peer addresses with blockies
=> [web3torrent] ChannelsList component shows peerAccount

packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/library/web3torrent-lib.ts
Fixes #1729.
Fixes #1738.
> The root cause of this is that the web3torrent seeder sends a final state update acknowledging the payment when it is complete. This arrives while the leacher has started calling closeChannel so the final payment is accepted into the store after finalState is called to create the final state.
> 
> I think there is two issues here:
> 
> #1554 I think the leacher store is accepting (or silently ignoring) the leacher's final payment update. We should probably throw an error in this case.
> The seeder's paymentChannelClient should wait to receive the final state before calling closeChannel
After some local testing I think this may be the cause of #1738 as well, since the `store` had two states with the same turnNum, causing the signature to be incorrect.
I've left …
=> Fix channels not closing on torrent finish

packages/xstate-wallet/src/chain.ts, packages/xstate-wallet/src/tests-with-chain/chain.test.ts
- The provider can be fetched on initialization
- The signer should only be available after ethereum is enabled.
Before then, we don't know what signing address we should use.
- The signer uses the selected address
Resolves https://github.com/statechannels/monorepo/issues/1732
=> Add provider and (proper) signer to chain

packages/xstate-wallet/src/chain.ts
After #1739 the wallet now asks the user to "Connect to MetaMask" every time even if they're already connected. This fixes that.
=> [xstate-wallet] Set mySelectedAddress to ethereum.selectedAddress on initialization

packages/xstate-wallet/src/workflows/tests/conclude-channel.test.ts, packages/xstate-wallet/src/workflows/tests/support-state.test.ts
Addresses: https://github.com/statechannels/monorepo/issues/1602
TODO
- ~~[ ] Refactor the test setup code (currently it is copied from `challenge.test.ts`)~~
Update: Latest commit also adds a test for the virtual funding case, which addresses: https://github.com/statechannels/monorepo/issues/1603
=> Add conclude-channel idempotency tests for direct and virtual funding

.env.circle-integration-rps, .env.circle-integration-w3t, .env.circle-integration-w3t-with-hub, packages/e2e-tests/puppeteer/__tests__/web3torrent/seed-download.test.ts, packages/e2e-tests/puppeteer/constants.ts
As per our discussion in standup, we should remove sources of failure until the circle integration tests pass reliably.
=> Don't use dappeteer in circle

packages/e2e-tests/puppeteer/helpers.ts
Returns useful error messages in circle:
```
console.log puppeteer/__tests__/web3torrent/seed-download.test.ts:99
B cancels download
FAIL  puppeteer/__tests__/web3torrent/seed-download.test.ts (65.291s)
Web3-Torrent Integration Tests
✕ allows peers to start torrenting (62732ms)
● Web3-Torrent Integration Tests › allows peers to start torrenting
Failed: "Timed out waiting for channelStatus.status === 'closed'"
```
=> Add timeouts to integration tests

packages/xstate-wallet/src/store/channel-store-entry.ts, packages/xstate-wallet/src/store/index.ts, packages/xstate-wallet/src/store/tests/channel-store-entry.test.ts, packages/xstate-wallet/src/workflows/tests/data.ts
Fixes #1554 by throwing an error when we have multiple states with the same turn number.
This would of caught #1729
=> Check for duplicate turn numbers in store invariant check

.circleci/config.yml
Builds source maps for `web3torrent` https://github.com/statechannels/monorepo/blob/a92bb3908ec6fe79c4b47cca1c19eb7c2a59b7c4/packages/web3torrent/config/webpack.config.js#L36-L36
=> [w3t] Add GENERATE_SOURCEMAP to CircleCI build env

packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/conclude-channel.ts, packages/xstate-wallet/src/workflows/tests/conclude-channel.test.ts
This is a quick fix to get the wallet to wait until there's a conclusion
proof.
=> [xstate-wallet] :pig: Add gap when creating final state

packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx
Virtual channels don't currently support challenging
Closes: #1721
=> fix: Remove Challenge Channel button from web3torrent

packages/e2e-tests/persistent-seeder/persistent-seeder.dockerfile, packages/e2e-tests/puppeteer/helpers.ts, packages/e2e-tests/puppeteer/scripts/web3torrent.ts, packages/web3torrent/src/constants.ts, packages/web3torrent/src/pages/welcome/Welcome.tsx
**This PR:**
1. Sets the pre-defined torrent to show in the welcome screen to be the same that is shared by the persistent seeder.
2. It also fixes a regression that I found, where the file that was shared, wasn't the correct file (because it would be replaced by the stub file for the tests).
3. It gives more time for [some](https://github.com/statechannels/monorepo/compare/persistent-seeder-set?expand=1#diff-d745dc9ef530a2204bfa4ffd6363d00cR255) [parts](https://github.com/statechannels/monorepo/compare/persistent-seeder-set?expand=1#diff-9ed3cedce43d8747b5dc9942f0b66cedR55) of the seeding process that could take more time and fail.
3. I decided to remove the check in the welcome screen for the persistent seeder torrent because the result wasn't to be trusted. 
The check is done, then, in …
=> Persistent Seeder Fix

.circleci/config.yml
We do this on `master`, and it should improve the reliability of the test.
=> Run production tests in band

packages/channel-client/src/channel-client.ts, packages/channel-client/src/types.ts, packages/channel-provider/src/types.ts, packages/client-api-schema/src/generated-schema.json, packages/client-api-schema/src/types.ts, packages/rps/src/utils/__tests__/rps-channel-client.test.ts, packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/pages/file/File.test.tsx, packages/web3torrent/src/pages/file/File.tsx, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/store/dexie-backend.ts, packages/xstate-wallet/src/store/memory-backend.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/store/tests/dexie-store.test.ts, packages/xstate-wallet/src/store/types.ts, packages/xstate-wallet/src/utils/helpers.ts
Fixes #1736.
Adds a `GetChannels` all to the wallet API and modifies web3torrent to call this when loading the `File` component. This allows the user to see the previous channels / balances they have already set up.
=> Add GetChannels call to wallet

package.json, yarn.lock
Since `etherlime` has not fixed [this issue](https://github.com/LimeChain/ethereum-transaction-debugger/issues/3) here is a temporary workaround to get `web3` out of our dependency tree.
=> Skip subdependency in order to remove web3

packages/client-api-schema/src/generated-schema.json, packages/web3torrent/src/library/types.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/pages/file/File.test.tsx, packages/web3torrent/src/pages/file/File.tsx
Fixes https://github.com/statechannels/monorepo/issues/1805.
The upsides are:
- More responsive UI instead. With a timer, the UI state lags by at most 1 seconds behind the data state.
- Finegrain control over what events trigger UI updates.
=> [web3torrent] Do not rely on a timer for UI updates

packages/web3torrent/src/logger.ts
If I call `window.saveWeb3torrentLogs()`, my browser downloads a file like this:
[web3torrent.Wed, 13 May 2020 18_52_55 GMT.f4cb9bbd3.pino.log](https://github.com/statechannels/monorepo/files/4624057/web3torrent.Wed.13.May.2020.18_52_55.GMT.f4cb9bbd3.pino.log)
=> [web3torrent] Expose downloadable pino logs

packages/web3torrent/src/App.test.tsx, packages/web3torrent/src/App.tsx, packages/web3torrent/src/clients/web3torrent-client.test.ts, packages/web3torrent/src/clients/web3torrent-client.ts, packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx, packages/web3torrent/src/hooks/use-budget.ts, packages/web3torrent/src/index.tsx, packages/web3torrent/src/pages/budgets/Budgets.tsx, packages/web3torrent/src/pages/file/File.test.tsx, packages/web3torrent/src/pages/file/File.tsx, packages/web3torrent/src/pages/upload/Upload.test.tsx, packages/web3torrent/src/utils/torrent-status-checker.test.ts, yarn.lock
There are:
- a web3torrent client. This is a torrent manager.
- a web3 torrent. This is one torrent with payments.
- a wire. A torrent can have many wires.
This PR hopes to remove the mental overhead of remembering that `web3torrent` constants do not represent web3 torrents but instead represent the web3torrent client.
https://github.com/statechannels/monorepo/pull/1827 preceeds this PR.
=> [web3torrent] Differentiate between client and torrent

packages/channel-provider/src/logger.ts, packages/web3torrent/src/logger.ts, packages/xstate-wallet/src/logger.ts
Expands on https://github.com/statechannels/monorepo/pull/1829.
Now, channel-provider and xstate-wallet logs are also downloaded by the `downloadWeb3torrentLogs()` function
[web3torrent.Wed, 13 May 2020 21_55_06 GMT.36df83790.0x32cEE11c2c29a3CC1A9b1cE3D671D7BaC54cFEdc.pino.log](https://github.com/statechannels/monorepo/files/4624960/web3torrent.Wed.13.May.2020.21_55_06.GMT.36df83790.0x32cEE11c2c29a3CC1A9b1cE3D671D7BaC54cFEdc.pino.log)
The simplest way to connect xstate-wallet logs to web3torrent logs was to post a message to the web3torrent's window on xstate-wallet log events.
Given that pattern, the simplest way to also include the channel-provider logs was to post a message to `window` on channel-provider log events.
=> Downloadable logs part 2

.circleci/config.yml
[Broke deploy](https://app.circleci.com/pipelines/github/statechannels/monorepo/6431/workflows/04ed0bfd-5d1c-4d88-80b7-d82970320659/jobs/27017)
=> Update version of CircleCI dependency cache key

packages/channel-provider/src/logger.ts, packages/web3torrent/config/webpack.config.js, packages/web3torrent/src/logger.ts, packages/xstate-wallet/src/logger.ts
I was using the `transmit` option in #1829 and #1836
While investigating around #1839, I realized that I could use the `write` option in any case.
This means
- I don't have to transform the logEvent thata `transmit` gives you: http://getpino.io/#/docs/browser?id=transmit-object
- I can keep the same console formatting (yellow for warn, red for error, etc) by passing an object for `write`: http://getpino.io/#/docs/browser?id=write-function-object
Sample:
[web3torrent.Thu, 14 May 2020 01_40_47 GMT.f0abd39f4.0x32cEE11c2c29a3CC1A9b1cE3D671D7BaC54cFEdc.pino.log](https://github.com/statechannels/monorepo/files/4625576/web3torrent.Thu.14.May.2020.01_40_47.GMT.f0abd39f4.0x32cEE11c2c29a3CC1A9b1cE3D671D7BaC54cFEdc.pino.log)
=> Improved pino logging

.env.circle-integration-w3t, packages/app-wallet-interface/source/index.html.md, packages/e2e-tests/puppeteer/__tests__/web3torrent/seed-download.test.ts, packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/integration-tests/close-withdraw.test.ts, packages/xstate-wallet/src/serde/app-messages/serialize.ts, packages/xstate-wallet/src/store/channel-store-entry.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/store/tests/channel-store-entry.test.ts, packages/xstate-wallet/src/ui/application-workflow.tsx, packages/xstate-wallet/src/ui/selectors.ts, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/close-ledger-and-withdraw.ts, packages/xstate-wallet/src/workflows/conclude-channel.ts, packages/xstate-wallet/src/workflows/tests/conclude-channel.test.ts, packages/xstate-wallet/src/workflows/tests/support-state.test.ts
Based on @geoknee's work in #1543. Adds withdrawal to conclude channel workflow. To prevent both players from submitting `finalizeAndWithdraw` transaction and have it fail for one player, only player A currently triggers the transaction.
TODO:
=> Add withdrawing to Direct Funding Conclude Channel

packages/e2e-tests/puppeteer/__tests__/rps/rps.test.ts, packages/e2e-tests/puppeteer/scripts/rps.ts, packages/rps/src/__stories__/index.tsx, packages/rps/src/components/HomePage.tsx, packages/rps/src/containers/HomePageContainer.tsx, packages/rps/src/redux/game/saga.ts, packages/rps/src/redux/store.ts
Since #1834 got merged, we are now able to have Player B resign and both players back to the lobby. Starting a new game does not yet work. 
Additional tweaks:
- push approve metamask flow to after a user click (avoids immediate MM popup which is considered bad UX)
- prevent user logging in until wallet is ready
There is still much work to do:
- Get a second game working
- Add `aResigns` step
- improve UX: currently A's wallet doesn't inform that your opponent resigned, and submits the transaction without your approval . Similarly B's wallet does not explain that the other user is submitting the withdrawal transaction.
=> [rps, ,e2e] Unskip bResigns step

.circleci/config.yml
The job has never passed. Once the job is passing, turn on the alert back on.
=> Turn off e2e-test-w3t-production alert

.circleci/config.yml, packages/e2e-tests/puppeteer/__tests__/web3torrent/seed-download.test.ts, packages/e2e-tests/puppeteer/helpers.ts, packages/xstate-wallet/src/ui/approve-budget-and-fund-workflow.tsx, packages/xstate-wallet/src/ui/close-ledger-and-withdraw.tsx
[Screenshot](https://27335-209829093-gh.circle-artifacts.com/0/home/circleci/project/packages/e2e-tests/screenshots/seed-download.1.png) made it clear the downloader is waiting on their transaction to be mined:
So this adds a wait if that UI is still up after the approve budget and fund UI helper returns (which returns after the deposit transaction is _submitted_ not mined).
=> Wait a little bit longer on Ropsten e2e test

packages/e2e-tests/puppeteer/helpers.ts, packages/persistent-seeder/package.json
[This](https://app.circleci.com/pipelines/github/statechannels/monorepo/6548/workflows/c71f67cf-a559-4388-ae32-81a05cb83bc5/jobs/27873/steps) job failed because 30 seconds wasn't enough for the download. I don't think we lose much going from 12 MB to ~1.3 MB.
=> Decrease size of e2e w3t file

packages/channel-provider/src/logger.ts, packages/web3torrent/src/logger.ts, packages/xstate-wallet/src/config.ts, packages/xstate-wallet/src/logger.ts
Logs are missing in [important jobs](https://app.circleci.com/pipelines/github/statechannels/monorepo/6600/workflows/ba81f5a6-137a-4813-b112-5b71fdc7cc68/jobs/28304/artifacts) because of an awkward environment variable.
=> Use JEST_WORKER_ID to detect IS_BROWSER_CONTEXT

.circleci/config.yml
I think this has been _overriding_ the settings we've had on CI and there seems to be no rationale for why it should be a default setting.
=> Remove default setting of NODE_ENV=test

packages/web3torrent/src/clients/web3torrent-client.test.ts, packages/web3torrent/src/clients/web3torrent-client.ts, packages/web3torrent/src/components/torrent-info/download-info/DownloadInfo.test.tsx, packages/web3torrent/src/components/torrent-info/download-info/DownloadInfo.tsx, packages/web3torrent/src/library/web3torrent-lib.ts
Pretty much self-explanatory. The `cancel()` function in `web3torrent-client.ts` is useless, and it just adds noise to the code.
=> Refactors the cancel functions out of w3t-client

packages/web3torrent/src/library/web3torrent-lib.ts
It adds support for closing **paying channels** (channels used to pay to the peer, as opposed to **payment channels** that the peer uses to pay to another peer).
It also adds some logs to follow the closing channel flow.
=> Refactor W3T closeChannels()

packages/web3torrent/src/library/client-seeding.test.ts, packages/web3torrent/src/library/types.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/utils/test-utils.ts
Currently, there are 2 ways to block a wire:
- web3torrent client `blockPeer` method.
- `paidStreamingExtension` `stop` method.
There are also 2 properties that manage the state of whether a peer is blocked.
- `PeerByTorrent` `allowed` field. 
- `paidStreamingExtension` `isForceChoking`.
The goal of this PR is to ensure that state is only stored once to avoid tricky race conditions. With this PR:
- All state on whether a peer is being blocked is managed by the wire's `paidStreamingExtension` via the `isForceChoking` property.
- `blockPeer` does not do any state management outside of `stop`.
=> [web3torrent] blockPeer vs stop

packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx, packages/web3torrent/src/library/client-seeding.test.ts, packages/web3torrent/src/library/paid-streaming-extension.ts, packages/web3torrent/src/library/types.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/utils/test-utils.ts
Lays the groundwork for https://github.com/statechannels/monorepo/issues/1735. Specifically, this should address https://github.com/statechannels/monorepo/issues/1735#issuecomment-630911254.
Also renaming `pseChannelId` to `seedingChannelId` and `peerChannelId` to `leechingChannelId`.
=> [web3torrent] index peerList by channel id instead of peer id

packages/web3torrent/src/library/paid-streaming-extension.ts
Consider the start signal logic: https://github.com/statechannels/monorepo/blob/176ce6ce8cd0fc23ede590cf979aab88d51e5a61/packages/web3torrent/src/library/paid-streaming-extension.ts#L114-L122
1. Start signal is sent. This is an asynchronous network operation.
1. Blocked requests are processed.
What happens if the seeder has been paid for 4 requests, but 5 requests are blocked. Then a stop signal is sent while trying to process the 5th requests. So the flow is:
1. Start signal is sent. This is an asynchronous network operation.
1. 4 blocked requests are processed.
1. A stop signal is sent. This is an asynchronous network operation.
1. 5th request is added to the blocked queue.
Is the start signal guaranteed to arrive before the stop signal? That depends on webtorrent implementation. And to …
=> [web3torrent] always ask for payment on stop signal

packages/e2e-tests/puppeteer/__tests__/optional/seed-download-cancel.test.ts, packages/e2e-tests/puppeteer/helpers.ts
Based on [this comment](https://github.com/puppeteer/puppeteer/issues/2735#issuecomment-470309033) that I found after [my hunch](https://github.com/statechannels/monorepo/pull/1923#issuecomment-631478009) that Web3Torrent's usage of WebSockets was interfering with the puppeteer functionality. Passed locally several times in a row, but then recently stopped working.
=> Use pipe: true on puppeteer

packages/e2e-tests/puppeteer/__tests__/optional/seed-download-cancel.test.ts, packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx, packages/web3torrent/src/components/torrent-info/download-info/progress-bar/ProgressBar.tsx
So, I still saw the same errors that #1922 was supposed to fix even after applying the changes.
As an experiment, I removed all usages of the `doneWhen` helper and now rely solely on the UI.
The test still throws this `Object` error alongside `Protocol error (Runtime.callFunctionOn): Target closed.`
However, in an interesting twist, if I run it with `USE_DAPPETEER=true`, it never fails.
=> Remove page.evaluate and page.exposeFunction from cancel test

.env.circle-integration-w3t-with-hub, packages/web3torrent/package.json, packages/web3torrent/src/components/domain-budget-table/DomainBudgetTable.scss, packages/web3torrent/src/components/domain-budget-table/DomainBudgetTable.tsx, packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.scss, packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx, packages/web3torrent/src/constants.ts, yarn.lock
This is a demo app. When it works, it's pretty awesome to consider what is going on under the hood. 
OTH if users just come away with an impression of  "webtorrent clone", they will have largely missed the point. 
I think one way of showing off more of how awesome state channels are is to display the number of "L2 transactions" in real time.
This changeset also introduces a blockie for our peer, which has the full address in a tooltip. Personally I think this looks nicer, and it might help identify peers. 
TODO (feedback welcomed)
---
=> [web3torrent] Channels display number of payments

packages/nitro-protocol/contracts/ForceMove.sol, packages/nitro-protocol/contracts/interfaces/IForceMove.sol, packages/nitro-protocol/src/transactions.ts, packages/nitro-protocol/test/contracts/ForceMove/forceMove.test.ts, packages/xstate-wallet/src/chain.ts, packages/xstate-wallet/src/config.ts, packages/xstate-wallet/src/tests-with-chain/chain.test.ts, packages/xstate-wallet/src/workflows/challenge-channel.ts
Based on @geoknee's work in #1907.
This gets the challenge transaction properly working for `rps`.
The integration tests haven't been updated to include challenging yet as I'd like to finish my work in #1935 and then update the integration tests to tests both challenging and responding to the challenge.
=> Get Challenge Transaction Working

packages/nitro-protocol/src/contract/transaction-creators/asset-holder.ts, packages/nitro-protocol/src/contract/transaction-creators/consensus-app.ts, packages/nitro-protocol/src/contract/transaction-creators/erc20-asset-holder.ts, packages/nitro-protocol/src/contract/transaction-creators/eth-asset-holder.ts, packages/nitro-protocol/src/contract/transaction-creators/force-move.ts, packages/nitro-protocol/src/contract/transaction-creators/nitro-adjudicator.ts
Making this change didn't break anything. And it seems to allow ethers to automatically provide an accurate estimate for the gas limit.
=> [ nitro protocol ] Remove all GAS_LIMIT instances

packages/e2e-tests/puppeteer/constants.ts
This [job](https://app.circleci.com/pipelines/github/statechannels/monorepo/6800/workflows/cd06efcf-60c6-480e-b77e-8f0e9cbdb3b8/jobs/29860/steps) failed because 90s was not long enough.
=> Increase max Ropsten e2e test wait timeout

packages/simple-hub/src/message/on-message.ts
Fixes harmless (I think?) error on console:
```
20-05-22 12:56:36.665 +0000] INFO  (simple-hub/86966 on mhz.local): makeDeposit: attempting to make 0 deposits
[2020-05-22 12:56:36.665 +0000] INFO  (simple-hub/86966 on mhz.local): makeDepost: making 0 deposits
[2020-05-22 12:56:36.665 +0000] ERROR (simple-hub/86966 on mhz.local): onNext is not a function
TypeError: onNext is not a function
at SafeSubscriber.observable.pipe.subscribe [as _next] (/Users/liam/Documents/Projects/statechannels/monorepo/packages/simple-hub/src/message/on-message.ts:38:11)
at process._tickCallback (internal/process/next_tick.js:68:7)
```
=> Set default value for onNext and onComplete for simple-hub

packages/client-api-schema/src/generated-schema.json, packages/client-api-schema/src/methods/UpdateChannel.ts, packages/client-api-schema/src/types.ts, packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/integration-tests/helpers.ts, packages/xstate-wallet/src/integration-tests/running.test.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/serde/app-messages/serialize.ts, packages/xstate-wallet/src/store/dexie-backend.ts, packages/xstate-wallet/src/store/index.ts, packages/xstate-wallet/src/store/memory-backend.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/store/tests/dexie-store.test.ts, packages/xstate-wallet/src/store/tests/memory-store.test.ts, packages/xstate-wallet/src/store/types.ts, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/conclude-channel.ts, packages/xstate-wallet/src/workflows/support-state.ts
Ticks R1, R3 & R6 of https://github.com/statechannels/monorepo/issues/1909
- Refactors the store according to the discussion on https://github.com/statechannels/monorepo/pull/1933
- Channel updates now all (?) occur within a transaction
- Adds a generic wallet error with code 500
- Refactors the running test not to use `waitForExpect`, but instead block on responses and notifications
- running test also tests for one error response, when it is not your turn
- Updates the `application` workflow to send error responses during a `PlayerUpdate`
Will remove draft status when
=> Store refactor

packages/simple-hub/src/logger.ts
Seeing the following log on the production hub: `Error: ENOENT: no such file or directory, open ''`
=> [simple-hub] Do not log to an empty destination

packages/channel-provider/src/logger.ts, packages/xstate-wallet/src/config.ts, packages/xstate-wallet/src/logger.ts
I noticed that even after disabling logs for production we were seeing log entries from channel provider and xstate wallet.
This PR copies the `LOG_LEVEL` logic from w3t to these packages so that logs will be disabled properly.
=> Add LogLevel to Channel Provider and Xstate Wallet

packages/channel-provider/src/ui-service.ts
Fixes #1975.
Using 1300 because it's Google's Material design convention https://github.com/mui-org/material-ui/blob/master/packages/material-ui/src/styles/zIndex.js
=> Fix web3torrent badge overlapping wallet modal

packages/e2e-tests/puppeteer/__tests__/stress.test.ts, packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/library/web3torrent-lib.ts
This PR:
- Prevents the web3torrentClient to trigger payments while a torrent is being cancelled (by pausing the torrent):
https://github.com/statechannels/monorepo/compare/w3t-close-channel?expand=1#diff-a84153ed9f3ab2bd13c41bca43b584c7R134
https://github.com/statechannels/monorepo/compare/w3t-close-channel?expand=1#diff-a84153ed9f3ab2bd13c41bca43b584c7L401
- moves the logic of waiting for the user's turn before closing to the PaymentChannelClient:
https://github.com/statechannels/monorepo/compare/w3t-close-channel?expand=1#diff-9b0f77e1a02c15a73ad86b3e5d0b6620R212
- Makes channelClose calls independent of each other:
https://github.com/statechannels/monorepo/compare/w3t-close-channel?expand=1#diff-a84153ed9f3ab2bd13c41bca43b584c7R522-R525
related to #1961 and #1918 and #1811
=> W3t close channel

packages/web3torrent/src/logger.ts
Otherwise, they get logged as `Browser 0 logged "JSHandle@object"` in the browser log
=> Serialize log objects when "logging to file"

packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/clients/web3torrent-client.test.ts, packages/web3torrent/src/clients/web3torrent-client.ts, packages/web3torrent/src/library/client-seeding.test.ts, packages/web3torrent/src/library/testing/test-utils.ts, packages/web3torrent/src/library/types.ts, packages/web3torrent/src/library/web3torrent-lib.ts
This PR does 3 things:
- It adds jsdocs for every method in the web3torrent library.
- It cleans up a lot of logs, by deconstructing props and formatting the text.
- It refactors the Web3TorrentClient to clean it up a LOT. Moving logic into the PaymentChannelClient, and to the Web3torrent library.
- It simplifies the TorrentEvents.NOTICE STOP event handler.
=> Web3Torrent Client and library refactor and docs improvement

packages/web3torrent/src/library/paid-streaming-extension.ts, packages/web3torrent/src/library/web3torrent-lib.ts
Implements @tomclose's [suggestion](https://github.com/statechannels/monorepo/issues/1992#issuecomment-635242533) from #1992:
> We should handle closing the channel in the case where someone doesn't have data for you for some time. This should happen before the torrent timeout kicks in. This would lead to the channels ending in a closed state, instead of in a disconnected state
I tested on [`ags/close-channels-on-my-turn`](https://github.com/statechannels/monorepo/pull/1997) by starting the stress test and killing two of the windows leaving no peer with the full file but two partially downloading from each other and it worked.
=> Kill channels after two keep-alive pings with zero progress

packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/library/web3torrent-lib.ts
- `PaymentChannelClient` uses the `Peer` and `Peers` types to prevent accidentally passing strings in the wrong order
- `formatAllocations`/`Participants` uses `Index` to order the peers in the outcomes/participants
=> Refactor some web3torrent stuff

packages/xstate-wallet/src/chain.ts
I think this might help with investigating #1995. One theory I have is that `getChainInfo` is returning stale/cached info sometimes so hopefully this log entry can confirm/refute that.
=> Add a log statement when querying the chain

packages/xstate-wallet/src/workflows/ledger-funding.ts
It [seems like](https://xstate.js.org/docs/guides/ids.html#identifying-state-nodes) `id` is what you're supposed to use when doing direct references of state nodes. Might help with #2003?
=> Use 'id' instead of 'key' for absolute xstate node reference

packages/xstate-wallet/src/chain.ts
While looking into logs/code for #1995 I noticed that when we query the chain we construct brand new `Contract`s instead of using the existing `Contract`s that we store on the `chain`.
I'm wondering if this may be the cause of #1995 due to some internal `ether` workings, so I've changed the query to use the existing contracts. Even if it does not solve #1995 I think it makes sense to use the existing `Contract`s instead of creating new ones each time we perform a query.
=> Use Existing Contracts when Querying the Chain

packages/xstate-wallet/src/index.ts
Now that we're relying on saved logs a lot more it probably make sense to log out the version so we can tell what changes are/aren't included when the log was generated.
=> Log out version

packages/channel-client/src/index.ts, packages/web3torrent/src/clients/payment-channel-client.ts
It looks like web3torrent wasn't building on `master`.  I'm not sure why this wasn't caught in our CI pipeline.
=> Get Web3Torrent Compiling

packages/xstate-wallet/src/utils/contract-utils.ts
```javascript
> const e = require('@ethersproject/providers')
> new e.InfuraProvider('ropsten')
InfuraProvider {
_isProvider: true,
formatter: Formatter {
formats: {
transaction: [Object],
transactionRequest: [Object],
receiptLog: [Object],
receipt: [Object],
block: [Object],
blockWithTransactions: [Object],
filter: [Object],
filterLog: [Object]
}
},
_network: {
name: 'ropsten',
chainId: 3,
ensAddress: '0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e',
_defaultProvider: [Function (anonymous)]
},
_maxInternalBlockNumber: -1024,
_lastBlockNumber: -2,
_events: [],
_pollingInterval: 4000,
_emitted: { block: -2 },
_fastQueryDate: 0,
connection: {
url: 'https://ropsten.infura.io/v3/84842078b09946638c03157f83405213'
},
_nextId: 42,
apiKey: '84842078b09946638c03157f83405213',
projectId: …
```
=> Hotfix getProvider

.circleci/config.yml
(Branched off of https://github.com/statechannels/monorepo/pull/2030)
They're almost identical, except for
- the test files
- the app
- the env variables (which are almost entirely defined in SC_ENV)
Also, don't install/run xvfb on integration tests
=> Refactor integration test jobs

.circleci/config.yml, packages/tic-tac-toe/package.json
We are starting to consistently observe the circleci `build` step running out of memory for the `master` branch. One of the issues seems to be that ember spins up many processes for building tic-tac-toe. On the surface, this is likely due to ember calculating machine resources as opposed to container resources. This seems related to [this issue](https://github.com/emberjs/ember.js/issues/15641).
=> Build step out of memory

packages/web3torrent/src/hooks/use-budget.ts, packages/web3torrent/src/pages/file/File.tsx
Fixes #2058 by manually fetching the budget after the download has started.
=> Manually fetch budget after download

packages/web3torrent/src/library/types.ts, packages/web3torrent/src/logger.ts
See https://github.com/statechannels/monorepo/issues/2041#issuecomment-637737955. One log line was 21MB
Now, the logs look like
```
[1591154850501] INFO  (web3torrent): << blockPeer
module: "web3torrent-lib"
from: {
"0x5d89f9b1da7b81f99ab786b78839d96a03cf3a4ff15f97e24d6d10d2a820dafe": {
"id": "0x18238000f59E26c69140F8072ac606c1309cc928",
"wire": {
"peerId": "2d5757303030372d422b36505049584376707237",
"amChoking": false,
"amInterested": false,
"peerChoking": true,
"peerInterested": true
},
"buffer": "0",
"beneficiaryBalance": "0",
"uploaded": 0
}
}
peerAccount: "0x18238000f59E26c69140F8072ac606c1309cc928"
seedingChannelId: "0x5d89f9b1da7b81f99ab786b78839d96a03cf3a4ff15f97e24d6d10d2a820dafe"
browserId: 0
```
(We should probably avoid logging the `torrent` at all.)
```
~/Downloads via ☕ …
```
=> Serialize wires when logging

.env.production-ropsten
The inline comment was getting picked up as part of the env var value.
=> Fix production

packages/xstate-wallet/src/store/dexie-backend.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/utils/helpers.ts
Fixes #2074 
The `setBudget` method in the dexie backend was not properly returning a budget, causing serialization failures later when we try and send out a notification. This only occurred with `releaseFunds` as we were returning the result from the dexie backend instead of the value being passed into `setBudget`
=> Fix releaseFunds Error

packages/web3torrent/src/library/paid-streaming-extension.ts, packages/web3torrent/src/library/types.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/logger.ts
While addressing the comments on https://github.com/statechannels/monorepo/pull/2064, I went down a deeper rabbit hole which will hopefully clean up the web3torrent logs.
The final product:
```
[1591221673660] TRACE (web3torrent):
module: "web3torrent-lib"
torrent: {
"destroyed": false,
"done": false,
"files": [
{
"_events": {},
"_eventsCount": 0,
"_destroyed": false,
"name": "web3torrent-tests-stub",
"path": "web3torrent-tests-stub",
"length": 520000,
"offset": 0,
"done": false,
"_startPiece": 0,
"_endPiece": 31
}
],
"infoHash": "797ac8cd087fa1ef4f1a21b7b71e3fe9e014989c",
"lastPieceLength": 12096,
"length": 520000,
"magnetURI": "magnet:?xt=urn:btih:797ac8cd087fa1ef4f1a21b7b71e3fe9e014989c&dn=web3torrent-tests-stub&tr=http%3A%2F%2Flocalhost%3A8000%2Fannounce&tr=udp%3A%2F%2Flocalhost%3A8000 …
```
=> Serialize torrents, PSEs, PSEWires, and Buffers

packages/devtools/package.json, yarn.lock
Saw this error on the Heroku logs for the persistent seeder:
```
2020-06-04T12:44:38.601843+00:00 app[persistent-seeder.1]: /statechannels/monorepo/node_modules/pino/lib/tools.js:187
2020-06-04T12:44:38.601843+00:00 app[persistent-seeder.1]: throw Error('Missing `pino-pretty` module: `pino-pretty` must be installed separately')
2020-06-04T12:44:38.601844+00:00 app[persistent-seeder.1]: ^
2020-06-04T12:44:38.601907+00:00 app[persistent-seeder.1]: Error: Missing `pino-pretty` module: `pino-pretty` must be installed separately
2020-06-04T12:44:38.601908+00:00 app[persistent-seeder.1]: at getPrettyStream (/statechannels/monorepo/node_modules/pino/lib/tools.js:187:11)
2020-06-04T12:44:38.601908+00:00 app[persistent-seeder.1]: at normalizeArgs …
```
=> Add pino-pretty as dependency to devtools

packages/xstate-wallet/src/utils/contract-utils.ts
As far as I can tell `InfuraProvider` is not working right now (see https://github.com/ethers-io/ethers.js/issues/868)
This PR disables it until the issue resolves so the persistent seeder will function.
Fixes #2056
=> Avoid using Infura Provider

packages/nitro-protocol/src/index.ts, packages/nitro-protocol/test/contracts/ConsensusApp/nullApp.test.ts
I stopped short of clearing out the ConsensusApp entirely, since this is imported into the `simple-hub` and `xstate-wallet`.
For now the documentation will explain both approaches, and the test I added is a signal for the null app in our source code.
=> [nitro-protocol] Add some more exports and a test for nullApp

packages/persistent-seeder/persistent-seeder.ts
=> Add HEADLESS config option for persistent-seeder

.env.production-ropsten, packages/channel-provider/src/logger.ts, packages/web3torrent/src/constants.ts, packages/web3torrent/src/logger.ts, packages/xstate-wallet/src/config.ts, packages/xstate-wallet/src/logger.ts
Closes https://github.com/statechannels/monorepo/issues/2057
USAGE:
```
> window.setLogLevel('trace')
logger.ts:244 web3torrent: level CHANGED from debug to trace
undefined
logger.ts:55 wallet: level CHANGED from info to trace
> window.setLogLevel('debugf')
logger.ts:250 Uncaught Error: Invalid log level debugf
at setLogLevel (logger.ts:250)
at <anonymous>:1:8
setLogLevel @ logger.ts:250
(anonymous) @ VM14010:1
> window.setLogLevel('debug')
logger.ts:244 web3torrent: level CHANGED from trace to debug
undefined
logger.ts:55 wallet: level CHANGED from trace to debug
> window.setLogLevel()
logger.ts:236 web3torrent: level CLEARED from debug to debug
undefined
logger.ts:59 wallet: level CLEARED from debug to info
```
=> Pino log levels are configurable from browser console

packages/xstate-wallet/src/utils/contract-utils.ts
For some reason importing the `InfuraProvider` with ``` import {InfuraProvider} from '@ethersproject/providers'; ``` caused an error.
Importing `providers` from `ethers` seems to work fine.
=> Add back InfuraProvider

package.json, packages/simple-hub/package.json, packages/xstate-wallet/package.json, packages/xstate-wallet/src/utils/contract-utils.ts, yarn.lock
The latest version of ethers contains the following: https://github.com/ethers-io/ethers.js/issues/861#issuecomment-638031278.
This allows us to remove the bespoke on-network-change reloading logic.
=> [xstate-wallet] Use ethers to reload page on network change

packages/web3torrent/src/App.tsx
Related to #2077.
On mobile wallets this property does not exist because there is no way to change networks without navigating away from the page on these wallets. That shouldn't prevent the page from loading.
Should resolve https://sentry.io/organizations/statechannels/issues/1717293691/?project=5228838&referrer=slack.
=> Check for window.ethereum.on function type in web3torrent

packages/web3torrent/src/constants.ts, packages/web3torrent/src/library/paid-streaming-extension.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/pages/file/File.tsx
PR description:
- Do not update UI on the most frequent webtorrent events: request, notice, upload, and download.
- Always after `onChannelUpdated`.
- Reduce frames-per-second to at most 10.
- Bump peer trust from 4 to 5.
=> [web3torrent] performance tweaks

packages/rps/package.json, packages/web3torrent/package.json, packages/xstate-wallet/package.json, yarn.lock
... and sync version number across packages.
I used [source-map-explorer ](https://www.npmjs.com/package/source-map-explorer)to profile the webpack output in `xstate-wallet`. Turns out `rimble-ui` is responsible for around **43%** of the unpacked javascript bytes. 
This change reduces that to around **40.3%**
This still leaves a lot to be desired. It looks like improvements are on the radar over at rimble-ui: https://github.com/ConsenSys/rimble-ui/pull/437
=> [rps,xstate-wallet] Upgrade rimble-ui

packages/channel-provider/src/logger.ts, packages/channel-provider/src/messaging-service.ts, packages/web3torrent/src/logger.ts, packages/xstate-wallet/config/webpack.config.js, packages/xstate-wallet/src/config.ts, packages/xstate-wallet/src/logger.ts
1. When I tried to set the log level to `trace`, it created an infinite loop:
Most of the non-Json-RPC message is a `PINO_LOG` message containing the error `"Received a non JsonRpc message"` :P
2. @kerzhner noticed that chrome expands trace calls. Firefox also seems to. So, trace log messages are redirected to `console.debug` instead.
3. `LOG_LEVEL` was not getting through the wallet's webpack config.
Fixes https://github.com/statechannels/monorepo/issues/2134
=> Fix some logging issues

packages/e2e-tests/puppeteer/helpers.ts
This should be much more useful, compared to [this](https://circle-production-customer-artifacts.s3.amazonaws.com/picard/5d85227bbc97ad5ba7cf4fb2/5ee13f1dc740a75af85bc6ef-0-build/artifacts/home/circleci/project/packages/e2e-tests/screenshots/seed-download.1.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20200611T180942Z&X-Amz-SignedHeaders=host&X-Amz-Expires=60&X-Amz-Credential=AKIAJR3Q6CR467H7Z55A%2F20200611%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=324fa3c6b2c352449cd6be0374ec016b7b7cf709cf68fb7e58d25876ce2f21a8).
=> Take screenshot of full page

packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/hooks/use-budget.ts
Fixes #2130 
The budget screen would call `createBudget` which would fail if the `etheuremEnable` workflow hadn't been run.
This PR changes `createBudget` to call `enable` if the `paymentChannelClient` hasn't been enabled.
=> Fix create budget from budget screen

.env.persistent-seeder, .env.production-goerli
PSA: Have switched the hub SC_ENV to the goerli one via heroku dashboard 🤞 .
I wonder if we should bring the persistent-seeder environment config in line with the simple-hub? i.e. remove `.env.persistent-seeder` and the baked-in references to it, and simply pass `.env.production-goerli` in the heroku dashboard?
=> Point persistent-seeder at goerli and tweak .env.production-goerli

packages/xstate-wallet/src/ui/factory-reset.tsx
Otherwise, the second factory reset fails:
```
Unhandled Rejection (DatabaseClosedError): DatabaseClosedError Database has been closed
```
=> Reload window after deleting database

.env.virtual-funding, packages/e2e-tests/puppeteer/constants.ts, packages/e2e-tests/puppeteer/helpers.ts
When running the multiple-leecher test locally, I find it hard to visually inspect the clients as devtools takes up much of the screen real estate.
With this PR, setting `SHOW_DEVTOOLS` to `false` helps.
=> [e2e] add SHOW_DEVTOOLS configuration

.env.virtual-funding, packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/components/torrent-info/TorrentInfo.tsx, packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx, packages/web3torrent/src/library/web3torrent-lib.ts
Fixes https://github.com/statechannels/monorepo/issues/1949.
The goal of the PR is to display the most relevant set of channels for the current torrent. We create an in-memory map of channel id to torrent hash that is updated when a channel is created, joined, or updated. The resulting behavior is:
- After page refresh, no channels are displayed from previous leeching or seeding.
- Only channels for the current file shared are displayed.
=> [web3torrent] Channel list UI

packages/channel-client/src/channel-client.ts, packages/channel-client/src/types.ts, packages/channel-client/tests/fakes/fake-channel-provider.ts, packages/channel-provider/src/channel-provider.ts, packages/channel-provider/src/types.ts, packages/client-api-docs/source/index.html.md, packages/client-api-schema/src/generated-schema.json, packages/client-api-schema/src/methods/EnableEthereum.ts, packages/client-api-schema/src/methods/GetWalletInformation.ts, packages/rps/src/redux/game/saga.ts, packages/rps/src/redux/store.ts, packages/rps/src/utils/__tests__/rps-channel-client.test.ts, packages/tic-tac-toe/app/services/user.ts, packages/web3torrent/src/App.tsx, packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/components/domain-budget/DomainBudget.tsx, packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx, packages/web3torrent/src/library/web3torrent-lib.ts, packages/xstate-wallet/src/integration-tests/approve-budget.test.ts, packages/xstate-wallet/src/integration-tests/close-withdraw.test.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/store/dexie-backend.ts, packages/xstate-wallet/src/store/memory-backend.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/store/types.ts, packages/xstate-wallet/src/workflows/ethereum-enable.ts
Fixes #2128.
Based on https://github.com/statechannels/monorepo/pull/2143#issuecomment-642811267.
> We discussed this on standup and the plan is to:
> 
> * Rename `selectedAddress` to `idealOutcomeAddress` or something like that which conveys that this is not a selected address but rather an address that, if ETH were sent there, would be easily accessible by the user. It will be set as the selected address in MetaMask the first time any app ever calls `EnableEthereum`.
> * Store `idealOutcomeAddress` in IndexedDB and re-use that as the destination address for all channels in the future instead of checking `ethereum.selectedAddress` each time.
> * Remove `destination` from being a property that can be provided by the application in the call to `CreateChannel`
=> Introduce destinationAddress concept

packages/web3torrent/package.json, packages/web3torrent/src/App.tsx, packages/web3torrent/src/hooks/use-budget.ts, packages/web3torrent/src/pages/file/File.tsx, packages/web3torrent/src/utils/react-utls.ts, yarn.lock
Fixes https://github.com/statechannels/monorepo/issues/2090 (mostly).
Fixes https://github.com/statechannels/monorepo/issues/1835 (mostly).
One common pattern in our code base:
1. Use `useEffect` hook to trigger an asynchronous operation after a component render.
1. At the asynchronous operation, update component state.
If the component is unmounted before step 2 completes, we see errors described in the issues above. This PR uses observables (instead of promises) in `useEffect` hooks in order to properly clean up after `useEffect` hooks. There remains one problematic hook: b6f8f0cb6.
Most of the `web3torrent` unit test log warnings should be fixed by this PR.
=> [web3torrent] clean up useEffect hooks

.env.circle-integration-w3t-with-hub, packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/utils/react-utls.ts
Instead of trying to win the "who can update first" five times, we instead obtain an unfair advantage by attempting to close before the app is notified, when the channel is updated.
Note: includes #2211
=> Make closeChannel more robust

packages/web3torrent/src/hooks/use-budget.ts
Calling an rxjs subscription `unsubscribe` method can lead to `TypeError: Cannot read property 'closed' of null`. I am not sure how to fix the underlying issue, so I have adopted the pattern of wrapping the unsubscribe invocation in a try/catch block
=> [web3torrent] use safe unsubscribe in use-budget

packages/web3torrent/src/library/paid-streaming-extension.ts, packages/web3torrent/src/library/types.ts, packages/web3torrent/src/library/web3torrent-lib.ts
Currently we have the problem that when seeder stops seeding, they choke, so no more requests are sent. They then might have to wait for the “no-progress timeout” for leecher to close the channel.
This PR adds a `PERMANENT_STOP` message, that the seeder sends to the leecher, which prompts them to close the channel.
=> Permanent stop

packages/web3torrent/src/components/domain-budget/DomainBudget.tsx, packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx
This ensures consistency across the two components even if the convention on lower casing is broken upstream of the UI.
=> Enforce lower casing in blockie calculation

.env.local-goerli, .env.production-goerli
Fixes #2175 .
I gave up trying different compiler versions etc to try and match the bytecode that was already deployed. 
I redeployed the contracts, noted the compiler version and method, and verified on etherscan. This PR would point our apps __at the newly deployed contract addresses__.
=> Redeploy contracts to goerli and verify

packages/web3torrent/src/library/web3torrent-lib.ts
In my testing, the following is the usual sequence of events when the leecher cancels download from one seeder:
1. Leeching channel id is set to null in `onChannelUpdated`.
1. Seeding channel id is set to null incorrectly in `closeChannel`.
This race condition might impact wires that are both seed and leech wires.
=> [web3torrent] for leecher, do not set seeding channel id to null blindly

packages/e2e-tests/puppeteer/__tests__/web3torrent/withdraw.test.ts, packages/web3torrent/src/components/domain-budget/DomainBudget.scss, packages/web3torrent/src/components/domain-budget/DomainBudget.tsx, packages/web3torrent/src/hooks/use-budget.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/pages/budgets/Budgets.tsx, packages/web3torrent/src/pages/file/File.tsx, packages/xstate-wallet/src/workflows/application.ts
Adds a `canWithdrawFeed` to the web3 torrent client that is used to notify the file component when the user should be allowed to withdraw.
The withdrawal button is disabled with a tooltip when there is an active torrent.
=> Only allow withdrawal when no active torrent

.env.circle-integration-w3t-with-hub, packages/e2e-tests/puppeteer/constants.ts, packages/e2e-tests/puppeteer/helpers.ts, packages/e2e-tests/puppeteer/parseBittorrentProtocolLogs.ts
This lets us know what's going on with wires.
I promised @kerzhner  I would look at some logs to see if wires were being dropped. There wasn't a way to see if wires were being dropped, so I decided to make those logs. Then I realized that webtorrent already logs lots of things, if you set `window.localStorage.debug = 'bittorrent-protocol'`, I just have to capture those and pino log them!
... this is what `debug` calls `console.log` with:
```
[
'%cbittorrent-protocol %c[5e0cb699] handshake i=%s p=%s exts=%o%c +11s',
'color: #9900CC',
'color: inherit',
'2045f638f8d12ad7d95c4876b2ebd851664e7579',
'2d5757303030372d31485472334634724c586b62',
{dht: false},
'color: #9900CC'
];
```
... after an hour, I managed to pino log it!
```
{"time":1592443875126,"msg":"handshake …
```
=> Add webtorrent logs

packages/web3torrent/src/pages/welcome/Welcome.scss, packages/web3torrent/src/pages/welcome/Welcome.tsx
~![Jun-18-2020 16-57-04](https://user-images.githubusercontent.com/1833419/85043844-c230d100-b184-11ea-80dd-ae948f20a350.gif)~
~Double pulse, 5 seconds of nothing, repeat.~
~Still seductive, but hopefully not _too_ seductive?~ Prefer box shadow option, below. 
Whatever we end up using here, we can roll out to other key moments in the user story. For example, I just finished the download: the "share link" button could pulse this way to nudge me into exploring that.
=> Button emphasis

packages/xstate-wallet/src/chain.ts
Sometimes when I load the Web3Torrent app I saw that I would go through the "EnableEthereumWorkflow" again, despite `window.ethereum.selectedAddress` being defined. I manually attempted to load https://xstate-wallet.statechannels.org and, really quickly, inspect `window.ethereum.selectedAddress` which _sometimes_ was `undefined` if I called it fast enough. I suspect what is happening is that there is a race condition between the initialization of `ChainWatcher` and MetaMask injecting `window.ethereum` into the app. This change should fix it.
=> Remove mySelectedAddress on ChainWatcher

packages/simple-hub/src/blockchain/eth-asset-holder.ts
Originally, we pushed gas price to 1000 gwei as a last resort to speed up Ropsten transactions. Now that production runs on Goerli, 15 gwei should be sufficient.
1000 gwei for a gas price results in the hub spending ~0.05 eth per deposit transaction, which drains the hub funds fairly quickly.
=> [simple-hub] reduce hub gas price from 1000 to 15 gwei

packages/nitro-protocol/docs/wallet-dev-tutorial/execute-state-transitions.md, packages/nitro-protocol/docs/wallet-dev-tutorial/finalize-a-channel-happy.md, packages/nitro-protocol/docs/wallet-dev-tutorial/finalize-a-channel-sad.md, packages/nitro-protocol/docs/wallet-dev-tutorial/fund-and-defund-off-chain.md, packages/nitro-protocol/docs/wallet-dev-tutorial/off-chain-funding.md, packages/nitro-protocol/docs/wallet-dev-tutorial/outcomes.md, packages/nitro-protocol/docs/wallet-dev-tutorial/release-assets.md, packages/nitro-protocol/website/sidebars.json
- removes tables from the outcomes section
- adds (long) section on indirect (d)efunding
- adds a passage about setup states
TODO
=> [nitro-docs] Add section on indirect (de)funding

package.json, packages/devtools/package.json, packages/e2e-tests/package.json, packages/jest-gas-reporter/package.json, packages/nitro-protocol/package.json, packages/persistent-seeder/package.json, packages/rps/package.json, packages/tic-tac-toe/package.json, packages/web3torrent/package.json, packages/xstate-wallet/package.json
I think some stale files in the build folder resulted in a broken build 0.1.3
(https://github.com/statechannels/nitro-tutorial/pull/1 -- evidence being I cleared the build folder, rebuilt, yarn linked and fixed the problem in this pull request).
=> Add clean-build-folder step to devtools build process

.circleci/config.yml, packages/client-api-schema/package.json, packages/client-api-schema/tsconfig.json, packages/wallet-core/.eslintrc.js, packages/wallet-core/package.json, packages/wallet-core/src/types.ts, packages/wallet-core/tsconfig.json, packages/xstate-wallet/.eslintrc.js, packages/xstate-wallet/package.json, packages/xstate-wallet/src/integration-tests/approve-budget.test.ts, packages/xstate-wallet/src/integration-tests/running.test.ts
This PR prepares the `wallet-core` package and `client-api-schema` package for publishing:
- updating their `package.json` files so that they publish the right things (up-to-date, compiled typescript files)
- updating their `tsconfig.json` files so that they compile the right things (no tests)
I've taken the liberty of publishing these two packages as of 2c7f551. You can explore the files that got published:
- https://www.npmjs.com/package/@statechannels/wallet-core
- https://www.npmjs.com/package/@statechannels/client-api-schema
(The "Explore" tab will let you browse the files.)
=> Publish wallet-core and client-api-schema

packages/nitro-protocol/docs/dapp-devs/quick-start.md
We have migrated Rock Paper Scissors, so the warning non longer applies.
=> [nitro-docs] Clarify note 

packages/wallet-core/package.json, packages/wallet-core/src/bignumber.ts, packages/wallet-core/src/index.ts, packages/wallet-core/src/serde/app-messages/deserialize.ts, packages/wallet-core/src/serde/app-messages/example.ts, packages/wallet-core/src/serde/app-messages/serialize.ts, packages/wallet-core/src/serde/wire-format/deserialize.ts, packages/wallet-core/src/serde/wire-format/example.ts, packages/wallet-core/src/state-utils.ts, packages/wallet-core/src/tests/outcomes-equal.test.ts, packages/wallet-core/src/types.ts, packages/wallet-core/src/utils/allocate-to-target.test.ts, packages/wallet-core/src/utils/contract-utils.ts, packages/wallet-core/src/utils/helpers.ts, packages/wallet-core/src/utils/index.ts, packages/wallet-core/src/utils/messages.ts, packages/wallet-core/src/utils/outcome.ts
Amounts cannot be safely stored in a Javascript number.
There is some contention over whether amounts should be stored in a string, or in a BigNumber class. Things
like storing and fetching amounts from the database, and serializing and deserializing are more complicated
with BigNumber classes. Constructing test data requires constantly importing BigNumber, and calling
`BigNumber.from(1)`, etc.
These problems are certainly not impossible to overcome, but they do add complexity, and can possibly add
bugs. Furthermore, saying that the type of an amount is BigNumber means your project has to commit to
using ethers, which is opinionated. Storing big numbers in string Javascript values is less opinionated.
This changeset is quite small, even after adding the (somewhat opinionated) Uint256 …
=> Add BigNumber utility class

packages/channel-client/package.json, packages/channel-provider/package.json, packages/client-api-schema/package.json, packages/e2e-tests/package.json, packages/persistent-seeder/package.json, packages/rps/package.json, packages/tic-tac-toe/package.json, packages/xstate-wallet/package.json, yarn.lock
https://github.com/statechannels/monorepo/releases/tag/client-api-schema%400.0.3
The new version mainly includes changes from https://github.com/statechannels/monorepo/pull/2296.
=> client-api-schema: bump version and publish tag

packages/channel-client/package.json
Entry point `channel-client` ends up indirectly importing more from the `tests` directory than initially thought. For example:
https://github.com/statechannels/monorepo/blob/c032fbcc8521dad43a6fd9952bb39650118cad24/packages/channel-client/src/channel-client.ts#L18
=> [channel-client] Include entire tests directory in published package

packages/channel-provider/package.json
The previous version did not include the required types files.
=> Publish @statechannels/channel-provider 0.0.5

packages/nitro-protocol/.eslintrc.js, packages/wallet-core/.eslintrc.js
Top level has them so we don't need them
=> Remove import/order in .eslintrc of sub-packages

package.json, yarn.lock
In my experience, npx seems to `fetchMetada` every time it runs when a package is not available in `node_modules/.bin`. This adds a second or two to every `yarn` run. Not a big deal, but we run `yarn` so frequently...
=> Add typesync to devDependencies

packages/server-wallet/src/protocols/actions.ts, packages/server-wallet/src/protocols/direct-funding.ts, packages/server-wallet/src/protocols/state.ts
It is important for `UpdateChannel` to specify all state variables --
otherwise, who decides which state variables to use? Should it come
from the latest state? the supported state? My latest state?
It seems like it's the protocol's responsibility to answer that.
When all state variables must be given, UpdateChannel and SignState
both mean the same thing: "Sign this state".
=> Consolidate UpdateChannel and SignState actions into a single, explicit action

packages/server-wallet/tsconfig.json
This is required to run knex commands using `ts-node`.
=> [server-wallet] Set module: commonjs in tsconfig

packages/server-wallet/src/wallet/index.ts
Very minor, but nice to use the exact types as defined by the API schema here. I'm hoping to use the fact they map one-to-one to be able to do some automatic forwarding of HTTP requests directly to these methods based on the method name only without any changes to the arguments passed in.
=> Use client-api-schema defined types

packages/nitro-protocol/docs/protocol-docs/tutorial.md, packages/nitro-protocol/docs/protocol-tutorial/deposit-assets.md, packages/nitro-protocol/docs/protocol-tutorial/execute-state-transitions.md, packages/nitro-protocol/docs/protocol-tutorial/finalize-a-channel-sad.md
These changes mirror those made in statechannels/nitro-tutorial repo, which now includes CI testing.
=> [docs] Pin tutorial to nitro-protocol v0.1.6.

packages/server-wallet/src/db/seeds/1_signing_wallet_seeds.ts, packages/server-wallet/src/handlers/__test__/join-channel.test.ts, packages/server-wallet/src/handlers/fixtures/join-channel.ts, packages/server-wallet/src/handlers/join-channel.ts, packages/server-wallet/src/models/__test__/channel.test.ts, packages/server-wallet/src/wallet/__test__/fixtures/states.ts, packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/__test__/integration/update-channel.test.ts, packages/server-wallet/src/wallet/__test__/sign-state.test.ts, packages/server-wallet/src/wallet/index.ts
- Adds a join-channel handler, similar to the existing update-channel handler
- Implements `joinChannel` on the wallet
- What if the messages are for unrelated channels?
- What is the definition of `status`? 
- What `turnNum` should be reported? That of `latest`? Or of `supported`?
- Should they be merged into a single, "maximal" result?
- If so, how do you order results?
=> Join channel

packages/server-wallet/e2e-test/ping/client.ts, packages/server-wallet/e2e-test/pong/controller.ts, packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/update-channel.test.ts, packages/server-wallet/src/wallet/index.ts
Adds two separate return types `SingleChannelResult` and `MultipleChannelResult`
=> Update Wallet API return types

packages/channel-client/api-extractor.json, packages/iframe-channel-provider/api-extractor.json
Gets rid of this dreaded diff after every yarn run:
```
warning: CRLF will be replaced by LF in packages/channel-client/temp/channel-client.api.md.
The file will have its original line endings in your working directory
warning: CRLF will be replaced by LF in packages/docs-website/docs/generated-apis/channel-client.api.json.
The file will have its original line endings in your working directory
warning: CRLF will be replaced by LF in packages/docs-website/docs/generated-apis/iframe-channel-provider.api.json.
```
=> Use lf for line endings for api-extractor generated files

packages/server-wallet/src/wallet/__test__/lock-app.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts
Resolves https://github.com/statechannels/statechannels/issues/2371.
See https://www.notion.so/App-level-concurrency-870d2e8e5e49436696bbc303d9976e02 for discussion.
It seems a bit strange to test this kind of code with a unit test like included here. The real test will be the [stress test](https://github.com/statechannels/statechannels/issues/2391)
=> Add `lockApp` method

packages/docs-website/docs/app-devs/quick-start-dapp.md, packages/iframe-channel-provider/src/channel-provider.ts, packages/iframe-channel-provider/src/iframe-service.ts, packages/iframe-channel-provider/src/postmessage-service.ts
I spent some time debugging this error:
```
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided does not match the recipient window's origin.
```
which you can see if you try and communicate with the wallet before the iframe has properly mounted. We need to make it clear to app devs that they should await these async methods in the correct order. Have also added an error if they are called out of order.
=> [channel-provider] Tweaks

packages/server-wallet/src/wallet/__test__/lock-app.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts
It seems like the default behaviour when a channel is missing should be
to throw a generic ChannelMissing error. This attempts to minimize the
chance that a missing channel goes unhandled.
This allows you to pass a custom missing channel handler, in case you
want to throw a different error.
=> Improve lockApp error handling

packages/server-wallet/src/logger.ts
Seems to be better practice to pipe output through `pino-pretty` e.g.,
```bash
./run-test | pino-pretty
```
=> Remove prettyPrint on pino

packages/devtools/src/config/env.ts
Our software presently depends on `NODE_ENV` to exist in order to read from the environment for certain things. One of those things is the `server-wallet`, which threw an error if `NODE_ENV` was undefined. This fixes that.
Importing is still ugly though this these warnings. But manageable for now.
```node
> require('@statechannels/server-wallet')
HUB_DESTINATION environment variable should be defined, you might see issues
[@statechannels/devtools] NODE_ENV is undefined — setting to "development"
{ Wallet: [Function: Wallet], getOrThrow: [Function: getOrThrow] }
```
=> Default NODE_ENV to development for usage of env.ts

packages/docs-website/website/package.json
to prepare all documented packages. Without this, the relevant circle step doesn't have all of the autogenerated files.
=> [docs] Modify build script

packages/server-wallet/e2e-test/e2e-utils/ping.ts, packages/server-wallet/e2e-test/e2e.test.ts, packages/server-wallet/e2e-test/scripts/ping.ts, packages/server-wallet/package.json, yarn.lock
- Creates a `ping.ts` script which accepts command line arguments, using yargs
- `e2e.test.ts` spawns a `ping` process, rather than creating a ping client within the same process as the jest test runnier
This makes it easier to create v1 & v2 stress tests: we can spawn multiple `ping` scripts to represent different actors. They can have different databases (different indexers) or the same database (simulating horizontal scaling).
=> [server-wallet/e2e-test] Run ping client in a separate process

packages/server-wallet/e2e-test/e2e.test.ts, packages/server-wallet/e2e-test/payer/client.ts, packages/server-wallet/e2e-test/receiver/app.ts, packages/server-wallet/e2e-test/receiver/controller.ts, packages/server-wallet/src/index.ts, packages/server-wallet/src/wallet/__test__/fixtures/messages.ts, packages/server-wallet/src/wallet/index.ts
It's still confusing that `pushMessage` accepts a `Message` but `MessageQueued` is a `WireMessage`, but at least now the difference is more jarring.
=> Disambiguate WireMessage and Message a bit

packages/iframe-channel-provider/src/channel-provider.ts
We expect a certain number of messages which will not be json-rpc related.
Closes #2438
=> [channel-provider] Restore early return to onMessage

packages/client-api-schema/src/data-types.ts, packages/client-api-schema/src/generated-schema.json, packages/client-api-schema/src/notifications.ts, packages/server-wallet/e2e-test/e2e.test.ts, packages/server-wallet/e2e-test/receiver/controller.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/protocols/application.ts, packages/server-wallet/src/protocols/state.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/index.ts
- the `toChannelResult: (cs: ChannelState) => ChannelResult` converter properly calculates (my interpretation of) `ChannelStatus`
- the `application` workflow does not notify a `ChannelProposed` notification.
- I think these notifications are redundant, given that the same data exists on the `ChannelResult`
- `pushMessage` returns the `ChannelResult` computed from each channel, once the channel is "marked as done"
Resolves https://github.com/statechannels/statechannels/issues/2378
=> Return channelResults from `pushMessage`

packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts
We do not know yet what the participant ID is, and the destination should probably not default to the signing address?
=> Add getParticipant method on server wallet

packages/server-wallet/src/wallet/__test__/signing-address.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts
`getSigningAddress` has the following behavior:
- if at least one signing address exists, return it.
- otherwise, create a signing address (and private key), store it, and return it.
=> [server-wallet] Add getSigningAddress to Wallet api

packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts, packages/server-wallet/src/wallet/index.ts
It is dangerous to start a query _outside_ a transaction, while
executing a transaction.
What happens if I call `createChannel` 10 times in a row?
1. I max out the connection pool, consuming 8 connections
2. Every ongoing transaction tries to get a new connection, to start
a new query outside of that transaction to get the next nonce
3. No transaction finishes, since no connections open up
We've reached a deadlock.
=> Fetch nonce before creating channel transaction

packages/server-wallet/src/db/migrations/20200812081700_signing_wallet.ts, packages/server-wallet/src/wallet/__test__/signing-address.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts
Fixes https://github.com/statechannels/statechannels/issues/2455
With a database constraint, the database will prevent creating more than one `signing_wallet` rows.
=> [server-wallet] Enforce one row for signing_wallets table

packages/server-wallet/src/wallet/__test__/add-signed-state.test.ts, packages/server-wallet/src/wallet/__test__/lock-app.test.ts, packages/server-wallet/src/wallet/__test__/sign-state.test.ts, packages/server-wallet/src/wallet/store.ts
Fixes https://github.com/statechannels/the-graph/issues/52
`ValidateSignatures` was relying on the `signer` address on the signature object instead of actually verifying the signature. This fixes `validateSignature` to actually validate the signature provided.
=> Fix ValidateSignatures

packages/nitro-protocol/src/contract/force-move-app.ts, packages/server-wallet/benchmarks/get-channel.benchmark.ts, packages/server-wallet/benchmarks/update-channel.benchmark.ts, packages/server-wallet/e2e-test/payer/client.ts, packages/server-wallet/e2e-test/receiver/controller.ts, packages/server-wallet/src/__test__/evm-validator.test.ts, packages/server-wallet/src/config.ts, packages/server-wallet/src/evm-validator.ts, packages/server-wallet/src/metrics.ts, packages/server-wallet/src/models/signing-wallet.ts, packages/server-wallet/src/utilities/signatures.ts, packages/server-wallet/src/wallet/__test__/add-signed-state.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts
This adds a naive `timerFactory` which lets us [time](https://github.com/statechannels/statechannels/compare/ags/wallet-benchmarks?expand=1#diff-da530680787955aca14faaf1899bcce0R87) some async, and slow sync function calls.
By [inspecting the output](https://github.com/statechannels/statechannels/commit/a65e6001b59b373cad67982938ead7be0c84f057) and auditing the code, I removed a number of database queries.
I also used [`fastSignState`](https://github.com/statechannels/statechannels/commit/d1bf1f3e75ef1e8d9a8bb88c000196c55d6fba4d) implemented by @kerzhner , which was a huge time saver in the stress test:
- [before d1bf1f3e75ef1e8d9a8bb88c000196c55d6fba4d](https://app.circleci.com/pipelines/github/statechannels/statechannels/8670/workflows/995f686f-d3f7-4c08-a3db-8166ef22270a/jobs/40855)
- …
=> Benchmark some wallet code, fix a serious bug, and speed things up

package.json, packages/channel-client/package.json, packages/client-api-schema/package.json, packages/devtools/package.json, packages/docs-website/website/package.json, packages/iframe-channel-provider/package.json, packages/integration-tests/package.json, packages/jest-gas-reporter/package.json, packages/nitro-protocol/package.json, packages/wallet-core/package.json, packages/wire-format/package.json, packages/xstate-wallet/package.json
Ensures clean working directory when running `lerna version`, so that immediately running `lerna publish` will not error out. See #2497 . It essentially rolls the `versions.json` file in our docs website in with the package.json files when the version commit is made. 
Also deletes `gitHead` entries, and removes an unecessary script from the top level `package.json`. Unfortunately I think `gitHead` entries will still be generated (and they shouldn't). It's difficult to test this without publishing things to npm.
=> [monorepo] Improvements to Publishing workflow

packages/server-wallet/src/index.ts
Builds on https://github.com/statechannels/statechannels/pull/2531.
Exporting configured knex is intended to help packages that use `server-wallet` and need to migrate the `server-wallet` database.
=> Export configured knex

packages/server-wallet/e2e-test/scripts/generate-profile-data.ts, packages/server-wallet/src/models/signing-wallet.ts, packages/server-wallet/src/utilities/__test__/signatures.test.ts, packages/server-wallet/src/utilities/signatures.ts, packages/server-wallet/src/wallet/__test__/add-signed-state.test.ts, packages/server-wallet/src/wallet/store.ts, packages/wallet-core/src/types.ts
This PR reduces the number of times that a (running) state is hashed to exactly once per wallet. This is the minimum number of times (since Alice can't trust the hash of the state that Bob sends Alice).
This is inspired by the [flamegraph](https://41825-209829093-gh.circle-artifacts.com/0/home/circleci/project/artifacts/1288.clinic-flame.html#selectedNode=6302&zoomedNode=&exclude=8000-0-0-0-780&merged=true) generated eg. on the current master.
Locally, I observed significant reductions in the time to run a stress test.
I also observed:
```
monorepo/packages/server-wallet on  ags/minimal-hashing [⇡$] is 📦 v0.3.4 via ⬢ v12.16.3 on ☁️  us-west-1 took 11s 
❯ ts-node benchmarks/update-channel.benchmark.ts
[@statechannels/devtools] NODE_ENV is undefined — setting to "development"
serial x 100: …
```
=> Minimal hashing

packages/server-wallet/package.json, packages/server-wallet/src/db-admin/knexfile.ts
Yes, I know, it does `require` devtools, but it can get by without it.
This is important for projects that depend on the server wallet and import the db-admin-connection. It is a temporary fix, since we aim to remove the use of configureEnvVariables.
=> adminKnex that gets exported does not "require" devtools

package.json
This shouldn't be necessary as all packages use the same version of ethers. Hoisting should save a little bit of disk space (modest, though since ethers is small).
=> Remove nohoist

packages/docs-website/docusaurus.config.js, packages/docs-website/package.json
Avoids relying on environment variables, which had led to some hacks and bad dev experience (`yarn build` failed with an uninformative error message if you didn't have the right env var set). 
I checked with the algolia team and this key is OK to check in to source control.
=> [docs-website] Inject algolia api key to source code

packages/docs-website/docs/contract-api/contract-inheritance.mdx, packages/docs-website/docusaurus.config.js
Closes #2555 
Currently, it works if there is no trailing `/` in the current url, but you get a 404 if there is (and there is if you navigate back to this page for a second time.
=> [docos-website] Use absolute links

.circleci/config.yml
I never saw this before on circle.
=> Add ~/.cache/yarn to save_cache list

packages/server-wallet/e2e-test/payer/client.ts, packages/server-wallet/e2e-test/receiver/app.ts, packages/server-wallet/e2e-test/receiver/controller.ts, packages/server-wallet/src/index.ts, packages/server-wallet/src/wallet/__test__/fixtures/messages.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts, packages/wallet-core/src/serde/wire-format/deserialize.ts, packages/wallet-core/src/serde/wire-format/example.ts, packages/wallet-core/src/serde/wire-format/serialize.ts, packages/wallet-core/src/types.ts, packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/workflows/tests/simple-hub.ts
Before this PR we had `Message` defined in multiple places
```ts
// in wire-protocol
export interface Message {
recipient: string; // Identifier of user that the message should be relayed to
sender: string; // Identifier of user that the message is from
data: {
signedStates?: SignedState[];
objectives?: Objective[];
};
}
// in client-api-schema
export interface Message {
data: unknown;
recipient: string;
sender: string;
}
// in wallet-core
export interface Message {
signedStates?: SignedState[];
objectives?: Objective[];
}
```
The wallet core type was totally incompatible with the other two :/. 
This PR renames the wallet-core `Message` to `Payload` - consistent with being the type of `Message['data']` from wire-protocol.
=> Rename wallet-core Message -> Payload

packages/docs-website/docs/app-devs/quick-start-dapp.md
We should point app developers at the most recent version of the wallet that we have deployed. In particular, v0.3.0 includes a number of fixes and passes the `integration-test` (so is known to work with `channel-client`, `iframe-channel-provider` and `client-api-schema` all @ 0.3.0). 
AFAIK more recent versions of those packages should also work with the 0.3.0 browser wallet, but we do not yet have a rigorous sem ver workflow in this repo so that is by no means guaranteed.
=> [docs-website] Point to latest deployed wallet

packages/server-wallet/readme.md, packages/server-wallet/src/wallet/__test__/fixtures/messages.ts, packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/__test__/sign-state.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts, packages/wallet-core/src/serde/wire-format/deserialize.ts, packages/wallet-core/src/serde/wire-format/example.ts, packages/wallet-core/src/serde/wire-format/serialize.ts, packages/wire-format/src/generated-schema.json, packages/wire-format/src/types.ts
This PR contains a bunch of fixes required to get the server-wallet to communicate using the wire-format:
* Updates wire-format to include the new `requests` property
* Updates wallet-core serde to not drop the `requests` property
* Changes the type of the message handed to `pushMessage` to `unknown`, and then validates the correct format immediately
* Ensures that the messages being sent from the wallet are the right format
The change to `unknown` is really important, as it will prevent users of the wallet from having to cast messages to the right type, as is happening all over the `payment-manager` and `receipt-manager`.
There are potential performance implementations, because converting from the wire-message format and back can involve hashing/signature recovery. In theory, this isn't …
=> Server wallet uses wire format

packages/server-wallet/benchmarks/update-channel.benchmark.ts
Every time I want to run this benchmark on `master`, I need to make this
change locally.
=> chore (server-wallet): fix update-channel benchmark

packages/client-api-schema/src/generated-schema.json, packages/client-api-schema/src/methods/CreateChannel.ts, packages/server-wallet/src/db/migrations/20200915140300_chain_service.ts, packages/wire-format/src/generated-schema.json, packages/wire-format/src/types.ts, packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/workflows/application.ts
Per discussion during standup, we discussed that a wallet might:
- Receive a prefund state without an objective.
- Later receive an objective that specifies how a channel should be funded.
The server wallet should default to the `Unknown` funding type for the case above. The `Unfunded` type is also added to support channels that do not have funding.
Also addresses https://github.com/statechannels/statechannels/pull/2561#discussion_r491503249
=> Add Unfunded and Unknown funding strategies

packages/server-wallet/src/models/funding.ts, packages/server-wallet/src/wallet/store.ts
`update` validates and updates every column of the table for a particular query which seems unnecessary (@andrewgordstewart ?). `patch` should be faster since it is a simpler query.
Tradeoff:
- Faster queries (I think?)
- Less validation
=> [server-wallet] Remove pre-database query data validation

packages/server-wallet/src/mock-chain-service/index.ts, packages/server-wallet/src/protocols/__test__/application.test.ts, packages/server-wallet/src/protocols/actions.ts, packages/server-wallet/src/protocols/application.ts, packages/server-wallet/src/wallet/index.ts
This is the first step for the wallet to use the new, rich `OnchainService` api.
=> Migrate from submitTransaction to fundChannel

packages/xstate-wallet/package.json
This is crucial for anyone wanting to use this package as a (dev) dependency
=> fix: Add missing dependency to xstate-wallet

packages/server-wallet/src/metrics.ts, packages/server-wallet/src/wallet/__test__/add-my-state.test.ts, packages/server-wallet/src/wallet/__test__/add-signed-state.test.ts, packages/server-wallet/src/wallet/__test__/get-first-participant.test.ts, packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts, packages/server-wallet/src/wallet/__test__/lock-app.test.ts, packages/server-wallet/src/wallet/__test__/sign-state.test.ts, packages/server-wallet/src/wallet/__test__/signing-address.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts
I think we agree that Knex is an implementation detail of a PostgreSQL specific implementation of a Store, thus it should not be known by a Wallet, especially if we intend on re-using that code in the browser.
=> Knex should be implementation detail of Store

.circleci/config.yml
1. it was flickering on circle
2. I think it is now _broken_ on circle (I think I know why...)
3. the last flamegraph I looked at was useless, since it now seems to profile a bunch of test setup code
Related to https://github.com/statechannels/statechannels/issues/2565
=> disable server wallet profiling on circle

.circleci/config.yml, packages/server-wallet/src/wallet/index.ts
Previously the test [would **pass** despite throwing a runtime error](https://app.circleci.com/pipelines/github/statechannels/statechannels/8956/workflows/f5416351-b446-43f5-b4b6-5d183f8b16ff/jobs/42603/parallel-runs/0/steps/0-105). I suppose that means the flame graphs that were generated were not representative of a full "cycle" of usage, as one part of the usage would fail; in particular, calls to `Wallet.getState` (which happened within `PayerClient.makePayment`)?
#2602 fixed the runtime error, but now [the test **fails** because it goes too long without output](https://app.circleci.com/pipelines/github/statechannels/statechannels/9130/workflows/711e983b-7525-4c5e-b163-47fafa91f5fc/jobs/43795/parallel-runs/0/steps/0-105).
The test goes too long without output because …
=> [server-wallet]: Restore knex as mutable property of Wallet

packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts, packages/wallet-core/src/serde/wire-format/serialize.ts
It's an optional parameter which means the function can skip computation of the `channelId` in the case it is already known.
=> [server-wallet] Pass channelId to serializeMessage

packages/client-api-schema/client-api-schema.api.md, packages/client-api-schema/temp/client-api-schema.api.md, packages/server-wallet/src/errors/wallet-error.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts, packages/wallet-core/src/serde/wire-format/deserialize.ts, packages/wallet-core/src/serde/wire-format/serialize.ts, packages/wallet-core/src/types.ts, packages/wallet-core/src/wire-protocol.ts, packages/wire-format/src/generated-schema.json, packages/wire-format/src/types.ts
For background, reference https://www.notion.so/Channel-creation-9f16c02442704490bde6203284f18026#b37bf705e2f742ada29eb1f005fdccd1.
The wallet:
- Sends an `OpenChannel` objective after signing state with turn 0.
- Creates a new channel in the database upon receiving a new state for which a channel does not exist.
- Updates `fundingStrategy` upon receiving the `OpenChannel` objective.
=> Remove CreateChannel objective

packages/server-wallet/e2e-test/e2e-utils.ts, packages/server-wallet/e2e-test/payer/client.ts, packages/server-wallet/e2e-test/payer/start.ts, packages/server-wallet/e2e-test/scripts/generate-profile-data.ts, packages/server-wallet/src/wallet/index.ts, yarn.lock
~Find a fix - suspect something to do with using `recordFunctionMetrics()` (I get a different error if I don't use that)  metrics~
~Apply fix~
#2565 Has been now been solved, but this PR:
-  inserts a change which makes the test properly fail if there is an error (which could save us in the future). 
- changes the `PayerClient` to accept configuration in it's constructor
- a little bit of refactoring here and there
=> [server-wallet] Fail profile job on error

packages/server-wallet/src/models/__test__/fixtures/channel.ts, packages/server-wallet/src/models/__test__/signing-wallet.test.ts, packages/server-wallet/src/models/signing-wallet.ts, packages/server-wallet/src/utilities/signatures.ts, packages/server-wallet/src/wallet/__test__/fixtures/states.ts
- And all signing is now sync (not async)
- SigningWallet.signState can take a State or StateWithHash, adds the hash if necessary
=> chore: remove reference to wallet-core signState

packages/integration-tests/package.json, packages/jest-gas-reporter/package.json, packages/jest-gas-reporter/src/index.ts, packages/nitro-protocol/package.json, yarn.lock
Used [`depcheck`](https://www.npmjs.com/package/depcheck) to find missing and unused dependencies. 
Dependency graph on master:
On this branch:
`npx lerna-dependency-graph -o graph.png -f png`
=> chore(jest-gas-reporter): Remove dependency on devtools

packages/server-wallet/e2e-test/e2e.test.ts, packages/server-wallet/src/utilities/__test__/messaging.test.ts, packages/server-wallet/src/utilities/messaging.ts, packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/index.ts
This PR implements two new functions that get called in the `wallet`:
- `mergeOutgoing`
- `mergeChannelResults`
`mergeOutgoing` merges multiple messages to the same `receipient` into one message. This allows one client to send all the messages to another in one request/response cycle.
`mergeMultipleChannelResults` merges `ChannelResult[]`s by only allowing one entry per a `channelId`. If there are multiple entries it takes the one with the highest `turnNum` . Fixes #2623 .
=> Merge Outgoing Messages to same recipient and duplicate channel results

package.json
It makes little sense to limit the concurrency to a smaller value on a PR  than it is on `master` (since if we ran out of memory on the feature branch we would run out of memory on master anyway). We run all tests on master and all or fewer tests on a PR.
=> Increase concurrency to default for test job

packages/server-wallet/e2e-test/payer/client.ts, packages/server-wallet/e2e-test/receiver/controller.ts, packages/server-wallet/src/onchain-service/__onchain-test__/onchain-service.test.ts, packages/server-wallet/src/onchain-service/onchain-service.ts, packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts, packages/server-wallet/src/wallet/index.ts
This PR introduces three new methods to the wallet API:
- JoinChannels - Allows the joining of multiple channels in one call to the wallet.
- UpdateFundingForChannels - Allows the updating of funding for multiple channels in one call to the wallet.
- MergeMessages - Merges multiple messages into one message. This is useful for merging the result of different API calls in one request/response cycle.
=> Add methods to wallet for batch processing

packages/server-wallet/src/config.ts, packages/server-wallet/src/utilities/workers/worker.ts
This ensures that worker threads only use one `postgres` connection. (This seems to be the default behaviour but this enforces it)
=> Enforce max connection pool size of 1 for threads

packages/server-wallet/package.json, packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/__chain-test__/stress.test.ts, packages/server-wallet/src/chain-service/chain-service.ts
For erc20 asset holders, the chain service calls `increaseAllowance` before depositing to address https://github.com/statechannels/statechannels/pull/2645#discussion_r499456033. The alternative (which is the implementation prior to this PR) is for the chain service to assume that `increaseAllowance` has already been called prior to the `fundChannel` api call.
This PR also:
- adds a unit test for depositing into a channel with 2 asset holder allocations.
- a stress test that creates 100 deposits (mostly to try to reproduce transaction nonce errors).
- adds a transaction queue to avoid nonce errors.
=> Chain service calls increaseAllowance for erc20 asset holders

packages/nitro-protocol/contracts/NitroAdjudicator.sol, packages/server-wallet/package.json, packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/chain-service/mock-chain-service.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/tsconfig.json
This PR build on https://github.com/statechannels/statechannels/pull/2661.
After a `ChainEventSubscriber` registers a channel with the chain service, the chain service will relay `AssetTransferred` events via `onAssetTransferred` api.
=> Add onAssetTransferred to ChainEventSubscribers

.github/workflows/publish-canary.yml, .github/workflows/publish.yml, lerna.json
Mostly copy-paste from the graph monorepo. 
Questions:
---
- We are not doing conventional commits very strictly in this repo. #2617 would help with that?
- Do we keep with lockstep versioning? Will these actions work with that?
=> ci: Add publish and publish-canary workflows

packages/nitro-protocol/src/contract/asset-holder.ts
The behaviour of ethers' `toHexString()` changed. And we probably shouldn't have relied on it in the first place?
=> fix: use more robust check when converting address

packages/server-wallet/src/wallet/__test__/lock-app.test.ts, packages/server-wallet/src/wallet/__test__/sign-state.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts
Idea: The `Store` should not be handling messaging logic. It should do very basic things like sign states, add channel objects to the DB, store objectives, and things like this. It is the wallet's job to interpret newly signed states and turn them into outgoing messages.
=> refactor: Move some (not all) messaging business logic out of Store

packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/chain-service/mock-chain-service.ts
Consider the case of a long running, gateway server wallet. The wallet will manage one ledger channel for each indexer. If there is indexer turnover, the server wallet will continuously create new ledger channels and register those channels with the chain service. Channel registration consumes resources as a new observable is created every time a channel is registered.
unregisterChannel api should be called when a wallet no longer cares about channel chain events.
=> unregisterChannel chain service api

packages/server-wallet/.vscode/launch.json, packages/server-wallet/e2e-test/payer/client.ts, packages/server-wallet/src/__test__/create-channel/direct-funding.test.ts, packages/server-wallet/src/protocols/__test__/application.test.ts, packages/server-wallet/src/protocols/application.ts, packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts
Before this PR, every participant signs postfund state with turn number 3. The challenges with this are:
- https://www.notion.so/Server-wallet-application-Bob-Alice-communication-c0127c3196694e14bd0cf4858955fa96#032978ba91394e87a9774c94fb1222a0.
- Only works for a 2 party channel. That's ok for now.
- Until every participant signs the postfund state, there is no supported postfund state. Maybe that's not a big deal.
With this PR, turn numbers increase for postfund states.
- Alice signs postfund turn 2
- Bob signs postfund turn 3.
=> server-wallet: increase turn numbers for postfund setup

.github/workflows/publish.yml, lerna.json, packages/docs-website/package.json
Without this, lerna is going to assume all packages have changed every time we try to publish. 
https://github.com/lerna/lerna/tree/master/commands/version#--include-merged-tags
=> Configure lerna to detect merged tags

packages/server-wallet/e2e-test/e2e-utils.ts, packages/server-wallet/e2e-test/payer/start.ts, packages/server-wallet/src/__test__/create-and-close-channel/direct-funding.test.ts, packages/server-wallet/src/__test__/create-and-close-channel/fake-funding.test.ts, packages/server-wallet/src/__test__/evm-validator.test.ts, packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/__chain-test__/stress.test.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/chain-service/mock-chain-service.ts, packages/server-wallet/src/config.ts, packages/server-wallet/src/db-admin/db-admin-connection.ts, packages/server-wallet/src/evm-validator.ts, packages/server-wallet/src/models/__test__/app-bytecode.test.ts, packages/server-wallet/src/models/app-bytecode.ts, packages/server-wallet/src/wallet/__test__/add-my-state.test.ts, packages/server-wallet/src/wallet/__test__/add-signed-state.test.ts, packages/server-wallet/src/wallet/__test__/get-first-participant.test.ts, packages/server-wallet/src/wallet/__test__/integration/close-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/__test__/integration/sync-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/update-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts, packages/server-wallet/src/wallet/__test__/lock-app.test.ts, packages/server-wallet/src/wallet/__test__/sign-state.test.ts, packages/server-wallet/src/wallet/__test__/signing-address.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts
Exposes a `RegisterAppDefinition` method on the `wallet` that registers the `bytecode` for that `AppDefiniton`. 
This new method uses the `chainService` to fetch the bytecode and then registers it in the database.
Currently the bytecode is overriden if `RegisterAppDefinition` is called twice to play nice with `ganache`. Once we start actually using `ChainId` we may want to throw an error if there already exists bytecode for a given definition.
=> [server-wallet] Allow registering of bytecode

packages/server-wallet/src/wallet/index.ts, yarn.lock
Most unit tests use a mock chain service. This reduces logging noise for unit tests.
=> refactor: log level of debug for mock chain service warning

packages/server-wallet/src/__chain-test__/direct-funding.test.ts, packages/server-wallet/src/__test__/create-and-close-channel/direct-funding.test.ts, packages/server-wallet/src/__test__/create-and-close-channel/fake-funding.test.ts, packages/server-wallet/src/db/seeds/1_signing_wallet_seeds.ts, packages/server-wallet/src/handlers/__test__/join-channel.test.ts, packages/server-wallet/src/handlers/join-channel.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/protocols/__test__/application.test.ts, packages/server-wallet/src/protocols/state.ts, packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts
This PR switches the turn number on prefund setups to be the index of the participant.
This allows for the supported turn during prefund/postfund to be the latest state signed by a participant.
=> Switch PrefundSetup turrnnum to be index of participant

packages/nitro-protocol/contracts/test/TestErc20AssetHolder.sol, packages/nitro-protocol/test/contracts/ERC20AssetHolder/deposit.test.ts, packages/nitro-protocol/test/contracts/NitroAdjudicator/concludePushOutcomeAndTransferAll.test.ts, packages/nitro-protocol/test/contracts/NitroAdjudicator/pushOutcomeAndTransferAll.test.ts
Headlines: 
`ERC20AssetHolder.deposit`:
```
Deposits Tokens (expectedHeld = 0):
76024 gas
Deposits Tokens (expectedHeld = 1):
46024 gas
```
Most expensive for first person to deposit, since they must create (instead of modify) a storage slot. Perhaps some interesting game theory there!
`concludePushOutcomeAndTransferAll`:
```
{ERC20: {A: 1, B: 1}}:
140121 gas
{ERC20: {At: 1, Bt: 1}} (At and Bt already have some TOK, so it's cheaper to pay out-- this is probably the norm, though):
110109 gas
10 TOK payouts:
406,543 gas
50 TOK payouts:
1,589,293 gas
100 TOK payouts:
2,656,645 gas
```
Context: that block gas limit of 8million.
=> [nitro-protocol] Enhance testing of ERC20 deposits and withdrawals

packages/iframe-channel-provider/package.json
When publishing a canary build, a conflicting dependency version warning
clued me into this issue
=> chore: remove "conflicting" dev dependency

.circleci/config.yml
=> chore: disable server-wallet-profiling step

packages/server-wallet/src/models/__test__/nonces.test.ts, packages/server-wallet/src/models/nonce.ts, packages/server-wallet/src/wallet/store.ts
The `Nonce` is currently not bumped on the receiving end and this can lead to issues when a party who has received many states decides to create a channel with an existing counterparty.
=> [server-wallet] Ensure Nonce gets bumped on reception of new signed states

packages/server-wallet/src/evm-validator.ts, packages/server-wallet/src/wallet/store.ts
Performs the validation done by the `validTransition`in the ForceMove contract in typescript. This allows us to validate the basic transition rules without using  the `EVM`.
Also we no longer try to validate `Prefund/postfundSetup`  state transitions in the `EVM`.
=> Validate ForceMove transition rules in typescript

packages/server-wallet/src/wallet/store.ts
You may want to store a state that is not a valid transition from a previously supported one (e.g., a new ledger update) but not consider it supported. In that case, you still want to check if a valid transition is there to determine if it is in fact supported but you don't want to discard the new state entirely.
=> fix: log error on invalid state transition of received state instead of throwing

packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts, packages/server-wallet/src/models/ledger-requests.ts, packages/server-wallet/src/protocols/actions.ts, packages/server-wallet/src/protocols/close-channel.ts, packages/server-wallet/src/protocols/process-ledger-queue.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts
When `closeChannel` is called on a channel that is ledger funded, it will kick off an objective for the wallet to close that channel and now with this PR, that objective does not complete unless the funds are re-allocated to its parent ledger channel. Works concurrently.
=> [server-wallet] Support ledger defunding

packages/server-wallet/src/wallet/store.ts
Following the approach outlined [here](https://github.com/statechannels/statechannels/pull/2728#issuecomment-715311687):
* it's too restrictive to check all state transitions for valid transitions, because new ledger states will always fail this check
* in the longer term we probably want to think more carefully about where we do this check
* but for now, we just turn it off for ledger channels
=> fix: disable validTransition check for ledger channels

packages/server-wallet/src/protocols/__test__/open-channel.test.ts, packages/server-wallet/src/protocols/open-channel.ts
`completeOpenChannel` should only generate the `completeObjective` after the last `postfund` state has been signed, NOT any postfund state.
After this is fixed and new server wallet package is published, the direct funding e2e test can be commented back in in the-graph repo: https://github.com/statechannels/the-graph/commit/6184cf377c4ae8069a34a5ffd8778f74c0275a81
=> fix: completeOpenChannel uses turn number

packages/server-wallet/jest/knex-setup-teardown.ts, packages/server-wallet/src/config.ts, packages/server-wallet/src/wallet/index.ts
If you
1. starting a transaction (acquires a connection)
2. executing a query (acquires a connection)
3. committing the transaction
Then at (2), there are no connections available, you are blocked
If the entire connection pool is at (1), every transaction is blocked and none of them proceed.
This detects this behaviour by setting the maximum size of the connection pool to be 1.
This change detects https://github.com/statechannels/statechannels/issues/2748 (and hopefully not other deadlocks!)
=> Set max of one connection in test knex config

packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts
The Wallet should not need to know about or care which models the Store relies on
=> refactor: encapsulate AppBytecode inside Store

packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts, packages/server-wallet/src/__test__/test-helpers.ts, packages/server-wallet/src/db/migrations/20201014174041_ledgers.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/protocols/actions.ts, packages/server-wallet/src/protocols/process-ledger-queue.ts, packages/server-wallet/src/protocols/state.ts, packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts, packages/wallet-core/src/serde/wire-format/deserialize.ts, packages/wallet-core/src/serde/wire-format/serialize.ts, packages/wallet-core/src/types.ts, packages/wire-format/src/generated-schema.json, packages/wire-format/src/types.ts
Changes the implementation in #2715, which has each part sign a state of its proposed update immediately, this PR first ensures the two parties exchange a sequence of "commits", sharing what they propose the next ledger update be before actually signing it (or the intersection of it and the others commit). This implementation uses "requests", but it might be argued that it should be an objective instead.
- Maintains that a Store need only store a single state per turn number
- This adds networking overhead
=> 📝💬🔏 Add two phase commit for ledger channel updates

packages/server-wallet/src/wallet/__test__/add-my-state.test.ts, packages/server-wallet/src/wallet/__test__/add-signed-state.test.ts, packages/server-wallet/src/wallet/__test__/get-first-participant.test.ts, packages/server-wallet/src/wallet/__test__/lock-app.test.ts, packages/server-wallet/src/wallet/__test__/sign-state.test.ts, packages/server-wallet/src/wallet/__test__/signing-address.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts
The `networkChainId` is wallet-wide, so there's no reason not to have it on the store too. If we put it on the store, that's one less thing we need to provide when creating channels. (Will be used in an upcoming PR).
=> Add networkChainId to store

packages/server-wallet/src/protocols/__test__/open-channel.test.ts, packages/server-wallet/src/protocols/open-channel.ts
I believe this is an off by one error. If your turn number is 0, and you have not signed anything yet, you want to sign the prefund setup if the latest turnNum is less than 2
=> fix: ensure prefund setup is signed if turnNum < participants.length

packages/server-wallet/src/db-admin/db-admin.ts, packages/server-wallet/src/models/__test__/objectives.test.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/models/objective.ts, packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts
This PR:
* Renames `Objective -> ObjectiveModel` and `ObjectiveChannel -> ObjectiveChannelModel` to make the different types more explicit.
* Changes `extract` from being a standalone function that took an `ObjectiveModel` to being an instance method, `toObjective` on the `ObjectiveModel`.
* Moves and renames the `ObjectiveStoredInDB` model to `DBObjective` and adds a brief description.
These changes should hopefully make it less confusing to work with objectives 🤞 .
=> A few refactors to the Objective model

packages/server-wallet/jest/chain-setup.ts, packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts, packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/config.ts, packages/server-wallet/src/protocols/close-channel.ts, packages/server-wallet/src/wallet/index.ts
The two major changes are:
1. The server wallet runloop does not wait for chain service calls. See https://github.com/statechannels/statechannels/commit/e68ea1596b5da9d122c3cef4c3a65d7df172a464 for reasoning.
1. all participants submit conclude and withdraw transactions. Addresses https://github.com/statechannels/statechannels/pull/2753#issuecomment-717302221
=> [server-wallet] iteration on conclude and withdraw

.github/workflows/publish-canary.yml
This seems to fix the issue that @andrewgordstewart where [his canary publish](https://github.com/statechannels/statechannels/actions/runs/336021827) failed. I have verified this by making the same change on the regular publish, and observing the publish succeed (where it also previously failed with the [same error](https://github.com/statechannels/statechannels/actions/runs/336247661)). I made that change in the actions editor on github, which ended up pushing the change directly to master 😳 .
The fact that this works seems to imply that the github actions cache became corrupted somehow. Both the failed builds had an exact cache hit. That cache would presumably have been written @snario's [canary publish](https://github.com/statechannels/statechannels/actions/runs/334809751) from a …
=> ci: bump canary publish cache

packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/wallet/index.ts
Either `fetchBytecode` or `registerAppDefinition` should reject when no contract is deployed at the target address.
This rules out applications using a "null app" for application rules.
However, it is more important for applications to not accidentally use a null app than it is to support null app applications.
If an application explicitly wants to use a null app, they can deploy an explicit version where `validTransition` returns `false`.
=> fetchBytecode rejects when bytecode is missing

packages/server-wallet/package.json, packages/server-wallet/src/evm-validator.ts, yarn.lock
This switches the `server-wallet` to use connext's version of `PureEVM`.
The main reason for this is that the previous version did not implement `ecRecover`.
This change allows the wallet to validate transitions in the evm that use `ecRecover`.
=> Use connext version of pure evm

.github/workflows/publish-canary.yml, .github/workflows/publish.yml
Provides the same protection as we enjoy on circle -- namely, that the action will fail out if changes to `yarn.lock` were not committed.
=> ci: use git diff --exit-code in GH actions

packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts
As is, the crashes would not lead to a test failure were the DB held purely in volatile memory. The point of the crashes is to detect problems with data not being persisted to disk.
=> Toughen up crashes (ledger funding test)

packages/server-wallet/src/db/migrations/20201027090001_channels_indexes.ts
[Direct quote]
> I propose we add an index in the server-wallet’s PostgreSQL channels table — in addition to channelId — on participants.
> Then, we can do this.wallet.getChannels(participants). If we also index on assetHolderAddress then we can make this.wallet.getLedgerChannel(assetHolderAddress, participants) and O(1) call. Which is an alias for getLedgerChannelForAllocation (since participants is [gateway,allocation.id]).
=> chore: add new database indexes for channels table

.circleci/config.yml
I am seeing cache hits on circle that are not followed by "Already up to date" message. This means we are wasting time restoring a dependency cache _and_ downloading and installing a bunch of packages. 
I don't understand why this happens, but have observed that invalidating the cache can help.
=> ci: bump cache key

packages/client-api-schema/client-api-schema.api.md, packages/client-api-schema/src/generated-schema.json, packages/client-api-schema/src/methods/CreateChannel.ts, packages/server-wallet/src/__test__/create-and-close-channel/fake-funding.test.ts, packages/server-wallet/src/protocols/__test__/close-channel.test.ts, packages/server-wallet/src/protocols/close-channel.ts, packages/server-wallet/src/protocols/open-channel.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts, packages/wire-format/src/generated-schema.json, packages/wire-format/src/types.ts, packages/xstate-wallet/src/messaging.ts
We've discussed this a few times, and I think the consensus was that "fake funding" is more descriptive than "unfunded". 
Related changes in the-graph: https://github.com/statechannels/the-graph/pull/254
=> refactor: rename Unfunded -> Fake funding

packages/server-wallet/src/wallet/store.ts
Following the force move contracts we should not be calling `validTransition` when transitioning to a `isFinal` state. 
This fixes the validation logic to respect that.
=> Fix: Do not evm validate final states

packages/server-wallet/src/wallet/store.ts
I don't think this was actively causing any issues but we should be using the same [check](https://github.com/statechannels/statechannels/blob/9c59e0683de67cdfa567302d52bed16e55bda080/packages/server-wallet/src/wallet/store.ts#L591) in both places we validate state transitions.
=> Minor fix to use the same alreadyHaveState check when validating transitions

packages/server-wallet/src/wallet/store.ts
Calling `deserializeState` triggered an additional call to `getStateSignerAddress` which does `ethers.utils.keccak256` and `ethers.utils.verifyMessage` in JS
1. https://github.com/statechannels/statechannels/blob/6aa64ccdb346722a40e1412df907d08f20ef7f60/packages/server-wallet/src/wallet/store.ts#L576-L576
2. https://github.com/statechannels/statechannels/blob/6aa64ccdb346722a40e1412df907d08f20ef7f60/packages/wallet-core/src/serde/wire-format/deserialize.ts#L84-L84
3. https://github.com/statechannels/statechannels/blob/6aa64ccdb346722a40e1412df907d08f20ef7f60/packages/wallet-core/src/state-utils.ts#L95-L98
4. https://github.com/statechannels/statechannels/blob/6aa64ccdb346722a40e1412df907d08f20ef7f60/packages/nitro-protocol/src/signatures.ts#L12-L14
=> fix: remove subtely introduced additional JS ecrecover call (via deserialization fn)

packages/server-wallet/src/wallet/__test__/add-my-state.test.ts, packages/server-wallet/src/wallet/__test__/fixtures/states.ts, packages/server-wallet/src/wallet/__test__/integration/close-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/__test__/integration/sync-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/update-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts, packages/server-wallet/src/wallet/__test__/sign-state.test.ts
Just addressing a FIXME in the code.
=> chore: remove duplicate implementation of stateWithHashSignedBy

packages/server-wallet/src/__test__/evm-validator.test.ts, packages/server-wallet/src/evm-validator.ts, packages/server-wallet/src/utilities/validate-transition.ts, packages/server-wallet/src/wallet/store.ts
In my pursuit to make the codebase easier to navigate and reason about I noticed there wasn't much of a need for the transition validation code to be so coupled to the `Store` implementation. This PR doesn't do much, but it moves the code into a separate file and removes unnecessary dependencies on `Knex` by parameterizing the bytecode. Otherwise it does not change any existing behaviours.
=> refactor: de-couple state transition validation from store and DB

packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/wallet/__test__/fixtures/create-channel.ts, packages/server-wallet/src/wallet/__test__/integration/create-ledger-channel.test.ts, packages/server-wallet/src/wallet/store.ts
I observed this error:
```
[1604329033593] ERROR (7338): [] PaymentServer - DataError: select "channels".* from "channels" where "asset_holder_address" = $1 and "participants" = $2 - invalid input syntax for type json
at wrapError (/node_modules/db-errors/lib/dbErrors.js:19:14)
at handleExecuteError (/node_modules/objection/lib/queryBuilder/QueryBuilder.js:1506:32)
at QueryBuilder.execute (/node_modules/objection/lib/queryBuilder/QueryBuilder.js:687:20) {
nativeError: error: invalid input syntax for type json
at Parser.parseErrorMessage (/node_modules/pg-protocol/src/parser.ts:357:11)
at Parser.handlePacket (/node_modules/pg-protocol/src/parser.ts:186:21)
at Parser.parse (/node_modules/pg-protocol/src/parser.ts:101:30)
at Socket.<anonymous> (/node_modules/pg-protocol/src/index.ts:7:48)
at …
```
=> fix: fix broken query on ledger channels in DB

packages/server-wallet/src/wallet/index.ts
While debugging I noticed that when you call `syncChannel` and provide the outbox to a wallet, let's say you provide `[3, 4]` being the latest turn numbers, then `this.store.pushMessage` will return `[3, 4]` and then the for loop this PR modifies would loop over `[3, 4]` and insert the `3` into the channel results and discard the `4`.
=> fix: ensure pushMessage returns latest channelResults

packages/nitro-protocol/contracts/AssetHolder.sol, packages/nitro-protocol/test/contracts/AssetHolder/transfer.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts
Adding a fine-grained transfer method helps get around the case where there is a "bad" destination in an `assetOutcome` (say, that `reverts` when we try to transfer an asset to it using `transferAll`) -- currently this would effectively lock all of the funds in the channel. The `transfer` method added in this PR would be an escape hatch, allowing the specific destination to be specified in the method call and selectively paid out.
TODO 
---
=> [nitro-protocol] Add a transfer method

packages/server-wallet/src/utilities/validate-transition.ts, packages/server-wallet/src/wallet/store.ts
Ignore old states that may be received from syncing when validating. Also moves the shouldValidate logic into it's own function for clarity.
I'll be adding tests but this can be done in a separate PR to prevent blocking @snario .
=> Ignore older states when validating

packages/server-wallet/e2e-test/payer/client.ts, packages/server-wallet/e2e-test/receiver/controller.ts, packages/server-wallet/package.json, packages/server-wallet/scripts/inject-wallet-version.js, packages/server-wallet/src/errors/wallet-error.ts, packages/server-wallet/src/logger.ts, packages/server-wallet/src/objectives/objective-manager.ts, packages/server-wallet/src/utilities/messaging.ts, packages/server-wallet/src/version.ts, packages/server-wallet/src/wallet/__test__/fixtures/messages.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts, packages/wallet-core/src/serde/wire-format/deserialize.ts, packages/wallet-core/src/serde/wire-format/example.ts, packages/wallet-core/src/serde/wire-format/serde.test.ts, packages/wallet-core/src/serde/wire-format/serialize.ts, packages/wallet-core/src/types.ts, packages/wire-format/src/__tests__/good_sample_messages.ts, packages/wire-format/src/generated-schema.json, packages/wire-format/src/types.ts, packages/xstate-wallet/src/config.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/store/tests/dexie-store.test.ts, packages/xstate-wallet/src/store/tests/memory-store.test.ts, packages/xstate-wallet/src/workflows/tests/virtual-funding.test.ts
_In the xstate wallet:_ populate this string using the githash (which we are already using and is injected during the webpack build). 
_In the server wallet:_ write the package version number into the compiled javascript before publishing. Use an empty string otherwise (e.g. with ts-node). 
Also throw an error if we got a message from a wallet at a different `walletVersion`.
=> Add walletVersion as a required string on wire-format.message.payload

.github/workflows/publish-canary.yml, .github/workflows/publish.yml
For reasons not fully understood, we occasionally run into build failures such as:
```
@statechannels/client-api-schema: ERROR: Internal Error: The referenced path was not found:
/home/runner/work/statechannels/statechannels/packages/client-api-schema/lib/src/notifications.d.ts
```
Resetting the cache fixes the problem, so it seems like it might be cache related.
We don't publish very often, so the advantage to having the cache is minimal.
=> ci: don't cache node_modules on the publish workflows

packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts, packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/db/migrations/20201029130000_transferred_out.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/models/funding.ts, packages/server-wallet/src/objectives/objective-manager.ts, packages/server-wallet/src/objectives/types.ts, packages/server-wallet/src/protocols/__test__/fixtures/channel-state.ts, packages/server-wallet/src/protocols/__test__/open-channel.test.ts, packages/server-wallet/src/protocols/close-channel.ts, packages/server-wallet/src/protocols/open-channel.ts, packages/server-wallet/src/protocols/state.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts
This work only impacts directly funded channels.
How it works before this PR: when processing the close channel objective, the wallet submits a `concludeAndWithdraw` transaction. If the transaction is successfully submitted or fails for an accepted reason (regardless of what happens during mining), the wallet allows the close channel objective to succeed.
How it works after this PR: the wallet only allows the close channel objective to succeed if the wallet has been notified of `AssetTransferred` events that show that all of the assets for the participant have been transferred out of the channel.
Follow up work includes the wallet emitting an event when the close channel objective succeeds. At the moment, the tests do not verify that the close channel objective succeeds for directly …
=> Close channel objective only completes when funds have been transferred

packages/channel-client/package.json, packages/client-api-schema/client-api-schema.api.md, packages/client-api-schema/package.json, packages/iframe-channel-provider/package.json, yarn.lock
quiets warnings about TS version
=> chore: upgrade api-extractor

packages/server-wallet/src/models/objective.ts
We currently only support `OpenChannel` and `CloseChannel` objectives in the wallet. This PR restricts the type of the internal `DBObjective` to these types. This should make this constraint clearer throughout the wallet code, and make it easier to refactor.
=> refactor: restrict objective type to those we currently support

packages/nitro-protocol/.eslintrc.js, packages/nitro-protocol/src/contract/challenge.ts, packages/nitro-protocol/src/contract/channel-storage.ts, packages/nitro-protocol/src/hex-utils.ts, packages/nitro-protocol/src/signatures.ts, packages/nitro-protocol/src/transactions.ts, packages/nitro-protocol/test/test-helpers.ts, packages/wallet-core/.eslintrc.js, packages/wallet-core/src/bignumber.ts, packages/wallet-core/src/serde/wire-format/deserialize.ts, packages/wallet-core/src/state-utils.ts, packages/wallet-core/src/utils/helpers.ts
This removes four TODOs from the codebase. Some eslint rules were disabled which allowed a lack of return values on functions and other basic typing related information.
We should periodically do this kind of work to keep the codebase clean
=> style: remove eslint rule disabling and add type information to utils

packages/nitro-protocol/contracts/AssetHolder.sol, packages/nitro-protocol/test/contracts/AssetHolder/claimAll.test.ts
...by using a checks/effects/interactions pattern. 
Currently, we call out to external contracts _before_ modifying the `assetOutcomeHash` for the target channel*: those external contracts could call back into `claimAll` or another `AssetHolder` function and try to exploit the unmodified storage. I can't think of an actual exploit RN because the `holdings` _has_ been updated by this point. 
In any case it seems worth a "modest" (~ 200 for our test cases) increase in gas to restore a safer pattern.
```
1. straight-through guarantee, 3 destinations:
40939 gas
2. swap guarantee,             2 destinations:
37771 gas
3. swap guarantee,             3 destinations:
40939 gas
4. straight-through guarantee, 2 destinations:
37602 gas
7. swap guarantee, overfunded, 2 destinations:
38850 gas
8. …
```
=> [nitro-protocol] Protect against reentrancy during claimAll

.github/workflows/publish-canary.yml
Without this, you can get surprising package resolution such as https://jubianchi.github.io/semver-check/#/%5E0.0.5-next.1805b9a.155%2B1805b9a/%220.0.5-next.f526a89.85%2Bf526a89%22
=> ci: pin to exact versions when canary publishing

packages/server-wallet/src/utilities/validate-transition.ts
Adds a workaround for #2842 by skipping validation when fake funding and receiving a post fund setup. 
This should solve the immediate issue while we think of a proper solution for handling this.
=> Add workaround for noisy log message

packages/docs-website/docs/contract-api/contract-inheritance.mdx, packages/nitro-protocol/contracts/ERC20AssetHolder.sol, packages/nitro-protocol/contracts/ETHAssetHolder.sol, packages/nitro-protocol/contracts/ForceMove.sol
This is required in solidity 0.7
=> [nitro-protocol] Redeclare SafeMath in extending contracts

packages/nitro-protocol/package.json, packages/nitro-protocol/test/contracts/AssetHolder/adjudicatorAddress.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/claimAll.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/setOutcome.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transfer.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts, packages/nitro-protocol/test/contracts/ERC20AssetHolder/deposit.test.ts, packages/nitro-protocol/test/contracts/ETHAssetHolder/deposit.test.ts, packages/nitro-protocol/test/contracts/ForceMove/challenge.test.ts, packages/nitro-protocol/test/contracts/ForceMove/checkpoint.test.ts, packages/nitro-protocol/test/contracts/ForceMove/conclude.test.ts, packages/nitro-protocol/test/contracts/ForceMove/respond.test.ts, packages/nitro-protocol/test/contracts/NitroAdjudicator/concludePushOutcomeAndTransferAll.test.ts, packages/nitro-protocol/test/contracts/NitroAdjudicator/pushOutcome.test.ts, packages/nitro-protocol/test/contracts/NitroAdjudicator/pushOutcomeAndTransferAll.test.ts, packages/nitro-protocol/test/contracts/NullApp/nullApp.test.ts, packages/nitro-protocol/test/contracts/TrivalApp/validTransition.test.ts, packages/nitro-protocol/test/test-helpers.ts
This cuts down nitro test run time by about a half (10 mins to about 5) on circle. 
It also closes the gap between local development (where tests will run concurrently, and *fail* some of the time because of that) and circle (where they do not). 
The key fix was not asserting on the balance of one of our test accounts (e.g. one that deploys contracts). 
Other fixes that I put in to avoid interference between tests: 
- generate a psuedorandom nonce for each channel used in each test, using the hash of the test name as a seed.
=> [nitro-protocol] Run chain tests concurrently

packages/server-wallet/src/wallet/wallet.ts
Observed this in an application; it is a bug
=> fix: don't throw an error on closeChannels call with empty array

packages/client-api-schema/client-api-schema.api.md, packages/client-api-schema/src/data-types.ts, packages/client-api-schema/src/generated-schema.json, packages/wallet-core/src/serde/wire-format/deserialize.ts, packages/wallet-core/src/serde/wire-format/serialize.ts, packages/wallet-core/src/types.ts, packages/wire-format/src/generated-schema.json, packages/wire-format/src/types.ts
We currently have a couple of properties on the wire-format that we're not using, and probably won't use, but make it harder to write wallet code because the wallet needs them available when constructing messages. This PR removes those properties.
The properties are:
* `participants` on the objective
* objectives always reference one or more channels, which can provide the participants
* we originally had participants on objectives because there was a thought that objectives could exist before the channels. This is no-longer the case in any of the current objectives, and I can't see it happening in the future.
* `sender` on the message
* we don't use this in the wallet, and shouldn't need to, as the wallet is deliberately agnostic to how messages arrived
* as messaging is handled by the …
=> Make sender and objective.participants optional in wire-format

packages/server-wallet/deployment/deploy.ts, packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts, packages/server-wallet/src/chain-service/__chain-test__/stress.test.ts, packages/server-wallet/src/config.ts, packages/server-wallet/src/wallet/wallet.ts
The wallet configuration contains 2 private keys. One signs states. The other signs ethereum transaction. Currently, the names are:
- `serverSignerPrivateKey` for state signing. This name is verbose yet communicates little. 
- server: we are looking at the server code, is that not obvious?
- signer: private keys are typically used for signing.
- privateKey: this part is important.
- `serverPrivateKey` for ethereum transaction signing. Same criticism.
=> Rename private keys

packages/nitro-protocol/contracts/ERC20AssetHolder.sol
The current implementation of `GRTAssetHolder` expects to override `_transferAsset` so this marks it as `virtual` allowing for the `GRTAssetHolder` .
I don't think there's any security implications here but would be good to get a second opinion on that.
=> Mark _transferAsset as virtual

.circleci/config.yml
No longer relevant since no  hub code exists in this repo
=> ci: remove ci jobs related to hub code

packages/server-wallet/src/wallet/wallet.ts
fixes #2876
signState fails for some indexers when adding a hash.
See issue for context.
=> fix: log failed signState attempt

packages/server-wallet/src/wallet/store.ts, packages/server-wallet/src/wallet/wallet.ts
Method is only used in one place and that one place is essentially hiding complexity of  modifiying the property of the parent class itself that is using it — no need to overcomplicate things
=> fix: remove store.destroy method

packages/server-wallet/src/wallet/wallet.ts
Should avoid potential scenarios where some code unknowingly uses these meant-to-be-private methods
=> chore: mark some wallet methods as private

.circleci/config.yml, packages/server-wallet/.env.test
- removes much dead wood
- doesn't spin up postgres container for the `prepare` step
- prefers a standard circleci image over any custom image (more likely to pull faster, removes need to maintain custom images)
- required changing the POSTGRES_USER from `root` to `postgres` (took me a long time to make this work 😞 )
Closes #2900 
Closes #2897
=> hefty CI config cleanup

packages/server-wallet/src/wallet/wallet.ts
Await `registerChannelWithChainService` so we don't have a bunch of queries attempting to execute after the method has finished executing.
This is an immediate fix for https://github.com/statechannels/the-graph/pull/337
We should probably create a separate issue to discuss longer term implications of this.
=> Await registerChannelWithChainService

packages/devtools/package.json, packages/jest-gas-reporter/package.json, packages/nitro-protocol/package.json, packages/server-wallet/package.json, packages/wallet-core/package.json, packages/wire-format/package.json
While publishing locally the version package.json were updated but the packages were not published.
This undoes that.
=> Revert to published versions

packages/server-wallet/.eslintrc.js, packages/server-wallet/src/chain-service/chain-service.ts
With Ganache, when transaction execution reverts, the revert reason is included in the thrown exeption. This is not the case for testnets like rinkeby (https://github.com/ethers-io/ethers.js/issues/446).
The alternative to querying the nitro adjudicator for its state is to use the [`eth-revert-reason` npm module](https://www.npmjs.com/package/eth-revert-reason). However, that module is not reliable as we see the following error: `You cannot use a blocknumber that has not yet happened.`
`eth-revert-reason` can be used more reliably if a delay is added before `ether-revert-reason` is invoked.
FIxes https://github.com/statechannels/statechannels/issues/2872
=> fix: do not rely on revert reason in chain service

packages/nitro-protocol/contracts/Token.sol
In an end to end stress test with The Graph we require several billion tokens and absent the asset holder I'm using this test artifact, but I'm limited to 10,000 tokens.
=> test: increase number of tokens minted in Token.sol contract

packages/server-wallet/src/models/__test__/channel.test.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/wallet/__test__/integration/close-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/sync-channel.test.ts
Use the `dropNonVariables` to prevent additional fields being stored in the database.
Fixes #2780
=> Do not allow non variable data in the db

packages/nitro-protocol/contracts/AssetHolder.sol, packages/nitro-protocol/contracts/ERC20AssetHolder.sol, packages/nitro-protocol/contracts/ETHAssetHolder.sol, packages/nitro-protocol/contracts/Token.sol, packages/nitro-protocol/contracts/interfaces/IAssetHolder.sol, packages/nitro-protocol/test/contracts/AssetHolder/claimAll.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transfer.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts
- remove unecessary keyword on Token constructor
- require successful asset transfer in ERC20AssetHolder.sol
- clarify documentation around which checks are performed
- update tests to assert on extra events
=> feat: emit AssetTransferred for internal transfers

packages/server-wallet/src/wallet/multi-threaded-wallet/manager.ts, packages/wire-format/package.json, packages/wire-format/src/__tests__/validator.test.ts, packages/wire-format/src/globals.d.ts, packages/wire-format/src/validator.ts, yarn.lock
Currently, we are seeing validation errors in The Graph testnet, and we don't know why: see https://github.com/graphprotocol/indexer/issues/107
```
> validateMessage({data: {foo: 'bar'}})
Uncaught WireFormatValidationError: Invalid message
at validateMessage (/Users/andrewstewart/Code/magmo/monorepo/packages/wire-format/lib/src/validator.js:29:15) {
jsonBlob: { data: { foo: 'bar' } },
errorMessages: [ "Unexpected property 'foo' found at root.data " ]
}
```
This PR adds the jsonBlob so that we can debug this issue in the test network.
=> refactor: wire format validators include useful data

packages/server-wallet/src/models/__test__/fixtures/channel.ts, packages/server-wallet/src/objectives/objective-manager.ts, packages/server-wallet/src/wallet/__test__/lock-app.test.ts, packages/server-wallet/src/wallet/__test__/sign-state.test.ts, packages/server-wallet/src/wallet/store.ts, packages/server-wallet/src/wallet/wallet.ts
With this change, I see a consistent ~15% increase in throughput on my machine (2018 15" Macbook Pro)
`master`:
```
┌─────────┬────────┬────────┬────────┬────────┬───────────┬──────────┬─────────┐
│ Stat    │ 2.5%   │ 50%    │ 97.5%  │ 99%    │ Avg       │ Stdev    │ Max     │
├─────────┼────────┼────────┼────────┼────────┼───────────┼──────────┼─────────┤
│ Latency │ 429 ms │ 469 ms │ 663 ms │ 965 ms │ 490.36 ms │ 86.47 ms │ 1351 ms │
└─────────┴────────┴────────┴────────┴────────┴───────────┴──────────┴─────────┘
┌───────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┬─────────┐
│ Stat      │ 1%      │ 2.5%    │ 50%     │ 97.5%   │ Avg     │ Stdev   │ Min     │
├───────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┼─────────┤
│ Req/Sec   │ 13      │ 13 …
```
=> Remove one query from the critical path

packages/nitro-protocol/src/contract/channel.ts, packages/nitro-protocol/test/src/contract/external-destination.test.ts
when computing channelId
add a test for helper isExternalDestination
Note that this is extremely unlikely to happen in the first place.
=> feat: catch external destination collisions

packages/nitro-protocol/contracts/AssetHolder.sol, packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts
gas savings are very small, and can increase / decrease depending on input data (due to increase equality checks.) 
Currently:
```
1. funded          -> 1 EOA:
20619 gas
2. overfunded      -> 1 EOA:
26237 gas
3. underfunded     -> 1 EOA:
29215 gas
4. funded      -> 1 channel:
30197 gas
5. overfunded  -> 1 channel:
45197 gas
6. underfunded -> 1 channel:
48174 gas
7. -> 2 EOA       full/full:
22828 gas
8. -> 2 EOA         full/no:
30556 gas
9. -> 2 EOA    full/partial:
33880 gas
10. -> 2 chan      full/full:
53590 gas
11. -> 2 chan        full/no:
49648 gas
12. -> 2 chan   full/partial:
71802 gas
```
As of e08e159
```
1. funded          -> 1 EOA:
20618 gas
2. overfunded      -> 1 EOA:
26236 gas
3. underfunded     -> 1 EOA:
29214 gas
4. funded      -> 1 channel:
30196 gas
5. overfunded  -> 1 …
```
=> perf: break out of loops a bit earlier

packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts, packages/server-wallet/src/protocols/process-ledger-queue.ts
Accidentally used wrong string equality check here: https://github.com/statechannels/statechannels/commit/aa92714f0070b3136ae8433d711ba278a3177f16#diff-964098fad72916397eba2a9798e08abfcd87f0c109078cb67deb01ed7a916321R55.
TODO:
=> fix: fix incorrect ledger funding insufficient funds error string equality check

packages/docs-website/docs/protocol-tutorial/outcomes.md, packages/nitro-protocol/contracts/AssetHolder.sol, packages/nitro-protocol/test/contracts/AssetHolder/claim.test.ts
Includes #2931
See also #2814 .
Gas costs (see accompanying test suite)
```
1. straight-through guarantee, 3 destinations:
40559 gas
3. swap guarantee,             3 destinations:
40547 gas
4. straight-through guarantee, 2 destinations:
37586 gas
7. swap guarantee, overfunded, 2 destinations:
53094 gas
8. underspecified guarantee, overfunded      :
52393 gas
```
=> feat(nitro-protocol): add claim method to AssetHolder

packages/docs-website/docs/contract-api/contract-inheritance.mdx, packages/nitro-protocol/contracts/CountingApp.sol, packages/nitro-protocol/contracts/ForceMove.sol, packages/nitro-protocol/contracts/NitroAdjudicator.sol, packages/nitro-protocol/contracts/TrivialApp.sol, packages/nitro-protocol/contracts/examples/SingleAssetPayments.sol, packages/nitro-protocol/contracts/interfaces/IAdjudicator.sol, packages/nitro-protocol/contracts/interfaces/IForceMove.sol, packages/nitro-protocol/contracts/interfaces/IForceMoveApp.sol, packages/nitro-protocol/src/contract/force-move-app.ts
Also, make `IForceMove` an `interface`, not an abstract contract.
=> style: consistent prefixing of contract interfaces with 'I'

packages/server-wallet/src/db/migrations/20201121100937_ledger_requests_idx.ts, packages/server-wallet/src/wallet/store.ts, packages/server-wallet/src/wallet/wallet.ts
When thinking about performance a bit I looked at this code and thought I could optimize the query made to the DB a bit instead of doing filtering in JS.
=> perf: optimize queries for ledger requests on run loop

.circleci/config.yml
I am yet again seeing cache hits followed by yarn installing stuff. Invalidating periodically seems to help.
=> ci: invalidate cache

packages/nitro-protocol/contracts/AssetHolder.sol, packages/nitro-protocol/contracts/ERC20AssetHolder.sol, packages/nitro-protocol/contracts/ETHAssetHolder.sol, packages/nitro-protocol/contracts/ForceMove.sol, packages/nitro-protocol/contracts/interfaces/IForceMove.sol
In theory this saves gas, although I am not seeing that in our test suite.
=> perf: make many public methods external

.circleci/config.yml, .gitignore, packages/nitro-protocol/.gitignore, packages/nitro-protocol/test/contracts/AssetHolder/claim.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/claimAll.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts, packages/nitro-protocol/test/contracts/ERC20AssetHolder/deposit.test.ts, packages/nitro-protocol/test/contracts/ETHAssetHolder/deposit.test.ts, packages/nitro-protocol/test/contracts/ForceMove/challenge.test.ts, packages/nitro-protocol/test/contracts/ForceMove/respond.test.ts, packages/nitro-protocol/test/test-helpers.ts
currently we only upload gas information from `jest-gas-reporter`, which actually is not working (empty output). 
This change makes it so we have a record from our test suite. Should make it far easier to track gas savings/regressions in pull requests.
=> ci: upload gas artifacts

packages/server-wallet/src/models/objective.ts, packages/server-wallet/src/objectives/objective-manager.ts, packages/server-wallet/src/protocols/close-channel.ts, packages/server-wallet/src/protocols/open-channel.ts
This PR refactors the `ObjectiveManager.crank` function:
* It now switches on objective type just once, at the beginning
* There are now two similar `crankOpenChannel` and `crankCloseChannel` methods
* And the actions are narrowed to the actual actions that those protocols can return
The PR creates some seemingly unnecessary duplication, but the idea is that these two different behaviours are only accidentally similar, and are heading for different objects. This is part of a move away from a one-size-fits-all, always-lock-exactly-one-channel-per-objective approach.
=> More protocol refactors

packages/server-wallet/src/config/defaults.ts, packages/server-wallet/src/config/types.ts, packages/server-wallet/src/config/utils.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/wallet.ts
Some minor changes to clean up the config.
- Removes some unused assetholder address config
- Exported config types from `ServerWallet` package
- Accept `chainId` as a number.
=> Config clean up

packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts, packages/server-wallet/src/protocols/open-channel.ts, packages/server-wallet/src/wallet/store.ts
Presently a ledger channel can be used to fund a channel after the ledger channel has already been closed. This adds a check to prevent `createChannel` from allowing it to be specified and a check in the protocol to ensure the ledger being used to fund a channel is actually running before proceeding with ledger funding.
=> [server-wallet] Prevent closed ledger channels from being able to fund channels

.github/workflows/commitlint.yml
This month, 103 of 131 (79%) merged pull requests got the carrot, meaning all of the commits on those PRs were conventional. I think it has done its job of encouraging conventional commits. 
The time seems right to refine this a little, as our changelogs are full of things like `fix: typo` which don't belong there. The carrot has probably encouraged overuse of `fix:`.
This is definitely not the long term solution but changing the emoji is designed to nudge everyone to remember: "These commits are going to affect the changelog" before clicking "merge". If the merger sees `fix: typo` they can either
1) ask the originator to rewrite the history
2) squash-merge the PR and fixup the commit message themselves. 
(NB: if you are unconventional in a single commit you won't get the badge at all, …
=> ci: swap carrot for memo

packages/nitro-protocol/contracts/ForceMove.sol, packages/nitro-protocol/contracts/NitroAdjudicator.sol, packages/nitro-protocol/contracts/interfaces/IForceMove.sol, packages/nitro-protocol/test/contracts/ForceMove/conclude.test.ts
cherry-picked and refined from #2955 
- also return channelId from conclude, to save some gas.
gas consumption went up a bit overall, however:
master; 
```
{ETH: {A: 1}}:
88585 gas
{ETH: {A: 1}, ETH2: {A: 2}}:
94773 gas
{ETH2: {A: 1, B: 1}}:
93511 gas
{ERC20: {A: 1, B: 1}}:
155782 gas
{ERC20: {At: 1, Bt: 1}} (At and Bt already have some TOK):
125782 gas
10 TOK payouts:
423928 gas
50 TOK payouts:
1615322 gas
100 TOK payouts:
2693927 gas
```
this branch: 
```
{ETH: {A: 1}}:
88714 gas
{ETH: {A: 1}, ETH2: {A: 2}}:
94902 gas
{ETH2: {A: 1, B: 1}}:
93616 gas
{ERC20: {A: 1, B: 1}}:
155887 gas
{ERC20: {At: 1, Bt: 1}} (At and Bt already have some TOK):
125899 gas
10 TOK payouts:
424057 gas
50 TOK payouts:
1615499 gas
100 TOK payouts:
2694080 gas
```
=> refactor: reuse _conclude in concludePush...All

packages/nitro-protocol/src/contract/outcome.ts, packages/nitro-protocol/src/transactions.ts, packages/nitro-protocol/test/contracts/ForceMove/challenge.test.ts, packages/nitro-protocol/test/contracts/NitroAdjudicator/pushOutcome.test.ts, packages/nitro-protocol/test/src/transactions.test.ts, packages/nitro-protocol/test/test-helpers.ts
Happy: by checking the tx size off chain, ganache was happy to accept a `challenge` transaction under 128KB without gorging on memory. 
Sad: tried rolling out the same thing for `pushOutcome`. Can get the same number of allocationItems in under 128KB but still seeing an out-of-memory error. 
- exports new constants
- tidies up test helpers
- adds comments around block gas limits
=> test: add off-chain tests against max outcome size, and on-chain test for challenging with max outcome size

packages/nitro-protocol/src/contract/asset-holder.ts, packages/nitro-protocol/test/src/contract/asset-holder.test.ts
The old approach does not work for strings where the first digit is `"0"` e.g., `"0x0..."`.
=> fix: use hexZeroPad to normalize string as bytes32 versus BigNumber.from

packages/nitro-protocol/hardhat.config.ts
e.g. for `concludePushOutcomeAndTransferAll` (other stats available as circle artifacts)
master: 
```js
{ETH: {A: 1}}:
88690 gas
{ETH: {A: 1}, ETH2: {A: 2}}:
94890 gas
{ETH2: {A: 1, B: 1}}:
93628 gas
{ERC20: {A: 1, B: 1}}:
155899 gas
{ERC20: {At: 1, Bt: 1}} (At and Bt already have some TOK):
125875 gas
10 TOK payouts:
424057 gas
50 TOK payouts:
1615475 gas
100 TOK payouts:
2694032 gas
```
here:
```js
{ETH: {A: 1}}:
79484 gas
{ETH: {A: 1}, ETH2: {A: 2}}:
83771 gas
{ETH2: {A: 1, B: 1}}:
83692 gas
{ERC20: {A: 1, B: 1}}:
144696 gas
{ERC20: {At: 1, Bt: 1}} (At and Bt already have some TOK):
114708 gas
10 TOK payouts:
402234 gas
50 TOK payouts:
1540636 gas
100 TOK payouts:
2552929 gas
```
=> perf: enable solidity compiler optimization

packages/docs-website/docs/protocol-tutorial/execute-state-transitions.md, packages/nitro-protocol/contracts/ForceMove.sol, packages/nitro-protocol/test/contracts/ForceMove/conclude.test.ts, packages/nitro-protocol/test/contracts/ForceMove/requireValidInput.test.ts
We are not able to use the type system to constrain the length of dynamically sized arrays; yet we _do_ use the type system  to constrain `numStates` and `whoSignedWhat` entries to be `uint8`s. 
Adding a runtime validation check makes it clear that we do not support more than 255 participants in a channel, and also (therefore) that the chain ought never to be supplied with more than 255 states (meaning `variableParts.length` and `whoSignedWhat[i] \forall i` are also always less than or equal to 255).
=> fix: improve semantic meaning of input parameters via runtime validation

packages/nitro-protocol/contracts/ForceMove.sol, packages/nitro-protocol/contracts/interfaces/IForceMove.sol, packages/nitro-protocol/src/contract/transaction-creators/nitro-adjudicator.ts, packages/nitro-protocol/test/contracts/ForceMove/conclude.test.ts, packages/nitro-protocol/test/contracts/NitroAdjudicator/pushOutcome.test.ts
Closes #2983 
- enhances `createPushOutcomeTransaction` to deal with concluded channels
- adds a test case to cover a concluded channel.
=> emit finalizesAt in Conclude event

packages/server-wallet/src/protocols/__test__/open-channel.test.ts, packages/server-wallet/src/protocols/open-channel.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts, packages/server-wallet/src/wallet/store.ts
This PR changes the style of test for the open channel protocol. It also fixes a pretty serious issue that was exposed by the change: that once it was a participant's turn to deposit, the protocol would deposit repeatedly, stopping only when the channel was funded (e.g. in an `{a: 5, b: 5}` channel, A would deposit 5 multiple times, possibly funding b's stake ... :/ ).
The open channel protocol test has changed from being a test of the pure protocol function, to encompassing more of the system. It (a) loads state into the store, (b) runs the protocol, and then (c) asserts on side-effects. This style will make it easier to refactor the protocols to make the queries more targeted and efficient.
=> Open channel protocol test

packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/__chain-test__/stress.test.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/chain-service/index.ts, packages/server-wallet/src/chain-service/mock-chain-service.ts, packages/server-wallet/src/chain-service/types.ts, packages/server-wallet/src/wallet/wallet.ts
The chain service can be run in two modes:
- PerDeposit allowance mode: if the chain service is requested to fund a channel with N tokens, the chain service increases asset holder allowance by N tokens.
- MaxUint mode: if the chain service is asked to fund a channel with N tokens, the chain service increases the allowance for the asset holder to `MaxUint256` if the allowance is less than half of `MaxUint256`.
This also removes the `allowanceAlreadyIncreased` fundChannel function option to simplify chain service behavior.
Fixes https://github.com/statechannels/statechannels/issues/2988, https://github.com/statechannels/statechannels/issues/2987
=> ChainService: Add allowanceMode option

packages/nitro-protocol/contracts/CountingApp.sol, packages/nitro-protocol/contracts/ForceMove.sol, packages/nitro-protocol/contracts/NitroAdjudicator.sol, packages/nitro-protocol/src/contract/outcome.ts, packages/server-wallet/package.json, packages/server-wallet/src/models/__test__/signing-wallet.test.ts, packages/wallet-core/src/serde/wire-format/example.ts, yarn.lock
=> perf: remove unecessary abi.encode

packages/server-wallet/src/utilities/validate-transition.ts
A legit "transition" is from turn 1 to 3 as there are no app rules checked in this phase to warrant enforcing turn taking.
=> fix: do not do turn number check for funding or closing stage channels

packages/server-wallet/e2e-test/payer/client.ts, packages/server-wallet/e2e-test/receiver/app.ts, packages/server-wallet/e2e-test/receiver/controller.ts, packages/server-wallet/src/errors.ts, packages/server-wallet/src/handlers/__test__/single-app-updater.test.ts, packages/server-wallet/src/handlers/single-app-updater.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/protocols/__test__/open-channel.test.ts, packages/server-wallet/src/type-aliases.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-ledger-channel.ts, packages/server-wallet/src/wallet/multi-threaded-wallet/index.ts, packages/server-wallet/src/wallet/multi-threaded-wallet/manager.ts, packages/server-wallet/src/wallet/multi-threaded-wallet/worker-data.ts, packages/server-wallet/src/wallet/multi-threaded-wallet/worker.ts, packages/server-wallet/src/wallet/types.ts, packages/server-wallet/src/wallet/wallet.ts
Adds a `pushUpdate` method to the wallet api, for pushing a message containing a single state that updates a running app channel. Should address some of the performance issues seen in https://github.com/statechannels/project-management/issues/4, by allowing objective cranking to be skipped in this case.
Still todo:
=> pushUpdate 

packages/server-wallet/deployment/deploy.ts, packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts, packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts, packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/__chain-test__/stress.test.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/config/defaults.ts, packages/server-wallet/src/config/types.ts, packages/server-wallet/src/db-admin/knexfile.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts, packages/server-wallet/src/wallet/wallet.ts
~The `ChainService` should not be instantiated inside the `server-wallet` as it is fundamentally an external component that is designed to be provided _to_ the `server-wallet`. Similarly, the implementation details of the wallet should not need to know about mocks or test fixtures, that should be left to the tests. So, this PR moves the instantiation of a `ChainService` into the constructor of a `server-wallet`. Applications are expected to provide it in the constructor.~
~It seems reasonable to force the `ChainService` to be in the constructor as without it the `server-wallet` is not able to do things like make deposits, withdrawals, or monitor the chain. These are fundamental requirements of a state channels wallet.~
Simplified this PR to simply consolidate wallet config options into …
=> [breaking change (new config option)] consolidate chain service configuration options 

packages/server-wallet/package.json, packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/config/__test__/validation.test.ts, packages/server-wallet/src/config/index.ts, packages/server-wallet/src/config/validation.ts, packages/server-wallet/src/wallet/wallet.ts, yarn.lock
Uses `joi` to validate incoming config files into the wallet.
Fixes https://github.com/statechannels/the-graph/issues/283
The logged errors are pretty readable out of the box: 
```
[1607031065478] ERROR (37103 on Alexs-MacBook-Pro.local): Validation error occured "databaseConfiguration.connection.password" is not allowed to be empty
dbName: "TEST_A"
walletVersion: ""
error: {
"message": "\"databaseConfiguration.connection.password\" is not allowed to be empty",
"path": [
"databaseConfiguration",
"connection",
"password"
],
"type": "string.empty",
"context": {
"label": "databaseConfiguration.connection.password",
"value": "",
"key": "password"
}
}
```
I chose `joi` because I didn't want to implement validation checks myself. It seemed like I would be rewriting a lot of very basic checks. …
=> Validate Incoming configuration files

netlify.toml, packages/docs-website/docs/contract-api/contract-inheritance.mdx, packages/docs-website/package.json, packages/docs-website/sidebars.json, packages/nitro-protocol/package.json, packages/nitro-protocol/readme.md, patches/hardhat+2.0.3.patch, yarn.lock
- patches hardhat to incluce `ast` field in contract artifacts
- updates our [solidoc fork](https://github.com/statechannels/solidoc) to ignore some of the `.json` files that hardhat outputs
- configures netlfiy gui to deploy from master and generate deploy previews for PRs (may turn the previews off, but for now they are on to check this works)
=> [nitro-protocol, docs-website] Resurrect docs#Contract API via patching hardhat

packages/server-wallet/src/state-utils.ts, packages/server-wallet/src/wallet/store.ts
"validate signatures" is too broad and can give the false impression
of the more rigorous checks we need
to do in order to infer a support proof
(e.g. was the state signed by its mover)
work towards #3035; increase clarity about where and why we perform checks on state channel state.
=> docs: clarify role of functions

packages/nitro-protocol/contracts/AssetHolder.sol, packages/nitro-protocol/contracts/interfaces/IAssetHolder.sol, packages/nitro-protocol/contracts/test/TESTAssetHolder.sol, packages/nitro-protocol/test/contracts/AssetHolder/transfer.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts
- zero amount allocations are not cleaned up
- pure functions used to compute new allocation on chain
(to ease emulation in client code)
- indices = [] implies we pay out to all
=> feat: accept a list of indices in transfer method (rebased version of #3011)

packages/server-wallet/src/handlers/__test__/single-app-updater.test.ts, packages/server-wallet/src/protocols/__test__/close-channel.test.ts, packages/server-wallet/src/protocols/__test__/open-channel.test.ts, packages/server-wallet/src/protocols/state.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts
This PR updates the close channel protocol tests, so they use the same approach as the open channel protocol tests (see https://github.com/statechannels/statechannels/pull/2995). Having the tests in this format will allow us to refactor the close channel protocols. 
It also makes a few improvements to the `TestChannel` class:
1. You can now set the `fundingStrategy` on a test channel
2. test channels can now insert themselves into a store
3. when creating a test channel, you can set `finalFrom: 10`, which will e.g. cause `state(11)` to return a double-signed 10
=> Close channel protocol tests

packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/protocols/state.ts
This PR adds a test for a previously untested codepath: multiple ongoing challenges. This test uncovered [a race condition with the on-block-mined callback](https://github.com/statechannels/statechannels/compare/cs-challenges-test?expand=1#diff-e0f323c73f419174cc1c56b6ea286508cbff6917c2c117382ff61ea7085bc136R332)
While there are a few ways to fix the race condition, it seems that using a [pqueue](https://www.npmjs.com/package/p-queue) has the lowest developer cognitive overhead. With a pqueue, the developer can assume a synchronous on-block-mined callback execution.
=> Chain service on-block-mined race condition

packages/nitro-protocol/src/index.ts, packages/server-wallet/deployment/deploy.ts, packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/chain-service.ts
Fixes #3043 
This updates the `ChainService` to check whether a channel is finalized/finalizing when the channel is registered with chain service. 
Currently, it's enough to just call `getChannelStorage` and check the `finalizationAt` value on there. 
When challenging becomes more fully-featured we'll want to also look at looking for `Challenge` events for the channel. Since we're not handling responding to a challenge right now I considered that out of scope.
=> Check finalization status when registering a channel

packages/docs-website/docs/docs/app-devs/make-api-calls.md, packages/docs-website/docs/docs/protocol-tutorial/release-assets.md, packages/nitro-protocol/contracts/AssetHolder.sol, packages/nitro-protocol/contracts/interfaces/IAssetHolder.sol, packages/nitro-protocol/src/contract/asset-holder.ts, packages/nitro-protocol/src/index.ts, packages/nitro-protocol/test/contracts/AssetHolder/claim.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/claimAll.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/computeNewAllocation.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transfer.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts, packages/nitro-protocol/test/contracts/NitroAdjudicator/concludePushOutcomeAndTransferAll.test.ts, packages/nitro-protocol/test/contracts/NitroAdjudicator/pushOutcomeAndTransferAll.test.ts, packages/nitro-protocol/test/test-helpers.ts, packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts, packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/chain-service/types.ts, packages/server-wallet/src/wallet/wallet.ts
This emits a close-to-minimal amount of information when transfer or claim is called: the information is sufficient for clients to construct a new AssetOutcome for a given channel in a given AssetHolder. They need this up-to-date data in order to successfully call transfer in future.
Example 1: my counterparty concluded, pushed, and transferred their own money out of a channel. Now I want to transfer my money out, but my view of the outcome on chain is out of date and my transaction will fail if I don't keep it fresh.
Example 2: someone called `concludePushOutcomeAndTransferAll`, and I want to be sure all the money got paid out. It's not the only way of doing this, but I can catch the `AllocationUpdated` event, feed it into the new typescript functions this PR introduces, and infer which …
=> Replace AssetTransferred with AllocationUpdated event

packages/nitro-protocol/.solhint.json, packages/nitro-protocol/contracts/AssetHolder.sol, packages/nitro-protocol/contracts/CountingApp.sol, packages/nitro-protocol/contracts/ERC20AssetHolder.sol, packages/nitro-protocol/contracts/ETHAssetHolder.sol, packages/nitro-protocol/contracts/ForceMove.sol, packages/nitro-protocol/contracts/NitroAdjudicator.sol, packages/nitro-protocol/contracts/examples/SingleAssetPayments.sol, packages/nitro-protocol/src/contract/transaction-creators/revert-reasons.ts, packages/nitro-protocol/src/valid-transition.ts, packages/nitro-protocol/test/contracts/AssetHolder/claim.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/claimAll.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transfer.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts, packages/nitro-protocol/test/contracts/ERC20AssetHolder/deposit.test.ts, packages/nitro-protocol/test/contracts/ETHAssetHolder/deposit.test.ts, packages/nitro-protocol/test/contracts/ForceMove/_acceptableWhoSignedWhat.test.ts, packages/nitro-protocol/test/contracts/ForceMove/conclude.test.ts, packages/nitro-protocol/test/contracts/ForceMove/respond.test.ts, packages/nitro-protocol/test/contracts/NitroAdjudicator/pushOutcome.test.ts, packages/nitro-protocol/test/revert-reasons.ts, packages/nitro-protocol/test/src/valid-transition.test.ts
The test will fail for now but easily fixed.
Reduces estimated gas costs of deploying NitroAdjudicator: `2566237` becomes `2420522` => `145715` drop.
Closes #3081
=> perf: use shorter reason strings

.circleci/config.yml, packages/docs-website/package.json
- No need to add to our dev dependencies, because here we install netlify-cli using `npx`. 
- It's 3 minutes extra (concurrently) on circle, rather than 10 minutes on netlify (which I will disable when this PR is merged). 
- ~For now this will build on *every* circle run~ should skip on non-master branches if `docs-website` has not changed.
Closes #3096
=> build: docs on circle

packages/docs-website/docusaurus.config.js
This will prevent us from merging a change that results in a broken link on the docs website.
=> build: throw error on broken links

packages/server-wallet/src/protocols/close-channel.ts, packages/server-wallet/src/protocols/open-channel.ts, packages/server-wallet/src/protocols/process-ledger-queue.ts, packages/server-wallet/src/wallet/__test__/lock-app.test.ts, packages/server-wallet/src/wallet/store.ts, packages/server-wallet/src/wallet/wallet.ts
* We have an object called a `Channel` and an object called a `ChannelState`.
* Currently `store.getChannel` returns a `ChannelState`. 
* This PR renames it to `getChannelState`
* In another PR, I'm going to recreate `getChannel` so that it actually returns a `Channel`
=> refactor: store.getChannel -> store.getChannelState

packages/nitro-protocol/contracts/AssetHolder.sol, packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts
Closes #3047 .
On the way uncovered a pretty serious underflow bug 🐛 .
=> [nitro-protocol] remove transferAll from AssetHolder 

.circleci/config.yml, packages/docs-website/package.json
It doesn't work quite the way I intended -- builds are not being triggered correctly at present.
=> build: do not use --scope with lerna when deciding whether to build the docs

packages/client-api-schema/src/data-types.ts, packages/client-api-schema/src/generated-schema.json, packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts, packages/server-wallet/src/__test__/test-helpers.ts, packages/server-wallet/src/models/__test__/channel.test.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/protocols/open-channel.ts, packages/server-wallet/src/protocols/state.ts
Currently the fundingStatus value is sometimes inaccurate. For example, it's possible to get 'Uncategorized' or 'ReadyToFund' when the channel is funded, but the funding hasn't been fetched from the db.
Fixing this would require always querying the db for funding, which might not be desirable for performance reasons. Instead, consumers will now receive `fundingStatus: undefined` if it hasn't be fetched.
=> refactor: make fundingStatus optional in the ChannelResult

packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/chain-service.ts
Chain service tests [recently started logging lines like the following after completion](https://app.circleci.com/pipelines/github/statechannels/statechannels/11097/workflows/e99a2892-2bb2-48a1-8bab-b33f7bf821c7/jobs/54160):
```
@statechannels/server-wallet: (node:3543) UnhandledPromiseRejectionWarning: Error: missing response (requestBody="{\"method\":\"eth_call\",\"params\":[{\"from\":\"0xd9995bae12fee327256ffec1e3184d492bd94c31\",\"to\":\"0xc9707e1e496c12f1fa83afbba8735da697cdbf64\",\"data\":\"0xfe9e5db9008070d7208570cdbc4d1657dbe98a29d15365084fb3ded89f5b4b4236e02e69\"},\"latest\"],\"id\":3639,\"jsonrpc\":\"2.0\"}", requestMethod="POST", serverError={"code":"ECONNRESET"}, url="http://0.0.0.0:8545", code=SERVER_ERROR, version=web/5.0.7)
```
While seemingly harmless, the log lines were a …
=> Chain service bug fix and test cleanups

packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts, packages/server-wallet/src/__test__/crash-tolerance/crash-tolerance.test.ts, packages/server-wallet/src/__test__/create-and-close-channel/direct-funding.test.ts, packages/server-wallet/src/__test__/create-and-close-channel/fake-funding.test.ts, packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/protocols/__test__/open-channel.test.ts, packages/server-wallet/src/protocols/direct-funder.ts, packages/server-wallet/src/protocols/ledger-funder.ts, packages/server-wallet/src/protocols/open-channel.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts, packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts, packages/server-wallet/src/wallet/store.ts
This PR refactors the `OpenChannelProtocol`:
* The protocol is now implemented as a `ChannelOpener` object, which has a `crank` method
* That `crank` is an asynchronous method that runs a sequence of fetch/update operations, inside a transaction that it starts.
* It calls out to a funding utility class (`DirectFunder` or `LedgerFunder`) depending on the funding type
* These utility classes also have async `crank` methods, which behave similarly to the `ChannelOpener`, apart from accepting a transaction, instead of starting their own
In my eyes, these changes make the protocols clearer and the code easier to understand. As I'm probably not going to be doing a lot of work in the wallet anymore though, it more matters what other people think. We don't have to go down this route if the people …
=> refactor open channel

packages/nitro-protocol/contracts/AssetHolder.sol, packages/nitro-protocol/contracts/interfaces/IAssetHolder.sol, packages/nitro-protocol/test/contracts/AssetHolder/claimAll.test.ts
It's just an alias for `claim(..,[])`
=> perf: remove claimAll from AssetHolder interface

packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/models/challenge-status.ts, packages/server-wallet/src/models/objective.ts, packages/server-wallet/src/objectives/objective-manager.ts, packages/server-wallet/src/protocols/__test__/challenge-submitter.test.ts, packages/server-wallet/src/protocols/challenge-submitter.ts, packages/server-wallet/src/wallet/__test__/challenge.test.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-ledger-channel.ts, packages/server-wallet/src/wallet/__test__/integration/challenge.test.ts, packages/server-wallet/src/wallet/store.ts, packages/server-wallet/src/wallet/types.ts, packages/server-wallet/src/wallet/wallet-response.ts, packages/server-wallet/src/wallet/wallet.ts, packages/wallet-core/src/serde/wire-format/deserialize.ts, packages/wallet-core/src/types.ts
Fixes #3078 
Introduces a new `challenge-submitter` protocol that is responsible for submitting a challenge transaction using the `chain-service`.
I've added `SubmitChallenge` as an `Objective` in `wallet-core`.  For now, it's a completely internal objective so I've defined `Objective = SharedObjective | SubmitChallenge`. (Sidenote: I find having objectives also defined in `wallet-core` slightly annoying and I'd rather just have them live only in `server-wallet`)
TODO:
=> Introduce Submit Challenge Protocol

packages/server-wallet/src/__test__/evm-validator.test.ts, packages/server-wallet/src/evm-validator.ts, packages/server-wallet/src/utilities/validate-transition.ts
Attempting to remove all instances of `createLogger` in places where it is unnecessary
=> refactor: decouple logger from evm transition validation

packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/chain-service/types.ts, packages/server-wallet/src/db/migrations/20210111135843_add_challenge_state.ts, packages/server-wallet/src/models/__test__/challenge-status.test.ts, packages/server-wallet/src/models/challenge-status.ts, packages/server-wallet/src/protocols/__test__/challenge-submitter.test.ts, packages/server-wallet/src/protocols/challenge-submitter.ts, packages/server-wallet/src/wallet/__test__/challenge.test.ts, packages/server-wallet/src/wallet/store.ts, packages/server-wallet/src/wallet/wallet.ts, packages/wallet-core/src/state-utils.ts
Fixes #3126 
This adds the `challenge-state` column to `ChallengeStatus` allowing us to store the state that was used to challenge.
We need to store the `challenge-state` so once the challenge expires we can call `PushOutcomeAndWithdraw` with that state.
It gets set when the `ChallengeRegistered` event is fired from the `chain-service`
=> feat: store challenge state

packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts
I discovered this bug while trying to write a test for ledger funding, where I spin up several application channels with various nonces. Unexpected results ensued. 
As in my case, a test author may often wish to pass `channelNonce: 0` or `bBal: 0`, to the `TestChannel` constructor, but the current implementation will silently and surprisingly override those values if they do. The intention was likely more to have
defaults set when the passed values are undefined (rather than 0). Hence this change https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator.
Side remark: I'm not sure why `channelNonce` defaults to 5. I think 0 would be less magic?
=> test: prefer nullish coallescing operator ?? to ||

packages/server-wallet/src/protocols/close-channel.ts, packages/server-wallet/src/protocols/state.ts
Simplifies the logic around `status` without changing any of the behaviour.
=> Refactor logic around computing 'status' of channel result

packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/db/migrations/20210112164123_add_push_outcome_status.ts, packages/server-wallet/src/models/chain-service-request.ts, packages/server-wallet/src/models/objective.ts, packages/server-wallet/src/objectives/objective-manager.ts, packages/server-wallet/src/protocols/__test__/defund-channel.test.ts, packages/server-wallet/src/protocols/challenge-submitter.ts, packages/server-wallet/src/protocols/channel-opener.ts, packages/server-wallet/src/protocols/close-channel.ts, packages/server-wallet/src/protocols/defund-channel.ts, packages/server-wallet/src/wallet/__test__/challenge.test.ts, packages/server-wallet/src/wallet/store.ts, packages/server-wallet/src/wallet/wallet.ts, packages/wallet-core/src/types.ts
Fixes #3113 
Introduces a `DefundChannel` protocol that is responsible for defunding a channel by calling either `pushOutcomeAndTransferAll` or `concludePushOutcomeAndTransferAll` on chain.
A `DefundChannel` objective now gets added when a channel is finalized.
The `DefundChannel` protocol is pretty simple and does the following:
- Checks if the channel is finalized on chain (by consulting the `ChallengeStatus` table) 
- If so it calls `pushOutcomeAndTransferAll`
- If not check if the channel has a conclusion proof
- If so it calls `concludePushOutcomeAndTransferAll`
- If not do nothing
=> Defund Channel Protocol

packages/server-wallet/src/handlers/__test__/single-app-updater.test.ts, packages/server-wallet/src/protocols/__test__/ledger-manager.test.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-ledger-channel.ts
The aim here is to preserve the current test suite, but reach farther in to the store/database in the setup and assertions of each test. This has the (beneficial?) effect of integrating more code into the tests, but also bypassing some of the implementation details of the `LedgerManager`. 
Specifically, when the work on this branch is done we shall no longer have any dependence on the `protocol()` function in the tests, nor on any `ProtocolAction`s. This means that those concepts can safely be refactored away in separate PR. 
Performing the refactor in this order means that we will maintain full test coverage throughout the refactor. This is in line with similar refactors executed/planned in the `open-channel` / `close-channel` protocols. 
Because I am moving case by case, I am hoping to …
=> test: rewrite ledger-manager.test.ts (part 0)

packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts
This issue is scoped purely to _test_ code, and concerns the behaviour of the `TestChannel` class in use in many of our suites.
There are obviously several approaches here
a) make `channelNonce` random (this proposal). Nonce collisions are made very unlikely automatically.
b) make `channelNonce` a required parameter, at least things are then very explicit in our tests. The test author has to take care to avoid nonce collisions (this is laborious but very easy typically).
c) implement a method to ensure `channelNonce` increments each time a new instance is created (similar to how our store does it):
```ts
class TestChannel {
static overallNonce = 0;
public nonce: number;
constructor(providedNonce?:number ) {
this.nonce = providedNonce ?? TestChannel.overallNonce++;
}
}
```
(although in …
=> test: default to a random channel nonce if none is provided.

packages/server-wallet/src/handlers/__test__/single-app-updater.test.ts, packages/server-wallet/src/protocols/__test__/ledger-manager.test.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts
A recent change #3152 caused the tests on master to fail with jest timeouts. My hypothesis is that the change introduced some inefficient code, namely generation of random integers, which made the difference for the timeouts.
This PR swaps out a random nonce for an incrementing nonce approach, which should be faster.
=> perf: TestChannel nonce is incrementing, not random

packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-ledger-channel.ts
This brings the `TestLedgerChannel` closer to how real ledger channels work, so it is pretty important IMO. 
- allow a non-mover to sign a state, but default to everyone signing every state.
(passing in an optional list of indices that defaults to everyone)
- force the appDefinition to be null
=> test: enhance TestLedgerChannel

.circleci/config.yml
in addition to master. This provides a utility for running all of the tests, as they do on master, to test/anticipate problems that don't arise when making changes to a feature branch. For example: changes that slow the tests down enough to trigger jest timeouts, but only when run alongside tests from other packages (which are usually skipped on feature branches). 
To do so, just reset the `test-ci` branch to the commit you want to run all of the tests on.
=> ci: introduce a branch that runs all tests

packages/server-wallet/src/protocols/state.ts
If a ledger channel is funding a payment channel, when the payment channel checks to see if its parent is funded it will not work if the parent is fake funded.
https://github.com/statechannels/statechannels/blob/f2b0d6b919ecb4eeaf2a86f5ef41c32e7ad97d43/packages/server-wallet/src/protocols/ledger-funder.ts#L66-L68
This makes this function above return `true`
=> fix: support fake funding in directFundingStatus

packages/server-wallet/src/db-admin/db-admin.ts
When testing, one expects that `truncateDB()` truncates the entire DB.
We often run this function in a `beforeAll()` block to get a
clean DB state for each test case.
Therefore we need to have all table names in this function.
=> test: add missing tables to truncateDB()

packages/server-wallet/jest/custom-matchers.ts, packages/server-wallet/jest/jest.config.js, packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts, packages/server-wallet/src/__test__/globals.d.ts
Establishes a more scalable pattern for extending `jest.expect`. 
1. Moves the existing  `toContainAllocationItem` matcher to a location where it may be more easily re-used (it's currently declared as a global variable, but is not guaranteed to be available in all tests). 
2. Adds a `toContainObject` matcher following this blog post https://medium.com/@andrei.pfeiffer/jest-matching-objects-in-array-50fe2f4d6b98. I anticipate this will be very useful when inspecting objects that contain arrays of objects with many keys besides the ones of interest, and where the position of those objects in the array is not important.
=> test: move custom matchers to setup file and add an additional toContainObject matcher

packages/server-wallet/src/db-admin/db-admin.ts
Fix a naming issue that was introduced by #3134 being merged with `master`
=> Fix Master

packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts, packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/protocols/__test__/defund-channel.test.ts, packages/server-wallet/src/protocols/defund-channel.ts
Fixes #3112.
The `chain-service` now detects the `Concluded` event from the adjudicator and dispatches a channel finalized event.
This PR also updates the `defund-channel` protocol to use the `holdings` table to determine if the outcome has been pushed or not.
=> feat: handle Concluded event from adjudicator

packages/server-wallet/package.json, packages/server-wallet/src/wallet/__test__/restarting.test.ts, packages/server-wallet/src/wallet/store.ts, packages/server-wallet/src/wallet/wallet.ts, yarn.lock
Fixes https://github.com/statechannels/project-management/issues/11
Changes the `wallet` to call `registerChannel` for existing channels on startup. Only channels that are not finalized on chain are called with `registerChannel`.
=> Call register channel on wallet start up

packages/server-wallet/src/protocols/__test__/ledger-manager.test.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-ledger-channel.ts
Of the remaining test cases that reference the `protocol()` function (etc), one is removed and the rest are converted over to a "manipulate the store" style. 
Relevant to https://github.com/statechannels/project-management/issues/22
Continuation of #3136
A subtlety I encountered was that as we now test `crank` (instead of `protocol`), we are testing the  *net* side effects of (potentially) several state-machine transitions in series. This means the intermediate states are not really available to assert on, and the tests need to be altered accordingly.
=> test: complete refactor of ledger-manager tests

.github/workflows/publish-canary.yml
Currently, it is easy to unwittingly break software that relies on the @statechhannels/* packages (e.g. TG), and not find out about it until some later point with an arbitrary delay. We would like a workflow that pushes changes out more predictably and frequently, so that we can pull in and test those changes more rapidly.
This PR triggers the current "canary" release workflow to be triggered at [7am UTC every day.](https://crontab.guru/#0_7_*_*_*). The schedule is easily altered if folks have other suggestions.
I went down this route, rather than making a brand new github action, because the idea of nightly builds is in fact what the [`--canary` flag](https://github.com/lerna/lerna/tree/main/commands/publish#--canary) was intended for. 
This work will only be completed when another …
=> build: trigger canary release on a schedule

packages/docs-website/docs/docs/overview.md
The comment shows up in the metadata of the webpage, which is very much unintended.
We don't really need this comment, as the docs website is checked for broken links automatically on circleCI.
=> docs: remove comment

packages/docs-website/package.json, packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/tsconfig.json
https://github.com/statechannels/project-management/issues/28 calls for documenation of the server wallet design, mostly from an internal-developer perspective. I consider the API of the `Wallet` class as an important part of that documentation, as well as for public-facing documentation. I think it will be very useful for "App developers" (currently these are chiefly other members of our core team) to understand the purpose and responsibility of each API call they may want to make. 
This change is preparatory work for actually documenting the API using [TSDoc](https://tsdoc.org/). Some of this documentation is in place already, but very patchy.  This change will:
- Spur on a more comprehensive set of TSDoc comments, which have the advantage of enhancing[ intellisence in …
=> chore: export SingleThreadedWallet class from pkg, disable removeComments in tsconfig

packages/server-wallet/e2e-test/e2e.test.ts, packages/server-wallet/e2e-test/payer/app.ts, packages/server-wallet/e2e-test/payer/client.ts, packages/server-wallet/e2e-test/payer/start.ts, packages/server-wallet/e2e-test/receiver/app.ts, packages/server-wallet/e2e-test/receiver/controller.ts, packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts, packages/server-wallet/src/__test__/crash-tolerance/crash-tolerance.test.ts, packages/server-wallet/src/__test__/create-and-close-channel/direct-funding.test.ts, packages/server-wallet/src/__test__/create-and-close-channel/fake-funding.test.ts, packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts, packages/server-wallet/src/wallet/__test__/challenge.test.ts, packages/server-wallet/src/wallet/__test__/integration/close-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/create-ledger-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/__test__/integration/sync-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/update-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/multi-threaded-wallet/index.ts, packages/server-wallet/src/wallet/multi-threaded-wallet/worker.ts, packages/server-wallet/src/wallet/wallet.ts
Updates the `Wallet.create` method to be `async`.
In #3148 an async function  `registerExistingChannelsWithChainService` is called in the constructor. Since it is async it can fail after the constructor has finished executing, causing issue with the tests.
The solution implemented is to change the `Wallet.Create` method to be async. This allows us to perform the registration or any other initialization logic before returning the `wallet`.  
These methods are using throughout our tests so I am relying on existing test coverage.
=> Wallet.Create is now async

packages/server-wallet/src/protocols/__test__/ledger-manager-protocol.test.ts
This file was recently (gradually) replaced by a new suite testing the same behaviour at a deeper level #3146 #3163 #3170. There is no reason that the two suites cannot live side-by-side for the moment. If the ledger manager is refactored, this suite could be re-deleted. The net effect of undeleting this will be that the "refactors" strictly increased test coverage, and we haven't lost anything.
=> test: undelete old test suite

packages/server-wallet/src/protocols/__test__/ledger-manager.test.ts
I am assuming `console.log` was left behind accidentally?
=> chore: remove console.log

packages/server-wallet/src/chain-service/mock-chain-service.ts, packages/server-wallet/src/protocols/__test__/defund-channel.test.ts, packages/server-wallet/src/protocols/defund-channel.ts
Chain service APIs that result in transaction submission return a promise that resolves to [`ethers` `TransactionResponse`](https://docs.ethers.io/v5/single-page/#/v5/api/providers/types/-%23-providers-TransactionResponse). The heuristic thus far has been for the chain service API consumer to await these promises to ensure that a transaction is submitted properly.
Note that this does **not** await transaction mining.
=> fix: await concludeAndWithdraw transaction submission

packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/wallet/types.ts, packages/server-wallet/src/wallet/wallet.ts
...and make into a static method. It's just a wrapper for
a static mehod for another class.
This function is in use in just one place in one place in the graph presently:
https://github.com/statechannels/the-graph/blob/ec3007419ca2747f4ae444576d22ebb7842e4b3d/packages/receipt-manager/src/receipt-manager.ts#L100
But it should be an easy fix `this.wallet.mergeMessages(...) => Wallet.mergeOutputs(...)`
=> chore: mergeMessages -> mergeOutputs

packages/server-wallet/e2e-test/payer/client.ts, packages/server-wallet/e2e-test/receiver/controller.ts, packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/wallet/wallet.ts
This method is a no-op, and it unnecessarily bloats the wallet API. This change restores a more usual approach to class inheritance.
Consumers will now need to be sure they have a `MultiThreadedWallet` before calling `warmUpThreads`. This is easy and this PR makes such a change by way of example.
=> chore: remove no-op method from SingleThreadedWallet

packages/server-wallet/e2e-test/e2e-utils.ts, packages/server-wallet/e2e-test/logger.ts, packages/server-wallet/e2e-test/payer/client.ts, packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/config/types.ts, packages/server-wallet/src/logger.ts, packages/server-wallet/src/wallet/wallet.ts
Improve E2E logging by ensuring that we log to the same file.
Fixes a few things and sets a few defaults so that we can expect everything to log to the same file in the e2e test.
- The payer and receiver wallet now log to the `../../artifiacts/e2e.log` with a `logLevel` of `trace`
- The chain service will now log to the same logger as it's wallet (instead of always defaulting to console/info)
- Fixed a check in `createLogger` that was checking `logLevel` instead of `logDestination`
Verified that a [new wallet init trace log](https://github.com/statechannels/statechannels/blob/5b38e59388edeb0009d4cce900d7cdc41be07acb/packages/server-wallet/src/wallet/wallet.ts#L139) shows up in the [e2e logs on CI.](https://circle-production-customer-artifacts.s3.amazonaws.com/picard/5d85227bbc97ad5ba7cf4fb …
=> chore: improve e2e logging

.github/workflows/publish-canary.yml
Please see #3191 for more context. This is a superior solution. 
I tested this by running the GH action manually from this branch. The first time the action ran, packages were published. I then reran the action and it [succeeded early](https://github.com/statechannels/statechannels/actions/runs/517468861) after 17 seconds. Unfortunately the original run seems to have disappeared since I re-ran: but proof that it ran is [here.](https://www.npmjs.com/package/@statechannels/server-wallet/v/1.14.2-next.2ee26f4ed.441)
=> ci: succeed early if canary already published

packages/client-api-schema/client-api-schema.api.md, packages/docs-website/scripts/api-documenter.js, packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/index.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/multi-threaded-wallet/index.ts, packages/server-wallet/src/wallet/types.ts, packages/server-wallet/src/wallet/wallet.ts
Adds explanations to our source code that will appear in our documentation website and intellisense in vscode. 
Towards https://github.com/statechannels/project-management/issues/28. In the mould of https://github.com/statechannels/statechannels/pull/3180. I think the motivation is self evident. 
1. TSDoc annotations were added to all SingleThreadedWallet public methods, apart from the ChainServiceSubscriber part (because it is not clear whether this should be part of the public API: see #3203 and [this suggestion](https://github.com/statechannels/statechannels/pull/3116/commits/35abe36a7552663f569efb05a21e54dd19dcd81a)). 
2. Additional symbols are exported from `server-wallet` package, as per the recommendation of `api-extractor`. 
3. Some tweaks to our documentation generation pipeline. …
=> docs: enhance server-wallet tsdoc

.circleci/config.yml, packages/client-api-schema/client-api-schema.api.md, packages/server-wallet/package.json
We want both to 
- have `prepare` complete as fast as possible, and to only perform tasks necessary to prepare a package for use / consumption by other packages
- enforce that the reports generated by api-extractor are checked in when the API of a package (currently, `server-wallet` and `client-api-schema`) changes. These reports provide a valuable spotlight on such changes.
This approach moves the api-extractor step out of `prepare` and into the dedicated circle job that handles the `docs-website`, (which was running the extractor anyway). So it achieves both goals.
Existing CI suite.
---
=> ci: remove api-extractor step from prepare lifecycle script

packages/server-wallet/e2e-test/challenge.test.ts, packages/server-wallet/e2e-test/e2e.test.ts, packages/server-wallet/e2e-test/payer/client.ts, packages/server-wallet/jest/jest.e2e.config.js, packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/models/objective.ts, packages/server-wallet/src/protocols/challenge-submitter.ts, packages/server-wallet/src/protocols/channel-closer.ts, packages/server-wallet/src/protocols/channel-opener.ts, packages/server-wallet/src/protocols/defund-channel.ts, packages/server-wallet/src/wallet/__test__/challenge.test.ts, packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts, packages/server-wallet/src/wallet/store.ts, packages/server-wallet/src/wallet/types.ts, packages/server-wallet/src/wallet/wallet.ts
Wallet emits 'objectiveStarted' & 'objectiveSucceeded' events, allowing applications to learn when API calls succeed.
See the RFC [here](https://www.notion.so/RCF-1-First-class-objectives-2a26247ce3244b8aafa4f9397df8465f#187917c1a0d54dd3bf9715f8415f65f2).
As the WalletResponse model already stores `succeededObjectives`, I opted to emit them at the end of a crank. I believe this increases the susceptibility of crashes, since the implementation follows the following story:
1. An objective might succeed
2. This might trigger other objectives to be cranked
3. Finally, `'objectiveSucceeded'` is emitted.
If the wallet crashes during (2), then the objective would succeed, but the app would never know.
We could emit `objectiveSucceeded` right away, when the objective succeeds. In this case, the …
=> Wallet emits 'objectiveStarted' & 'objectiveSucceeded' events

packages/server-wallet/src/models/objective.ts
The lodash utility currently in use does not provide type safety. For example, if we add properties to `dbObj: DBObjective`, they will not be omitted unless we update this function, and this will lead to a runtime error when we try to validate the objective coming over the wire, due to pollutant properties.
Here, any required properties will be checked by the TS compiler. Optional properties are still a bit of a risk -- I will tackle that in another PR  #3251 
(Extra context: we may well add new properties to objectives, soon. See #3230). 
---
=> refactor: make toWireObjective type safe / more robust

packages/server-wallet/src/models/objective.ts, packages/server-wallet/src/protocols/__test__/challenge-submitter.test.ts, packages/server-wallet/src/protocols/__test__/defund-channel.test.ts, packages/wallet-core/src/serde/wire-format/deserialize.ts, packages/wallet-core/src/types.ts, packages/wire-format/src/generated-schema.json, packages/wire-format/src/types.ts
- it makes little sense to allow both undefined an an empty array
- greater certainty about properties makes type interconversion safer
I think there is a possibility that this property is entirely removed in future. This change will make that easier if we want to do it, and does not count as a vote for keeping the property. 
---
=> fix: make participants a required property of objectives

packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts, packages/server-wallet/src/wallet/__test__/integration/close-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts, packages/server-wallet/src/wallet/types.ts, packages/server-wallet/src/wallet/wallet-response.ts
createdObjectives are stored in a WalletResponse, and then returned in Single/MultipleChannelOutput to the app.
Fixes #3228, with a slightly expanded scope: it's important for the app to learn about objectives created as a direct result of an API call.
I chose not to modify the wallet API, besides adding optional `newObjectives` to `Single/MultipleChannelResult`, because it seemed outside the scope of this PR.
9/9
=> New objectives are returned in ChannelResults

packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/protocols/channel-closer.ts, packages/server-wallet/src/protocols/direct-funder.ts, packages/server-wallet/src/protocols/ledger-funder.ts
`directFundingStatus` of `ChannelState` has likely outlived its usefulness. The original intention with `directFundingStatus` was to create a function that maps a channel + funding database state to a channel funding string.
We are seeing the channel opener and defunding protocols reimplement parts of the `directFundingStatus`. That's probably the right approach. This way we can build up smaller functions that can answer specific questions such as:
- Is this directly funded channel fully funded?
- Do I have any funds in this channel that I can claim?
This PR is working toward addressing https://github.com/statechannels/statechannels/issues/3124.
This PR is a refactor, so no additional tests have been added.
=> Do not rely on directFundingStatus internally

packages/server-wallet/src/models/objective.ts, packages/server-wallet/src/wallet/store.ts
Currently, the various methods on `ObjectiveModel` have different return types: either a promise resolving to a`DBObjective` or to an `ObjectiveModel` instance. Most code in `store.ts` uses the former type, so it is far more convenient to return that. 
The current workarounds in the various `ensureObjective` functions involve preparing a `DBObjective`, `insert`ing it, and if success, returning the thing that was prepared beforehand. This PR moves to a model where the `insert` method accepts a type that may *not* be a `DBObjective`. Now in the `ensureObjective` functions, we simply return the result of `insert` if it succeeds. 
The reason for this alternative pattern is that we shortly intend to introduce timestamps to `DBObjectives`. If these timestamps are added at the data model layer, …
=> refactor: ObjectiveModel.insert returns a DBObjective

packages/server-wallet/src/db/migrations/20210126122745_add_objective_timestamp_columns.ts, packages/server-wallet/src/models/__test__/objectives.test.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/models/objective.ts, packages/server-wallet/src/protocols/__test__/challenge-submitter.test.ts, packages/server-wallet/src/protocols/__test__/defund-channel.test.ts, packages/server-wallet/src/wallet/__test__/challenge.test.ts, packages/server-wallet/src/wallet/store.ts
Add a `createdAt` and `progressLastMadeAt` columns to the `objectives` table. Does not add any methods to query these fields, yet (the next PR in this stack does that #3264). Towards #3230.
**what is the problem being solved**
The app requires a means to detect inactivity on an ongoing objective, so that it can i) try and synchronize data with peers to get the objective going again or ii) launch a challenge to recover funds. This first step installs a location for the wallet to store the data required to track objective progress. 
**why this is a good approach**
The most important timestamp here is the `progressLastMadeAt`. If this timestamp is long enough ago (let's say, 10x the expected network latency), then this is a very strong indication that the objective will no longer progress …
=> add objective timestamps

packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/protocols/__test__/defund-channel.test.ts, packages/server-wallet/src/protocols/__test__/ledger-manager.test.ts, packages/server-wallet/src/protocols/channel-closer.ts, packages/server-wallet/src/protocols/defund-channel.ts, packages/server-wallet/src/protocols/defunder.ts
This PR creates a new `Defunder` class. The purpose of the class is to implement the `isChannelDefunded` function. The function is meant to operate as a cranker (and maybe should be renamed to `crank`?). This approach mimics the funding approach in channel opener.
CloseChannel and DefundChannel (and later ChallengeChannel) protocols share the `Defunder` class to make progress toward defunding a channel. The Defunder interprets the complete state of the channel (states signed and chain state) and attempts to take the next step in defunding the channel if such a step can be taken.
This PR is a refactor and has no additional tests. This PR is making progress toward https://github.com/statechannels/statechannels/issues/3124.
=> Unify defunding logic between Close and Defund protocols

packages/server-wallet/src/models/__test__/objectives.test.ts, packages/server-wallet/src/models/objective.ts, packages/server-wallet/src/protocols/__test__/defund-channel.test.ts
Objective timestamps are now treated consistently as a Date type.
Previously we treated timestamps on the objective as `strings` however `knex` would return a `Date` type that we would sometimes get converted to a `string` (depending on the code path)
To fix this  the timestamp fields have been changed to `Date`s on the `Objective`. This reflects the type `knex` gives us and will be easier to manipulate than a string.
Two new basic tests have been added that test the correct type is returned.
=> Objective timestamps are now treated consistently as a Date type.

packages/server-wallet/src/models/__test__/channel.test.ts
These functions were added in #3256.
This work follows #3267.
=> Add unit tests for channel model funding getters

packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts, packages/server-wallet/src/wallet/wallet.ts
Expose a `getObjective` method, to mirror the existing `getState` method.
Currently, there is no way to learn about the timestamps or status of an objective. (Except possibly for objectives that go across the wire, but they are bundled up inside messages for opponents). 
This approach is good because it allows information about timestamps to be queried. It is therefore a "pull", and should be robust against wallet/app restarts (in contrast to event emission).
Shortcomings: you can only get one objective at a time, and you need to know its id. 
Towards #3230 and the sprint goal of first class objectives. Builds on #3263 .
An existing case in  `create-channel.test.ts` has had an assertion added.
---
=> feat: add API method for fetching objective

packages/server-wallet/jest/knex-setup-teardown.ts, packages/server-wallet/src/config/defaults.ts, packages/server-wallet/src/models/__test__/channel.test.ts, packages/server-wallet/src/wallet/__test__/add-my-state.test.ts, packages/server-wallet/src/wallet/__test__/sign-state.test.ts
One way of introducing deadlocks is to
1. ask for a connection c1 (eg. when starting a transaction)
2. as a blocking step before releasing c1, asking for another connection c2
When your connection pool has size n, this obviously creates deadlocks when n async functions execute 1 before any of them execute 2.
With this change, code with this pattern will time out when running unit tests.'
=> test: detect resource deadlocks caused by starved transaction pool

packages/server-wallet/src/wallet/multi-threaded-wallet/manager.ts
Extracts the common code in the currently implemented multi-threaded wallet API into a generic `sendOperation` function.
The code refactored here is almost entirely overlapping. I am DRYing it out, as I wish to change the implementation of each API function in order to address https://github.com/statechannels/statechannels/issues/3262
---
* See screenshots below
* This is purely a refactor. There's no good place to write a test that passes, but I promise I will add a test when resolving https://github.com/statechannels/statechannels/issues/3262 
To make your life easier, feel free to peruse these diffs:
=> DRY WorkerManager with a sendOperation method

packages/server-wallet/src/db-admin/db-admin.ts
Make "createdb" more robust by avoiding throwing fatal error if db already exists
Then, following a single blank line, a summary of the change and which issue is fixed, including 
UT repeatedly create "TEST_A" and "TEST_B", if one fails to clean up somehow, it will fail all future test case
If db already exists then no good to recreate it regardless
We yet don't know how DB destroy failed but it can be due to process killed while running.
=> enhance:createdb - don't error out if db already exists

packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/protocols/channel-opener.ts
This is a genuine refactor and does not change any behaviour. I don't think we have any bugs around this at present, but I want to reduce the chance we get one in future. 
This PR aims to be a little more precise on terminology, and to reduce the chance of confusion between a complete setup round and a supported setup state. 
In the prefund stage, the two concepts are the same. But I have a preference for using the "complete" terminology, still, as it seems simpler to me to match the terminology for the postfund round, which I think should change.
In the postfund stage, participant `0` can make state `n` supported as soon as they sign it: they get the remaining `n-1` signatures from the prefund stage. I think it is important that wallets do not have their `OpenChannel` objective succeed, …
=> refactor: rename getters and add comments

packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/__test__/sync-objectives.test.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/models/objective.ts, packages/server-wallet/src/wallet/__test__/fixtures/open-channel-objective.ts, packages/server-wallet/src/wallet/__test__/sync-objectives.test.ts, packages/server-wallet/src/wallet/store.ts, packages/server-wallet/src/wallet/wallet-response.ts, packages/server-wallet/src/wallet/wallet.ts
Add a new SyncObjective method to the wallet API.
This PR introduces a new method on the wallet `syncObjectives`. It accepts a list of `objectiveId`s and returns a message that can be sent to other counterparties. 
The syncObjectives method will also call `syncChannel` for any relevant channels so the message payload will contain all relevant channels for the objective.
The main use case this is designed around is for resending objectives if a message gets dropped.
Two new test files have been added to test the functionality. One is a unit test, while the other is more of an integration style test with two wallets.
It would be nice to test this is out on an e2e style test however I think the amount of effort to do that is outside the scope of this PR.
=> Add SyncObjective method to Wallet

packages/server-wallet/e2e-test/e2e.test.ts, packages/server-wallet/e2e-test/payer/client.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/multi-threaded-wallet/index.ts, packages/server-wallet/src/wallet/multi-threaded-wallet/manager.ts, packages/server-wallet/src/wallet/multi-threaded-wallet/worker.ts, packages/server-wallet/src/wallet/store.ts, packages/server-wallet/src/wallet/wallet.ts
Workers forward events emitted from their wallet, on to the main thread. The main thread re-emits the event from their wallet.
Fixes #3262.
Fixes #3228.
To do this, I needed to make a significant change to the MultiThreadedWallet:
- before, the WorkerManager would send an operation to the worker, listen for one `'message'` event, and _assume that the event contains the result of API call_
- after, the WorkerManager will send an operation to the worker, listen to `'message'` events _until the event contains the result of the API call_
This allows the worker to also forward wallet events to the main thread.
With @lalexgap, I considered changing the type of the value that's sent back by the worker. This was ruled out, as it would have required a large change to the SingleThreadedWallet. It …
=> MultiThreadedWallet emits events

packages/server-wallet/src/models/__test__/adjudicator-status.test.ts, packages/server-wallet/src/models/adjudicator-status.ts, packages/server-wallet/src/protocols/__test__/defund-channel.test.ts, packages/server-wallet/src/wallet/store.ts, packages/server-wallet/src/wallet/wallet.ts
```
// If the query does not contain a result, existing === []
const existing = await AdjudicatorStatusModel.query(knex).where({channelId});
// This condition is false if existing === []
if (!existing)
```
This PR fixes the issue above and wires through `finalizedAt` parameter from the wallet API to the `AdjudicatorState` model as `finalizesAt` is required to be non-null
=> Fix AdjudicatorState setFinalized

packages/server-wallet/src/__test__/sync-objectives.test.ts
Disables the assertion on `newObjectives` as due to https://github.com/statechannels/statechannels/issues/3289 we can receive `newObjectives`
=> test: disable new objective check

packages/server-wallet/src/protocols/ledger-funder.ts
At the moment, a ledger channel might be directly funded or fake funded. In the future, a ledger channel might be virtually funded or funded by another ledger channel.
In any of the above cases, when funding a channel with a ledger channel, we should only proceed with the ledger funding protocol if the ledger channel is in the running stage regardless of how it was funded.
This hopefully addresses https://github.com/statechannels/statechannels/issues/3295.
=> fix: do not assume that a ledger channel is directly funded

packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts, packages/server-wallet/src/protocols/__test__/defunder.test.ts, packages/server-wallet/src/protocols/channel-closer.ts, packages/server-wallet/src/protocols/defund-channel.ts, packages/server-wallet/src/protocols/defunder.ts
The bulk of this PR is the addition of Defunder protocol tests. A couple minor changes are also included. These are:
- Defunder protocol ensures that all relations needed for the protocol are joined when `crank` is invoked.
- Defunder for ledger funded channels checks that the channel has a conclusion proof.
This PR fixes https://github.com/statechannels/statechannels/issues/3124 as it is the last piece of work needed.
---
=> Defunder protocol tests

packages/server-wallet/src/models/objective.ts, packages/server-wallet/src/wallet/store.ts, packages/server-wallet/src/wallet/wallet.ts
...and into `createChannel` and `approveObjective`.
The various `ensure*Objective()` functions all do very similar but slightly different things, and are called into both when
- instigating an objective myself (should be OK to pre approve)
- receiving an objective from a counter-party (should ask app for approval).
The wider context is that I want to remove `ensureObjectives` entirely because it is not clear what the function is responsible for, and it makes several non-obvious decisions when it executes. A blocker to that work is that the existing functionality of this function is heavily leaned on. The functionality about approval and about insertion / checking existence in the DB should be fairly straightforward, but any other functionality needs to be preserved too. This PR takes that …
=> move "ledger channel patching" outside of ensureOpenChannelObjective

packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/models/objective.ts, packages/server-wallet/src/objectives/close-channel.ts, packages/server-wallet/src/protocols/__test__/close-channel.test.ts, packages/server-wallet/src/protocols/__test__/defunder.test.ts, packages/server-wallet/src/protocols/channel-closer.ts, packages/server-wallet/src/protocols/defund-channel.ts, packages/server-wallet/src/protocols/defunder.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/store.ts, packages/wallet-core/src/types.ts, packages/wire-format/src/generated-schema.json, packages/wire-format/src/types.ts
Assume a 2-party, directly funded channel, though the following easily generalizes to `n` parties.
Once participants A and B hold a conclusion proof, the following sequence should occur:
1. The channel should be concluded on-chain.
1. The channel outcome should be pushed to all AssetHolders.
1. In each AssetHolder, funds should be transferred to each participant.
The above can be done in 1 or many transactions. Regardless of how many transactions are mined, at least 1 transaction is a "collaborative" transaction: a transaction that benefits both parties, but only one party pays gas fees.
This PR introduces a transaction submitter order for collaborative conclusions. The order is agreed upon when the collaborative conclusion objective is created. At the moment, the order is hardcoded as …
=> Introduce deterministic transaction submission

packages/server-wallet/package.json, packages/server-wallet/src/db-admin/db-admin.ts
The below issue was flagged when attempting to get @NiloCK's Ubuntu machine to pass all wallet tests.
Database manipulations occur either via:
1. Postgres db commands such as `createdb`/`dropdb`
1. `knex`
Different postgres users are used throughout the codebase:
1. In some cases `postgres` user is hardcoded.
2. In some cases, server wallet database configuration is respected. This happens when `knex` is used for database manipulations. The default user for the server wallet database configuration is `postgres`. 
3. In some cases, the system user is used.
This PR eliminates case 3.
=> fix: do not use system user for postgres

packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/__chain-test__/stress.test.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/chain-service/mock-chain-service.ts, packages/server-wallet/src/chain-service/types.ts, packages/server-wallet/src/wallet/__test__/restarting.test.ts, packages/server-wallet/src/wallet/wallet.ts
Closes #3332. Supercedes the work done in #3328.
Currently, we pass the chain id down to constructor for the ethereum `JsonRPCProvider`. This is good because errors will be thrown in the event that the chain reports a different id to the one passed to it's constructor. But it is bad because the constructor chain is all synchronous, and the errors are thrown asynchronously (they have to be, because they are triggered by RPCs). It's also bad that many errors are thrown. As a consequence, there is no test for this behaviour.
The approach of this PR is to allow the provider to setup without a named chain id (it will just use the one from the chain it talks to, eventually), but to expose an async method which can be used to ensure the chain has the expected id. This async method is called …
=> Add a chainService.checkChainId() and call during wallet creation

packages/server-wallet/jest/with-peers-setup-teardown.ts, packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts
All the other DB names in the `server-wallet` are prefixed with `server_wallet`.
This updates the `TEST_A/B` databases to be named `SERVER_WALLET_TEST_A/B` to follow the existing pattern.
=> chore: clean up db names

packages/server-wallet/jest/jest.stress.config.js
Unused code test config file can confuse or obscure actual test configuation
Remove `server-wallet/jest/jest.stress.config.js`
It is not immediately obvious that this file is unused, but:
- its testMatch glob does not map to any files in the repository
- test:stress in package.json does not refer to it
- circleCI config.yml runs test:stress and does not refer to it
File as-is is a source of confusion wrt structure of test suites
---
=> chore: remove unused jest.stress.config file

packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/__test-with-peers__/sync-objectives.test.ts, packages/server-wallet/src/models/objective.ts, packages/server-wallet/src/objectives/close-channel.ts, packages/server-wallet/src/objectives/objective-manager.ts, packages/server-wallet/src/protocols/__test__/challenge-submitter.test.ts, packages/server-wallet/src/protocols/__test__/close-channel.test.ts, packages/server-wallet/src/protocols/__test__/defund-channel.test.ts, packages/server-wallet/src/protocols/__test__/defunder.test.ts, packages/server-wallet/src/protocols/__test__/open-channel.test.ts, packages/server-wallet/src/protocols/challenge-submitter.ts, packages/server-wallet/src/protocols/channel-closer.ts, packages/server-wallet/src/protocols/channel-opener.ts, packages/server-wallet/src/protocols/defund-channel.ts, packages/server-wallet/src/protocols/defunder.ts, packages/server-wallet/src/protocols/direct-funder.ts, packages/server-wallet/src/protocols/ledger-funder.ts, packages/server-wallet/src/wallet/__test__/challenge.test.ts, packages/server-wallet/src/wallet/__test__/fixtures/open-channel-objective.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-ledger-channel.ts, packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts, packages/server-wallet/src/wallet/store.ts, packages/server-wallet/src/wallet/types.ts, packages/server-wallet/src/wallet/wallet-response.ts, packages/server-wallet/src/wallet/wallet.ts
Problems:
1)  it's possible to pass an `OpenChannel` objective to `ObjectiveModel.insert`, but get back something asserted as e.g.  a `DBCloseChannel` objective. 
2) `DBObjective` is a poor of name, since the type is used throughout the wallet and not just in the database / ORM. 
This PR:
- restores the correlation between the input of `ObjectiveModel.insert<>()`and the return value. If you pass in an `OpenChannel` objective (from wallet core), TS will infer that you get back a `WalletObjective<OpenChannel>` (essentially the same thing, but with some `ExtraProperties`). You don't even need to use the `<>`.
- Deprecates DBObjective entirely. I deprecated it in the first commit, and then applied the large number of renaming changes in the second commit. 
Shortcomings: we end up with deeply …
=> deprecate DBObjective in favour of WalletObjective<> 

packages/docs-website/docs/docs/protocol-tutorial/execute-state-transitions.md
The question of "how programmable" the `challengeDuration` of a channel is has come up while thinking about HTLCs.
The answer I think is a bit subtle, and turns on the definitions of `FixedPart`, `channelId` and `support`.
=> docs: clarify the role of FixedPart

packages/server-wallet/e2e-test/scripts/generate-profile-data.ts, packages/server-wallet/src/utilities/validate-transition.ts, packages/server-wallet/src/wallet/store.ts
Note that there are a couple places in the monorepo where a variable is compared with `undefined` via `== undefined`. These comparisons are left as is since maybe `null` is an acceptable value for these comparisons.
```
> null == undefined
true
> null === undefined
false
```
=> chore: use === instead of == for comparison

packages/server-wallet/src/__test-with-peers__/create-and-close-channel/ledger-funding.test.ts, packages/server-wallet/src/db/migrations/20210218145000_add_addn_ledger_request_columns.ts, packages/server-wallet/src/models/__test__/channel.test.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/models/channel/outcome.ts, packages/server-wallet/src/models/channel/state.ts, packages/server-wallet/src/models/ledger-request.ts, packages/server-wallet/src/models/objective.ts, packages/server-wallet/src/protocols/__test__/close-channel.test.ts, packages/server-wallet/src/protocols/__test__/defunder.test.ts, packages/server-wallet/src/protocols/__test__/ledger-manager.test.ts, packages/server-wallet/src/protocols/defunder.ts, packages/server-wallet/src/protocols/ledger-funder.ts, packages/server-wallet/src/protocols/ledger-manager.ts, packages/server-wallet/src/type-aliases.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-ledger-channel.ts, packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/store.ts, packages/server-wallet/src/wallet/wallet.ts
Adds a new ledger channel algorithm
The ledger funding algorithm in current master (roughly) works as follows:
- When an objective wants a channel to added to / removed from a ledger channel it creates a `LedgerRequest`. The request stores the `channelId`, `ledgerId`, and whether it's a fund/defund.
- After all objectives have been cranked, the `LedgerManager` processes the ledger request queue.
- In order to decide what update to propose, the participants exchange *ledger proposals.* Roughly, both participants send each other the list of changes they're willing to make at this point, and the actual change is computed by taking the intersection.
- A ledger update is then proposed containing this intersection, which should be accepted by each party.
As far as I'm aware, there isn't high …
=> feat: new ledger channel algorithm

packages/server-wallet/jest/with-peers-setup-teardown.ts, packages/server-wallet/src/__test-with-peers__/crash-tolerance/crash-tolerance.test.ts, packages/server-wallet/src/__test-with-peers__/create-and-close-channel/direct-funding.test.ts, packages/server-wallet/src/__test-with-peers__/create-and-close-channel/fake-funding.test.ts, packages/server-wallet/src/__test-with-peers__/create-and-close-channel/ledger-funding.test.ts, packages/server-wallet/src/__test-with-peers__/utils.ts, packages/server-wallet/src/__test__/test-helpers.ts, packages/server-wallet/src/message-service/test-message-service.ts, packages/server-wallet/src/message-service/types.ts
Introduces a new message service responsible for sending messages between participants.
This introduces the concept of a "MessageService". The responsibility of this message service is to send messages to opponents and trigger the `incomingMessageHandler` when receiving a message.
Longer-term the `wallet` will accept a `MessageServiceFactory`  from the `app`. This allows the `wallet` to create a message service while supplying a callback that can push the message into the wallet.
The initial implementation is a `TestMessageService` used for the majority of the `with-peers` tests. (Ledger funding was skipped since we expect it to change drastically soon). 
1. New `MessageServiceInterface` and associated types.
2. New `TestMessageService`
3. Updated `with-peer` tests to use …
=> Implement a basic Messaging Service

packages/server-wallet/package.json, packages/server-wallet/src/evm-validator.ts, packages/server-wallet/tsconfig.json, yarn.lock
While working on something else I noticed that the `setTimeout` function returned something different than the typing specified. That is because our `tsconfig` included the `dom` library.
This PR removes the `dom` entry and makes some other changes to support that.
1. Remove `dom` entry from `server-wallet` ts-config: 3f57bea
2. Update the `server-wallet` to ignore the '@types' from the parent `node_modules`: 08591df
3. Upgraded some depenencies that were causing type issues: 445de9b & 445de9b
4. Fixed a `TextEncoder` usage so it is compliant with node. : 6a3b63c
=> chore: Remove DOM Lib from server-wallet tsconfig

packages/docs-website/docs/docs/implementation-notes/force-move.md, packages/docs-website/docs/docs/implementation-notes/null-app.md, packages/docs-website/docs/docs/protocol-tutorial/finalize-a-channel-sad.md, packages/docs-website/docs/docs/protocol-tutorial/understand-adjudicator-status.md, packages/nitro-protocol/notes/blog-posts/gas-optimizations/gas-usage-chart.py, packages/nitro-protocol/notes/force-move-implementation.md, packages/nitro-protocol/src/transactions.ts, packages/nitro-protocol/test/contracts/ForceMove/challenge.test.ts
Following #2963 , I found a few more instances where the old terminology survives. 
As the linked PR does not have a description, I'll record the reasoning here from memory.
It's not ideal to have the same name for a method and a contract. It is also not ideal to use a protocol-specific term where a more self-contained one would do. The change from `forceMove` to `challenge` reduces the overall size of our terminology.
=> change many forceMove -> challenge

packages/server-wallet/jest/jest.with-peers.config.js
Stops the `knex-setup-teardown` for running with the `with-peers` tests.
The `with-peers` tests use their own databases instead of `server_wallet_test `. So when `knex-setup-teardown` runs it results in a lot of [errors](https://circleci.com/api/v1.1/project/github/statechannels/statechannels/59915/output/104/0?file=true&allocation-id=605ce537d2e8bd5c218de1f4-0-build%2F4C7CA54) due to trying to connect to `server_wallet_test` which does not exist for the `with-peers` tests.
=> Don't run knex-setup-teardown for with-peers test

.circleci/config.yml, packages/interop-tests/jest/chain-setup.ts, packages/interop-tests/src/__test__/interop.test.ts, packages/server-wallet/deployment/deploy.ts
In CircleCi, tests for multiple packages run concurrently. Consequently, two packages cannot use the same database for tests or ganache instance.
This PR fixes the errors in https://app.circleci.com/pipelines/github/statechannels/statechannels/12305/workflows/9b433693-aa21-423d-bbc4-03b07b3e3f52/jobs/60258.
=> Fix resource contention between server-wallet and interop-tests packages

packages/nitro-protocol/test/contracts/ERC20AssetHolder/deposit.test.ts
This change means that we record the amount of gas spent on approving tokens for an ERC20AssetHolder as [an artifact of our CI test suite](https://circle-production-customer-artifacts.s3.amazonaws.com/picard/5d85227bbc97ad5ba7cf4fb2/6061c70816220a0c872a496f-0-build/artifacts/home/circleci/project/packages/nitro-protocol/gas-artifacts/erc20-deposit.gas.md?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20210330T141252Z&X-Amz-SignedHeaders=host&X-Amz-Expires=60&X-Amz-Credential=AKIAJR3Q6CR467H7Z55A%2F20210330%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=e92b4c32f340ddbc65d15bc4bf1b7043f03b4ea3c5453df091b8e5ecff663066). In fact we tend to use the [`increaseAllowance` method](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/243adff49ce1700e0ecb99fe522fb16cff1d1ddc/contracts/token/ERC …
=> test: log out gas cost for increaseAllowance

.circleci/config.yml
I have noticed an uptick in the time taken to complete the `prepare` step on circle.
We are currently not updating the cache key that we try to load from, so we almost never get a hit and never benefit from caching. This should fix that and hopefully make that step run faster.
=> ci: fix mixmatch in cache key

packages/server-wallet/jest/with-peers-setup-teardown.ts
Swallow the knex abort error when tearing down with peers test.
Occasionally we'll see knex connection pool aborted [errors](https://app.circleci.com/pipelines/github/statechannels/statechannels/12374/workflows/df905483-8ad2-4c5f-811c-75723997f688/jobs/60868/parallel-runs/0/steps/0-104) when destroying the engines in the `with-peers` test.
This is due to the fact that we use a `TestMessageService` that delays message processing. This means we may have an open connection to the database when attempting to destroy the engines.
This change simply swallows the error. Since the error is simply an artifact of our test setup I think this is ok.
---
=> Swallow knex abort error in test tear down

packages/nitro-protocol/.eslintrc.js, packages/nitro-protocol/src/contract/challenge.ts, packages/nitro-protocol/test/contracts/AssetHolder/claim.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/claimAll.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/computeNewAllocation.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/computeNewAllocationWithGuarantee.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transfer.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts, packages/nitro-protocol/test/contracts/ForceMove/challenge.test.ts, packages/nitro-protocol/test/contracts/ForceMove/requireValidInput.test.ts, packages/nitro-protocol/test/contracts/NitroAdjudicator/concludePushOutcomeAndTransferAll.test.ts, packages/nitro-protocol/test/test-helpers.ts
We currently have a bunch of unused variables floating around in `nitro-protocol`, as well as a TODO to reinstate a linting rule that would warn us about them. 
This PR reinstates the rule, and quiets the resulting warnings by removing the unused variables.
=> chore: resintate linting rule

packages/wallet-core/src/protocols/direct-funder.ts, packages/wallet-core/src/state-utils.ts, packages/wallet-core/src/tests/direct-funder.test.ts, packages/wallet-core/src/tests/test-helpers.ts
This implements one pure-function variation of a direct-funder "protocol", which is the first step towards #3418.
This introduces a "rich objective" data structure called, for lack of more creativity, an `OpenChannelObjective`. (I suggest we review terminology here.) This "rich objective" stores:
- the target channel id
- the goal starting state of the target channel
- my index in the channel
It then stores some additional data:
- signatures on the expected preFS state's hash
- on-chain funding status
- funding requests submitted
- signatures on the expected postFS state's hash
The cranker receives the current "objective state" as well as an event. This updates the "objective state" and generates some actions. (In other words, the cranker is a state chart!)
This implementation is a …
=> Implement pure-function DirectFunder in wallet-core

packages/wallet-core/.eslintrc.js
- DRY up `no-process-env` override
- enable the `no-unused-vars` rule in wallet-core
The level is intentionally set as error to prevent silly time-wasting:
https://app.circleci.com/pipelines/github/statechannels/statechannels/12395/workflows/5d7beef2-0fd2-4d37-af4a-eeaeadf41df0/jobs/60969/parallel-runs/0/steps/0-106
=> Update wallet-core eslint

packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/__test-with-peers__/crash-tolerance/crash-tolerance.test.ts, packages/server-wallet/src/__test-with-peers__/create-and-close-channel/direct-funding.test.ts, packages/server-wallet/src/__test-with-peers__/create-and-close-channel/ledger-funding.test.ts, packages/server-wallet/src/chain-service/types.ts, packages/server-wallet/src/engine/__test__/integration/update-funding.test.ts, packages/server-wallet/src/engine/engine.ts, packages/server-wallet/src/engine/types.ts
There were two ways of "updating the channel funding" at the engine level. This removes one, and keeps the `ChainServiceSubscriberInterface` implementation, called `holdingUpdated`.
It is important to test `holdingUpdated`, because that is the function that gets called when the chain service notices that holdings are updated. Using the (removed) `updateChannelFunding` introduced the risk of using untested code.
The `ChainServiceSubscriberInterface` is more flexible as a generic interface. The `ChainService` doesn't need to know that `Engine.holdingUpdated` also accepts an optional `EngineResponse` and returns a `SingleChannelOutput`, but consumers of the `Engine` (mostly tests?) can take advantage of this to remove some indirection.
I intentionally stopped short of removing …
=> Remove duplicate funding logic

packages/server-wallet/src/engine/__test__/fixtures/test-channel.ts, packages/server-wallet/src/engine/__test__/fixtures/test-ledger-channel.ts, packages/server-wallet/src/engine/store.ts, packages/server-wallet/src/models/ledger-request.ts, packages/server-wallet/src/protocols/__test__/ledger-manager.test.ts, packages/server-wallet/src/protocols/challenge-submitter.ts, packages/server-wallet/src/protocols/channel-closer.ts, packages/server-wallet/src/protocols/channel-opener.ts, packages/server-wallet/src/protocols/defund-channel.ts, packages/server-wallet/src/protocols/ledger-manager.ts
Currently, `ledger-manager.test.ts` tests `LedgerManager.crank`, which is asynchronous and requires DB access.
This PR exposes the synchronous logic (which accounts for ~90% of the logic of LedgerManager) as a public method, and incrementally refactors `testLedgerCrank` to be a synchronous function. The synchronous logic is purish -- it does not mutate the `Channel` model, but does mutate the `LedgerRequests[]` models that are passed in.
The main motivation of this work is to move the ledger funding protocol into `wallet-core`, where it can be re-used by the `xstate-wallet` package. Secondary benefits are:
1. the tests are significantly faster: with no DB access, I observed a 50% speedup locally. Since it previously took ~60s to run the entire test suite, this is a significant boon to …
=> Test synchronous LedgerManager logic

packages/xstate-wallet/src/channel-wallet.ts
2 bugs fixes are:
- add channel to `registeredChannels` list after the channel is registered with the chain watcher.
- `channelFunding` is undefined for a channel before a chain event is observed or a deposit is triggered. This PR accounts for this situation.
=> Fix onOpenChannelObjective in xstate wallet

packages/nitro-protocol/config/jest/jest.ninja-nitro.config.js, packages/nitro-protocol/package.json
I was having some confusion / trouble when attempting to run specific test files, owing to the `yarn test` script calling multiple test configurations and not passing arguments to each.
This config handles specific-file arguments, and serves as a convenient shorthand for running 
Adding more configuration increases mental load. In the event that ninja-nitro is replaces nitro, maybe the distinction between existing test configurations and this one disappears, and this config should be removed.
The new configuration runs the expected tests.
---
=> chore: add helper config for ninja-nitro tests

packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts, packages/server-wallet/src/__test-with-peers__/crash-tolerance/crash-tolerance.test.ts, packages/server-wallet/src/__test-with-peers__/create-and-close-channel/direct-funding.test.ts, packages/server-wallet/src/__test-with-peers__/create-and-close-channel/fake-funding.test.ts, packages/server-wallet/src/__test-with-peers__/create-and-close-channel/ledger-funding.test.ts, packages/server-wallet/src/__test-with-peers__/ensure-objectives.test.ts, packages/server-wallet/src/__test-with-peers__/sync-objectives.test.ts, packages/server-wallet/src/engine/engine.ts, packages/server-wallet/src/engine/types.ts, packages/server-wallet/src/models/objective.ts, packages/server-wallet/src/wallet.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/types.ts, packages/server-wallet/src/wallet/wallet.ts
Introduces the new create channels API on the wallet.
The main focus of this PR was updating the create channels API method to return a result that would be informative and useful. A new `ObjectiveResult` has been introduced that can be returned by the `Wallet` for any objective API calls.
The `ObjectiveResult` contains some basic information: `ChannelId, ObjectiveId, currentStatus` that gives some information about the objective and the current status.
It also includes a `done` promise. This promise resolves when the objective is complete. In the case of `createChannels` it resolves when the channel is fully funded and ready to use. The idea is that there is a simple promise that API users can `await` to get back a channel that is useful.
The `done` promise should **always resolve**. If …
=> Create Channels API

packages/xstate-wallet/src/integration-tests/closing.test.ts, packages/xstate-wallet/src/integration-tests/helpers.ts, packages/xstate-wallet/src/integration-tests/running.test.ts, packages/xstate-wallet/src/store/tests/dexie-store.test.ts, packages/xstate-wallet/src/store/tests/memory-store.test.ts
This PR is stacked on top of https://github.com/statechannels/statechannels/pull/3455.
- Uncomment tests that now compile.
- Unskip tests that pass.
There is are still 5 skipped, failing tests in the `xstate-wallet` package. After briefly looking into those test failures, I decided not to pursue fixing those tests as it is yet unclear exactly which pieces of the xstate-wallet will be reused.
=> Enable more xstate wallet tests

packages/xstate-wallet/package.json, packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/integration-tests/closing.test.ts, packages/xstate-wallet/src/integration-tests/helpers.ts, packages/xstate-wallet/src/integration-tests/running.test.ts, packages/xstate-wallet/src/logger.ts, packages/xstate-wallet/src/store/tests/dexie-store.test.ts, packages/xstate-wallet/src/store/tests/memory-store.test.ts, packages/xstate-wallet/src/ui/selectors.ts, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/support-state.ts, packages/xstate-wallet/src/workflows/virtual-defunding-as-hub.ts, packages/xstate-wallet/src/workflows/virtual-defunding-as-leaf.ts, patches/xstate+4.17.1.patch, yarn.lock
Note that https://github.com/statechannels/statechannels/pull/3453 preceeds this PR.
When unit tests for xstate wallet are run, we see a warning that floods the logs:
```
console.warn
Warning: Attempted to spawn an Actor (ID: "undefined") outside of a service. This will have no effect.
61 |     spawnObserver: assign<HasChannelId>((ctx: HasChannelId) => ({
62 |       ...ctx,
> 63 |       observer: !ctx.observer ? spawn(notifyWhenSupported(store, ctx)) : ctx.observer
|                                 ^
64 |     }))
65 |   }
66 | });
at Object.warn (../../node_modules/xstate/lib/utils.js:451:26)
at ../../node_modules/xstate/lib/interpreter.js:1078:21
at Object.consume (../../node_modules/xstate/lib/serviceScope.js:16:38)
at Object.spawn (../../node_modules/xstate/lib/interpreter.js:1075:25) …
```
=> Patch xstate to remove a very noisy warning

packages/xstate-wallet/package.json, packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/integration-tests/closing.test.ts, packages/xstate-wallet/src/integration-tests/helpers.ts, packages/xstate-wallet/src/integration-tests/running.test.ts, packages/xstate-wallet/src/logger.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/store/tests/dexie-store.test.ts, packages/xstate-wallet/src/store/tests/memory-store.test.ts, packages/xstate-wallet/src/ui/selectors.ts, packages/xstate-wallet/src/utils/wallet-core-v0.8.0.ts, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/support-state.ts, packages/xstate-wallet/src/workflows/virtual-defunding-as-hub.ts, packages/xstate-wallet/src/workflows/virtual-defunding-as-leaf.ts, patches/xstate+4.17.1.patch, yarn.lock
xstate-wallet functionality that depends on `wallet-core` `serializeChannelEntry` was abandoned during the import of the xstate-wallet as `serializeChannelEntry` is not part of the more recent `wallet-core` versions.
This PR comments this functionality back in as well as copies over `serializeChannelEntry` into the xstate-wallet.
=> Comment in abandoned xstate wallet functionality

packages/nitro-protocol/test/contracts/ninja-nitro/AdjudicatorFactory/deployAndPayout.test.ts, packages/nitro-protocol/test/contracts/ninja-nitro/SingleChannelAdjudicator/transfer.test.ts
Initial vs final account balances were not checked in `deployAndPayout.test.ts`. This PR adds this check.
re: #3412
- Accessing, summing, and comparing balances here is not entirely trivial due to the ways that allocation outcomes are represented and handled by different parts of the system.
- The usefulness of this test (and others like it in the codebase) depends on the accuracy of this data fetching.
- This data fetching is approached somewhat ad-hoc throughout the tests
These account balance tests could likely benefit from a deduplication refactor effort.
Tested via manual verification (debugger, console) of recorded and compared balances.
---
=> Add EOA Balances check to deployAndPayout test

packages/wallet-core/src/protocols/direct-funder.ts, packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/store/store.ts
Before this PR, the xstate channel wallet used a quickly implemented direct funder protocol.
This PR brings the newly implemented, pure `DirectFunder` from `wallet-core`  to the `xstate-wallet`. The unmodified interop tests is used to validate that the behavior of the channel wallet is unchanged.
=> Use pure direct funder in xstate wallet

packages/nitro-protocol/contracts/ninja-nitro/AdjudicatorFactory.sol, packages/nitro-protocol/contracts/ninja-nitro/SingleChannelAdjudicator.sol, packages/nitro-protocol/test/contracts/ninja-nitro/SingleChannelAdjudicator/deposit.test.ts
The create2 architecture is pretty interesting!
As is, on the base branch, you can send money (ETH) to a contract before it has been deployed... and you can't send money there after it has been deployed! 🤪 
This PR adds a test to confirm this, and then makes a change to fix the behaviour so we can always send ETH. 
https://docs.soliditylang.org/en/v0.8.3/contracts.html?highlight=receive#receive-ether-function
=> [ninja-nitro] Make SingleChannelAdjudicator payable

packages/server-wallet/src/__test-with-peers__/create-and-close-channel/direct-funding.test.ts, packages/server-wallet/src/engine/__test__/integration/join-channel.test.ts, packages/server-wallet/src/engine/__test__/integration/push-message.test.ts, packages/server-wallet/src/engine/engine.ts
There is a hypothesis that this logic might be causing CI test failures like [this](https://app.circleci.com/pipelines/github/statechannels/statechannels/12545/workflows/dfe9cad8-8b20-488a-ad7e-94eda24ed4ae/jobs/61806) as these failures appear to start with https://github.com/statechannels/statechannels/pull/3439
=> chore: remove wallet-core, pure DirectFunder logic from server-wallet

packages/xstate-wallet/src/workflows/application.ts
These duplicate calls were introduced during `xstate-wallet` reclaim.
=> chore: remove duplicate calls in xstate-wallet application workflow

packages/interop-tests/src/__test__/interop.test.ts, packages/wallet-core/.vscode/launch.json, packages/wallet-core/src/protocols/direct-funder.ts, packages/wallet-core/src/tests/direct-funder.test.ts, packages/xstate-wallet/src/channel-wallet.ts
When a wallet receives an open channel objective, the wallet should:
1. Store the objective.
2. Notify the application of the objective.
3. Not take any actions before the application approves the objective.
It is likely that the `approved` field belongs on all objective types. But, for now, we are only considering the open channel objective.
This PR adds objective approval to `OpenChannelObjective` while leaving xstate-wallet api unchanged.
=> Add approved field to OpenChannelObjective

packages/server-wallet/jest/custom-matchers.ts, packages/server-wallet/jest/with-peers-setup-teardown.ts, packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/__test-with-peers__/crash-tolerance/crash-tolerance.test.ts, packages/server-wallet/src/__test-with-peers__/jumpstart.test.ts, packages/server-wallet/src/__test-with-peers__/utils.ts, packages/server-wallet/src/__test-with-peers__/wallet/ensure-objectives.test.ts, packages/server-wallet/src/__test-with-peers__/wallet/jumpstart.test.ts, packages/server-wallet/src/__test__/globals.d.ts, packages/server-wallet/src/engine/engine.ts, packages/server-wallet/src/engine/store.ts, packages/server-wallet/src/wallet/types.ts, packages/server-wallet/src/wallet/wallet.ts
Add a new jumpstart objectives method that can be used to make progress on objectives.
The main use case for this is continuing progress after a wallet crashes or restarts.
The `jumpStart` works by querying for all `approved` objectives and calling `ensureObjective` on them.
A new suite of tests have been added for the jumpstart method. This should also be tested by a more extensive E2E test.
---
=> Add Jumpstart objectives method

packages/server-wallet/.eslintignore, packages/server-wallet/jest/custom-matchers.ts, packages/server-wallet/jest/jest.config.js, packages/server-wallet/jest/knex-setup-teardown.ts, packages/server-wallet/jest/test-teardown.ts, packages/server-wallet/jest/with-peers-setup-teardown.ts
The `jest` folder is currently excluded from linting which makes editing these files more annoying.
This change simple includes the jest folder typescript files in linting.
=> Include jest typescript folders in linting

packages/nitro-protocol/config/jest/jest.contracts.config.js, packages/nitro-protocol/config/jest/jest.ninja-nitro.config.js, packages/nitro-protocol/deployment/deploy-ninja-nitro-contracts.ts, packages/nitro-protocol/deployment/deploy-test-contracts.ts, packages/nitro-protocol/jest/ninja-nitro-contract-test-setup.ts, packages/nitro-protocol/package.json
The aim is to have the ninja-nitro as loosely coupled to the existing code as possible, to avoid confusion. All ninja-nitro code can be in appropriately namespaced files / folders.
=> separate ninja-nitro test setup

packages/nitro-protocol/src/index.ts
... in their own namespace. This makes them usable by external projects.
=> export NinjaNitro artifacts

packages/interop-tests/jest/jest.config.js, packages/interop-tests/src/__test__/interop.test.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/xstate-wallet/src/chain.ts, packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/store/index.ts, packages/xstate-wallet/src/store/store.ts
The main goal of this PR is to add the `**browser** wallet creates channel + cooperates with server wallet to fund channel` itnerop test and the browser wallet functionality for the test to pass. Before this PR, `**server** wallet creates channel + cooperates with browser wallet to fund channel` was already passing.
Browser wallet channel creation works as follows:
1. Existing `CreateChannel` JSON RPC API is used for channel creation.
2. On that API invocation, the browser wallet creates and stores a rich `OpenChannelObjective`. The objective is **not** approved.
3. In the test, the objective is approved via an API call to the browser wallet. When the wallet is run in the browser, the objective approval will come from the user clicking an approve button.
4. When the objective is approved, …
=> [xstate-wallet] Adding channel creation to browser wallet

packages/server-wallet/jest/with-peers-setup-teardown.ts, packages/server-wallet/src/__test-with-peers__/crash-tolerance/crash-tolerance.test.ts, packages/server-wallet/src/__test-with-peers__/create-and-close-channel/direct-funding.test.ts, packages/server-wallet/src/__test-with-peers__/create-and-close-channel/fake-funding.test.ts, packages/server-wallet/src/__test-with-peers__/create-and-close-channel/ledger-funding.test.ts, packages/server-wallet/src/__test-with-peers__/sync-objectives.test.ts, packages/server-wallet/src/__test-with-peers__/utils.ts, packages/server-wallet/src/__test-with-peers__/wallet/ensure-objectives.test.ts, packages/server-wallet/src/__test-with-peers__/wallet/jumpstart.test.ts, packages/server-wallet/src/message-service/test-message-service.ts
Refactor `with-peers` setup and teardown methods to no longer rely on global objects.
Instead, the setup and teardown methods return their own `PeerSetup` object cotaining the `engines` and `messagingService`.
This is done to prevent issues like #3486 where one test has a reference to a `engine` or `messageService` that gets unassigned by another test.
The `crashAndRestart` function has also been refactored and the tests that rely on it have been re-enabled.
I am relying on the existing `with-Peers` test to provide testing.
---
=> Refactor with peers to no longer rely on global variables

packages/nitro-protocol/contracts/ForceMove.sol, packages/nitro-protocol/contracts/interfaces/IForceMove.sol, packages/nitro-protocol/contracts/ninja-nitro/OutcomeTransformations.sol, packages/nitro-protocol/contracts/ninja-nitro/SingleChannelAdjudicator.sol, packages/nitro-protocol/deployment/deploy-test-contracts.ts, packages/nitro-protocol/src/ninja-nitro/helpers.ts, packages/nitro-protocol/test/contracts/ninja-nitro/SingleChannelAdjudicator/claim.test.ts, packages/nitro-protocol/test/contracts/ninja-nitro/SingleChannelAdjudicator/computeNewAllocationWithGuarantee.test.ts, packages/nitro-protocol/test/test-helpers.ts
This PR introduces a new `claim.test.ts` file, in the ninja-nitro folder. The test cases are identical to those targeting our existing `AssetHolder.sol` contract (including the `claimAll` ones). The test script itself is necessarily quite different, and has been completely rewritten. 
This PR also makes the required changes to `SingleChannelAdjudicator.sol` to get the tests to pass. The reason why this wasn't a relatively simple copy-paste job (as it was with `transfer`), is that `claim` involves two channels: in the new design this means it involves two instances of the `SingleChannelAdjudicator`. One of those channels (the guarantor) holds the funds; the other (the target) must have its outcome (`status`) mutated. 
The solution here is to call `claim` on the target channel. This …
=> [ninja-nitro] Implement claim

packages/server-wallet/jest/custom-matchers.ts, packages/server-wallet/jest/with-peers-setup-teardown.ts, packages/server-wallet/src/__test-with-peers__/wallet/ensure-objectives.test.ts, packages/server-wallet/src/__test-with-peers__/wallet/jumpstart.test.ts, packages/server-wallet/src/wallet/wallet.ts
Fixes #3483. Fixes #3510.
This is a collection of fixes that are required to get `EnsureObjective` working properly.
1. A [fix](d8d86b6) for the objectiveId check on `objectiveSuceeded` that would always return true.
2. A [fix](6adf909) to the custom matcher so it prints out error results properly.
3. A small [enhancement](067b88c) to the ensure objective tests that checks the channel results.
4.  Some other minor fixes.
With these changes, we no longer see the `knex` errors from #3483 as we are actually waiting to get back an actual result from the `wallet`. Previously objective succeeded would be fired even if the objective had not suceeded.
=> Fix EnsureObjective

packages/interop-tests/package.json, packages/interop-tests/src/__test__/interop.test.ts
This PR refactors the brittle logic in the interop test to filter server wallet notifications for a notification that contains the postfund state.
Fixes https://github.com/statechannels/statechannels/issues/3495
=> [interop-test] Add a more reliable postfund check

.eslintrc.js, packages/server-wallet/.eslintrc.js
Enables the no-self compare lint rule to prevent us from shooting ourselves in the feet.
=> chore: add no self compare lint rule

packages/browser-wallet/src/channel-wallet.ts
🥞 stacked on https://github.com/statechannels/statechannels/pull/3505.
As of https://github.com/statechannels/statechannels/pull/3505, `crankRichObjectives` is a generic handler for any objective event. `approveRichObjectives` function contains custom logic for just the Approve event.  The custom logic sends the objective to other participants.
This approve event logic will not get triggered for events arriving directly to `crankRichObjectives`.
=> [browser-wallet] refactor: collapse approve objective into crank objective function

packages/browser-wallet/src/channel-wallet-types.ts, packages/browser-wallet/src/channel-wallet.ts, packages/browser-wallet/src/index.ts, packages/browser-wallet/src/store/store.ts, packages/browser-wallet/src/ui/objective/confirm-create-channel-workflow.tsx, packages/browser-wallet/src/ui/objective/objective-context.tsx, packages/browser-wallet/src/ui/objective/objective.tsx, packages/browser-wallet/src/ui/stories/application-workflow.stories.tsx, packages/browser-wallet/src/ui/stories/approve-budget-and-fund-workflow.stories.tsx, packages/browser-wallet/src/ui/stories/close-ledger-and-withdraw.stories.tsx, packages/browser-wallet/src/ui/stories/confirm-create-channel-workflow.stories.tsx, packages/browser-wallet/src/ui/stories/enable-ethereum.stories.tsx, packages/browser-wallet/src/ui/stories/open-channel-objective.stories.tsx, packages/browser-wallet/src/ui/wallet.tsx, packages/browser-wallet/src/ui/workflows/application-workflow.tsx, packages/browser-wallet/src/ui/workflows/approve-budget-and-fund-workflow.tsx, packages/browser-wallet/src/ui/workflows/challenge-channel-workflow.tsx, packages/browser-wallet/src/ui/workflows/close-ledger-and-withdraw.tsx, packages/browser-wallet/src/ui/workflows/confirm-create-channel-workflow.tsx, packages/browser-wallet/src/ui/workflows/enable-ethereum-workflow.tsx, packages/interop-tests/tsconfig.json, packages/wallet-core/src/protocols/direct-funder.ts, packages/wallet-core/src/tests/direct-funder.test.ts
Browser wallet UI can be:
- xstate machine based. This is the established UI methodology in the browser wallet.
- objective based. This is added in this PR.
For objective based UI, the following are the ways that the `ChannelWallet` communicates with the UI and the UI communicates with the `ChannelWallet`:
- On initialization, the `ChannelWallet` is supplied an `updateUI` function that the `ChannelWallet` must invoke whenever the `ChannelWallet` needs the UI to update.
- The UI is supplied a function that can be invoked with an Objective event argument. This function is wired up on `ChannelWallet` initialization.
This PR has been tested with:
- existing unit and interop tests.
- storybook to display new UI.
- manual calls to browser wallet APIs. …
=> [browser-wallet] Add UI for Open Channel Objective

packages/interop-tests/src/__test__/interop.test.ts, packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/engine/__test__/sync-objectives.test.ts, packages/server-wallet/src/engine/engine-response.ts, packages/server-wallet/src/engine/engine.ts, packages/server-wallet/src/engine/types.ts, packages/server-wallet/src/index.ts, packages/server-wallet/src/protocols/channel-closer.ts, packages/server-wallet/src/protocols/channel-opener.ts, packages/server-wallet/src/wallet/wallet.ts
Update Engine-Response to return messages by objective id.
By indexing messages by objective id it allows the `wallet` to get messages specifically per an objective.
This is helpful in `ensureObjective` as we can only send the messages for the objective instead of all the messages.
Instead of forcing all existing code to specify an `ObjectiveId` when adding a message to `EngineResponse` it is optional. If no `ObjectiveId` is specified the message is added to the collection under the key of `NO_OBJECTIVE_ID`.
For backwards compatibility, there is an `outbox` property on `SyncChannelResult` that contains all messages (including those added with no objective Id). This allows most existing code to continue to work without any changes.
---
=> Engine-Response returns messages by objective id

packages/browser-wallet/src/channel-wallet-types.ts, packages/browser-wallet/src/channel-wallet.ts, packages/browser-wallet/src/index.ts, packages/browser-wallet/src/store/store.ts, packages/browser-wallet/src/ui/objective/confirm-create-channel-workflow.tsx, packages/browser-wallet/src/ui/objective/objective-context.tsx, packages/browser-wallet/src/ui/objective/objective.tsx, packages/browser-wallet/src/ui/wallet.tsx, packages/wallet-core/src/index.ts, packages/wallet-core/src/protocols/direct-funder.ts, packages/wallet-core/src/protocols/index.ts, packages/wallet-core/src/protocols/objective.ts, packages/wallet-core/src/tests/direct-funder.test.ts
🥞 stacked on https://github.com/statechannels/statechannels/pull/3509
Browser wallet is the only consumer of rich objectives at the moment. Browser wallet hardcoded the following assumptions:
- Only one rich objective is expected in the store. As a result, the browser wallet assumes that an objective event is intended for the stored objective.
- Only the DirectFunder open channel objective is considered.
This PR introduces the `RichObjective` and `RichObjectiveEvent` abstractions to help the browser wallet remove the above assumptions. At the moment, a RichObjective is always DirectFunder.OpenChannelObjective and a RichObjectiveEvent is always a DirectFunder.OpenChannelEvent
=> [browser-wallet] Introduce RichObjective and RichObjectiveEvent types

packages/browser-wallet/src/channel-wallet.ts, packages/browser-wallet/src/store/store.ts
🥞 stacked on https://github.com/statechannels/statechannels/pull/3511
The browser wallet store defines feeds. The feeds are event emitters wrapped in an observable. This pattern does NOT provide type safety. The store can emit an event where the event name does not match the event data type.
With rxjs subjects, we guarantee type safety as well as reduce a level of indirection. Only rich objective feeds have been refactored. Legacy feeds from wallet
v1 remain as is.
=> [browser-wallet] Guarantee type safety for rich objective feeds

packages/nitro-protocol/addresses.json, packages/nitro-protocol/hardhat.config.ts, packages/nitro-protocol/package.json
This is mostly just exploration of how easy it might be to deploy our stuff to arbitrum.
Answer: very easy.
See this transaction for example https://explorer.arbitrum.io/#/tx/0xc97de88cecc8b162a994577768cb07cf36496809f05cc2d00a1ead396748f96f 
I don't believe it is straightforward for us to run our test suite against something other than a local ganache instance... so I didn't do that yet.
=> deploy nitro contracts to arbitrum testnet

packages/browser-wallet/package.json, yarn.lock
This is a small step to cleaning up unused dependencies. `@material-ui/icons` is one of the largest dependencies in the repo.
=> build: remove unused @material-ui/icons dependency

packages/server-wallet/src/engine/__test__/fixtures/test-channel.ts, packages/server-wallet/src/engine/__test__/integration/join-channel.test.ts, packages/server-wallet/src/engine/__test__/integration/push-message.test.ts, packages/server-wallet/src/engine/__test__/sync-objectives.test.ts, packages/server-wallet/src/engine/engine.ts, packages/server-wallet/src/engine/store.ts, packages/server-wallet/src/models/__test__/objectives.test.ts, packages/server-wallet/src/models/objective.ts, packages/server-wallet/src/objectives/close-channel.ts, packages/server-wallet/src/protocols/__test__/challenge-submitter.test.ts, packages/server-wallet/src/protocols/__test__/close-channel.test.ts, packages/server-wallet/src/protocols/__test__/defund-channel.test.ts, packages/server-wallet/src/protocols/__test__/defunder.test.ts
Stops `PushMessage` from updating the status of approved objectives to pending.
Fixes #3523.
Before this PR the `pushMessage` on method on the `store` would call `ObjectiveModel.insert` on each objective it received in a message.
For every objective type besides `CloseChannel` `pushMessage` would call `ObjectiveModel.insert` with `preApprove` set to `false`.
This means that `ObjectiveModel.Insert` would update the status of approved objectives to pending.
The change in this PR is to switch from a `preApprove` boolean flag to an optional status argument: `approvalStatus?:'approved'|'pending'`. This allows us to only override the status if we intend to. Otherwise, it is left untouched.
It does seems like a code smell that we have a method called `insert` that's a partial `upsert` but I …
=> Fix pushMessage updating approved objective statuses to pending

packages/nitro-protocol/contracts/ninja-nitro/AdjudicatorFactory.sol, packages/nitro-protocol/test/contracts/ninja-nitro/AdjudicatorFactory/createChannel.test.ts
Record a reference of what deploying our proxies would be.
Pen and paper suggests 62K , the test suggests 64.7K, implying about 2.7K for constructing the proxy creation code (via [`abi.encodePacked`](https://ethereum.stackexchange.com/questions/729/how-to-concatenate-strings-in-solidity)). 
1. Code path stripped down to minimize unnecessary gas expenditure (no event emitted, for example)
2. test added
---
=> add test for create2ing the channel

.github/pull_request_template.md
Update PR template to match projectmanagement repo
---
=> chore: update PR template with notion links

packages/server-wallet/src/__test-with-peers__/utils.ts, packages/server-wallet/src/__test-with-peers__/wallet/approve-objective.test.ts, packages/server-wallet/src/__test-with-peers__/wallet/ensure-objectives.test.ts, packages/server-wallet/src/engine/engine.ts, packages/server-wallet/src/engine/store.ts, packages/server-wallet/src/message-service/test-message-service.ts
**STACKED ON #3485** 
Makes sure the Objective is returned with the correct status in `ApproveObjective`.
There are a few changes here to make sure we return the correct status:
- We now lock on the objectiveId when we fetch the objective.
- We refetch the objectives after `takeActions` is called.
A new test suite has been added to test `ApproveObjective`. Also the previous failures in #3485 were resolved with these changes.
---
=> Update ApproveObjectives to return correct status on objectives

packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/__test-with-peers__/utils.ts, packages/server-wallet/src/__test-with-peers__/wallet/approve-objective.test.ts, packages/server-wallet/src/__test-with-peers__/wallet/ensure-objectives.test.ts, packages/server-wallet/src/engine/engine.ts, packages/server-wallet/src/engine/store.ts, packages/server-wallet/src/message-service/test-message-service.ts, packages/server-wallet/src/wallet/wallet.ts
This requires #3527 for the tests to pass.
Introduces a new `approveObjectives` function on the API.
The `approveObjectives`  allows users to approve and make progress on an objective that another participant has approved.
Practically this replaces the `joinChannels` API method.  Instead of calling `joinChannels` on a collection of channelIds we now call `approveObjectives` on a collection of `createChannel` objective ids.
The `ensure-objective` test suite have been updated to use `approveObjective`.
---
=> Add approveObjectives API

packages/server-wallet/src/db-admin/db-admin.ts
Properly awaits `knex.destroy` in the `db-admin`. This may be causing issues with `knex` failing to acquire a connection in some tests.
=> Properly await knex.destroy in DB-Admin

packages/interop-tests/src/__test__/interop.test.ts, packages/server-wallet/e2e-test/challenge.test.ts, packages/server-wallet/e2e-test/e2e.test.ts, packages/server-wallet/e2e-test/payer/client.ts, packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/__test-with-peers__/utils.ts, packages/server-wallet/src/__test-with-peers__/wallet/approve-objective.test.ts, packages/server-wallet/src/__test-with-peers__/wallet/close-channels.test.ts, packages/server-wallet/src/__test-with-peers__/wallet/ensure-objectives.test.ts, packages/server-wallet/src/__test-with-peers__/wallet/jumpstart.test.ts, packages/server-wallet/src/engine/__test__/challenge.test.ts, packages/server-wallet/src/engine/__test__/integration/create-channel.test.ts, packages/server-wallet/src/engine/__test__/integration/push-message.test.ts, packages/server-wallet/src/engine/engine.ts, packages/server-wallet/src/engine/multi-threaded-engine/worker.ts, packages/server-wallet/src/engine/store.ts, packages/server-wallet/src/engine/types.ts, packages/server-wallet/src/message-service/test-message-service.ts, packages/server-wallet/src/wallet/types.ts, packages/server-wallet/src/wallet/wallet.ts
Removes Objective events from the engine.
This simplifies dealing with the `engine`. Instead of listening for objective events, objectives are returned from the engine api.
The `wallet` is also now an `EventEmitter` with one event `ObjectiveProposed`.  This event fires when the `wallet` receives a new proposed objective from a participant.  `wallet.approveObjectives` can then be used to approve the objective.
Currently there is still a `channel-updated` event. I think this can be deprecated as well but I would like to tackle this in a separate PR.
The wallet now queries the DB when executing `ensureObjective`. This is a pragmatic choice, simplifying the logic to determine when wallet API functions should resolve. Ideally, these API calls should resolve as soon as the objective succeeds -- …
=> Remove Objective Events from the engine

packages/interop-tests/package.json
We should also unpublish https://www.npmjs.com/package/interop-tests if we can.
=> make interop-tests private

.github/workflows/publish-canary.yml
The purpose of these nightly builds was to get the latest changes pulled into consuming projects at a high frequency to flag any breaking changes / regressions. 
I don't think that need exists for us right now, hence we can avoid spamming npm.
=> disable nightly builds

packages/nitro-protocol/test/contracts/NitroAdjudicator/concludePushOutcomeAndTransferAll.test.ts
...by using a faster way to generate distinct destinations. Because that happens 100 times in this test.
On my machine, this test takes 128 seconds (and longer on circle). With this change, it only takes 29 seconds.
=> [nitro-protocol] speed up slowest test 

packages/interop-tests/src/__test__/interop.test.ts, packages/server-wallet/e2e-test/e2e.test.ts, packages/server-wallet/e2e-test/payer/client.ts, packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts, packages/server-wallet/src/engine/engine-response.ts, packages/server-wallet/src/engine/engine.ts, packages/server-wallet/src/engine/multi-threaded-engine/index.ts, packages/server-wallet/src/engine/multi-threaded-engine/manager.ts, packages/server-wallet/src/engine/multi-threaded-engine/worker.ts, packages/server-wallet/src/engine/types.ts, packages/server-wallet/src/objectives/types.ts
Removes the `ChannelUpdated` event from the engine and thus stops the `engine` from being an `EventEmitter`.
This means the `engine` is a simple request/response model that is much easier to deal with.
This causes the directly funded chain test to fail, so it has been skipped for now and will be re-enabled after the chain service is removed from the engine. (See https://github.com/statechannels/statechannels/issues/3548, https://github.com/statechannels/statechannels/issues/3549 )
---
=> Remove all events from engine

packages/nitro-protocol/test/contracts/NitroAdjudicator/concludePushOutcomeAndTransferAll.test.ts
I'm seeing this flickering a bit, citing timeout. Possibly as side effect of #3560
=> increase timeout for concludePushOutcomeAndTransferAll

packages/nitro-protocol/contracts/ForceMove.sol, packages/nitro-protocol/gas-benchmarks/gas.ts
Our docs state that the maximum length of the participants array is 255, but our  runtime check is actually that the length of the participants array is less than 255. It should check that the length is less than or equal to 255.
This PR fixes the check.
=> Fix check on maximum number of participants

packages/nitro-protocol/package.json
They are the shortest tests, and the easiest to break.
=> fail earlier by running gas benchmarks first

packages/nitro-protocol/gas-benchmarks/benchmark.test.ts, packages/nitro-protocol/gas-benchmarks/vanillaSetup.ts
The current gas benchmark test file:
1. is quite repetitive with converting to/from BigNumbers and awaiting transactions to be mined
2. doesn't give you a hint about what to do in the case of a test failure (you should fix the expectation, and not the test, in many cases)
3. won't be that easy to change to a "fuzzy" check which doesn't require strict equality
A custom matcher can:
*  DRY out the code, and provide a single place to fuzzify the expectation if we want to later on
* provide a custom message, including context-specific hints
1.  adds a custom matcher, following [the documentation for jest.](https://jestjs.io/docs/expect#async-matchers)
2. uses that matcher in the benchmark test file
Existing test continue to pass.  A manual mutation confirms the new message pops up as …
=> Add a toConsumeGas jest matcher

packages/nitro-protocol/gas-benchmarks/vanillaSetup.ts
This is a quick addition to the `toConsumeGas` error matcher that saves us the trouble of reading large numbers and trying to compare them.
I've tested the behaviour of this locally. It:
- prints with expected formatting
- has the correct sign
---
=> Add a diff indicator (+/- X) to error message of toConsumeGas

packages/nitro-protocol/contracts/AssetHolder.sol, packages/nitro-protocol/gas-benchmarks/benchmark.test.ts, packages/nitro-protocol/gas-benchmarks/fixtures.ts, packages/nitro-protocol/gas-benchmarks/gas.ts
adds a case for a happy exit with ETH, and one for ERC20 tokens. Follow on work from #3544.
Non-essential Changes:
~Includes #3571~
=> More gas benchmarking

.circleci/config.yml, packages/nitro-protocol/deployment/deploy-test-contracts.ts, packages/nitro-protocol/test/contracts/AssetHolder/claim.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/claimAll.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transfer.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts, packages/nitro-protocol/test/contracts/ERC20AssetHolder/deposit.test.ts, packages/nitro-protocol/test/contracts/ETHAssetHolder/deposit.test.ts, packages/nitro-protocol/test/contracts/ForceMove/challenge.test.ts, packages/nitro-protocol/test/contracts/ForceMove/conclude.test.ts, packages/nitro-protocol/test/contracts/ForceMove/respond.test.ts, packages/nitro-protocol/test/contracts/NitroAdjudicator/concludePushOutcomeAndTransferAll.test.ts, packages/nitro-protocol/test/test-helpers.ts
[See this pitch.](https://www.notion.so/statechannels/Improved-gas-benchmarking-in-nitro-protocol-d14938f9671a48588e6974462e9ffb00)
We now have an entirely new and improved method of recording gas consumption  (see #3544). 
This PR removes the legacy code we were using to measure gas usage. It should
* reduce test duration 
* discourage use of the legacy method and therefore encourage use of the new method
* stop cluttering dev's laptops with data that is never cleaned up 🗑️
=> [nitro-protocol] Remove writeGasConsumption helper

.circleci/config.yml, packages/server-wallet/jest/chain-setup.ts, packages/server-wallet/jest/jest.chain.config.js, packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/wallet/wallet.ts
**based on top of #3564 and #3555** 
Adds a very basic test that ensures direct funding works between two wallets using a chain service running against a real ganache.
Currently, the test creates and then closes a channel. It ensures that the wallet promises resolve successfully and that the funds on ganache get updated correctly.
=> PR3: Direct funding test using chain and two wallets

packages/nitro-protocol/gas-benchmarks/vanillaSetup.ts, packages/nitro-protocol/package.json
At the top level of the monorepo, we thread the `--max-warnings=0` flag down to the `yarn lint:check` script.
This usually forces us to tidy up lint warnings (unused variables, etc). However, if `yarn lint:check = eslint && something else`, the flag never gets to the eslint bit where it is needed. 
I think we probably ought to be writing the flag into each package. Here's a step in that direction with nitro-protocol.
=> fix some eslint settings and warnings

.circleci/config.yml
Should result in cache hits on circle (during `yarn install`) which haven't been happening in a while...
Rerunning circle on this branch brought the `prepare` step down from 5m46 to 2m45 (!)
=> Bump cache and add missing path

packages/interop-tests/src/__test__/interop.test.ts, packages/interop-tests/src/message-service.ts
Fixes #3592.
Update the interop tests to use a server wallet and message service. This allows us to re-enable these tests.
=> Re-enable interop test

.circleci/config.yml, package.json, packages/browser-wallet/package.json, packages/client-api-schema/package.json, packages/devtools/package.json, packages/jest-gas-reporter/package.json, packages/nitro-protocol/.gitignore, packages/nitro-protocol/gas-benchmarks/vanillaSetup.ts, packages/nitro-protocol/hardhat.config.ts, packages/nitro-protocol/package.json, packages/server-wallet/package.json, packages/wallet-core/package.json, packages/wire-format/package.json, yarn.lock
https://www.notion.so/statechannels/Add-TypeChain-tooling-f17342226cb44244be4820b9937c9fae
This PR brings us to a state where we can do this: 
I didn't spread the types around the codebase much, yet. For now I just used them in the gas benchmarking test. We can do more of that kind of thing in future PRs.
=> Add typechain to nitro-protocol

packages/nitro-protocol/gas-benchmarks/benchmark.test.ts, packages/nitro-protocol/gas-benchmarks/fixtures.ts, packages/nitro-protocol/gas-benchmarks/gas.ts
Follows the established benchmarking patterns. introduces a ledger channel funding the channel in question. Both are challenged and the money is pushed down from L to X and then out. (The scenario being that the counter-party goes offline).
=> Benchmark sad defunding of a ledger-funded channel

packages/nitro-protocol/gas-benchmarks/benchmark.test.ts, packages/nitro-protocol/gas-benchmarks/fixtures.ts, packages/nitro-protocol/gas-benchmarks/gas.ts
Follows on from #3601.
* adds a benchmark for a virtually funded channel
* improves the inline diagrams a bit and replicates them in actual test script
* introduces a `TestChannel` class which helps DRY out the fixtures somewhat
When this PR is merged, we can consider this [associated pitch](https://www.notion.so/statechannels/Improved-gas-benchmarking-in-nitro-protocol-d14938f9671a48588e6974462e9ffb00) as completed.
=> benchmark sad path for exiting a virtually-funded channel

packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts, packages/server-wallet/src/wallet/types.ts, packages/server-wallet/src/wallet/wallet.ts, packages/wallet-core/src/types.ts
Fixes #3504 
Adds an update channel method to the `wallet`. The directly funded channel test has been updated to call `updateChannel`.
Due to #3600 validate transition fails when there is no `bytecode` provided.  The directly funded test has been updated to use the `COUNTING_APP` to get around this. This also means once #3576 is resolved we'll be validating the transition with the evm.
=> Add "Update Channel" to wallet API

packages/nitro-protocol/contracts/AssetHolder.sol, packages/nitro-protocol/contracts/NitroAdjudicator.sol, packages/nitro-protocol/contracts/Outcome.sol, packages/nitro-protocol/contracts/examples/EmbeddedApplication.sol, packages/nitro-protocol/contracts/examples/HashLockedSwap.sol, packages/nitro-protocol/contracts/examples/SingleAssetPayments.sol, packages/nitro-protocol/gas-benchmarks/gas.ts
This is unnecessary.
The change also saves a tiny bit of gas.
=> [nitro-protocol] Do not cast enum type to uint8

packages/docs-website/docs/docs/protocol-tutorial/understand-adjudicator-status.md
This is a hangover from an old terminology we no longer use,
and is inaccurate / confusing.
=> [docs-website] remove mention of "thumbprint"

packages/nitro-protocol/gas-benchmarks/benchmark.test.ts, packages/nitro-protocol/gas-benchmarks/fixtures.ts, packages/nitro-protocol/gas-benchmarks/gas.ts, packages/nitro-protocol/gas-benchmarks/vanillaSetup.ts, packages/nitro-protocol/src/transactions.ts
...to reflect removal of pushOutcome. 
This PR shows off the new flows enabled by the new architecture. 
It also shows off the fact that the new implementation is not gas optimised; although we still get some gas savings by removing `pushOutcome` I expect there is quite a lot of room for improvement in future PRs. 
⚠️ base not master. 
Expected to pass:
* `yarn contract:compile` in nitro-protocol
* `yarn test:gas` in nitro-protocol
Expected to fail
* everything else
=> update gas benchmarking code

packages/nitro-protocol/test/contracts/MultiAssetHolder/computeNewAllocation.test.ts, packages/nitro-protocol/test/contracts/MultiAssetHolder/computeNewAllocationWithGuarantee.test.ts, packages/nitro-protocol/test/contracts/MultiAssetHolder/isExternalDestination.test.ts, packages/nitro-protocol/test/src/contract/multi-asset-holder.test.ts
This is just a simple change so that the existing test suite can run against the new architecture.
=> point AssetHolder tests at MultiAssetHolder

packages/interop-tests/src/message-service.ts, packages/server-wallet/package.json, packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/__chain-test__/socket-io-directly-funded-channel.test.ts, packages/server-wallet/src/message-service/legacy-test-message-service.ts, packages/server-wallet/src/message-service/socket-io-message-service.ts, packages/server-wallet/src/message-service/test-message-service.ts, packages/server-wallet/src/message-service/types.ts, packages/server-wallet/src/wallet/wallet.ts, yarn.lock
Fixes #3616
This implements a basic but viable message service that can be used by the server wallet to communicate.
It uses the socket.io library to communicate. The socket.IO library defaults to webSocket and falls back to http long polling if that doesn't work.
Unlike the `TestMessageService` it can work between processes or servers.
Currently, peer registry is pretty rudimentary. I've added a `registerPeerMessageService` method to the `wallet` that can be used to register a url for a peer message service. Right now the method accepts a `peerUrl:string` but that may be limiting in the future (if we want to use a more complex addressing system than a `string`).
=> Implement Message Service that can work between servers

packages/server-wallet/src/engine/store.ts
Previously the store would only set the logger if `timingMetrics` were enabled. Otherwise, it defaulted to a logger that outputted to the console. This means that it would log out to the console instead of using the logger provided from the wallet/engine.
Now the store properly sets the logger if one is provided. This gets rid of those annoying "missing bytecode" console logs that we see all the time.
=> Stop store from always logging to console

packages/nitro-protocol/contracts/MultiAssetHolder.sol, packages/nitro-protocol/contracts/NitroAdjudicator.sol, packages/nitro-protocol/gas-benchmarks/gas.ts, packages/nitro-protocol/test/contracts/NitroAdjudicator/transferAllAssets.test.ts
The existing implementation of this function calls into an "outer" `transfer` function in a loop. This is inefficient because for every asset
* indices are checked for validity (monotonically increasing) unnecessarily
* events are emitted
* storage is checked and written to
This PR has the function in question call in to the inner `_transfer` function in the loop, and then has the requisite checks and writes to storage performed once before/after the loop.
~The commit history will show that~ I flirted with deleting the `statusOf` storage variable as a further optimisation, but decided against doing that now (see #3394).
=> gas optimise `transferAllAssets`

packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/db/migrations/20201014174041_ledgers.ts, packages/server-wallet/src/db/migrations/20201027090001_channels_indexes.ts, packages/server-wallet/src/engine/__test__/fixtures/test-channel.ts, packages/server-wallet/src/engine/__test__/integration/create-ledger-channel.test.ts, packages/server-wallet/src/engine/__test__/integration/join-channel.test.ts, packages/server-wallet/src/engine/engine.ts, packages/server-wallet/src/engine/store.ts, packages/server-wallet/src/models/__test__/fixtures/channel.ts, packages/server-wallet/src/models/channel.ts
Our server wallet database schema has a `channels` table with an `assetHolderAddress` column.  This is currently only used for flagging when a channel is a ledger channel.  This is needlessly indirect and potentially confusing, as well as making refactoring the contract architecture difficult (what if there aren't any asset holders). 
This approach is good because the new column name and data type more accurately reflect the semantic meaning of the information being stored. It also makes #3624 easier to achieve. 
There's one point of contention, which is the way I have updated the db migrations here. I have just edited an existing migration file rather than adding a new migration to rename the column name. I figured this was preferable because we have no DBs in production right now, and …
=> swap `assetHolderAddress` column for `isLedgerChannel` column in channels table

packages/nitro-protocol/contracts/MultiAssetHolder.sol, packages/nitro-protocol/gas-benchmarks/gas.ts
This was spotted by Andrew and is similar to the previous PR.
Notable:
- this change **only** had effects on the deploy gas cost. It looks like the benchmarking suite takes the `transferAllAssets` route for each case. In the happy-path it gets there via [concludeAndTransferAllAssets](https://github.com/statechannels/statechannels/blob/cfba1f6975cbdd85958254ff8abb54c9722fc351/packages/nitro-protocol/gas-benchmarks/benchmark.test.ts#L91), and [directly](https://github.com/statechannels/statechannels/blob/cfba1f6975cbdd85958254ff8abb54c9722fc351/packages/nitro-protocol/gas-benchmarks/benchmark.test.ts#L126) in the sad-path. Do we consider this a gap in the benchmarking?
- unlike the previous PR, this one re-uses the `outcomeBytes memory` function parameter, which I think in context is OK, …
=> Remove (another) duplicate abi.encode call

packages/server-wallet/deployment/deploy.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/chain-service/types.ts
These are a collection of changes that I've made to the chain service while working on testing infrastructure.
- deploy now be passed an rpc endpoint (nice for scripting)
- chain service now reads env vars when constructed (nice for scripting) 
- remove some obsolete methods from the chain service interface
=> Chain service tweaks for testing infrastructure

packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts, packages/server-wallet/src/config/types.ts, packages/server-wallet/src/config/validation.ts, packages/server-wallet/src/engine/engine.ts, packages/server-wallet/src/engine/store.ts, packages/server-wallet/src/message-service/socket-io-message-service.ts, packages/server-wallet/src/wallet/types.ts, packages/server-wallet/src/wallet/wallet.ts
These are a collection of changes that I've made to the wallet and message service while working on testing infrastructure.
- Wallet now emits a ChannelUpdated event
- Wallet accepts a private key to use to create its address (useful for testing)
- call updateFunding in the AssetOutcomeUpdated event handler so the holdings are correctly updated when closing a channel.
Happy to break these into separate PRs if needed/wanted.
=> Wallet tweaks for testing infrastructure

packages/client-api-schema/src/generated-schema.json, packages/nitro-protocol/src/contract/transaction-creators/nitro-adjudicator.ts, packages/nitro-protocol/src/transactions.ts, packages/server-wallet/src/__chain-test__/socket-io-directly-funded-channel.test.ts, packages/server-wallet/src/__test-with-peers__/create-and-close-channel/fake-funding.test.ts, packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/__chain-test__/stress.test.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/chain-service/event-tracker.ts, packages/server-wallet/src/chain-service/mock-chain-service.ts, packages/server-wallet/src/chain-service/types.ts, packages/server-wallet/src/db/migrations/20200818083933_funding.ts, packages/server-wallet/src/engine/__test__/add-signed-state.test.ts, packages/server-wallet/src/engine/__test__/fixtures/test-channel.ts, packages/server-wallet/src/engine/__test__/fixtures/update-channel.ts, packages/server-wallet/src/engine/store.ts, packages/server-wallet/src/handlers/__test__/single-app-updater.test.ts, packages/server-wallet/src/models/__test__/channel.test.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/models/funding.ts, packages/server-wallet/src/protocols/__test__/defund-channel.test.ts, packages/server-wallet/src/protocols/__test__/defunder.test.ts, packages/server-wallet/src/protocols/defunder.ts, packages/server-wallet/src/protocols/direct-funder.ts, packages/server-wallet/src/protocols/state.ts, packages/server-wallet/src/wallet/wallet.ts
Tests that pass on this branch:
`chain-service.test.ts` ( but only if `yarn link @statechannels/native-utils` against https://github.com/statechannels/native-utils/pull/26 )
`stress.test.ts` (confirmed manually, it doesn't run by default)
=> update chain service to not use asset holders or pushoutcome

packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/__test-with-peers__/utils.ts, packages/server-wallet/src/__test-with-peers__/wallet/create-ledger-channel.test.ts, packages/server-wallet/src/engine/engine.ts, packages/server-wallet/src/wallet/wallet.ts
Fixes #3656 
Adds CreateLedgerChannel to the wallet API. 
Essentially we're exposing the existing CreateLedgerChannel on the engine via the wallet.
=> Add the CreateLedger channel to the Wallet API

packages/server-wallet/e2e-testing/scripts/load-generator.ts, packages/server-wallet/e2e-testing/test-data/load-data.json
Fixes #3661 
Implements some saner options for the load generator.  Update steps have been removed to keep things simpler.
The new options:
- duration:  Roughly how long test will run for
- createRate: how many channels should be created (per second)
- closeRate: how many channels should be closed (per second). If set to 0 no channels are closed.
- closeDelay: The miminum amount of time to wait after a channel has been created before scheduling a close step.
=> Clean up load-generator timing options

packages/nitro-protocol/test/contracts/ForceMove/_validSignatures.test.ts
This test consistently fails due to timeout on at least one dev machine (mine!) with tests run in parallel (`yarn test`), but succeeds as is when run independently (eg: `yarn test _validSignatures`).
With this timeout config removed, the test is still constrained by the global timeout config of 90 seconds.
Incremental adjustments to the timeout (20 seconds, 30 seconds, 40 seconds) resulted in fewer and less predictable errors but failing tests nonetheless.
Relaxing the timeout constraint makes the feedback from a successful test run less informative.
Alternatively, the test suite could be adjusted to run tests sequentially by default. This slows the test suite runs substantially.
---
=> remove timeout configuration

packages/nitro-protocol/contracts/MultiAssetHolder.sol, packages/nitro-protocol/gas-benchmarks/gas.ts, packages/nitro-protocol/test/contracts/MultiAssetHolder/claim.test.ts, packages/nitro-protocol/test/contracts/MultiAssetHolder/computeNewAllocationWithGuarantee.test.ts
This PR closes #3672. The problem is described in some detail in the issue thread, and summarized here:
> [the] issue is that there are **no checks in place** to confirm that the target channel's outcome[assetIndex] refers to the same determined asset as the guarantee, which opens up a potential attack vector where, say, a guarantee of USDT tokens is used to update the ETH allocation on a target channel.
Changes here include
- a test case in `claim.test.ts` which constructs a guarantee on the asset address for USDT and attempts to apply this guarantee to a target channel with ETH at the same index of its outcome. The test case is expected to revert (we should not be able to trade USDT for ETH!), but did not.
- the addition of a check on asset addresses of guarantees and target channel …
=> Check guarantee and target outcome assets match

packages/nitro-protocol/test/contracts/NitroAdjudicator/concludeAndTransferAllAssets.test.ts
this might prevent a test flicker we are seeing Flickering test [nitro-protocol/concludeAndTransferAllAssets] #3682
=> set gas limit explicitly

packages/nitro-protocol/test/contracts/MultiAssetHolder/claim.test.ts, packages/nitro-protocol/test/contracts/MultiAssetHolder/transfer.test.ts, packages/nitro-protocol/test/test-helpers.ts
(Rewrite of the commit history of #3687 , originally authored by @andrewgordstewart )
The affected test helpers do not require knowing the private key corresponding to the signing address that generates:
the destination; or
the channel id
When this is the case, it's much faster to generate a random hex string. Creating an ethers wallet is already slow; doing so in a jest environment is very slow (I believe it takes on the order of 100ms.)
=> More performant random channel/destination generation

packages/server-wallet/e2e-testing/scripts/load-generator.ts, packages/server-wallet/e2e-testing/scripts/start-all.ts, packages/server-wallet/e2e-testing/scripts/start-load-node.ts, packages/server-wallet/e2e-testing/test-data/load-data.json, packages/server-wallet/e2e-testing/test-data/sample-direct-load-data.json, packages/server-wallet/e2e-testing/test-data/sample-ledger-load-data.json, packages/server-wallet/e2e-testing/types.ts, packages/server-wallet/e2e-testing/wallet-load-node.ts, packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/wallet/types.ts, packages/server-wallet/src/wallet/wallet.ts
Fixes #3657
The load generator and load node now support ledger-funded channels.
The load generator has some new options.
- `--fundingStrategy`: Either direct or ledger
- `--createLedgerDuration`:  The amount of time ledger channels will be created for. If `createLedgerDuration==duration` then ledger channels will constantly be created. If `createLedgerDuration < duration` ledger channels only get created for the first `createLedgerDuration`.
- `--ledgerDelay`: The amount of time to wait before attempting to use a ledger channel for funding. This is used to allow time for the ledger channels to be directly funded.
- `--ledgerRate`: How many ledger channels per second to create.
The basic load generator flow :
- we create `createLedgerDuration*ledgerRate`of CreateLedger steps.
- For each …
=> Add test infrastructure for testing ledger funded channels

packages/server-wallet/jest/with-peers-setup-teardown.ts, packages/server-wallet/src/__test-with-peers__/wallet/jumpstart.test.ts
Three minor changes:
- Truncate databases after trying to create them. Previously the first test that would run would fail to truncate the databases as they did not exist yet.
- Fix an accidentally large timeout value
- increase the poll time for syncing as checking for stale objectives every `50ms` seems a little overboard.
=> Minor With Peers Test Tweaks

packages/server-wallet/src/engine/__test__/sync-objectives.test.ts, packages/server-wallet/src/engine/engine.ts
Fixes #3583  (maybe?)
When syncing an OpenChannel Objective we now sync the funding ledger channel as well.
Previously syncObjective method would only send the **app** channel to peers and not **ledger** channels. This meant that if the initial message containing the ledger channel was dropped no amount of syncing would complete the objective.
I believe this explains the flickering tests. We have a test scenario using `{dropRate:0.1}` which means 10% of messages should be dropped. If the first message happens to be dropped then the test was doomed to fail, since syncing wouldn't include the ledger info.
=> Sync Ledger Channels for OpenChannel Objective

packages/wallet-core/package.json
Things like this are difficult to spot in a `yarn` monorepo -- that is, until someone tries to use one of our packages by installing from npm.
I discovered this while experimenting with pinning dependants of nitro-protocol to a version published to npm.
=> add missing dependency

packages/nitro-protocol/src/index.ts, packages/server-wallet/src/chain-service/chain-service.ts
I think this will fix #3717.
I would like to have a way of testing or linting for this problem in future. Something like https://www.npmjs.com/package/eslint-plugin-monorepo although this didn't pick up this issue when I tried it.
=> import/export computeNewOutcome thru entry point

packages/server-wallet/e2e-testing/wallet-load-node.ts
Fixes #3722 
If the node wasn't assigned any create ledger steps it would log that direct funding was being used. We now check for the presence of a create ledger step for any serverId to avoid this.
=> Fix Funding Typo

packages/server-wallet/src/chain-service/chain-service.ts
Read the `process.env.NITRO_ADJUDICATOR_ADDRESS` var when constructing the `chainService` instead of when the chain servic file is loaded.
This is to make testing more convenient. Previously you could inadvertently load the file before you had a chance to set `process.env.NITRO_ADJUDICATOR_ADDRESS` resulting in the `chain-service` using a `0x0000...`.
I ran into this with the stress test as the LoadNodes have references to the `ServerWallet` which has a reference to `ChainService`. This meant that `nitroAdjudicatorAddress` got set as soon as the LoadNode file was loaded before we had a chance to set the `process.env` vars.
=> Chain Service reads process.env.NITRO_ADJUDICATOR_ADDRESS when constructed

packages/nitro-protocol/contracts/MultiAssetHolder.sol, packages/nitro-protocol/contracts/interfaces/IMultiAssetHolder.sol
I have had to use some tricks to avoid[ `stack too deep`. ](https://soliditydeveloper.com/stacktoodeep)
Notably, block scoping and the use of a new struct `ClaimArgs` to reduce the number of variables on the stack. 
See #3683
=> add claim implementation

packages/server-wallet/e2e-testing/scripts/load-generator.ts
Instead of using `ledgerRate` and `createLedgerDuration` arguments, the load-generator takes a `amountOfLedgerChannels`. 
CreateLedgerChannel steps will be scheduled in the first 5 seconds regardless of the duration. 
This makes the load-generator slightly more straightforward to use. I've also tried to clean up the argument descriptions so they're more understandable.
=> Simplify Load Generator arguments

packages/nitro-protocol/contracts/MultiAssetHolder.sol, packages/nitro-protocol/test/contracts/MultiAssetHolder/claim.test.ts
Marked draft because alterations to `computeNewOutcomeWithGuarantee.test.ts` (and `deposit.test.ts`?) are still incoming.
=> Integrate exit format claim tests

packages/nitro-protocol/gas-benchmarks/benchmark.test.ts, packages/nitro-protocol/gas-benchmarks/fixtures.ts
to gas benchmarks.
Buy calling this function at judicious moments during the benchmarking script,
we can be sure the script achieves the defined goal of moving money through a network of channels to Alice
=> add an assertEthBalancesAndHoldings fn

packages/nitro-protocol/contracts/MultiAssetHolder.sol, packages/nitro-protocol/gas-benchmarks/gas.ts, packages/nitro-protocol/src/contract/multi-asset-holder.ts, packages/nitro-protocol/test/contracts/MultiAssetHolder/claim.test.ts, packages/nitro-protocol/test/contracts/MultiAssetHolder/computeNewAllocationWithGuarantee.test.ts
The `claim` function uses an array called `payouts` (internally) to build up payouts for each of the destinations in the target channel at the supplied `indices`. We are not currently updating this array correctly in general: particularly in the case where the `guarantee` has an entry that is absent from the target outcome. Essentially, a different party gets the funds that should go to their rightful owner.
Example: We are claiming a guarantee of `[A,I,x]` (funded with `10`) targeting an outcome of `{x:10,I:10}` with `indices=[]` signalling our wish to claim all of the target allocations. `I` should be paid 10 and `x` should not be paid anything. Instead, `x` is paid `10` and `I` is not paid anything. The problem with the current implementation is that inside …
=> fix claim.test.ts and remove payouts from computeNewAllocationWithGuarantee in order to fix critical bug

packages/nitro-protocol/gas-benchmarks/fixtures.ts, packages/nitro-protocol/gas-benchmarks/gas.ts
This is failing on master currently, because we merged 
1.  extra assertions about the movement of money during the benchmark script, which passed CI because the (then) 
a) buggy claim implementation AND 
b) the incorrect guarantee order
interacted (accidentally) to make the money move as intended
2. a fix to the buggy claim implementation
In separate PRs. The second was not rebased or brought up to date with master before being merged. 
This PR fixes 1b to restore balance to the galaxy. 
The "correct" order for a guarantee in the virtual funding protocol must have the intermediary as the lowest priority, because they can recover their funds via a pair of guarantees. Alice and Bob have only the one guarantee to claim on, so must each have a higher priority than Ingrid (including when they …
=> fix guarantee order in gas benchmark fixtures

packages/wire-format/src/__tests__/good_sample_messages.ts, packages/wire-format/src/generated-schema.json, packages/wire-format/src/types.ts
The wire format consists of typescript types, a json schema and validator functions for messages sent between nitro wallets. 
It is necessary to update the package if we want wallets to work with the exit format, since they need to pass messages (for signing by counterparties) that can eventually be submitted to chain.
The approach taken here is:
*  ensure the new `metadata` and `allocationType` fields are present and correct, as well as
*  renaming `allocationItems` to `allocations` (as per the exit format). 
* I have removed the `Guarantee` outcome type, since this is now just an allocation with certain metadata. 
* I have also removed the `Allocation(s)` type as this collides with new types coming out of exit format. It is also unnecessary given the removal of `Guarantee` type.
* …
=> Update wire-format to comply with exit-format

packages/nitro-protocol/gas-benchmarks/gas.ts, packages/nitro-protocol/gas-benchmarks/vanillaSetup.ts
This PR offers readability improvement on `gas.ts` and on test output, via:
- snake_cased inputs and outputs of large numbers (`34_254`)
- colour-coded test output for happpy (green) and sad (red) changes to gas consumption
- adding a percentage to the reported difference of gas consumption
the text colouring functions are gnarly low-level bash stuff which may not behave as expected in all environments, and whose workings are not obvious at a glance. Works on my machine!
against manual manipulations of the values in `gas.ts`
No
---
=> Small improvements to gas-benchmark tests

packages/docs-website/docs/docs/server-app-devs/quick-start-contracts.md
Fix small typo in `quick-start-contracts.md`.
Replaced `stae` by `state`.
---
=> fix typo in quick-start-contracts.md
