statechannels/statechannels

.circleci/config.yml, packages/web3torrent/package.json
=> [ci] Adds CircleCI configuration

packages/web3torrent/package.json, yarn.lock
This PR fixes a TypeScript build error for the `web3torrent` React App.
Fixes #8.
=> [web3torrent] Fixes build process

.prettierrc, packages/web3torrent/package.json, packages/web3torrent/src/index.tsx, packages/web3torrent/src/types.ts, tslint.json, yarn.lock
=> [monorepo] Adds .prettierrc and some minor rule requirements

packages/jest-gas-reporter/src/index.ts
Previously, the gas reporter would result in unhandled rejections, and
jest returning exit code 0 even when tests failed.
=> Properly handle errors in GasReporter

.circleci/config.yml
We are running into memory issues on #49, this splits the jobs up and perhaps will help with memory limits.
=> Split jobs on CircleCI into build,lint,test

packages/nitro-protocol/docs/nitro-intro.md
Fix grammar/spelling of solidity -> Solidity
=> [docs] fix: Grammar - solidity -> Solidity

yarn.lock
Running `yarn` on a fresh clone of the repo yielded an updated lockfile.
=> Run yarn -- updates yarn.lock

.circleci/config.yml
Most utilities for monitoring memory will read from data related
to the physical computer running our docker container.
This explains the seemingly low memory usage in the current artifacts.
See https://shuheikagawa.com/blog/2017/05/27/memory-usage/
> Yay! You're creating a new PR. Keep in mind these guidelines:
>
> - Set the title following this convention:
>
>   [feature-group][change-summary]
>
>   where:
>
>   - `feature-group` represents either a monorepo package, or other features such as "documentation" or "lint".
>   - `change-summary` is a one-sentence version of the PR description.
>
> - Tag the PR appropriately:
>   - If you're early-opening a PR in do further work on it, create it as a Draft Pull Request.
>   - If it belongs to a package, use the corresponding label (i.e. …
=> Fix memory usage logging in circle config

renovate.json
Group non-major dependency updates in a single PR
https://docs.renovatebot.com/presets-group/#groupallnonmajor
=> Reconfigure renovate groups

packages/nitro-protocol/docs/adjudicator/state-format.md, packages/nitro-protocol/docs/quick-start.md
=> [documenation] Tweaks to the quick-start and state-format docs.

packages/nitro-protocol/.gitignore
=> Ignore .outputParameter

.circleci/config.yml, package.json, packages/embedded-wallet/package.json, packages/jest-gas-reporter/package.json, packages/nitro-protocol/package.json, packages/wallet/package.json, packages/wallet/src/contract-tests/adjudicator-events.test.ts, packages/web3torrent/package.json, yarn.lock
Seems unnecessary to be linting on the CI and every time we run a test script.
I think it might be wiser to make linting a pre-commit hook instead.
=> Remove linting from test scripts.

packages/embedded-wallet/external-app/index.html, packages/embedded-wallet/src/app/App.tsx, packages/embedded-wallet/src/message-handlers/connect-to-hub/ConnectToHub.tsx, packages/embedded-wallet/src/message-handlers/index.ts, packages/embedded-wallet/src/ui/animations.css, packages/embedded-wallet/src/ui/dialog/Dialog.tsx, packages/embedded-wallet/src/ui/flow-process/FlowProcess.tsx, packages/embedded-wallet/src/ui/flow-process/FlowStep.module.css, packages/embedded-wallet/src/ui/flow-process/FlowStep.tsx, packages/embedded-wallet/src/ui/index.ts, packages/embedded-wallet/src/ui/spinner/Spinner.module.css, packages/embedded-wallet/src/ui/spinner/Spinner.tsx
Resolves #79.
Also adds:
- a new `Spinner` component
- a new `FlowProcess` component
=> [embedded-wallet] Implements "Connect to Hub" screen

package.json, packages/embedded-wallet/README.md
=> [embedded-wallet] Adds README

packages/wallet/src/contract-tests/test-utils.ts, packages/wallet/src/contract-tests/transactions.test.ts, packages/wallet/src/redux/protocols/dispute/responder/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/dispute/responder/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/dispute/responder/reducer.ts, packages/wallet/src/utils/transaction-generator.ts
Adds calls to `checkpoint` and tests pass
=> Support refute transactions

packages/wallet/src/redux/protocols/dispute/responder/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/dispute/responder/reducer.ts, packages/wallet/src/utils/transaction-generator.ts
Some changes weren't linted for some reason I did not explore fully.
=> Apply yarn lint:write to repo

packages/jest-gas-reporter/.prettierrc.js, packages/jest-gas-reporter/src/index.ts
Standardize linting on this package.
=> Apply yarn lint:write to jest-gas-reporter

packages/nitro-protocol/contracts/CounterfactualAdapterApp.sol, packages/nitro-protocol/package.json, yarn.lock
This is basically just a proof of concept of how `CounterfactualApp`s can be used in this framework.
=> Add CounterfactualAdapterApp

packages/nitro-protocol/contracts/ForceMove.sol, packages/nitro-protocol/contracts/interfaces/IForceMove.sol, packages/nitro-protocol/src/contract/challenge.ts, packages/nitro-protocol/src/contract/state.ts, packages/wallet/src/contract-tests/adjudicator-events.test.ts, packages/wallet/src/redux/actions.ts, packages/wallet/src/redux/adjudicator-state/__tests__/reducer.test.ts, packages/wallet/src/redux/adjudicator-state/state.ts, packages/wallet/src/redux/sagas/adjudicator-watcher.ts, packages/wallet/src/redux/sagas/challenge-response-initiator.ts
Assuming you were genuinely offline, you will need this information to respond.
=> Include signature in AdjudicatorState when challenge arises

package.json, packages/embedded-wallet/public/wallet.js, packages/web3torrent/public/index.html, packages/web3torrent/src/pages/download/Download.tsx, packages/web3torrent/src/types.ts
We did it!
This adds the complete downloading flow.
[Demo!](https://drive.google.com/open?id=1TZVN8zpfVUMsp7cfuTFXGtTuOWtI6zfA)
closes #150
=> [Web3torrent] [Embedded Wallet] integration

packages/embedded-wallet/package.json, packages/embedded-wallet/src/ui/button/Button.test.tsx, packages/embedded-wallet/src/ui/button/Button.tsx, packages/embedded-wallet/src/ui/dialog/Dialog.test.tsx, packages/embedded-wallet/src/ui/dialog/Dialog.tsx, packages/embedded-wallet/src/ui/flow-process/FlowProcess.test.tsx, packages/embedded-wallet/src/ui/flow-process/FlowStep.test.tsx, packages/embedded-wallet/src/ui/icon/Icon.test.tsx, packages/embedded-wallet/src/ui/icon/Icon.tsx, packages/embedded-wallet/src/ui/slider/Slider.test.tsx, packages/embedded-wallet/src/ui/slider/Slider.tsx, packages/embedded-wallet/src/ui/spinner/Spinner.test.tsx, yarn.lock
This PR adds a basic unit test suite for all components under the `ui` directory.
Contributes to #199.
=> [embedded-wallet] Adds unit tests to all generic UI components

packages/embedded-wallet/src/dialogs/budget-allocation/BudgetAllocation.tsx, packages/embedded-wallet/src/dialogs/no-hub/NoHub.tsx, packages/embedded-wallet/src/json-rpc-router/JsonRpcRoute.tsx, packages/embedded-wallet/src/ui/button/Button.tsx, packages/embedded-wallet/src/ui/dialog/Dialog.tsx
=> [embedded-wallet] Replaces [] with null on JSX

packages/embedded-wallet/src/json-rpc-router/JsonRpcRouter.test.tsx
=> [embedded-wallet] Adds JsonRpcRouter unit tests

packages/embedded-wallet/src/flow-router/FlowRouter.test.tsx
=> [embedded-wallet] Adds tests for FlowRouter

packages/embedded-wallet/src/message-dispatchers/allocate/allocate.test.ts, packages/embedded-wallet/src/message-dispatchers/close-wallet/close-wallet.test.ts
=> [embedded-wallet] Adds unit tests for message dispatchers

packages/embedded-wallet/src/dialogs/budget-allocation/BudgetAllocation.tsx, packages/embedded-wallet/src/dialogs/connect-to-hub/ConnectToHub.tsx, packages/embedded-wallet/src/dialogs/no-hub/NoHub.tsx, packages/embedded-wallet/src/flows/onboarding/Onboarding.test.tsx, packages/embedded-wallet/src/flows/onboarding/Onboarding.tsx
=> [embedded-wallet] Added onboarding flow tests

packages/embedded-wallet/src/dialogs/budget-allocation/BudgetAllocation.test.tsx, packages/embedded-wallet/src/dialogs/budget-allocation/BudgetAllocation.tsx
=> [embedded-wallet] Adds tests for Budget Allocation screen

packages/embedded-wallet/src/dialogs/no-hub/NoHub.test.tsx
=> [embedded-wallet] Adds tests for No Hub screen

packages/embedded-wallet/src/dialogs/connect-to-hub/ConnectToHub.test.tsx, packages/embedded-wallet/src/dialogs/connect-to-hub/ConnectToHub.tsx
Adds the last suite of unit tests.
Resolves #199.
=> [embedded-wallet] Adds tests for "Connect to Hub" screen

packages/embedded-wallet/package.json
=> [embedded-wallet] Adds yarn script to run coverage analysis

packages/web3torrent/src/clients/web3torrent-client.ts, packages/web3torrent/src/components/torrent-info/TorrentInfo.tsx, packages/web3torrent/src/components/torrent-info/download-info/DownloadInfo.tsx, packages/web3torrent/src/constants.ts, packages/web3torrent/src/library/types.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/pages/download/Download.tsx, packages/web3torrent/src/pages/upload/Upload.tsx, packages/web3torrent/src/types.ts, packages/web3torrent/src/utils/magnet.ts, packages/web3torrent/src/utils/torrent-status-checker.ts, packages/web3torrent/tests/client-seeding.test.ts
This PR completes the flow between Web3Torrent and Embedded Wallet with real torrents and files.
[DEMO TIME!](https://drive.google.com/open?id=1ZRco_6EoDpwdqDB3Cj-mfmKVjEmuN4uZ)
It also:
closes #218
closes #216
=> [Web3torrent][Embedded Wallet]  Refactor & Improved integration

packages/web3torrent/package.json, packages/web3torrent/src/components/torrent-info/TorrentInfo.test.tsx, packages/web3torrent/src/components/torrent-info/TorrentInfo.tsx, packages/web3torrent/src/components/torrent-info/upload-info/UploadInfo.tsx, packages/web3torrent/src/library/types.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/utils/test-utils.ts
Contributes to #215.
Added some `@todo` tags for further discussion.
=> [web3torrent] Adds tests for TorrentInfo and MagnetLinkButton

packages/web3torrent/src/components/torrent-info/download-info/DownloadInfo.test.tsx, packages/web3torrent/src/components/torrent-info/download-info/DownloadInfo.tsx, packages/web3torrent/src/utils/torrent-status-checker.ts
=> [web3torrent] Adds DownloadInfo tests

packages/web3torrent/src/components/torrent-info/download-info/progress-bar/ProgressBar.test.tsx
=> [web3torrent] Adds tests for ProgressBar

packages/web3torrent/src/utils/magnet.test.ts, packages/web3torrent/src/utils/magnet.ts
Implements unit tests for the magnetParser util functions. And refactors some edge cases that I found.
#215
=> [Web3Torrent] Add magnetParser tests

packages/web3torrent/src/clients/embedded-wallet-client.ts, packages/web3torrent/src/pages/download/Download.test.tsx, packages/web3torrent/src/pages/download/Download.tsx, packages/web3torrent/src/pages/upload/Upload.test.tsx, packages/web3torrent/src/pages/upload/Upload.tsx
Adds tests for the Upload and Download Pages, refactors the Embedded Wallet interaction functions  into a separate file, and refactors the download and upload pages code to be easier to read and test.
#215
=> [Web3torrent] Add Download and Upload Pages tests

packages/web3torrent/src/components/torrent-info/upload-info/UploadInfo.test.tsx, packages/web3torrent/src/components/torrent-info/upload-info/UploadInfo.tsx
=> [web3torrent] Adds tests for <UploadInfo />

packages/web3torrent/src/clients/embedded-wallet-client.test.ts, packages/web3torrent/src/clients/embedded-wallet-client.ts
=> [web3torrent] Add tests for EmbeddedWalletClient

packages/web3torrent/src/utils/torrent-status-checker.test.ts, packages/web3torrent/src/utils/torrent-status-checker.ts
=> [web3torrent] Adds tests for TorrentStatusChecker

packages/web3torrent/src/clients/web3torrent-client.test.ts
=> [web3torrent] Adds tests for Web3TorrentClient

packages/web3torrent/src/components/form/form-button/FormButton.tsx, packages/web3torrent/src/components/form/spinner/Spinner.scss, packages/web3torrent/src/components/form/spinner/Spinner.tsx, packages/web3torrent/src/pages/download/Download.test.tsx, packages/web3torrent/src/pages/download/Download.tsx
Contributes to #254. Resolves #256.
=> [web3torrent] Implements Spinner on "Start Download" button

packages/web3torrent/src/components/torrent-info/TorrentInfo.test.tsx, packages/web3torrent/src/components/torrent-info/TorrentInfo.tsx
=> [web3torrent] Removes references to estimated costs

packages/web3torrent/public/index.html
=> [web3torrent] Changes the app title

packages/channel-provider/package.json, packages/channel-provider/src/ui-service.ts, packages/channel-provider/tests/ui-service.test.ts
During the refactor on #282, CSS styles weren't updated, causing the bug described in #288. 
This PR resolves #288.
=> [channel-provider] Fixes bad CSS selectors

packages/web3torrent/src/pages/file/File.tsx, packages/web3torrent/src/pages/upload/Upload.tsx, packages/web3torrent/src/pages/welcome/Welcome.tsx
This PR removes any Lorem-ipsum-esque text on the app and replaces it with proper wording.
Resolves #239.
=> [web3torrent] Adds proper texts

packages/devtools/README.md, packages/nitro-protocol/readme.md, packages/nitro-protocol/website/siteConfig.js, readme.md
⚠️ base branch not master
And a few other tweaks. I expanded the scope of the work to include all PRs in the monorepo.
=> [monorepo] Improve readme by removing outdated info

packages/engine/src/redux/protocols/existing-ledger-funding/reducer.ts, packages/engine/src/redux/protocols/ledger-top-up/__tests__/reducer.test.ts, packages/engine/src/redux/protocols/ledger-top-up/__tests__/scenarios.ts, packages/engine/src/redux/protocols/ledger-top-up/reducer.ts, packages/engine/src/redux/protocols/ledger-top-up/states.ts
=> [engine] Update Ledger Top Up Protocol to use Signed States

packages/engine/src/contract-tests/eth-asset-holder-events.test.ts, packages/engine/src/domain/commitments/__tests__/index.ts, packages/engine/src/redux/protocols/funding/reducer.ts, packages/engine/src/redux/protocols/virtual-funding/__tests__/reducer.test.ts, packages/engine/src/redux/protocols/virtual-funding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/virtual-funding/readme.md, packages/engine/src/redux/protocols/virtual-funding/reducer.ts, packages/engine/src/redux/protocols/virtual-funding/states.ts, packages/engine/src/utils/data-type-utils.ts, packages/engine/src/utils/nitro-converter.ts, packages/engine/src/utils/transaction-generator.ts
Updates the virtual funding protocol to use SignedStates and Outcomes. Fixes #339.
=> [engine] Update Virtual Funding to Signed State

packages/web3torrent/.storybook/addons.js, packages/web3torrent/.storybook/config.js, packages/web3torrent/.storybook/presets.js, packages/web3torrent/package.json, packages/web3torrent/src/components/form/form-button/FormButton.stories.tsx, packages/web3torrent/src/components/form/form-button/README.md, yarn.lock
=> [web3torrent] Adds Storybook support + FormButton story

packages/web3torrent/src/components/form/spinner/README.md, packages/web3torrent/src/components/form/spinner/Spinner.stories.tsx
=> [web3torrent] Adds stories for Spinner

packages/web3torrent/src/clients/embedded-wallet-client.ts, packages/web3torrent/src/components/torrent-info/TorrentInfo.scss, packages/web3torrent/src/components/torrent-info/TorrentInfo.test.tsx, packages/web3torrent/src/components/torrent-info/TorrentInfo.tsx, packages/web3torrent/src/pages/file/File.scss, packages/web3torrent/src/pages/file/File.tsx
This PR will:
close #360 
and
close #267
=> [Web3Torrent] FileName into new row - Feedback allocation canceled

packages/engine/src/redux/protocols/close-ledger-channel/__tests__/reducer.test.ts, packages/engine/src/redux/protocols/close-ledger-channel/__tests__/scenarios.ts, packages/engine/src/redux/protocols/close-ledger-channel/readme.md, packages/engine/src/redux/protocols/close-ledger-channel/reducer.ts, packages/engine/src/redux/protocols/funding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/funding/reducer.ts, packages/engine/src/redux/protocols/reducer-helpers.ts, packages/engine/src/redux/protocols/withdrawing/__tests__/scenarios.ts
Fixes #373 , fixes #341 , fixes #348
=> [engine] Update Funding, Close Ledger, and Withdraw protocols

packages/engine/src/redux/protocols/close-ledger-channel/__tests__/reducer.test.ts, packages/engine/src/redux/protocols/close-ledger-channel/__tests__/scenarios.ts, packages/engine/src/redux/protocols/close-ledger-channel/readme.md, packages/engine/src/redux/protocols/close-ledger-channel/reducer.ts, packages/engine/src/redux/protocols/defunding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/defunding/reducer.ts, packages/engine/src/redux/protocols/funding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/funding/reducer.ts, packages/engine/src/redux/protocols/ledger-defunding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/ledger-defunding/reducer.ts, packages/engine/src/redux/protocols/reducer-helpers.ts, packages/engine/src/redux/protocols/virtual-defunding/__tests__/reducer.test.ts, packages/engine/src/redux/protocols/virtual-defunding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/virtual-defunding/reducer.ts, packages/engine/src/redux/protocols/withdrawing/__tests__/scenarios.ts
Fixes #343, fixes #344, fixes #371
=> [engine] Update various defunding protocols

packages/engine/src/redux/protocols/close-ledger-channel/__tests__/reducer.test.ts, packages/engine/src/redux/protocols/close-ledger-channel/__tests__/scenarios.ts, packages/engine/src/redux/protocols/close-ledger-channel/readme.md, packages/engine/src/redux/protocols/close-ledger-channel/reducer.ts, packages/engine/src/redux/protocols/defunding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/defunding/reducer.ts, packages/engine/src/redux/protocols/funding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/funding/reducer.ts, packages/engine/src/redux/protocols/ledger-defunding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/ledger-defunding/reducer.ts, packages/engine/src/redux/protocols/ledger-funding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/ledger-funding/reducer.ts, packages/engine/src/redux/protocols/ledger-funding/states.ts, packages/engine/src/redux/protocols/reducer-helpers.ts, packages/engine/src/redux/protocols/virtual-defunding/__tests__/reducer.test.ts, packages/engine/src/redux/protocols/virtual-defunding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/virtual-defunding/reducer.ts, packages/engine/src/redux/protocols/virtual-funding/reducer.ts, packages/engine/src/redux/protocols/withdrawing/__tests__/scenarios.ts
=> [engine] Update Ledger Funding to Signed States

packages/engine/src/redux/protocols/close-ledger-channel/__tests__/reducer.test.ts, packages/engine/src/redux/protocols/close-ledger-channel/__tests__/scenarios.ts, packages/engine/src/redux/protocols/close-ledger-channel/readme.md, packages/engine/src/redux/protocols/close-ledger-channel/reducer.ts, packages/engine/src/redux/protocols/defunding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/defunding/reducer.ts, packages/engine/src/redux/protocols/existing-ledger-funding/reducer.ts, packages/engine/src/redux/protocols/funding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/funding/reducer.ts, packages/engine/src/redux/protocols/ledger-defunding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/ledger-defunding/reducer.ts, packages/engine/src/redux/protocols/ledger-funding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/ledger-funding/reducer.ts, packages/engine/src/redux/protocols/ledger-funding/states.ts, packages/engine/src/redux/protocols/new-ledger-channel/__tests__/scenarios.ts, packages/engine/src/redux/protocols/new-ledger-channel/components/funding-step.tsx, packages/engine/src/redux/protocols/new-ledger-channel/reducer.ts, packages/engine/src/redux/protocols/reducer-helpers.ts, packages/engine/src/redux/protocols/virtual-defunding/__tests__/reducer.test.ts, packages/engine/src/redux/protocols/virtual-defunding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/virtual-defunding/reducer.ts, packages/engine/src/redux/protocols/virtual-funding/reducer.ts, packages/engine/src/redux/protocols/withdrawing/__tests__/scenarios.ts, packages/engine/src/utils/outcome-utils.ts
=> [engine] Update New Ledger Funding Protocol to Signed States

packages/nitro-protocol/package.json, packages/nitro-protocol/src/signatures.ts
⚠️ base not master
Use ethers instead.
=> [nitro-protocol] Remove web3-eth-accounts

netlify-ignore.sh, packages/nitro-protocol/bin/compile.js, packages/nitro-protocol/package.json, packages/nitro-protocol/src/signatures.ts
=> [nitro-protocol] Use minimal dependencies

packages/engine/src/redux/protocols/close-ledger-channel/__tests__/reducer.test.ts, packages/engine/src/redux/protocols/close-ledger-channel/__tests__/scenarios.ts, packages/engine/src/redux/protocols/close-ledger-channel/readme.md, packages/engine/src/redux/protocols/close-ledger-channel/reducer.ts, packages/engine/src/redux/protocols/defunding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/defunding/reducer.ts, packages/engine/src/redux/protocols/existing-ledger-funding/__tests__/reducer.test.ts, packages/engine/src/redux/protocols/existing-ledger-funding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/existing-ledger-funding/readme.md, packages/engine/src/redux/protocols/existing-ledger-funding/reducer.ts, packages/engine/src/redux/protocols/existing-ledger-funding/states.ts, packages/engine/src/redux/protocols/funding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/funding/reducer.ts, packages/engine/src/redux/protocols/ledger-defunding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/ledger-defunding/reducer.ts, packages/engine/src/redux/protocols/ledger-funding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/ledger-funding/reducer.ts, packages/engine/src/redux/protocols/ledger-funding/states.ts, packages/engine/src/redux/protocols/ledger-top-up/reducer.ts, packages/engine/src/redux/protocols/new-ledger-channel/__tests__/scenarios.ts, packages/engine/src/redux/protocols/new-ledger-channel/components/funding-step.tsx, packages/engine/src/redux/protocols/new-ledger-channel/reducer.ts, packages/engine/src/redux/protocols/reducer-helpers.ts, packages/engine/src/redux/protocols/virtual-defunding/__tests__/reducer.test.ts, packages/engine/src/redux/protocols/virtual-defunding/__tests__/scenarios.ts, packages/engine/src/redux/protocols/virtual-defunding/reducer.ts, packages/engine/src/redux/protocols/virtual-funding/reducer.ts, packages/engine/src/redux/protocols/withdrawing/__tests__/scenarios.ts, packages/engine/src/utils/outcome-utils.ts
=> [engine] Convert Existing Ledger Funding to Signed States

packages/web3torrent/src/components/share-list/share-file/ShareFile.stories.tsx
=> [web3torrent] Add stories for ShareFile

packages/web3torrent/.storybook/web3torrent-client.mock.js, packages/web3torrent/.storybook/webpack.config.js, packages/web3torrent/src/components/torrent-info/download-info/DownloadInfo.stories.tsx
=> [web3torrent] Add stories for DownloadInfo

packages/web3torrent/src/components/torrent-info/download-info/progress-bar/ProgressBar.stories.tsx
=> [web3torrent] Adds stories for ProgressBar

packages/engine/src/contract-tests/adjudicator-events.test.ts, packages/engine/src/contract-tests/eth-asset-holder-events.test.ts, packages/engine/src/contract-tests/test-utils.ts, packages/engine/src/contract-tests/transactions.test.ts, packages/engine/src/redux/protocols/withdrawing/reducer.ts, packages/engine/src/utils/transaction-generator.ts
=> [engine] Update Transaction tests to Signed States

packages/web3torrent/src/components/torrent-info/download-link/DownloadLink.stories.tsx
=> [web3torrent] Add stories for DownloadLink

yarn.lock
This PR refreshes some packages missing in `master`.
=> [monorepo] Update yarn.lock

packages/web3torrent/README.md
Resolves #357.
Rendered version [here](https://github.com/statechannels/monorepo/tree/web3torrent/storybook-readme/packages/web3torrent/README.md).
=> [web3torrent] Update README with new demo link + Storybook instructions

packages/web3torrent/src/components/torrent-info/upload-info/UploadInfo.stories.tsx
=> [web3torrent] Adds stories for UploadInfo

packages/web3torrent/package.json, packages/web3torrent/src/components/torrent-info/magnet-link-button/MagnetLinkButton.stories.tsx
=> [web3torrent] Adds stories for MagnetLinkButton

.gitignore, packages/nitro-protocol/.yarnrc, packages/nitro-protocol/package.json
=> [nitro-protocol] Do not build docs during yarn build

packages/rps/truffle.js
Just commented out truffle-hdwallet-provider from the project, as it was breaking stuff (and I checked, that repo it's deprecated now, and it moved to [Truffle's monorepo](https://github.com/trufflesuite/truffle/tree/develop/packages/hdwallet-provider).
Anyway, with this PR, we can make attempts to join and create games
I think that it's firebase issues from here
=> [RPS] commented breaking code, added todo

readme.md
Not sure if the label and color makes sense. Just wanted it to look nice
=> [monorepo] docs: Fix readme chat badge

netlify-ignore.sh, packages/app-wallet-interface/README.md
config for new package app-wallet-interface
=> [monorepo] Update netlify-ignore script

packages/rps/contracts/RockPaperScissors.sol, packages/rps/package.json, packages/rps/src/contract-tests/rock-paper-scissors.test.ts
And correct any bugs along the way!
=> [rps] Increase rps contract test coverage

packages/rps/src/utils/channelClient.ts
This PR picks up the changes described in #427.
=> [rps] [channel-client] Continue expanding the Channel Client API

packages/rps/src/contract-tests/rock-paper-scissors.test.ts, packages/rps/src/core/__tests__/app-data.test.ts, packages/rps/src/core/app-data.ts
=> [rps] appData types and encoding/decoding

packages/rps/src/utils/channelClient.ts
=> [rps] [channel-client] Adds error codes

packages/wallet/src/redux/sagas/__tests__/message-handler.test.ts
Previously the test wasn't actually running. Oops!
=> [wallet] Fix message handler test

packages/hub/src/test/test_data.ts, packages/hub/src/wallet/db/migrations/20190215150548_channels.ts, packages/hub/src/wallet/db/queries/__test__/channels.test.ts, packages/hub/src/wallet/db/queries/channels.ts, packages/hub/src/wallet/db/seeds/2_allocator_channels_seed.ts, yarn.lock
Fixes https://github.com/statechannels/monorepo/issues/419. Also, removes the outdated `rulesAddress` from the `channels` table.
=> [hub] Add chainId to channels table

packages/hub/src/hub/handlers/handle-ongoing-process-action.ts, packages/hub/src/test/test_data.ts, packages/hub/src/wallet/db/migrations/20190215150548_channels.ts, packages/hub/src/wallet/db/migrations/20190219211138_channel_states.ts, packages/hub/src/wallet/db/queries/__test__/channels.test.ts, packages/hub/src/wallet/db/queries/channels.ts, packages/hub/src/wallet/db/queries/getCurrentState.ts, packages/hub/src/wallet/db/seeds/2_allocator_channels_seed.ts, packages/hub/src/wallet/index.ts, packages/hub/src/wallet/models/channelState.ts, packages/hub/src/wallet/services/__test__/channelManager.test.ts, packages/hub/src/wallet/services/__test__/ledgerChannelManager.test.ts, packages/hub/src/wallet/services/channelManager.ts, packages/hub/src/wallet/services/depositManager.ts, packages/hub/src/wallet/services/ledgerChannelManager.ts, yarn.lock
Fixes https://github.com/statechannels/monorepo/issues/418 and https://github.com/statechannels/monorepo/issues/416.
Includes a few renames. Most of the interesting changes are in `ledgerChannelManager.ts` and `channelManager.ts`.
=> [hub] wire up handling ongoing process actions

packages/nitro-protocol/src/contract/transaction-creators/force-move.ts, packages/nitro-protocol/src/contract/transaction-creators/nitro-adjudicator.ts, packages/nitro-protocol/src/transactions.ts, packages/nitro-protocol/test/contracts/NitroAdjudicator/concludePushOutcomeAndTransferAll.test.ts, packages/wallet/src/contract-tests/transactions.test.ts, packages/wallet/src/redux/protocols/withdrawing/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/withdrawing/reducer.ts, packages/wallet/src/utils/transaction-generator.ts
Addresses https://github.com/statechannels/monorepo/issues/28
=> Use concludePushOutcomeAndTransferAll in wallet

readme.md
=> [monorepo] Update readme.md

packages/hub/src/test/test-constants.ts, packages/hub/src/test/test_data.ts, packages/hub/src/wallet/__test__/depositManager.test.ts, packages/hub/src/wallet/__test__/wallet.test.ts, packages/hub/src/wallet/db/migrations/20190215150548_channels.ts, packages/hub/src/wallet/db/migrations/20190219211138_channel_states.ts, packages/hub/src/wallet/db/queries/__test__/channels.test.ts, packages/hub/src/wallet/db/queries/channels.ts, packages/hub/src/wallet/db/queries/walletProcess.ts, packages/hub/src/wallet/db/seeds/2_allocator_channels_seed.ts, packages/hub/src/wallet/db/utils.ts, packages/hub/src/wallet/models/__test__/channelState.test.ts, packages/hub/src/wallet/models/allocation.ts, packages/hub/src/wallet/models/channelParticipants.ts, packages/hub/src/wallet/models/channelState.ts, packages/hub/src/wallet/models/outcome.ts, packages/hub/src/wallet/services/__test__/channelManager.test.ts, packages/hub/src/wallet/services/__test__/ledgerChannelManager.test.ts, packages/hub/src/wallet/utilities/outcome.ts
Fixes https://github.com/statechannels/monorepo/issues/450.
- most of the interesting changes are in `outcome.ts`.
- missing columns added to the ChannelStates table.
- some cleanup of database seeds and test data.
=> [hub] Guarantor channels

packages/wallet/src/redux/channel-store/reducer.ts, packages/wallet/src/redux/protocols/dispute/challenger/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/dispute/challenger/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/dispute/challenger/container.tsx, packages/wallet/src/redux/protocols/dispute/challenger/reducer.ts, packages/wallet/src/redux/protocols/dispute/challenger/states.ts
I have an english checker in my IDE and this was showing as red because `Doesnt` is not a word. Hope no one minds 😅
=> Rename ChannelDoesntExist to ChannelDoesNotExist

packages/wallet/src/redux/actions.ts, packages/wallet/src/redux/sagas/__tests__/message-handler.test.ts, packages/wallet/src/redux/sagas/__tests__/message-sender.test.ts, packages/wallet/src/redux/sagas/message-handler.ts, packages/wallet/src/redux/sagas/message-sender.ts
Returns the response for `UpdateState` specified in https://app-wallet-interface.netlify.com/#update-state
=> [wallet] Fix Update Channel Response

packages/app-wallet-interface/source/index.html.md
Adds an error for Push Message failure.
=> [api] Add Push Message Errors

packages/rps/src/redux/login/saga.ts, packages/rps/src/redux/message-service/saga.ts, yarn.lock
=> [rps] Scrub out wallet

packages/rps/src/redux/game/actions.ts, packages/rps/src/redux/message-service/channel-updated-listener.ts, packages/rps/src/redux/message-service/message-queued-listener.ts, packages/rps/src/utils/channelClient.ts
Closes #454 .
TODO 
~~- [ ] game reducer handles new action~~
=> [rps] Add channelUpdatedListener()

packages/rps/src/redux/message-service/firebase-inbox-listener.ts
=> [rps] Add firebaseInboxListener()

packages/rps/src/core/channel-state.ts, packages/rps/src/redux/game-v2/__tests__/scenarios.ts, packages/rps/src/redux/game-v2/saga.ts, packages/rps/src/redux/game/actions.ts, packages/rps/src/redux/message-service/channel-updated-listener.ts, packages/rps/src/redux/message-service/firebase-inbox-listener.ts, packages/rps/src/redux/message-service/message-queued-listener.ts, packages/rps/src/utils/channel-client.ts, packages/rps/src/utils/rps-channel-client.ts
=> Wire up new sagas to rpsChannelClient

packages/rps/src/redux/message-service/firebase-inbox-listener.ts, packages/rps/src/redux/store.ts, packages/rps/src/utils/channel-client.ts
=> [rps] FirebaseInboxListener tweaks

packages/channel-provider/.eslintrc.js, packages/devtools/.eslintrc.js, packages/ganache-deployer/.eslintrc.js, packages/nitro-protocol/.eslintrc.js
I think this rule sucks. Who's with me!? #546
=> Remove comment capitalization rule

packages/rps/src/components/LobbyPage.tsx, packages/rps/src/components/OpenGameCard.tsx, packages/rps/src/redux/auto-opponent/__tests__/auto-opponent.test.ts, packages/rps/src/redux/auto-opponent/auto-opponent.ts, packages/rps/src/redux/auto-opponent/auto-player.ts, packages/rps/src/redux/auto-opponent/index.ts, packages/rps/src/redux/game/__tests__/player-a.test.ts, packages/rps/src/redux/game/actions.ts, packages/rps/src/redux/game/auto-player-a.test.ts, packages/rps/src/redux/game/saga.ts, packages/rps/src/redux/message-service/channel-updated-listener.ts, packages/rps/src/redux/message-service/message-queued-listener.ts, packages/rps/src/utils/channel-client.ts
Could do with some tidying, but if you run `npx jest src/redux/game/auto-player-a.test.ts`, then two autoplayers will play all the way through, from `Lobby` to `GameOver`. :)
=> RPS AutoPlayer and AutoOpponent

packages/rps/src/__stories__/index.tsx, packages/rps/src/containers/GameBarContainer.tsx, packages/rps/src/redux/game/__tests__/scenarios.ts
=> [rps] Use sensible amounts of ETH in test scenarios

packages/wallet/src/redux/actions.ts, packages/wallet/src/redux/adjudicator-state/__tests__/reducer.test.ts, packages/wallet/src/redux/adjudicator-state/reducer.ts, packages/wallet/src/redux/adjudicator-state/state.ts, packages/wallet/src/redux/protocols/direct-funding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/direct-funding/reducer.ts, packages/wallet/src/redux/selectors.ts
It is an illusion to think that these functions and data structured are any kind of indicator of on-chain funding. The adjudicator has no balance. This removes this code, so we can fix it appropriately in a forthcoming PR...
=> Remove adjudicator funding / balance code

packages/rps/README.md, packages/rps/config/env.js, packages/rps/src/redux/auto-opponent/auto-opponent.ts, packages/rps/src/redux/auto-opponent/auto-player.ts, packages/rps/src/redux/game/__tests__/scenarios.ts, packages/rps/src/redux/store.ts
Try
```
$ AUTO_OPPONENT=B yarn start
```
=> Allow auto-player and/or opponent to be started from environment variables

packages/wallet/src/redux/sagas/asset-holder-watcher.ts
Master is currently failing due to a test failing associated with #586.  This fixes the test to get master passing again.
=> [Wallet] Fix Failing Test

.circleci/config.yml
Slightly easier for a n00b to read.
=> Rename some CircleCI symbols

package.json, packages/channel-provider/package.json, packages/devtools/package.json, packages/embedded-wallet/package.json, packages/hub/package.json, packages/jest-gas-reporter/package.json, packages/nitro-protocol/package.json, packages/rps/package.json, packages/rps/src/core/app-data.ts, packages/rps/src/redux/message-service/firebase-inbox-listener.ts, packages/rps/src/redux/metamask/saga.ts, packages/rps/src/redux/open-games/saga.ts, packages/wallet/package.json, packages/web3torrent/package.json, yarn.lock
This also updates some `redux-saga` packages because they were not compatible.
=> Update to TypeScript 3.7.2

packages/wallet/package.json, packages/wallet/puppeteer/helpers.ts, packages/wallet/puppeteer/tsconfig.json
- Sets module:commonJS when starting puppeteer script so `ts-node` will work
- Updates the port in puppeteer helper function to be correct
=> [wallet] Update puppeteer script

packages/wallet/src/contract-tests/transactions.test.ts, packages/wallet/src/redux/protocols/direct-funding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/direct-funding/reducer.ts, packages/wallet/src/redux/protocols/new-ledger-channel/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/new-ledger-channel/reducer.ts, packages/wallet/src/redux/sagas/transaction-sender.ts, packages/wallet/src/utils/transaction-generator.ts
Fixes some small issues that were causing depositing to fail.
=> [wallet] Deposit Fixes

packages/devtools/src/utils/network-setup.ts, packages/wallet/src/contract-tests/adjudicator-events.test.ts, packages/wallet/src/contract-tests/eth-asset-holder-events.test.ts, packages/wallet/src/contract-tests/test-utils.ts, packages/wallet/src/contract-tests/transactions.test.ts, packages/wallet/src/redux/actions.ts, packages/wallet/src/redux/asset-holders-state/reducer.ts, packages/wallet/src/redux/asset-holders-state/state.ts, packages/wallet/src/redux/protocols/direct-funding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/direct-funding/__tests__/scenarios.ts, packages/wallet/src/redux/protocols/direct-funding/reducer.ts, packages/wallet/src/redux/store.ts, packages/wallet/tsconfig.json
I fixed a few `TODO`s from the `wallet`.
=> [wallet] Fix miscellaneous TODOs

packages/wallet/src/redux/channel-store/channel-state/valid-transition.ts
I think @Alonski had asked about this, so recording this for future inquiries.
=> [wallet] Add a helpful comment around usage of Buffer

packages/rps/src/redux/auto-opponent/auto-player.ts, packages/rps/src/redux/game/__tests__/player-b.test.ts, packages/rps/src/redux/game/__tests__/scenarios.ts, packages/rps/src/redux/game/reducer.ts
- saves quite a lot of lines
- is easier to compare with diagrams such as 
- is easier to catch bugs: in fact I found that one state was being entirely skipped over in a test (now fixed)
=> [rps] Refactor game reducer to switch on state, not action

packages/wallet/puppeteer/__tests__/funding.test.ts, packages/wallet/puppeteer/__tests__/state-updating.test.ts, packages/wallet/puppeteer/__tests__/update-state.test.ts, packages/wallet/puppeteer/helpers.ts, packages/wallet/src/redux/channel-store/channel-state/states.ts, packages/wallet/src/redux/protocols/direct-funding/__tests__/reducer.test.ts, packages/wallet/src/redux/protocols/direct-funding/reducer.ts, packages/wallet/src/redux/sagas/messaging/__tests__/message-handler.test.ts, packages/wallet/src/redux/sagas/messaging/__tests__/message-sender.test.ts, packages/wallet/src/redux/sagas/messaging/message-handler.ts, packages/wallet/src/redux/sagas/messaging/message-sender.ts, packages/wallet/src/redux/sagas/messaging/outgoing-api-actions.ts, packages/wallet/src/redux/selectors.ts, packages/wallet/src/utils/json-rpc-utils.ts
Fixes  depositing so the second player deposits correctly. Also extended the integration test to catch this failure.
=> [wallet] Fix Depositing

.circleci/config.yml, packages/client-api-schema/.eslintrc.js, packages/client-api-schema/package.json, packages/client-api-schema/schema/join-channel.json, packages/client-api-schema/schema/update-channel.json, packages/client-api-schema/types/index.d.ts, packages/wallet/src/redux/sagas/messaging/__tests__/message-handler.test.ts, packages/wallet/src/redux/sagas/messaging/message-handler.ts, packages/wallet/src/utils/json-rpc-utils.ts
Uses `client-api-schema` in the `wallet`.
=> [wallet] Use client-api-schema

packages/hub/.eslintrc.js, packages/hub/package.json, packages/hub/src/wallet/db/queries/__test__/channels.test.ts, packages/hub/src/wallet/services/__chain-test__/asset-holder-watcher.test.ts, packages/hub/src/wallet/services/__test__/channelManager.test.ts, packages/hub/src/wallet/services/__test__/depositManager.test.ts
Following @snario's lead.
The intention of this PR is to define the fewest eslint configuration settings + to inherit reasonable recommended rules.
=> [hub] mimic wallet eslint config

.eslintignore, .vscode/settings.json, packages/channel-client/.eslintrc.js, packages/channel-client/.prettierrc.js, packages/channel-client/jest.config.js, packages/channel-client/package.json, packages/channel-client/src/index.ts, packages/channel-client/src/types.ts, packages/channel-client/tests/index.test.ts, packages/channel-client/tsconfig.json, packages/channel-provider/package.json, packages/nitro-protocol/.eslintrc.js, yarn.lock
=> [channel-client] Add package for ChannelClient

packages/rps/src/redux/game/__tests__/player-b.test.ts, packages/rps/src/redux/game/reducer.ts
=> [rps] Allow player B to cancel

packages/channel-provider/src/channel-provider.ts, packages/channel-provider/src/types.ts, packages/client-api-schema/schema/channel-result.json, packages/client-api-schema/schema/close-channel.json, packages/client-api-schema/schema/create-channel.json, packages/client-api-schema/schema/update-channel.json, packages/client-api-schema/types/index.d.ts, packages/wallet/puppeteer/__tests__/update-state.test.ts, packages/wallet/src/json-rpc-validation/validator.ts, packages/wallet/src/redux/sagas/messaging/__tests__/message-sender.test.ts, packages/wallet/src/redux/sagas/messaging/message-sender.ts
Standardizes the result to be a `ChannelResult`
=> [client-api-schema] Update Client API Schema

packages/hub/src/communication/index.ts, packages/hub/src/hub/handlers/__test__/handle-wallet-message.test.ts, packages/hub/src/hub/handlers/handle-new-process-action.ts, packages/hub/src/hub/handlers/handle-ongoing-process-action.ts, packages/hub/src/hub/handlers/handle-wallet-message.ts, packages/hub/src/message/firebase-relay.ts, packages/hub/src/message/sample-messages/channel-joined.json, packages/hub/src/message/sample-messages/channel-open.json, packages/hub/src/message/sample-messages/strategy-proposed.json
- respond to `Channel.Open` with `Channel.Joined`.
- Start adding `handleWalletMessage` unit tests. `handleWalletMessage` is the outermost function in the hub that is still simple to unit test.
=> [hub] Channel.Open handler

packages/rps/.gitignore, packages/rps/package.json
Seems like the `lint:check` command was broken recently. This fixes it.
=> [rps] Fix RPS linting configuration

packages/channel-client/src/types.ts
Per https://github.com/statechannels/monorepo/pull/704#discussion_r356523401
=> [channel-client] Remove unnecessary error classes

packages/hub/package.json, packages/rps/package.json, packages/wallet/package.json, yarn.lock
Seeing this error with the old dependencies:
=> Upgrade firebase dependencies

packages/wallet/.eslintignore, packages/wallet/puppeteer/helpers.ts, packages/wallet/puppeteer/scripts/funding.ts, packages/wallet/puppeteer/scripts/rps.ts
This is phase 1 of doing some end to end testing between two users playing RPS. Next steps are to wrap the script with test clauses so that it can be a part of the integration tests suite, and then following that to also include a real working hub in the mix, too.
=> [wallet] Add an end to end test script file for playing RPS with default funding

packages/wallet/puppeteer/helpers.ts
Fixes a race condition in the puppeteer tests where `JoinChannel` was called by player B before receiving any of Player A's messages.
Also check that page isn't closed when calling `pushMessage` which was resulting in a `Target is Closed` error occasionally after the tests had been run.
=> [wallet] Fix race condition in Puppeteer test

packages/hub/.env.development, packages/rps/.env, packages/rps/.env.production, packages/wallet/.env, packages/wallet/.env.production
It looks like the payment attached to the old magmo firebase has been removed and I'm assuming it will get shut down eventually.
I've created a new `firebase` database for dev and prod for `rps` under my consensys account.
=> Switch to new firebase instance

.circleci/Dockerfile, .circleci/config.yml
This should shave off some time from CircleCI, maybe a few seconds.
=> Add USE_NATIVE_SOLC to CircleCI builds

.circleci/config.yml, package.json, packages/devtools/package.json, packages/wallet/README.md, packages/wallet/package.json, packages/wallet/puppeteer/__tests__/rps.test.ts, packages/wallet/puppeteer/helpers.ts, packages/wallet/puppeteer/scripts/rps.ts
Some problems encountered...
- `USE_VIRTUAL_FUNDING=TRUE` makes these tests hard to configure
- Unreliable, sometimes messaging doesn't go through
=> [rps] Wrap rps test into an integration test

packages/rps/src/redux/store.ts
This mirrors the behaviour in `auto-opponent.test.ts` but switches on environment variables. Essentially, do not try and talk to the wallet, use a `FakeWalletClient`, and do not start certain sagas.
=> [rps] Fix rootSaga to allow auto opponent to work

packages/rps/src/components/LobbyPage.tsx
=> Add a simple UI to prompt the user to play themself

packages/wallet/src/redux/protocols/concluding/container.tsx
The UI mentioned a hub for both cases of using a hub or not.
=> [rps] Remove unnnecessarily specific UI

packages/channel-provider/src/ui-service.ts, packages/rps/src/components/ProfilePage.tsx, packages/wallet/src/containers/wallet.tsx, packages/wallet/src/redux/protocols/dispute/responder/components/wait-for-approval.tsx, packages/wallet/src/redux/protocols/shared-components/acknowledge-x.tsx, packages/wallet/src/redux/protocols/shared-components/acknowledge.tsx, packages/wallet/src/redux/protocols/shared-components/yes-or-no.tsx, packages/wallet/src/redux/protocols/withdrawing/components/wait-for-approval.tsx, packages/wallet/src/styles/wallet.scss
Some tweaks to the wallet styling to get it looking like it used to.
The twitter address part of the profile has been removed since we don't need it.
=> Wallet styling tweaks

packages/hub/src/wallet/models/outcome.ts, packages/nitro-protocol/src/index.ts, packages/wallet/.storybook/webpack.config.js, packages/wallet/src/redux/asset-holders-state/state.ts, packages/wallet/src/redux/protocols/existing-ledger-funding/reducer.ts, packages/wallet/src/redux/protocols/virtual-funding/reducer.ts, packages/wallet/src/utils/contract-utils.ts, packages/wallet/src/utils/outcome-utils.ts, packages/wallet/src/utils/transaction-generator.ts
This should help us iterate on the wallet UI.
- copy config from rps
- fix a bunch of imports
Note: it is a bit sluggish, and webpack seems to warn about things being "big"
=> [wallet] Get storybook working

packages/rps/contracts/RockPaperScissors.sol
=> [RPS] chore: Fix spelling mistake

packages/wallet-specs/src/mock-messages.ts, packages/wallet-specs/src/protocols/create-channel/protocol.ts, packages/wallet-specs/src/protocols/virtual-funding/protocol.ts, packages/wallet-specs/src/protocols/wallet/protocol.ts, packages/wallet-specs/src/store.ts, packages/wallet-specs/src/wire-protocol.ts
- Adds `set/getParticipant` methods to the store
- Cleans up miscellaneous store code
- Fixes a couple bugs around participants/private keys
=> Add basic participant management

packages/e2e-tests/puppeteer/__tests__/rps.test.ts, packages/e2e-tests/puppeteer/scripts/rps.ts
tabA is also playerA to avoid confusion
=> [e2e] Make tab <-> player relationship clearer

packages/wallet-specs/src/index.ts, packages/wallet-specs/src/protocols/advance-channel/protocol.ts, packages/wallet-specs/src/protocols/create-channel/protocol.ts, packages/wallet-specs/src/protocols/funding/protocol.ts, packages/wallet-specs/src/protocols/join-channel/protocol.ts, packages/wallet-specs/src/protocols/ledger-funding/protocol.ts, packages/wallet-specs/src/protocols/support-state/protocol.ts, packages/wallet-specs/src/store.ts
Switches protocols to use IStore.
Does the same thing as #861 but without the nasty merge conflicts.
=> Protocols connect to an IStore, not a Store 

packages/xstate-wallet/tsconfig.json, packages/xstate-wallet/webpack.config.js
=> Fix xstate wallet build

packages/wallet-specs/src/ChannelStoreEntry.ts, packages/wallet-specs/src/__tests__/data.ts, packages/wallet-specs/src/__tests__/integration.test.ts, packages/wallet-specs/src/__tests__/utils.ts, packages/wallet-specs/src/chain.ts, packages/wallet-specs/src/protocols/depositing/protocol.test.ts, packages/wallet-specs/src/protocols/depositing/protocol.ts, packages/wallet-specs/src/store.ts
See commit messages for visualizations of the updates.
=> [base: ags/conclude] Clean up depositing machine

packages/hub/src/hub/handlers/__test__/handle-ongoing-process-action.test.ts, packages/hub/src/test/test-data.ts, packages/hub/src/wallet/models/allocation.ts, packages/hub/src/wallet/models/outcome.ts, packages/hub/src/wallet/services/__test__/channelManager.test.ts, packages/hub/src/wallet/services/__test__/ledgerChannelManager.test.ts, packages/hub/src/wallet/services/channelManager.ts, packages/hub/src/wallet/services/ledgerChannelManager.ts, packages/hub/src/wallet/utilities/blockchain.ts, packages/hub/src/wallet/utilities/outcome.ts, packages/nitro-protocol/src/index.ts, packages/tic-tac-toe/.eslintignore, packages/wallet-protocols/src/ChannelStoreEntry.ts, packages/wallet-protocols/src/calculations.ts, packages/wallet-protocols/src/index.ts, packages/wallet-protocols/src/protocols/virtual-fund-as-leaf/protocol.ts, packages/wallet-protocols/src/store.ts, packages/wallet/src/redux/__tests__/state-helpers.ts, packages/wallet/src/redux/protocols/consensus-update/reducer.ts, packages/xstate-wallet/src/chain.ts
and export from module root
Closes #464 .
=> [nitro] Remove non-module imports

packages/wallet/config/paths.js
Including `appPreBuiltArtifacts`
Closes #319
=> [wallet] Remove reference to contracts folders

packages/wallet-protocols/README.md, packages/wallet-protocols/src/__tests__/integration.test.ts, packages/wallet-protocols/src/index.ts, packages/wallet-protocols/src/protocols/advance-channel/protocol.ts, packages/wallet-protocols/src/protocols/conclude-channel/protocol.ts, packages/wallet-protocols/src/protocols/create-channel/protocol.ts, packages/wallet-protocols/src/protocols/depositing/protocol.test.ts, packages/wallet-protocols/src/protocols/depositing/protocol.ts, packages/wallet-protocols/src/protocols/direct-funding/protocol.ts, packages/wallet-protocols/src/protocols/funding/protocol.ts, packages/wallet-protocols/src/protocols/join-channel/protocol.ts, packages/wallet-protocols/src/protocols/ledger-funding/protocol.ts, packages/wallet-protocols/src/protocols/support-state/protocol.ts, packages/wallet-protocols/src/protocols/wallet/protocol.ts, packages/wallet-protocols/src/store.ts, packages/wallet-protocols/src/temp-store.ts, packages/xstate-wallet/src/index.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/workflow-manager.ts, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/tests/application.test.ts
This is a first step towards #894. Thought that these changes would make sense, given that the next step is to create a `IndexedDbStore`. Wanted to get them in now, as they touch a lot of files.
=> Rename Store->EmphemeralStore and IStore->Store

packages/xstate-wallet/src/workflows/application.ts
Before this PR it was possible to call actions with the wrong type of event, which would cause runtime errors. By creating the machine using `Machine(config).withConfig(options, context)`, we weren't able to make use of xstate's action type-safety:
```ts
type Event1 = {type: 'FOO'; bar: string};
type Event2 = {type: 'FOO2'; bar: number};
type Event = Event1 | Event2;
const bazMachine = Machine<any, any, Event>({
initial: 'start',
states: {
start: {
on: {
FOO: {
actions: [
(c, e) => e.bar, // here it knows that e of type Event1
'badlyTypedActon'
]
}
}
}
}
}).withConfig({
actions: {
// but here the only check it does is that Event2 extends Event
// it's lost the context of where badlyTypedAction is being called
badlyTypedAction: (c, e: Event2) => e.bar ** 2
}
});
```
This PR implements an …
=> Change the application workflow to support typesafe actions

packages/wallet-protocols/src/__tests__/virtualFunding.integration.test.ts, packages/wallet-protocols/src/json-rpc.ts, packages/wallet-protocols/src/messaging.ts, packages/wallet-protocols/src/protocols/conclude-channel/protocol.ts, packages/wallet-protocols/src/protocols/funding/protocol.ts, packages/wallet-protocols/src/protocols/partial-withdrawal/protocol.ts, packages/wallet-protocols/src/protocols/support-state/protocol.ts, packages/wallet-protocols/tsconfig.json
Closes https://github.com/statechannels/monorepo/issues/941
=> Remove unused locals

yarn.lock
I ran `yarn install` in the monorepo root and noticed that the `yarn.lock` file has changed.
=> Run yarn install

packages/channel-client/src/channel-client.ts, packages/channel-client/src/types.ts, packages/channel-client/tests/utils.ts, packages/client-api-schema/schema/channel-result.json, packages/client-api-schema/schema/create-channel.json, packages/client-api-schema/schema/definitions.json, packages/client-api-schema/schema/update-channel.json
Switched the schema so that json-rpc allocation type is `TokenAllocations` instead of `AllocationAssetOutcome`.
=> Clean up allocation schema

packages/hub/manual-test/firebase-feeder.ts, packages/hub/src/message/firebase-relay.ts
=> Use toLowerCase() for Firebase messages in hub

packages/xstate-wallet/src/store/memory-channel-storage.ts, packages/xstate-wallet/src/store/memory-store.test.ts, packages/xstate-wallet/src/store/memory-store.ts, packages/xstate-wallet/src/store/types.ts
Stab at creating interfaces for the store and store entry.
=> Create interface for Store/ Store Entries

packages/xstate-wallet/src/store/index.ts, packages/xstate-wallet/src/store/memory-channel-storage.ts, packages/xstate-wallet/src/store/memory-store.test.ts, packages/xstate-wallet/src/store/memory-store.ts, packages/xstate-wallet/src/store/outcome-utils.ts, packages/xstate-wallet/src/store/types.ts, packages/xstate-wallet/src/store/wire-protocol.ts
=> Store changes

packages/app-wallet-interface/source/index.html.md, packages/xstate-wallet/src/messaging.ts
Restores compatibility with RPS.
=> [xstate-wallet]  Call ethereum enable and pass selectedAddress to app on request

packages/wallet/package.json, packages/wallet/src/index.tsx, yarn.lock
The adds Sentry to the Wallet.
Filtering for events is done in Sentry via URL filtering
=> [wallet] Add Sentry to Wallet

packages/xstate-wallet/src/store/memory-channel-storage.ts, packages/xstate-wallet/src/store/memory-store.test.ts, packages/xstate-wallet/src/store/memory-store.ts, packages/xstate-wallet/src/workflows/support-state.ts
Reverts statechannels/monorepo#1012
=> Revert "Store states when they arrive"

packages/xstate-wallet/src/store/memory-channel-storage.ts, packages/xstate-wallet/src/store/memory-store.ts, packages/xstate-wallet/src/store/state-utils.ts, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/conclude-channel.ts
Adds the conclude channel protocol to the xstate wallet and call it from the application workflow
=> Add Close Channel protocol to Xstate Wallet

packages/wallet/notes/index.md
=> Fix the mermaid diagram in wallet docs

package.json, packages/app-wallet-interface/package.json, packages/client-api-schema/package.json, packages/client-api-schema/src/generated-schema.json, packages/hub/package.json, packages/rps/package.json, packages/wallet/package.json, packages/xstate-wallet/package.json, yarn.lock
1. Ran `yarn` and it recommended some changes from `master` to some `.json` files
2. Ran these which standardize some `package.json` formats
```
npx syncpack set-semver-ranges
npx syncpack format
npx syncpack fix-mismatches
```
=> Run syncpack and yarn

packages/web3torrent/src/clients/web3t-channel-client.ts, packages/web3torrent/src/pages/file/File.tsx
Following `rps`, this client exposes a friendlier interface for the `web3torrent` app to interact with.
=> [web3torrent] Add Web3TorrentChannelClient

packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/integration-tests/helpers.ts, packages/xstate-wallet/src/integration-tests/running.test.ts, packages/xstate-wallet/src/utils/workflow-utils.ts, packages/xstate-wallet/src/workflows/application.ts
Updates the application workflow to properly handle the `UpdateChannel` request from the app. Also adds a "integration test" that checks that `UpdateChannel` is being handled.
=> Handle Player State Updates

packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/ui/application-workflow.tsx, packages/xstate-wallet/src/ui/confirm-create-channel-workflow.tsx, packages/xstate-wallet/src/ui/wallet.tsx, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/depositing.ts
- Avoid using default and named exports in a module.
- Remove a few unneeded returns.
=> A few cleanup

packages/rps/src/components/HomePage.tsx, packages/web3torrent/src/App.tsx, packages/web3torrent/src/components/layout/layout-header/LayoutHeader.tsx
=> [rps,web3t] Handle no metamask in Connection Banner

packages/channel-client/tests/fakes/fake-channel-provider.ts, packages/web3torrent/README.md, packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/clients/web3t-channel-client.ts, packages/web3torrent/src/clients/web3torrent-client.ts, packages/web3torrent/src/components/channel-list/ChannelList.tsx, packages/web3torrent/src/constants.ts, packages/web3torrent/src/index.tsx, packages/web3torrent/src/library/client-seeding.test.ts, packages/web3torrent/src/library/pse-middleware.ts, packages/web3torrent/src/library/testing/test-utils.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/pages/file/File.tsx
Mostly in response to PR review comments from #1058 .
=> [web3t] Tidy up

packages/web3torrent/src/App.tsx
=> [webt] Move ConnectionBanner inside <main> tags

packages/channel-client/tests/channel-client.test.ts, packages/channel-client/tests/fake-channel-client.test.ts, packages/channel-client/tests/fakes/fake-channel-provider.ts
=> [channel-client] Enhance the FakeChannelProvider to handle multiple channels

packages/web3torrent/README.md, packages/web3torrent/src/library/web3torrent-lib.ts
=> [W3T] Add diagram to web3torrent

packages/web3torrent/src/clients/web3torrent-client.ts, packages/web3torrent/src/components/share-list/ShareList.test.tsx, packages/web3torrent/src/components/share-list/share-file/ShareFile.stories.tsx, packages/web3torrent/src/components/share-list/share-file/ShareFile.tsx, packages/web3torrent/src/components/torrent-info/TorrentInfo.test.tsx, packages/web3torrent/src/components/torrent-info/TorrentInfo.tsx, packages/web3torrent/src/constants.ts, packages/web3torrent/src/types.ts, packages/web3torrent/src/utils/magnet.test.ts, packages/web3torrent/src/utils/magnet.ts, packages/web3torrent/src/utils/test-utils.ts
Compute cost from a CONSTANT * num_pieces [current behaviour]
( anticipated future behaviour might be CONSTANT * num_bytes instead )
=> [web3t] Strip out cost property

packages/xstate-wallet/src/chain.ts, packages/xstate-wallet/src/utils.ts, packages/xstate-wallet/src/workflows/ledger-funding.ts, packages/xstate-wallet/src/workflows/tests/ledger-funding.test.ts, packages/xstate-wallet/src/workflows/tests/virtual-funding.test.ts
=> [change base to master] Ledger funding error handling

packages/web3torrent/src/library/web3torrent-lib.ts
Less clicking required :-)
Fixes #1104
=> [web3t] Leecher auto-closes channels when download finishes

packages/simple-hub/package.json, packages/simple-hub/src/message/firebase-relay.ts, packages/simple-hub/src/server.ts
This PR converts listening to firebase, forming a response, and sending the response from promises to observables.
=> [simple-hub] introduce observables

packages/channel-client/src/channel-client.ts, packages/channel-client/src/types.ts, packages/channel-client/tests/fakes/fake-channel-provider.ts, packages/channel-provider/src/types.ts, packages/client-api-schema/src/generated-schema.json, packages/client-api-schema/src/types.ts, packages/rps/src/utils/__tests__/rps-channel-client.test.ts, packages/simple-hub/src/blockchain/__chain-test__/deposit.test.ts, packages/web3torrent/src/clients/payment-channel-client.ts, packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/event-types.ts, packages/xstate-wallet/src/integration-tests/create-budget.test.ts, packages/xstate-wallet/src/integration-tests/helpers.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/serde/app-messages/deserialize.ts, packages/xstate-wallet/src/serde/app-messages/serialize.ts, packages/xstate-wallet/src/store/memory-store.ts, packages/xstate-wallet/src/store/types.ts, packages/xstate-wallet/src/ui/approve-budget-and-fund-workflow.tsx, packages/xstate-wallet/src/ui/selectors.ts, packages/xstate-wallet/src/ui/stories/approve-budget-and-fund-workflow.stories.tsx, packages/xstate-wallet/src/workflows/approve-budget-and-fund.ts, packages/xstate-wallet/src/workflows/confirm-create-channel.ts, packages/xstate-wallet/src/workflows/create-budget-and-fund.ts
Because the base for https://github.com/statechannels/monorepo/pull/1112 wasn't master ...
=> Basic budgeting functionality (PR to merge into master this time ...)

packages/simple-hub/package.json, packages/simple-hub/src/wallet/index.ts, packages/simple-hub/src/wallet/xstate-wallet-internals/index.ts
Fixes https://github.com/statechannels/monorepo/issues/1177
=> simple-hub: remove xstate-wallet dependency

packages/xstate-wallet/src/workflows/index.ts, packages/xstate-wallet/src/workflows/tests/create-and-fund.test.ts, packages/xstate-wallet/src/workflows/tests/ledger-funding.test.ts, packages/xstate-wallet/src/workflows/tests/virtual-defunding.test.ts, packages/xstate-wallet/src/workflows/tests/virtual-funding.test.ts, packages/xstate-wallet/src/workflows/virtual-defunding-as-hub.ts, packages/xstate-wallet/src/workflows/virtual-defunding-as-leaf.ts
=> Hub defunding workflow

packages/web3torrent/src/library/web3torrent-lib.ts
This is commented out, but it is unclear to me why it is here. Maybe we can discuss here.
=> [w3t] Remove commented out discovery code

packages/web3torrent/src/library/client-seeding.test.ts
This is one part of https://github.com/statechannels/monorepo/issues/1182
There was another subtle bug that prevents the torrent to finish downloaded: Both the seeder and leecher was never `enabled` or initialized, so seeder's `mySigningAddress` var is always null, and never be able to accept payments, and the leecher is permanently blocked after turnNum 4.
I haven't got the time to refactor the code and add more tests yet, but at least we have something to cover the full case for now.
=> Add back test to cover the completed torrent download case

packages/web3torrent/README.md, packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx, packages/web3torrent/src/components/torrent-info/download-info/DownloadInfo.tsx, packages/web3torrent/src/components/torrent-info/upload-info/UploadInfo.tsx, packages/web3torrent/src/library/types.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/pages/file/File.tsx, packages/web3torrent/src/utils/test-utils.ts
These mostly arise out of the (tempting but incorrect) assumption that anyone who uploads is a seeder.
=> [web3t] Remove incorrect usages of 'seeder'

packages/tic-tac-toe/ember-cli-build.js
=> [TTT] Run setupDeployEnv only for dev environments

packages/channel-client/tests/constants.ts, packages/channel-client/tests/fake-channel-client.test.ts
Fixes https://github.com/statechannels/monorepo/issues/1107
=> channel-client: Add multiple channels tests

packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/messaging.ts
https://github.com/statechannels/monorepo/pull/1219#issuecomment-599460805
=> Get xstate wallet to send ChannelProposed, instead of ChannelUpdated

packages/simple-hub/.gitignore, packages/simple-hub/.vscode/launch.json, packages/simple-hub/package.json, packages/simple-hub/src/blockchain/eth-asset-holder.ts, packages/simple-hub/src/constants.ts, packages/simple-hub/src/message/__test__/firebase-relay.test.ts, packages/simple-hub/src/message/firebase-relay.ts, packages/simple-hub/src/server.ts, packages/simple-hub/src/utils.ts, packages/simple-hub/src/wallet/__test__/deposit.test.ts, packages/simple-hub/src/wallet/__test__/respond-to-message.test.ts, packages/simple-hub/src/wallet/deposit.ts, packages/simple-hub/src/wallet/respond-to-message.ts, packages/simple-hub/src/wallet/test-helpers/index.ts, packages/simple-hub/src/wallet/xstate-wallet-internals/index.ts
https://github.com/statechannels/monorepo/pull/1227 preceeds this PR.
Rules for depositing are: on a prefund state, the following have to be true:
1. 2 participant channel.
1. The hub is a participant.
1. The hub decides to support the state.
The hub no longer matches `Deposited` asset holder events.
=> simple-hub: deposit after receiving first prefund state

packages/simple-hub/package.json, packages/simple-hub/src/message/firebase-relay.ts, packages/simple-hub/src/utils.ts, packages/simple-hub/src/wallet/respond-to-message.ts, packages/simple-hub/src/wallet/test-helpers/index.ts, yarn.lock
`lodash/fp` provides very similar curried function support as `ramda` but seems to have friendlier Typescript definitions.
=> simple-hub: ramda to lodash/fp

packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx
Fixes https://github.com/statechannels/monorepo/issues/1216
~~WIP: Auto close channel when leecher runs out of funds~~
=> Web3torrent: Improve channel closing UI and workflow

packages/tic-tac-toe/package.json, yarn.lock
Fixes https://app.circleci.com/pipelines/github/statechannels/monorepo/4305/workflows/e077f433-64f7-4056-bf10-c758c94d0e2f/jobs/15247
=> ttt: upgrade @fullhuman/postcss-purgecss

packages/web3torrent/src/App.tsx, packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/components/layout/layout-header/LayoutHeader.tsx, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/pages/file/File.test.tsx, packages/web3torrent/src/pages/file/File.tsx, packages/web3torrent/src/pages/upload/Upload.tsx, packages/web3torrent/src/pages/welcome/Welcome.test.tsx, packages/web3torrent/src/pages/welcome/Welcome.tsx
App currently doesn't work as it tries to get information from the wallet before it has enabled the channel provider.
=> [web3t] Fix enable race condition

packages/e2e-tests/puppeteer/helpers.ts, packages/wallet/src/redux/sagas/messaging/message-handler.ts, packages/wallet/src/redux/sagas/messaging/message-sender.ts, packages/wallet/src/redux/sagas/messaging/outgoing-api-actions.ts
1. `window.ethereum` was not exposed inside of `iframe`s inside `rps`
2. `EnableEthereum` was not returning an address
=> [rps, wallet] Fix e2e tests

packages/xstate-wallet/src/channel-wallet.ts
Fixes a compilation error that snuck in a merge.
=> Fix xstate wallet build error

packages/client-api-schema/src/generated-schema.json, packages/client-api-schema/src/types.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/ui/enable-ethereum-workflow.tsx, packages/xstate-wallet/src/ui/wallet.scss, packages/xstate-wallet/src/workflows/ethereum-enable.ts
Work towards fixing https://github.com/statechannels/monorepo/issues/1240. Probably worth merging now, as it includes work on the json-rpc error format, which will be useful elsewhere.
=> Better ethereum enable error handling

packages/simple-hub/readme.md
=> [simple-hub] Update readme.md

packages/xstate-wallet/package.json, packages/xstate-wallet/src/ui/enable-ethereum-workflow.tsx, packages/xstate-wallet/src/ui/stories/enable-ethereum.stories.tsx, packages/xstate-wallet/src/ui/wallet.tsx, packages/xstate-wallet/src/ui/window-context.tsx, yarn.lock
=> Handle the case of no metamask / wrong network

packages/web3torrent/src/clients/web3torrent-client.test.ts, packages/web3torrent/src/clients/web3torrent-client.ts, packages/web3torrent/src/components/torrent-info/download-info/DownloadInfo.tsx, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/types.ts, packages/web3torrent/src/utils/torrent-status-checker.ts
Fixes https://github.com/statechannels/monorepo/issues/1230
The UI looks like below after Cancel Download is pressed:
=> Web3torrent: Handle peer cancelling downloads

packages/web3torrent/scripts/start.js, packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.scss, packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx, packages/web3torrent/src/components/torrent-info/download-info/DownloadInfo.scss, packages/web3torrent/src/components/torrent-info/download-info/DownloadInfo.tsx, packages/web3torrent/src/components/torrent-info/upload-info/UploadInfo.scss, packages/web3torrent/src/components/torrent-info/upload-info/UploadInfo.tsx, packages/web3torrent/src/utils/torrent-status-checker.ts
This PR to a degree closes #1130 
**Update:** With Liam's request, I added column headers to the table.
I also changed some more stuff in the UI (removed and reordered some parts, changed the data transfer column):
=> Show UI feedback for Disconnected Peer

packages/web3torrent/README.md, packages/web3torrent/notes/channels-integration.md, packages/web3torrent/src/constants.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/utils/calculateWei.ts
Theses notes should go into greater detail than the readme, and will provide a source of reference for devs and for a future blog post. 
At this time I don't think the code is sufficiently clear as to be self documenting, so I think this will be useful. 
PR also moves some constants to `constants.ts`.
=> [web3torrent] Add some notes on how channels are integrated

packages/xstate-wallet/src/workflows/approve-budget-and-fund.ts, packages/xstate-wallet/src/workflows/index.ts
Fixes https://github.com/statechannels/monorepo/issues/1225
=> Allocate to hub first when creating ledger channel

.vscode/launch.json, packages/xstate-wallet/.vscode/launch.json, packages/xstate-wallet/package.json, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/ui/approve-budget-and-fund-workflow.tsx, packages/xstate-wallet/src/ui/close-ledger-and-withdraw.tsx, packages/xstate-wallet/src/ui/enable-ethereum-workflow.tsx, packages/xstate-wallet/src/ui/layout.tsx, packages/xstate-wallet/src/ui/stories/close-ledger-and-withdraw.stories.tsx, packages/xstate-wallet/src/ui/stories/helpers.tsx, packages/xstate-wallet/src/ui/theme.ts, packages/xstate-wallet/src/ui/wallet.tsx, yarn.lock
Not done yet, but the first screen is there. Have made a couple of changes to the wallet screen framework, which are probably worth merging, in case anyone else wants to touch the UI.
=> Close and withdraw ui

packages/channel-client/src/channel-client.ts, packages/channel-client/tests/fakes/fake-channel-provider.ts, packages/client-api-schema/src/generated-schema.json, packages/client-api-schema/src/types.ts, packages/xstate-wallet/src/chain.ts, packages/xstate-wallet/src/integration-tests/approve-budget.test.ts, packages/xstate-wallet/src/integration-tests/helpers.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/serde/app-messages/deserialize.ts, packages/xstate-wallet/src/serde/app-messages/serialize.ts, packages/xstate-wallet/src/store/channel-store-entry.ts, packages/xstate-wallet/src/store/memory-channel-storage.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/store/types.ts, packages/xstate-wallet/src/ui/approve-budget-and-fund-workflow.tsx, packages/xstate-wallet/src/ui/selectors.ts, packages/xstate-wallet/src/ui/stories/approve-budget-and-fund-workflow.stories.tsx, packages/xstate-wallet/src/utils/budget-utils.ts, packages/xstate-wallet/src/workflows/approve-budget-and-fund.ts
Updates the `budget` based on the discussion in stand up and https://www.notion.so/State-Channels-4cc770686d05438bb23b3c37f4069d7e?p=ce435f483e044d8291a8a01f570391d4
=> Budget Refactor

packages/channel-provider/src/channel-provider.ts, packages/xstate-wallet/src/index.ts
...before returning from `mountWalletComponent()`.
=> [xstate-wallet][channel-provider] Wait for wallet to be ready

packages/xstate-wallet/.eslintrc.js, packages/xstate-wallet/src/chain.ts, packages/xstate-wallet/src/integration-tests/approve-budget.test.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/serde/wire-format/deserialize.ts, packages/xstate-wallet/src/serde/wire-format/serialize.ts, packages/xstate-wallet/src/store/memory-channel-storage.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/tests-with-chain/chain.test.ts, packages/xstate-wallet/src/utils/workflow-utils.ts, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/approve-budget-and-fund.ts, packages/xstate-wallet/src/workflows/close-ledger-and-withdraw.ts, packages/xstate-wallet/src/workflows/confirm-create-channel.ts, packages/xstate-wallet/src/workflows/create-and-fund-ledger.ts, packages/xstate-wallet/src/workflows/create-and-fund.ts, packages/xstate-wallet/src/workflows/depositing.ts, packages/xstate-wallet/src/workflows/ethereum-enable.ts, packages/xstate-wallet/src/workflows/support-state.ts, packages/xstate-wallet/src/workflows/virtual-funding-as-hub.ts
Probably not the best time to add this rule as the wallet is under rapid development, but this would be nice in the near future. Makes our code more readable in my opinion.
=> xstate-wallet: add arrow-body-style rule

packages/channel-client/src/channel-client.ts, packages/channel-client/src/types.ts, packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/pages/file/File.tsx
When there is no budget, use `undefined`.
=> [web3torrent] Remove {} from type for budgetCache

packages/xstate-wallet/src/constants.ts, packages/xstate-wallet/src/index.ts, packages/xstate-wallet/webpack.config.js
Introduces a`CLEAR_STORAGE_ON_LOAD` env variable that clears out the indexedDb backend on load.
=> Add env variable to clear storage on load

packages/channel-client/src/channel-client.ts, packages/client-api-schema/src/generated-schema.json, packages/client-api-schema/src/types.ts, packages/tic-tac-toe/package.json, packages/xstate-wallet/package.json, packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/event-types.ts, packages/xstate-wallet/src/index.ts, packages/xstate-wallet/src/integration-tests/approve-budget.test.ts, packages/xstate-wallet/src/integration-tests/close-withdraw.test.ts, packages/xstate-wallet/src/integration-tests/closing.test.ts, packages/xstate-wallet/src/integration-tests/funding.test.ts, packages/xstate-wallet/src/integration-tests/helpers.ts, packages/xstate-wallet/src/integration-tests/running.test.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/serde/app-messages/deserialize.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/ui/stories/application-workflow.stories.tsx, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/tests/application.test.ts, packages/xstate-wallet/src/workflows/tests/data.ts, yarn.lock
Sets an application site when creating a channel so budget lookups work correctly during the create and fund workflow.
=> Set ApplicationSite when creating a channel

packages/client-api-schema/src/__tests__/good_sample_requests.ts, packages/client-api-schema/src/generated-schema.json, packages/client-api-schema/src/parse-request.ts, packages/client-api-schema/src/types.ts, packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/wire-format/src/generated-schema.json, packages/wire-format/src/types.ts, packages/xstate-wallet/src/constants.ts, packages/xstate-wallet/src/integration-tests/helpers.ts, packages/xstate-wallet/src/workflows/conclude-channel.ts
Has the side effect that concluding now works :-).
=> Strengthen Request validation

packages/web3torrent/src/constants.ts, packages/web3torrent/src/library/web3torrent-lib.ts
=> Set initial leecher balance as torrent size

packages/xstate-wallet/package.json, packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/integration-tests/approve-budget.test.ts, packages/xstate-wallet/src/integration-tests/close-withdraw.test.ts, packages/xstate-wallet/src/integration-tests/funding.test.ts, packages/xstate-wallet/src/integration-tests/helpers.ts, packages/xstate-wallet/src/render.tsx, packages/xstate-wallet/src/ui/approve-budget-and-fund-workflow.tsx, packages/xstate-wallet/src/ui/stories/approve-budget-and-fund-workflow.stories.tsx, packages/xstate-wallet/src/ui/wallet.tsx, packages/xstate-wallet/src/workflows/approve-budget-and-fund.ts, yarn.lock
This PR:
1. Gets typesafety from xstate's typestates on the view components
2. Improves the screens for approve budget and fund.
A few samples:
=> Approve budget and fund screens

packages/simple-hub/src/server.ts
Longer term solution is to address this issue: https://github.com/statechannels/monorepo/issues/1374
=> simple-hub: limit error retries

packages/e2e-tests/puppeteer/helpers.ts, packages/xstate-wallet/src/ui/application-workflow.tsx
Use the class name to as the selector to make the tests flicker less.
=> Improve web3torrent ingegration tests

.circleci/config.yml, packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/constants.ts, packages/web3torrent/src/pages/file/File.tsx, packages/xstate-wallet/package.json, packages/xstate-wallet/src/index.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/store/tests/indexedDB-store.test.ts, packages/xstate-wallet/src/workflows/tests/create-and-fund.test.ts, yarn.lock
Fixes two issues:
- Approve Budget And Fund is started when creating/uploading if no budget exists.(Essentially. hardcoding `AUTO_FUND_LEDGER` )
- Fixes some issues around domains were they not being set or parsed correctly.
Fixes #1325
=> Create budget if does not exist, fix domain parsing

packages/xstate-wallet/package.json
It seems to work fine locally. Maybe it works fine on circle, too!
=> Run xstate tests in parallel on circle

.circleci/config.yml, packages/e2e-tests/puppeteer/helpers.ts
Make the configs match what we did locally.
Also this commit has small fixes on the test artefacts upload.
=> Clean up web3torrent integration test CI configs

packages/simple-hub/src/blockchain/eth-asset-holder.ts, packages/simple-hub/src/logger.ts, packages/simple-hub/src/message/firebase-relay.ts, packages/simple-hub/src/server.ts, packages/simple-hub/src/wallet/chain-event.ts, packages/simple-hub/src/wallet/respond-to-message.ts
Also, convert `logger` module to export an object instead of a function.
=> [simple-hub]: log message before responding

.circleci/config.yml, packages/e2e-tests/package.json, packages/e2e-tests/puppeteer/__tests__/web3torrent.test.ts, packages/e2e-tests/puppeteer/__tests__/web3torrent/seed-download.test.ts, packages/e2e-tests/puppeteer/__tests__/web3torrent/withdraw.test.ts, packages/e2e-tests/puppeteer/constants.ts, packages/e2e-tests/puppeteer/helpers.ts, packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/components/site-budget-table/SiteBudgetTable.tsx, packages/web3torrent/src/pages/file/File.tsx, packages/xstate-wallet/src/ui/close-ledger-and-withdraw.tsx
Fixes #1421  with a pretty basic withdrawal integration test.
Note: 15cefd0 ups the resource class for the integration tests to `large` and allows them to run in parallel.
=> Basic withdrawal integration test

.circleci/config.yml, packages/e2e-tests/puppeteer/helpers.ts
Fix the CI configs that are related to artifacts upload
=> Fix web3torrent integration test artifacts upload

packages/e2e-tests/puppeteer/__tests__/web3torrent/seed-download.test.ts, packages/e2e-tests/puppeteer/__tests__/web3torrent/withdraw.test.ts, packages/e2e-tests/puppeteer/helpers.ts, packages/web3torrent/.vscode/launch.json, packages/xstate-wallet/src/ui/application-workflow.tsx, packages/xstate-wallet/src/ui/confirm-create-channel-workflow.tsx
This PR updates direct funding PR and also has a fix for the failing integration tests. The torrent upload URL has changed.
Fixes https://github.com/statechannels/monorepo/issues/1383
=> Fix integration tests and update direct funding UI

packages/client-api-schema/src/__tests__/parse-request.test.ts, packages/client-api-schema/src/index.ts, packages/client-api-schema/src/validation.ts, packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/messaging.ts, packages/xstate-wallet/src/serde/app-messages/example.ts, packages/xstate-wallet/src/serde/app-messages/serialize.ts, packages/xstate-wallet/src/serde/wire-format/serialize.ts, packages/xstate-wallet/src/utils/helpers.ts, packages/xstate-wallet/src/workflows/application.ts
Fixes #1447 
Enables validating of outgoing responses. I've also fixed a few different formatting errors that was causing the response validation to fail.
=> Enable validation of outgoing responses

packages/xstate-wallet/src/chain.ts
...not from the `window` property (which is updated async, and therefore might not exist yet).
This should fix the following race condition: 
- call `window.ethereum.enable()` and wait for the promise to resolve
- inspect / use `window.ethereum.selectedAddress` and expect it to exist (with some p > 0, it does not yet exist)
The solution is that `window.ethereum.enable` resolves to `[selectedAddress]`, i.e. that which will be set on `window.ethereum.selectedAddress` some time in the future. So we wait for the enable promise to resolve, store the value, and use that as our source of truth when querying the selectedAddress.
=> [xstate-wallet] Return selectedAddress from Chain property

.circleci/config.yml, packages/e2e-tests/puppeteer/__tests__/web3torrent/seed-download.test.ts, packages/e2e-tests/puppeteer/__tests__/web3torrent/withdraw.test.ts, packages/e2e-tests/puppeteer/helpers.ts
+ add `browserId` to pino logs to be able to source the browser logs
=> Separate logs per e2e test file

packages/e2e-tests/puppeteer/__tests__/web3torrent/seed-download.test.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/workflows/tests/virtual-defunding.test.ts, packages/xstate-wallet/src/workflows/virtual-defunding-as-leaf.ts, packages/xstate-wallet/src/workflows/virtual-funding-as-hub.ts
=> Release channel funds when virtual defunding

packages/xstate-wallet/src/ui/approve-budget-and-fund-workflow.tsx, packages/xstate-wallet/src/workflows/approve-budget-and-fund.ts, packages/xstate-wallet/src/workflows/tests/approve-budget-and-fund.test.ts
=> Create budget after deposit

packages/xstate-wallet/src/store/store.ts
(Hopefully) fixes https://github.com/statechannels/monorepo/issues/1478
=> setApplicationSite acquires lock before updating store

.circleci/config.yml
Slightly helpful for the next reader
=> Add comments to CircleCI Config Env Vars

packages/xstate-wallet/package.json, packages/xstate-wallet/src/index.ts, packages/xstate-wallet/src/store/dexie-backend.ts, packages/xstate-wallet/src/store/indexedDB-backend.ts, packages/xstate-wallet/src/store/memory-backend.ts, packages/xstate-wallet/src/store/tests/dexie-store.test.ts, packages/xstate-wallet/src/store/types.ts, yarn.lock
Adds a Dexie backend which has feature parity with the indexedDB backend.
This backend should be updated to use proper Dexie features, like indexes, transactions, etc. This PR takes the approach that we can do this incrementally with a working dexie backend.
=> Add Dexie backend

packages/xstate-wallet/src/chain.ts
Based off my investigation in #1433.
`ethers` default polling time is 4 seconds which can be a bit long. This sets it to 50 ms when the `chainUpdatedFeed ` is subscribed to.
Most of #1433 is caused by metamask 20 second polling time so this only helps slightly.
=> Enable faster polling in ethers.js

packages/xstate-wallet/package.json, packages/xstate-wallet/src/store/dexie-backend.ts, packages/xstate-wallet/src/store/index.ts, packages/xstate-wallet/src/store/memory-backend.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/store/tests/dexie-store.test.ts, packages/xstate-wallet/src/store/types.ts, yarn.lock
=> Add transactions to backend interface

.circleci/config.yml, packages/simple-hub/start-dev-server.ts
Fixes https://github.com/statechannels/monorepo/issues/1537
=> Store simple-hub logs on circle

packages/xstate-wallet/package.json, yarn.lock
Apparently the infinitely deep type definitions bug is fixed!
https://github.com/davidkpiano/xstate/releases/tag/xstate%404.9.0
=> Upgrade xstate

packages/tic-tac-toe/app/components/game-card.hbs, packages/tic-tac-toe/app/components/game-card.ts, packages/tic-tac-toe/app/controllers/games.ts, packages/tic-tac-toe/app/controllers/games/index.ts, packages/tic-tac-toe/app/controllers/games/waiting.ts, packages/tic-tac-toe/app/helpers/format-ether.ts, packages/tic-tac-toe/app/models/message.ts, packages/tic-tac-toe/app/routes/application.ts, packages/tic-tac-toe/app/routes/games.ts, packages/tic-tac-toe/app/routes/games/waiting.ts, packages/tic-tac-toe/app/services/current-game.ts, packages/tic-tac-toe/app/services/ttt-channel-client.ts, packages/tic-tac-toe/app/services/user.ts, packages/tic-tac-toe/app/templates/games.hbs, packages/tic-tac-toe/app/templates/games/index.hbs, packages/tic-tac-toe/app/templates/games/waiting.hbs
This PR handles creating and joining a channel between two players for a Tic Tac Toe game.
Currently, this PR doesn't go beyond the opening of the channel. The actual start of the game and playing of the game will be handled in the next PR.
There are multiple cleanups that need to be done but I just want to get this PR merged in to keep the scope small and will continue iterating in the next PR.
Closes: #1120
=> [TTT] Create Channel for Game

packages/web3torrent/scripts/build.js, packages/xstate-wallet/scripts/build.js
=> Fix piping issue with build scripts

packages/simple-hub/src/blockchain/eth-asset-holder.ts
=> Add slightly more logs to deposit function on hub

.env.circle-integration-w3t-with-hub, .env.virtual-funding, packages/xstate-wallet/src/store/dexie-backend.ts, packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/store/tests/dexie-store.test.ts
- Fixes dexie import
- Fixes nested transaction issue by emitting `'ChannelUpdated'` events _after_ the transaction is committed
- sets `USE_INDEXED_DB = 'true'` in root .env files
=> Fix dexie backend

packages/xstate-wallet/src/chain.ts
Might fix #1591 .
Based on monitoring the network usage of `metamask` it looks like switching `ganache` to port `8545`  causes `metamask` to not cache blockchain requests and send them immediately to `ganache`.
I initially disabled `QUICK_POLLING` to clean up the `ganache` logs to debug #1591, but after making this change I haven't been able to reproduce #1591 since, so I think this might be the main cause.
Before this change occasionally I would see  the `event` be fired by `ethers` but when we queried the `contracts` by calling `holdings` we didn't get the latest amount (which would cause us to get stuck on "waiting for hub to deposit")
I'm not sure if disabling the quick polling fully fixes this or just minimizes the chances it occurs (or I just got really lucky on my local tests 😛) …
=> Revert quick polling

packages/xstate-wallet/src/chain.ts, packages/xstate-wallet/src/channel-wallet.ts, packages/xstate-wallet/src/store/channel-store-entry.ts, packages/xstate-wallet/src/store/dexie-backend.ts, packages/xstate-wallet/src/store/state-utils.ts, packages/xstate-wallet/src/ui/stories/approve-budget-and-fund-workflow.stories.tsx, packages/xstate-wallet/src/ui/stories/close-ledger-and-withdraw.stories.tsx, packages/xstate-wallet/src/ui/stories/confirm-create-channel-workflow.stories.tsx, packages/xstate-wallet/src/ui/stories/enable-ethereum.stories.tsx
Replace all console logging statements with pino-based logger.
I didn't touch the dexie files as I believe @andrewgordstewart is still working on them
=> Update console logging statements

.circleci/config.yml, .env.circle-integration-rps, .env.circle-integration-w3t, .env.circle-integration-w3t-with-hub, .env.persistent-seeder, packages/devtools/src/ganache/index.ts, packages/devtools/src/index.ts, packages/e2e-tests/puppeteer/__tests__/rps/rps.test.ts, packages/e2e-tests/puppeteer/__tests__/web3torrent/seed-download.test.ts, packages/e2e-tests/puppeteer/__tests__/web3torrent/withdraw.test.ts, packages/e2e-tests/puppeteer/helpers.ts
In the end, I got this to work with some pretty minor tweaks to our circle config.
=> [e2e] Enable dappeteer on circle

packages/web3torrent/src/pages/file/File.tsx, packages/web3torrent/src/pages/upload/Upload.tsx
This caused me hours of strife. Hopefully helps the next guy. 
ref: https://github.com/webtorrent/bittorrent-tracker/pull/337
=> Add q&a on troubleshooting on web3torrent UI

packages/channel-provider/package.json, packages/devtools/package.json, packages/e2e-tests/package.json, packages/e2e-tests/persistent-seeder-deployment/build-push-release.sh, packages/e2e-tests/persistent-seeder-deployment/entrypoint.sh, packages/e2e-tests/persistent-seeder-deployment/persistent-seeder.dockerfile, packages/e2e-tests/persistent-seeder-deployment/persistent-seeder.dockerfile.dockerignore
**This branch is where I'm approaching the persistent-seeder deployment.**
Mi first step is deploying manually the docker instance in heroku.
After I get that to work (**currently deployed, but with an error on the script itself**), I plan to automate it with circleci.
=> Persistent seeder deployment

packages/e2e-tests/puppeteer/__tests__/web3torrent/seed-download.test.ts, packages/e2e-tests/puppeteer/helpers.ts, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/conclude-channel.ts, packages/xstate-wallet/src/workflows/tests/application.test.ts
Fixes #1606.
Adds some stricter checks around visibility in the integration tests.
Fixes #1608
=> More checks on the integration tests

packages/devtools/src/config/env.ts
Might this bring us a bit closer to foolproofness around env vars?
=> [devtools] Echo env vars

packages/xstate-wallet/src/ui/approve-budget-and-fund-workflow.tsx, packages/xstate-wallet/src/ui/stories/approve-budget-and-fund-workflow.stories.tsx
Fixes #1599 by removing a header to add more space to the UI.
Also gets storybook working in the xstate wallet again.
=> Fix Approve Budget button overflow

packages/web3torrent/src/clients/payment-channel-client.ts
=> Enable wallet before creating budget

packages/simple-hub/package.json, packages/simple-hub/src/constants.ts, packages/simple-hub/src/wallet/xstate-wallet-internals/index.ts, yarn.lock
`ethers/utils` is not a valid module in ethers v5.
=> [simple-hub] ethers utils import

.circleci/config.yml, packages/simple-hub/docker/build-push-release.sh, packages/simple-hub/docker/simple-hub.dockerfile, packages/simple-hub/readme.md
F&R simple-hub-staging -> simple-hub-production
=> [simple-hub] change heroku application naming  

packages/web3torrent/src/library/web3torrent-lib.ts
=> [web3torrent] web3torrent-lib log cleanups

.circleci/config.yml, .env.circle-integration-rps, .env.circle-integration-w3t, .env.circle-integration-w3t-with-hub, packages/e2e-tests/.gitignore, packages/e2e-tests/puppeteer/__tests__/rps/rps.test.ts, packages/e2e-tests/puppeteer/__tests__/web3torrent/seed-download.test.ts, packages/e2e-tests/puppeteer/__tests__/web3torrent/withdraw.test.ts, packages/e2e-tests/puppeteer/constants.ts, packages/e2e-tests/puppeteer/helpers.ts
=> Always upload screenshots on circle

.env.persistent-seeder, packages/e2e-tests/puppeteer/scripts/persistent-seeder.ts
This hopefully deals with https://github.com/statechannels/monorepo/issues/1755
=> Disable logging in persistent-seeder

packages/xstate-wallet/webpack-build.config.js, packages/xstate-wallet/webpack.config.js
Following https://docs.sentry.io/platforms/javascript/sourcemaps/
=> [xstate-wallet] Define source-map output file

packages/web3torrent/src/clients/payment-channel-client.ts
Allows a user to decline the approve budget and fund prompt without causing errors.
=> [web3torrent] Handle user declining budget

packages/xstate-wallet/src/workflows/application.ts
maybe fixes #1789 (I was seeing the same behaviour of states out of order that went away with this change but I'm not sure exactly how the states got out of order)
Previously we were using `tap` to get the latest entry that is our turn and sign the state. However it looks like it was not blocking on `signAndAddState` so the `conclude-channel` would start without a signed final state.
This change makes sure that the `signFinalState` service resolves only when `signAndAddState` completes.
I think the use of indexedDB transactions prevented us from running into this when using the dexie backend (since `conclude-channel` would block until the transaction in `signAndAddState` completed). However when using the memory backend we can run into this.
I'm not sure exactly how the states get out of …
=> Update SignFinalState to only resolve after the state is signed

.circleci/config.yml
Some of these paths did not exist, some were missing.
=> Point save_lib to correct directories

.circleci/config.yml
Based on https://circleci.com/docs/2.0/yarn/
=> Save yarn cache on CircleCI

packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/xstate-wallet/src/store/channel-store-entry.ts
(See https://github.com/statechannels/monorepo/issues/1842)
=> getLatestPaymentReceipt filters on channel id

.env.circle-integration-w3t, .env.circle-integration-w3t-with-hub, .env.production-ropsten
Seemed to fix this issue with the X server not responding when I SSH'd in
=> Add CLOSE_BROWSERS to CircleCI configs

.circleci/config.yml
Should fix https://app.circleci.com/pipelines/github/statechannels/monorepo/6533/workflows/9e6811a6-88d3-4798-b01b-b206dfb20d18/jobs/27770/steps
=> Fix simple hub release

packages/tic-tac-toe/app/controllers/game.ts, packages/tic-tac-toe/app/core/app-data.ts
Currently, closeChannel doesn't work.
There is more work to be done in this area but this PR enables actually winning/losing/drawing a game.
=> [TTT] Handle Victory/Draw states in TTT

.circleci/config.yml, .dockerignore, packages/e2e-tests/puppeteer/__tests__/optional/seed-download-cancel.test.ts, packages/e2e-tests/puppeteer/constants.ts
Tests passed reliably when ssh'd in to circleci with these changes
=> Changes to e2e test structure for ✅s

packages/xstate-wallet/src/store/store.ts, packages/xstate-wallet/src/workflows/application.ts
Possibly might help with #1883, specifically the symptom that led to the creation of the issue: `Attempting to sign a stale state`.
=> [xstate-wallet] Add transaction-based updateChannel to Store

.circleci/config.yml
=> Cache build artifacts across CircleCI workflows

packages/web3torrent/src/library/web3torrent-lib.ts
Now it will close the channel only when closed, and the correct channel only.
Fixes #1889
=> Refactor channel updated listener

package.json, packages/devtools/package.json, packages/e2e-tests/package.json, packages/jest-gas-reporter/package.json, packages/nitro-protocol/package.json, packages/nitro-protocol/readme.md, packages/persistent-seeder/package.json, packages/rps/package.json, packages/simple-hub/package.json, packages/tic-tac-toe/package.json, packages/web3torrent/package.json, packages/xstate-wallet/package.json
So we can write a nice tutorial on how to interact with the contracts.
=> [ devtools, nitro-protocol ] Prepare to publish

packages/simple-hub/src/blockchain/eth-asset-holder.ts
Fixes https://github.com/statechannels/monorepo/issues/1908.
=> simple-hub: pay 100x default gas fees

packages/xstate-wallet/src/ui/approve-budget-and-fund-workflow.tsx
Short term improvement for #1720
=> Slightly improve hub depositing UI for now

packages/web3torrent/src/library/web3torrent-lib.ts
=> Adds better logging when the torrent it's done

.circleci/config.yml
=> Add Slack notification for persistent-seeder release

packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.scss, packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx
=> Add connection status indicator

packages/e2e-tests/puppeteer/__tests__/optional/seed-download-cancel.test.ts, packages/e2e-tests/puppeteer/__tests__/web3torrent/seed-download-complete.test.ts, packages/web3torrent/src/components/domain-budget-table/DomainBudgetTable.scss, packages/web3torrent/src/components/domain-budget-table/DomainBudgetTable.tsx, packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.scss, packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx
=> [web3torrent] UI Improvements

packages/simple-hub/package.json, packages/simple-hub/src/blockchain/eth-asset-holder.ts
Hub deposits on ropsten are so slow right now...
=> [simple-hub] Pay higher gas fees

package.json, packages/devtools/package.json, packages/devtools/tsconfig.json, packages/e2e-tests/package.json, packages/jest-gas-reporter/package.json, packages/nitro-protocol/package.json, packages/persistent-seeder/package.json, packages/rps/package.json, packages/simple-hub/package.json, packages/tic-tac-toe/package.json, packages/web3torrent/package.json, packages/xstate-wallet/package.json
=> [devtools] Patch @statechannels/devtools

packages/web3torrent/src/components/torrent-info/peer-network-stats/PeerNetworkStats.test.tsx, packages/web3torrent/src/components/torrent-info/peer-network-stats/PeerNetworkStats.tsx
=> Update 'peers connected' UI to reflect active channels

packages/nitro-protocol/contracts/NitroAdjudicator.sol, packages/nitro-protocol/src/index.ts
As I write the nitro-tutorial, I am spotting some things that could be nicer about this package (for external consumers).
=> [nitro-protocol] Tweaks before publishing package

packages/channel-provider/src/messaging-service.ts
=> Show error message on wallet error response

.env.persistent-seeder
Fixes https://sentry.io/organizations/statechannels/issues/1686026055/?project=5236239&query=is%3Aunresolved
=> Add missing env vars for persistent-seeder

packages/xstate-wallet/src/chain.ts
Hoping that this will help investigate https://github.com/statechannels/monorepo/issues/1995.
=> xstate-wallet: log Deposited and AssetTransferred events

packages/xstate-wallet/src/chain.ts
Hoping that additional log lines will help debug a couple of issues:
1. https://github.com/statechannels/monorepo/issues/1995
1. Duplicate contract events. No no github issue exists yet since I don't have a good set of logs.
=> [xstate-wallet] Log all asset holder events

packages/channel-provider/src/messaging-service.ts
Addresses https://github.com/statechannels/monorepo/pull/1994/files#r431489570.
=> [channel-provider] Only reject listener promise if event id matches

packages/xstate-wallet/src/index.ts
Fixes https://github.com/statechannels/monorepo/issues/2000
=> [xstate-wallet] Remove initialization of stub functionality

packages/xstate-wallet/src/integration-tests/running.test.ts, packages/xstate-wallet/src/store/index.ts, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/tests/application.test.ts
=> Refactor application workflow closeChannel

packages/web3torrent/src/clients/web3torrent-client.ts, packages/web3torrent/src/constants.ts, packages/web3torrent/src/library/paid-streaming-extension.ts, packages/web3torrent/src/library/types.ts, packages/web3torrent/src/library/web3torrent-lib.ts, packages/web3torrent/src/pages/welcome/Welcome.tsx, packages/web3torrent/src/utils/check-torrent-in-tracker.ts, packages/web3torrent/tracker/index.js
I've added a bunch of comments to the project.
If someone has any doubts, or suggestions to things I should try to explain, I'm happy to give it a try.
=> Add Comments and info

packages/xstate-wallet/src/utils/contract-utils.ts
Should address https://sentry.io/organizations/statechannels/issues/1697515651/?project=5236239&referrer=slack
=> Use InfuraProvider when mocking for persistent-seeder and e2e tests

packages/web3torrent/src/constants.ts, packages/web3torrent/src/pages/upload/Upload.tsx
Ups the budget size and adds a file size check to avoid running into #2003
=> Add basic file size limitations

packages/xstate-wallet/src/chain.ts
This is a quick workaround for #1995 that uses the amount from the event. This allows us to avoid the issue where the chain query returns stale data.
=> Use Amount from Deposited Event

packages/web3torrent/config/webpack.config.js
=> [web3torrent] Don't filter / whitelist env vars

packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/approve-budget-and-fund.ts, packages/xstate-wallet/src/workflows/conclude-channel.ts, packages/xstate-wallet/src/workflows/create-and-fund.ts, packages/xstate-wallet/src/workflows/tests/conclude-channel.test.ts, packages/xstate-wallet/src/workflows/tests/create-and-fund.test.ts, packages/xstate-wallet/src/workflows/tests/virtual-defunding.test.ts, packages/xstate-wallet/src/workflows/virtual-defunding-as-leaf.ts
Fixes #2033.
Pretty simple change that sends out a budget notification whenever we reserveFunds/releaseFunds/createBudget.
=> Send out budget notifications

packages/xstate-wallet/src/utils/contract-utils.ts
Also, convert `getProvider` method into a singleton.
Fixes https://github.com/statechannels/monorepo/issues/2055.
=> [xstate-wallet] refresh page on network change

packages/e2e-tests/puppeteer/helpers.ts, packages/web3torrent/src/components/domain-budget-table/DomainBudgetTable.scss, packages/web3torrent/src/constants.ts
Some minor changes around @geoknee's work.
This PR
- restores styling to the withdraw button
- gets the failing test passing
- sets the budget to 100 Mwei (temporarily) to make progress on the pie chart visible.
I've held off on styling the pie-chart  as I think it may be worth discussing first.
=> Minor Budget related changes

packages/simple-hub/.vscode/launch.json, packages/simple-hub/src/blockchain/eth-asset-holder.ts
Fixes https://github.com/statechannels/monorepo/issues/1520.
=> [simple-hub] log sentry error when hub balance is below 1 eth

packages/web3torrent/src/logger.ts, packages/xstate-wallet/src/ui/approve-budget-and-fund-workflow.tsx
Fixes #2072.
Adds a pretty simple hub timeout page that gets displayed after waiting for 5 minutes for the hub. It provides a button to download logs and a link to our github issue page.
=> Adds a basic hub timeout page

packages/web3torrent/src/components/domain-budget-table/turnNumToNumPayments.test.ts, packages/web3torrent/src/components/torrent-info/channels-list/ChannelsList.tsx
This is a little inaccurate as is.
=> [web3torrent] Improve payment counting

.env.persistent-seeder, packages/web3torrent/src/constants.ts
=> [web3torrent] Override default INITIAL_BUDGET_AMOUNT in env var

.circleci/Dockerfile, .circleci/config.yml, packages/nitro-protocol/contracts/Token.sol, packages/nitro-protocol/deployment/deploy.js, packages/nitro-protocol/package.json, packages/tic-tac-toe/package.json, packages/xstate-wallet/deployment/deploy.js, yarn.lock
=> [nitro-protocol] upgrade oz contracts

packages/web3torrent/package.json, packages/web3torrent/src/index.tsx, yarn.lock
Adds a simple check for mobile devices and renders out a message saying we don't support mobile.
=> Add simple mobile device check

packages/web3torrent/src/App.tsx
Shows a basic warning if your balance is less than the initial budget amount with a link to a faucet.
Fixes #2116
=> show warning if balance is low

packages/nitro-protocol/package.json, packages/nitro-protocol/readme.md, packages/rps/package.json, packages/simple-hub/package.json, packages/tic-tac-toe/package.json, packages/xstate-wallet/package.json
=> [nitro-protocol] Tweak readme, add test folder to npm package

packages/e2e-tests/puppeteer/scripts/web3torrent.ts
It was using the hub address and did not work with dappeteer
=> Change etherlime index for web3torrent dev script and add Dappeteer

packages/xstate-wallet/src/chain.ts
Fixes https://github.com/statechannels/monorepo/issues/1995
=> Poll the chain when subscribed to the chainUpdatedFeed

packages/web3torrent/src/components/domain-budget/DomainBudget.tsx, packages/web3torrent/src/utils/calculateWei.ts, packages/web3torrent/src/utils/prettyPrintWei.test.ts
=> [web3torrent] Domain budget tweaks

packages/xstate-wallet/src/tests-with-chain/chain.test.ts
The old test seems unnecessarily complicated, given what we want to test.
I ran this test a few times locally, and it passed. Before, it was failing locally.
=> Fix chain test

packages/web3torrent/src/App.tsx, packages/xstate-wallet/src/chain.ts, packages/xstate-wallet/src/ui/approve-budget-and-fund-workflow.tsx, packages/xstate-wallet/src/workflows/approve-budget-and-fund.ts, packages/xstate-wallet/src/workflows/tests/approve-budget-and-fund.test.ts
Fixes #2116 
Adds a balance check to the approve budget and fund workflow and removes it from the application.
The workflow waits until the user deposits enough funds before proceeding.
=> Add balance check to Approve Budget and Fund

packages/xstate-wallet/src/chain.ts
Fixes #2070. 
Sets a fixed gas price so we don't run into issues where metamask mistakingly estimates the gas price as 0.
The value of 20 gwei is kind of arbitrary (as transactions will get picked up with a much lower gas price) but seems[ roughly inline](https://ethgasstation.info/) with the main network.
=> Set a fixed gas price

packages/xstate-wallet/package.json
Via copy of redirects map to the build directory.
=> [xstate-wallet] Hopefully fix factory reset

packages/web3torrent/src/library/client-seeding.test.ts, packages/web3torrent/src/library/testing/setup.js
Hopefully fixes https://github.com/statechannels/monorepo/issues/2178#issuecomment-644230975.
=> [web3torrent] wait for tracker to start listening before unit tests

packages/xstate-wallet/src/messaging.ts
=> Run enableEthereum again if no destinationAddress in indexedDb

packages/persistent-seeder/persistent-seeder.ts
=> Fix persistent seeder

packages/channel-provider/src/messaging-service.ts, packages/web3torrent/src/clients/payment-channel-client.ts
=> Handle user rejecting withdrawal

packages/xstate-wallet/src/store/dexie-backend.ts, packages/xstate-wallet/src/ui/factory-reset.tsx
Fixes https://github.com/statechannels/monorepo/issues/2198
=> Fix factory reset

packages/web3torrent/src/clients/payment-channel-client.ts, packages/web3torrent/src/library/paid-streaming-extension.ts, packages/web3torrent/src/library/web3torrent-lib.ts
Fixes https://github.com/statechannels/monorepo/issues/2215
=> Troubleshooting mutliple leecher test

packages/e2e-tests/puppeteer/__tests__/web3torrent/seed-download-seeder-cancel.test.ts, packages/web3torrent/src/library/paid-streaming-extension.ts, packages/web3torrent/src/library/web3torrent-lib.ts
=> Get seeder cancelling to work

packages/web3torrent/src/components/torrent-info/TorrentInfo.tsx
Some basic logic to hide/disable the stop button when appropriate.
=> Stop button clean up

packages/xstate-wallet/src/store/store.ts
This is a pretty major bug. Ideally we would have a unit test for this.
Closes #2222
=> Budget fix

.env.circle-integration-w3t-with-hub, packages/e2e-tests/puppeteer/__tests__/optional/multiple-leecher.test.ts, packages/web3torrent/src/library/web3torrent-lib.ts
I've run the multiple leacher test multiple times, cancelling at random. All seems to work 🎉  🤞 .
=> Mark torrent as destroyed to cancel. Fixes #2227

packages/web3torrent/src/App.tsx, packages/web3torrent/src/components/domain-budget/DomainBudget.scss, packages/web3torrent/src/components/domain-budget/DomainBudget.tsx, packages/web3torrent/src/components/layout/layout-header/LayoutHeader.tsx, packages/web3torrent/src/pages/welcome/Welcome.scss, packages/web3torrent/src/pages/welcome/Welcome.tsx, packages/xstate-wallet/package.json, packages/xstate-wallet/src/ui/approve-budget-and-fund-workflow.tsx, yarn.lock
Tom and I paired and came up with a list of improvements. I am working through those here
https://www.notion.so/web3Torrrent-user-stories-21c3aace7d17448ebfbe5b0a9750f4d5
=> [ web3torrent ] User-story focussed UI overhaul

packages/web3torrent/src/components/domain-budget/DomainBudget.tsx, packages/web3torrent/src/components/torrent-info/TorrentInfo.scss, packages/web3torrent/src/components/torrent-info/TorrentInfo.tsx, packages/web3torrent/src/components/torrent-info/download-link/DownloadLink.tsx, packages/web3torrent/src/components/torrent-info/magnet-link-button/MagnetLinkButton.tsx, packages/web3torrent/src/pages/file/File.tsx
Tweaks some of the UI screens. Fixes #2237. Fixes #2238. Fixes #2239.
=> WIP: UI Tweaks

packages/web3torrent/src/components/layout/layout-header/LayoutHeader.tsx, packages/web3torrent/src/pages/welcome/Welcome.tsx, packages/xstate-wallet/src/ui/close-ledger-and-withdraw.tsx
Staying consistent by displaying a spinner any time we wait for the chain or the hub.
=> [xstate-wallet] Add spinners to close ledger workflow

packages/nitro-protocol/docs/dapp-devs/quick-start.md, packages/nitro-protocol/readme.md, packages/nitro-protocol/website/versioned_docs/version-0.1.1/dapp-devs/quick-start.md
The quoted contract would not actually compile.
=> [nitro] Tweak readme

.vscode/settings.json, packages/benchmarking/package.json, packages/nitro-protocol/bin/compile.js, packages/nitro-protocol/package.json, packages/rps/package.json, packages/simple-hub/package.json, packages/tic-tac-toe/package.json, packages/wallet-core/package.json, packages/wallet-core/src/logger.ts, packages/wallet-core/src/store/tests/dexie-store.test.ts, packages/xstate-wallet/bin/generateConfigs.ts, packages/xstate-wallet/package.json, packages/xstate-wallet/src/logger.ts, packages/xstate-wallet/src/workflows/application.ts, yarn.lock
I think it would fix [this failure](https://app.circleci.com/pipelines/github/statechannels/monorepo/7704/workflows/602851e4-fe5a-4ffa-b23e-f254fe40a9d1/jobs/36570/steps).
=> [wallet-core] Fix errors & [nitro-protocol] Reduce size of build artifacts

packages/wallet-core/readme.md, readme.md
and insert readme for walet-core
=> Update top level readme

packages/channel-client/.eslintrc.js, packages/client-api-schema/.eslintrc.js, packages/e2e-tests/.eslintrc.js, packages/persistent-seeder/.eslintrc.js, packages/wire-format/.eslintrc.js
=> Simplify linting configs

packages/simple-hub/package.json, packages/wallet-core/package.json, packages/wire-format/.gitignore, packages/wire-format/package.json, packages/xstate-wallet/package.json, yarn.lock
- Include correct files for npm publishing.
- Bump version.
=> [wire-format] Package publishing

packages/xstate-wallet/package.json
Adding as a dependency to `apps`
=> Publish @statechannels/xstate-wallet

packages/wallet-core/package.json, packages/xstate-wallet/package.json, yarn.lock
We no longer need the beta version.
=> Upgrade ethers out of beta, to 5.0.7

packages/wallet-core/.eslintrc.js, packages/wallet-core/src/bignumber.ts, packages/wallet-core/src/config.ts, packages/wallet-core/src/serde/app-messages/deserialize.ts, packages/wallet-core/src/serde/app-messages/example.ts, packages/wallet-core/src/serde/app-messages/serialize.ts, packages/wallet-core/src/serde/wire-format/example.ts, packages/wallet-core/src/serde/wire-format/serde.test.ts, packages/wallet-core/src/serde/wire-format/serialize.ts, packages/wallet-core/src/state-utils.ts, packages/wallet-core/src/tests/outcomes-equal.test.ts, packages/wallet-core/src/utils/allocate-to-target.test.ts, packages/wallet-core/src/utils/budget-utils.ts, packages/wallet-core/src/utils/helpers.ts, packages/wallet-core/src/utils/messages.ts, packages/wallet-core/src/utils/outcome.ts
I strongly prefer this rule and there is an autofix.
=> Add imports/order rule to eslintrc.js for wallet-core

packages/nitro-protocol/docs/wallet-dev-tutorial/execute-state-transitions.md, packages/nitro-protocol/website/versioned_docs/version-0.1.1/wallet-dev-tutorial/execute-state-transitions.md
Following discussion in our forum.
=> [docs] Improve clarity around storage of states by wallets.

packages/nitro-protocol/docs/products.md, packages/nitro-protocol/website/sidebars.json, packages/nitro-protocol/website/siteConfig.js
This is written in mermaid which makes it pretty easy to maintain.
Open to suggestions around terminology &c.
=> [docs] Insert a "products" diagram

packages/server-wallet/src/protocols/actions.ts, packages/server-wallet/src/protocols/application.ts
Adds some basic action creators to help clean up protocols.
=> Add basic action creators

packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts, packages/server-wallet/src/wallet/__test__/sign-state.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts
Resolves https://github.com/statechannels/statechannels/issues/2365
=> createChannel returns outgoing messages & channel results

packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts
Implements `PushMessage` in the `Store` and moves a bunch of logic out of the `Channels` mode into the `Store`
=> Implement PushMessage in the Store

packages/server-wallet/package.json, packages/wallet-core/src/config.ts
Addresses (albeit poorly) #2381
=> Minimal changes to allow server-wallet to be imported

packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts
Also, adds some documentation.
=> Remove unnecessary query from `lockApp`

packages/docs-website/website/package.json, packages/docs-website/website/siteConfig.js
=> [docs] Add search

packages/server-wallet/e2e-test/e2e-utils/ping.ts
We recently merged two conflicting changes to master.
=> Fix import

packages/channel-client/.eslintrc.js, packages/channel-client/package.json, packages/client-api-schema/.eslintrc.js, packages/client-api-schema/package.json, packages/client-api-schema/src/data-types.ts, packages/client-api-schema/src/generated-schema.json, packages/iframe-channel-provider/.eslintrc.js, packages/iframe-channel-provider/package.json, readme.md, yarn.lock
also add eslint plugin for tsdoc
=> [monorepo] Add instructions for typescript docstrings

packages/server-wallet/src/config.ts, packages/server-wallet/src/db/config.ts
=> Allow process.env defined database password

packages/server-wallet/jest/knex-setup-teardown.ts, packages/server-wallet/src/db/migrations/20200818083933_funding.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/models/funding.ts, packages/server-wallet/src/protocols/__test__/application.test.ts, packages/server-wallet/src/protocols/application.ts, packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts, packages/server-wallet/src/wallet/__test__/lock-app.test.ts, packages/server-wallet/src/wallet/index.ts
Adds basic support for sending a funding event to the wallet.
=> Accept a funding event in the server wallet

packages/wire-format/src/__tests__/bad_sample_messages.ts, packages/wire-format/src/__tests__/good_sample_messages.ts, packages/wire-format/src/__tests__/validator.test.ts
=> [wire-format] Add test cases for null and '' objectives

.circleci/config.yml
Run `sudo apt-get update` before installing postgresql-client
Fixes issue #2487
=> Fix issue 2484

packages/server-wallet/e2e-test/scripts/generate-profile-data.ts, packages/server-wallet/e2e-test/scripts/profile.sh
Runs the `doctor` command that generates a generic performance report. IE: https://41655-209829093-gh.circle-artifacts.com/0/home/circleci/project/artifacts/1570.clinic-doctor.html
=> Runs the doctor command as well

packages/server-wallet/package.json, packages/server-wallet/src/index.ts
Also, export the `Outgoing` type.
=> server-wallet: Change main to top level index

packages/server-wallet/src/utilities/__test__/signatures.test.ts, packages/server-wallet/src/utilities/signatures.ts, packages/server-wallet/src/wallet/store.ts
Switch to libAuth to recover the address.
=> Use libAuth to recover the address

.circleci/config.yml, packages/server-wallet/.env.development, packages/server-wallet/e2e-test/payer/client.ts, packages/server-wallet/e2e-test/payer/start.ts, packages/server-wallet/e2e-test/receiver/controller.ts, packages/server-wallet/e2e-test/scripts/profile.sh, packages/server-wallet/package.json, packages/server-wallet/src/config.ts, packages/server-wallet/src/metrics.ts, packages/server-wallet/src/state-utils.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts, yarn.lock
Adds some metrics and outputs them as `PerformanceEntries`.
Adds the option to output them to a file so they can be parsed by `jq`
=> Output Metrics

lerna.json, package.json, packages/benchmarking/package.json, packages/channel-client/package.json, packages/client-api-schema/package.json, packages/devtools/package.json, packages/docs-website/package.json, packages/iframe-channel-provider/package.json, packages/integration-tests/package.json, packages/jest-gas-reporter/package.json, packages/nitro-protocol/package.json, packages/server-wallet/package.json, packages/wallet-core/package.json, packages/wire-format/package.json, packages/xstate-wallet/package.json
This version has already been published on npm.
=> Bump version to 0.3.5

packages/server-wallet/src/db/migrations/20200915140300_chain_service.ts, packages/server-wallet/src/protocols/application.ts
Specifically, address https://github.com/statechannels/statechannels/pull/2561#discussion_r491508503 and https://github.com/statechannels/statechannels/pull/2561#discussion_r491507854
=> Address feedback from PR 2561

yarn.lock
Running yarn after publishing packages
=> chore: run yarn

packages/server-wallet/src/wallet/store.ts
Adresses https://github.com/statechannels/statechannels/pull/2607#discussion_r494288131.
=> Remove unnecessary timer

packages/server-wallet/src/db/migrations/20200915140300_chain_service.ts
Fixes https://github.com/statechannels/statechannels/issues/2570
=> [server-wallet] Default value for chainServiceRequests

packages/server-wallet/benchmarks/fast-signature.benchmark.ts, packages/server-wallet/benchmarks/wasm-signature.benchmark.ts, packages/server-wallet/package.json, packages/server-wallet/src/models/signing-wallet.ts, packages/server-wallet/src/state-utils.ts, packages/server-wallet/src/utilities/__test__/signatures.test.ts, packages/server-wallet/src/utilities/signatures.ts, packages/server-wallet/src/wallet/store.ts, yarn.lock
I'd like to see if this works on circle.
=> [server-wallet] Use @statechannels/wasm-utils

packages/server-wallet/package.json
This version has been published to npm.
=> Ags/server wallet 0.3.8 alpha.1

packages/devtools/src/ganache/server.ts
=> fix(devtools): Spawn ganache command in a shell

packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts, packages/server-wallet/src/wallet/index.ts
Implements a basic Create Channels method
=> Add Create Channels function in Server Wallet

.circleci/config.yml, packages/server-wallet/e2e-test/e2e-utils.ts, packages/server-wallet/src/config.ts, packages/server-wallet/src/logger.ts, packages/server-wallet/src/utilities/workers/manager.ts, packages/server-wallet/src/utilities/workers/worker.ts
Improve logging around worker threads to make it easier to monitor/understand in a production environment.
=> Improve logging around worker threads

packages/devtools/src/ganache/server.ts, packages/nitro-protocol/src/contract/transaction-creators/erc20-asset-holder.ts, packages/server-wallet/.vscode/launch.json, packages/server-wallet/package.json, packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/chain-service.ts
This PR is extends https://github.com/statechannels/statechannels/pull/2641.
=> Add erc20 support to the chain service

packages/server-wallet/src/__test__/create-channel/direct-funding.test.ts
=> test: Add direct funding wallet to wallet test

.github/workflows/commitlint.yml
... but to put a label on the PR, thereby offering whimsical encouragement / incentive to get the lint check to pass.
=> Modify commitlint action to always pass

packages/server-wallet/src/__test__/crash-tolerance/crash-tolerance.test.ts, packages/server-wallet/src/db-admin/db-admin.ts, packages/server-wallet/src/db/migrations/20201014174039_objectives.ts, packages/server-wallet/src/models/__test__/objectives.test.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/models/objective.ts, packages/server-wallet/src/wallet/index.ts
TODO
---
```
Objective.relationMappings.objectivesChannels: join: either `from` or `to` must point to the owner model table and the other one to the related table. It might be that specified table 'channels' is not correct
```
=> Replace individual columns with a single jsonb column in objectives db table, and introduce objectives_channels linker table

packages/server-wallet/src/__chain-test__/direct-funding.test.ts, packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/wallet/index.ts
Addresses https://github.com/statechannels/statechannels/pull/2726#discussion_r510751610.
=> refactor: rename onHoldingUpdated to holdingUpdated, singleChannelOutput event to channelUpdate

packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/store.ts
Only attempt to validate states when they haven't already been seen.
This should fix the  `"Turn number check failed."` errors we've been seeing. We may want to think about how to handle state validation in further detail so we don't run into these errors again.
=> fix: only validate new states

packages/client-api-schema/client-api-schema.api.md, packages/client-api-schema/src/generated-schema.json, packages/client-api-schema/src/methods/CreateChannel.ts, packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts, packages/server-wallet/src/db/migrations/20200915140300_chain_service.ts, packages/server-wallet/src/db/migrations/20201014174041_ledgers.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/protocols/state.ts, packages/server-wallet/src/wallet/__test__/integration/join-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts, packages/wallet-core/src/types.ts, packages/wire-format/src/generated-schema.json, packages/wire-format/src/types.ts
~Created to generate discussion~
Required for multiple ledger channels on the same asset holder.
=> [server-wallet] Passing in ledger channel ID to create channel params

packages/server-wallet/src/wallet/index.ts
I think this is mostly a question of style, but it seems that the current code is unnecessarily eye-catching and unexpected to the majority.
=> refactor: do not bind class methods

packages/server-wallet/src/protocols/process-ledger-queue.ts
Based on a suggestion by @geoknee to always sign the intersection
=> [server-wallet] Simplify ledger funding algorithm

packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/store.ts
The `Store` was preparing outbound messages including objectives and signed states when it did not need to. This refactors that code into the wallet API handlers and has the added benefit of increasing re-usability by other API handler methods (i.e., `createChannel`, `createChannels`, and `createLedgerChannel` all re-use the same logic which re-uses `this.store.createChannel`).
=> refactor: de-couple outgoing messages from Store

packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/models/nonce.ts, packages/server-wallet/src/wallet/__test__/add-signed-state.test.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/store.ts
Ran through some (not all) functions in the `Store` implementation and tried to simplify them using generally reasonable coding standards.
=> [server-wallet] Clean store.ts

packages/server-wallet/src/wallet/index.ts
Adds a method to register bytecode without going to the chain.
=> Add register byte code method

packages/server-wallet/src/wallet/index.ts
Applications can run into confusing situations where a message pertaining to some channels A and B might return an outbound message related to some ledger L funding other channels C and D. In general this isn't too harmful, but if an application is relying on several concurrent streams of messages related to channels it might expect that sequences of exchanges relate to the same set of channels and don't involve channels related to other ledgers.
=> refactor: only process ledgers related to arguments to takeActions

packages/server-wallet/src/utilities/validate-transition.ts, packages/server-wallet/src/wallet/__test__/validate-transition.test.ts
Adds some tests of the validate transition function.
Fixes #2789 .
=> Add validate transition tests

packages/server-wallet/src/wallet/index.ts
Similar to https://github.com/statechannels/statechannels/pull/2818 but for `crankUntilIdle` (I forgot to add it there)
=> fix: only crank channels related to those in the arguments to crankUntilIdle

packages/nitro-protocol/contracts/AssetHolder.sol
These are unecessary, reduce readability and cost gas
=> refactor: remove many SafeMath.add()

packages/server-wallet/src/wallet/index.ts
In an application I have seen us use the mergeMessages API externally which seems like an anti pattern. We should be able to make one call to the wallet and get an outbox prepared. This adds a plural sync channel method for that purpose
=> feat: add syncChannels API method handler on server-wallet

packages/docs-website/docs/implementation-notes/force-move.md, packages/docs-website/docs/protocol-tutorial/understand-channel-storage.md
and remove replicated notes
https://5fa4193bb4fe669a2670c6b0--nitro-protocol.netlify.app/protocol-tutorial/understand-channel-storage
=> docs: simply quote solidity for channel modes

packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts
This will hopefully prevent test flickers https://app.circleci.com/pipelines/github/statechannels/statechannels/10193/workflows/fea71c0a-1f5e-40e4-a48f-cadb3be53423/jobs/50136
=> test: anticipate race condition

packages/server-wallet/src/state-utils.ts, packages/server-wallet/src/utilities/helpers.ts, packages/server-wallet/src/wallet/store.ts
Two small tweaks to make the file smaller and more readable.
=> [server-wallet] Minor improvements to Store.ts code organization

packages/server-wallet/src/utilities/messaging.ts
This was added when debugging once and it made its way to master.
=> fix: remove unnecessary list reversal

packages/server-wallet/src/utilities/helpers.ts, packages/server-wallet/src/wallet/store.ts, packages/wallet-core/src/types.ts
Seems to be something that was missed in the initial implementation.
=> fix: ensure check on closeChannel in pushMessage

packages/server-wallet/package.json, packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/handlers/update-channel.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/models/objective.ts, packages/server-wallet/src/objectives/objective-manager.ts, packages/server-wallet/src/objectives/types.ts, packages/server-wallet/src/protocols/close-channel.ts, packages/server-wallet/src/protocols/state.ts, packages/server-wallet/src/wallet/__test__/integration/create-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/create-ledger-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/index.ts, packages/server-wallet/src/wallet/response-builder.ts, packages/server-wallet/src/wallet/store.ts, packages/server-wallet/src/wallet/wallet.ts, packages/wallet-core/src/serde/wire-format/deserialize.ts
Completes the work started in https://github.com/statechannels/statechannels/pull/2865.
=> Wallet fully converted to use ResponseBuilder

packages/server-wallet/package.json, yarn.lock
Fixes some issues acquiring a connection from the connection pool.
See https://github.com/knex/knex/issues/2820#issuecomment-620628867
=> fix: upgrade knex to 0.21.x

packages/server-wallet/src/wallet/store.ts, packages/server-wallet/src/wallet/wallet.ts
=> refactor: remove usage of DB model in wallet API handler

packages/server-wallet/e2e-test/logger.ts
fixes these types of test failures:
https://app.circleci.com/pipelines/github/statechannels/statechannels/10374/workflows/4b6029dc-d67b-41eb-bfb8-f1987dc0cf8d/jobs/51093
=> test: fix flickering test

.circleci/Dockerfile, .circleci/config.yml, packages/devtools/package.json, packages/jest-gas-reporter/package.json, packages/nitro-protocol/contracts/AssetHolder.sol, packages/nitro-protocol/contracts/CountingApp.sol, packages/nitro-protocol/contracts/ERC20AssetHolder.sol, packages/nitro-protocol/contracts/ETHAssetHolder.sol, packages/nitro-protocol/contracts/ForceMove.sol, packages/nitro-protocol/contracts/NitroAdjudicator.sol, packages/nitro-protocol/contracts/Outcome.sol, packages/nitro-protocol/contracts/Token.sol, packages/nitro-protocol/contracts/TrivialApp.sol, packages/nitro-protocol/contracts/examples/SingleAssetPayments.sol, packages/nitro-protocol/contracts/interfaces/Adjudicator.sol, packages/nitro-protocol/contracts/interfaces/ForceMoveApp.sol, packages/nitro-protocol/contracts/interfaces/IAssetHolder.sol, packages/nitro-protocol/contracts/interfaces/IForceMove.sol, packages/nitro-protocol/contracts/test/TESTAssetHolder.sol, packages/nitro-protocol/contracts/test/TESTAssetHolder2.sol, packages/nitro-protocol/contracts/test/TESTForceMove.sol, packages/nitro-protocol/contracts/test/TESTNitroAdjudicator.sol, packages/nitro-protocol/contracts/test/TestErc20AssetHolder.sol, packages/nitro-protocol/contracts/test/TestEthAssetHolder.sol, packages/nitro-protocol/hardhat.config.ts, packages/nitro-protocol/package.json, yarn.lock
~⚠️ base is not master, see #2893~
Closes #2870
=> [nitro-protocol] Upgrade solidity to 0.7.4

packages/server-wallet/src/__test__/evm-validator.test.ts, packages/server-wallet/src/evm-validator.ts, packages/server-wallet/src/metrics.ts, packages/server-wallet/src/utilities/validate-transition.ts, packages/server-wallet/src/wallet/multi-threaded-wallet/worker.ts, packages/server-wallet/src/wallet/store.ts
=> chore: add sync and async timer for performance metrics

packages/devtools/package.json, packages/jest-gas-reporter/package.json, packages/nitro-protocol/package.json, yarn.lock
=> chore: Remove solc

packages/nitro-protocol/package.json
Fixes the artifact path so it actually contains the contract artifacts
=> fix: fix artifacts path

packages/docs-website/docs/protocol-tutorial/execute-state-transitions.md
I'd like to invite feedback on the wording here. 
For chainId I have assumed #2914 will be merged.
=> docs: add precautions section

packages/nitro-protocol/contracts/AssetHolder.sol, packages/nitro-protocol/test/contracts/AssetHolder/claimAll.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transfer.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts
Preparatory work for adding a `claim` method.
=> refactor: tidy up and dry out AssetHolder.sol a bit

packages/devtools/src/ganache/server.ts, packages/server-wallet/jest/chain-setup.ts, packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts, packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/chain-service.ts
Fixes https://github.com/statechannels/statechannels/issues/2873.
=> Wait for 6 blocks before emitting a chain event

packages/server-wallet/src/db/migrations/20201121100936_objectives_channels_idx.ts
```
gateway=> EXPLAIN ANALYZE (SELECT * FROM objectives_channels  WHERE channel_id = '0x53bdbb78af3ff8c252aa74c04d5e670ec4d44972e076bd9f4ac4a7a69240e87d');
QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------
Gather  (cost=1000.00..6266.91 rows=1 width=146) (actual time=0.643..31.103 rows=1 loops=1)
Workers Planned: 2
Workers Launched: 2
->  Parallel Seq Scan on objectives_channels  (cost=0.00..5266.81 rows=1 width=146) (actual time=12.738..20.625 rows=0 loops=3)
Filter: ((channel_id)::text = '0x53bdbb78af3ff8c252aa74c04d5e670ec4d44972e076bd9f4ac4a7a69240e87d'::text)
Rows Removed by Filter: 62470
Planning Time: 0.052 ms
Execution Time: 31.120 ms
(8 rows)
gateway=> EXPLAIN ANALYZE (SELECT * FROM …
```
=> perf: add channel_id index to objectives_channels

packages/nitro-protocol/src/signatures.ts, packages/nitro-protocol/test/contracts/ForceMove/challenge.test.ts
=> test: reliably generate incorrect signatures

packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/config.ts
=> fix: remove unused stateChannelPrivateKey config entry

packages/server-wallet/src/objectives/objective-manager.ts, packages/server-wallet/src/protocols/close-channel.ts, packages/server-wallet/src/protocols/open-channel.ts
This is a first step towards simplifying the protocol logic. It makes a couple of (hopefully non-controversial) refactors to the ObjectiveManager and to the Protocols.
=> Small refactors to ObjectiveManager and Protocols

packages/nitro-protocol/test/contracts/AssetHolder/transfer.test.ts
In preparation for a refactor of this method.
=> test: record gas consumption in transfer

packages/nitro-protocol/test/contracts/AssetHolder/claimAll.test.ts
The test occasionally times out on circle: https://app.circleci.com/pipelines/github/statechannels/statechannels/10854/workflows/ef1c8bab-082c-4562-9a66-9a3fea128b77/jobs/53157
=> test: increase test timeout for claimAll tests

packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/chain-service/types.ts
Done while trying to get the chain service working in production
=> Logging and configuration improvements to ChainService

packages/server-wallet/src/utilities/validate-transition.ts, packages/server-wallet/src/wallet/__test__/validate-transition.test.ts
I'm hedging my bets about how we tackle #3035. This is a simple and targeted way of fixing one of the items raised by the auditors.
=> fix: check channelNonce during state transition

packages/server-wallet/src/__test__/evm-validator.test.ts, packages/server-wallet/src/evm-validator.ts, packages/server-wallet/src/utilities/validate-transition.ts
To more clearly describe the narrow scope of this function.
=> refactor: rename function

packages/nitro-protocol/src/index.ts, packages/server-wallet/src/__test__/crash-tolerance/crash-tolerance.test.ts, packages/server-wallet/src/__test__/create-and-close-channel/direct-funding.test.ts, packages/server-wallet/src/__test__/create-and-close-channel/fake-funding.test.ts, packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts, packages/server-wallet/src/models/__test__/signing-wallet.test.ts, packages/server-wallet/src/protocols/close-channel.ts, packages/server-wallet/src/wallet/__test__/fixtures/participants.ts
Adds a check before closing a channel to ensure it does not fund any other channel before being closed.
=> [server-wallet] Do not close a channel until no channel is funded by it

packages/nitro-protocol/config/jest/jest.config.js, packages/server-wallet/jest/jest.config.js
- quiets a warning in the console
=> chore: use tsconfig instead of tsConfig in config

packages/client-api-schema/src/__tests__/sample_messages/requests/good.ts, packages/client-api-schema/src/generated-schema.json, packages/client-api-schema/src/methods/CreateChannel.ts, packages/server-wallet/e2e-test/payer/client.ts, packages/server-wallet/src/__chain-test__/directly-funded-channel.test.ts, packages/server-wallet/src/__test__/crash-tolerance/crash-tolerance.test.ts, packages/server-wallet/src/__test__/create-and-close-channel/direct-funding.test.ts, packages/server-wallet/src/__test__/create-and-close-channel/fake-funding.test.ts, packages/server-wallet/src/__test__/create-and-close-channel/ledger-funding.test.ts, packages/server-wallet/src/__test__/test-helpers.ts, packages/server-wallet/src/wallet/__test__/fixtures/create-channel.ts, packages/server-wallet/src/wallet/__test__/integration/create-ledger-channel.test.ts, packages/server-wallet/src/wallet/wallet.ts
Fixes #3060.
This should not be merged until https://github.com/statechannels/the-graph/issues/489 is ready to go.
=> Require Challenge Duration when creating a channel

packages/nitro-protocol/hardhat-deploy/01-eth-asset-holder.ts, packages/nitro-protocol/readme.md
Justification being, we don't yet need to do this and it is expensive. 
Towards #3081
=> do not deploy ETHAssetHolder to mainnet

packages/server-wallet/src/models/channel.ts
=> refactor: swap JS based hashState to use wasm utility

packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/wallet/wallet.ts
Feedback for https://github.com/statechannels/statechannels/pull/3074
=> PR3074 feedback

packages/docs-website/docs/docs/protocol-tutorial/finalize-a-channel-sad.md
These slipped through the net before.
=> docs: replace forceMove with challenge

packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/objectives/types.ts, packages/server-wallet/src/wallet/__test__/integration/update-funding.test.ts, packages/server-wallet/src/wallet/index.ts
=> refactor: change Wallet from object to abstract class

packages/server-wallet/src/protocols/challenge-submitter.ts
Fixes a merge issue that broke `master`
=> Fix incorrect method name

packages/nitro-protocol/package.json
=> fix: correct nitro-protocol dependencies

packages/server-wallet/src/wallet/store.ts
When writing tests that use multiple `TestChannel.insertInto(store,...)` calls, I was seeing a `UniqueViolationError` despite us having code that ostensibly catches and swallows these errors. It seems that the test for catching that error is a little too specific on how the error should look. 
The solution here: 
- Increases consistency (uniform check used everywhere, rather than sometimes inspecting the name and sometimes inspecting the name and extra properties)
- Uses imported type rather than rolling our own (less cruft, higher chance to stay in sync with the library that defines the error)
=> refactor: use instanceof test for UniqueViolationError

packages/server-wallet/src/handlers/__test__/single-app-updater.test.ts, packages/server-wallet/src/protocols/__test__/ledger-manager.test.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-ledger-channel.ts
=> test: rewrite ledger-manager.test.ts (part 1)

packages/server-wallet/src/protocols/ledger-manager.ts, packages/server-wallet/src/wallet/__test__/fixtures/test-channel.ts, packages/server-wallet/src/wallet/__test__/integration/create-ledger-channel.test.ts, packages/server-wallet/src/wallet/__test__/integration/push-message.test.ts, packages/server-wallet/src/wallet/wallet.ts, packages/wallet-core/src/constants.ts, packages/wallet-core/src/index.ts
=> refactor: introduce NULL_APP_DATA const

packages/server-wallet/src/wallet/store.ts
Got caught by another merge issue with #3132  :(
To prevent this in the future I've required merges into `master` to be up to date.
=> Fix Master AGAIN

packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/wallet/wallet.ts
Stacked on top of #3179 . Relevant to https://github.com/statechannels/project-management/issues/28
This method is currently undocumented; its behaviour is not entirely obvious just from the name.
=> docs: add TSDoc to addSigningKey()

packages/server-wallet/src/protocols/ledger-manager.ts, packages/server-wallet/src/wallet/wallet.ts
And reposition error handling code.
This is designed to be a genuine refactor, and to not change the behaviour of the code at all (just make the current behaviour more explicit). 
I believe it is slightly easier to understand / reason about as a result. I also added a comment. 
it is also a bit neater (I don't like very long try/catch blocks)
This grew out of #3169
=> refactor: add comment on handling cranking errors

readme.md
=> docs: add note about checking in reports

packages/server-wallet/src/models/__test__/channel.test.ts
These functions were added in https://github.com/statechannels/statechannels/pull/3256.
This work follows https://github.com/statechannels/statechannels/pull/3267.
=> Add unit tests for channel model funding getters

packages/server-wallet/src/protocols/__test__/defund-channel.test.ts
Sharing common test setup makes it easier to reason about how tests differ from each other. This PR is a refactor.
This work follows https://github.com/statechannels/statechannels/pull/3257
=> Factor out common test setup in DefundChannel tests

.github/ISSUE_TEMPLATE/spike.md
=> chore: create spike template

packages/server-wallet/src/wallet/multi-threaded-wallet/worker.ts
I looked at the logs of the test changed in https://github.com/statechannels/statechannels/pull/3281/commits/fcbd171fb8c4d85aaa909d46cb766860e07498d9.
=> feat: worker threads include threadId in log statements

packages/server-wallet/src/models/channel.ts
Fixes https://github.com/statechannels/statechannels/issues/3269
=> refactor: change isDirectFunded  parameter to be more verbose

packages/server-wallet/src/models/__test__/channel.test.ts, packages/server-wallet/src/models/channel.ts, packages/server-wallet/src/protocols/direct-funder.ts
Fixes https://github.com/statechannels/statechannels/issues/3268
=> refactor: add an explicit type for funding milestones

readme.md
Update readme.md, mention the correct node version we should depend on.
=> ehn:update readme.md to mention the correct node version we should depend on.

packages/server-wallet/src/objectives/objective-manager.ts, packages/server-wallet/src/protocols/challenge-submitter.ts, packages/server-wallet/src/protocols/channel-closer.ts, packages/server-wallet/src/protocols/channel-opener.ts, packages/server-wallet/src/protocols/defund-channel.ts
I'm hoping this will help us maintain a consistent pattern for cranking objectives. Accompanied by some comments on how to approach this in general.
=> chore: introduce Cranker<> type

readme.md
version 2.18.0 does not exist - was a typo
=> chore: change node version to 12.18.0

.github/pull_request_template.md
Update PR template with hyperlink to zenhub pipeline definition. Though the process is to first update `project-management` repo with the proposed template updates, it seems the PR template in 'statechannels` repo has been more recently updated.
Thus once this change is approved, the project management and graph-payments repo will be updated
---
=> chore: update PR template with zenhub pipeline definition

packages/server-wallet/src/objectives/objective-manager.ts, packages/server-wallet/src/wallet/store.ts
and use in ObjectiveManager.
See #3131
=> introduce getAndLockObjective

packages/devtools/src/ganache/server.ts, packages/server-wallet/e2e-test/challenge.test.ts, packages/server-wallet/server-wallet.api.md, packages/server-wallet/src/chain-service/__chain-test__/chain-service.test.ts, packages/server-wallet/src/chain-service/__chain-test__/stress.test.ts, packages/server-wallet/src/chain-service/chain-service.ts, packages/server-wallet/src/config/defaults.ts, packages/server-wallet/src/wallet/wallet.ts
So that we get an error early on if there is a mismatch. 
It is critical that the chain we deposit funds to is the same as the chain specified in the signed `States` that the rest of the wallet deals with.
This PR passes the `networkChainId` wallet config variable down to the `ChainService` constructor. There, it is passed down again to the ethers `JsonRpcProvider` constructor. This should mean an error is thrown (I think asynchronously) if a network mismatch is detected. 
Shortcomings: the constructor arguments aren't super elegant, being an object and a number (I tried putting the number in the object, but I wanted it to be required and that wasn't straightforward given the use of `Partial<>`.)
1.  when we start a ganache server, we now set `_rpcChainId`, so that the ganache reports its …
=> pass chainId to the chain service

.github/pull_request_template.md
Updating PR template to match project management repo
Please explain which reason, if any, why this requires more than one approval.
---
=> chore: update PR template with additional project management checkbox

packages/nitro-protocol/test/contracts/NitroAdjudicator/concludePushOutcomeAndTransferAll.test.ts
The resulting gas costs is useful reference information to store on circle after our tests run. 
---
=> test: insert a case for defunding a single erc20

packages/nitro-protocol/contracts/ETHAssetHolder.sol
"insufficient comparand" is not a good description for failing to meet an equality condition.
=> improve reason string

packages/nitro-protocol/contracts/ForceMove.sol
=> remove duplicated code

packages/interop-tests/src/__test__/interop.test.ts
Fixes failing master: https://app.circleci.com/pipelines/github/statechannels/statechannels/12303/workflows/f1ac840d-43f4-417c-8c7a-c8644fc02cd1/jobs/60243
=> chore: fix interop test import

packages/server-wallet/jest/with-peers-setup-teardown.ts
Store the logs from the `with-peers` test in the artifacts folder on CI and adds some logging.
---
=> Save With-Peers test logs

packages/interop-tests/jest/jest.config.js, packages/interop-tests/package.json, packages/xstate-wallet/scripts/start.js, packages/xstate-wallet/src/chain.ts, packages/xstate-wallet/src/channel-wallet.ts, yarn.lock
With this PR:
- `yarn start` works when executed in `packages/xstate-wallet`
- `yarn test` continues to work when executed in `packages/interop-tests`
Fixes https://github.com/statechannels/statechannels/issues/3408
=> Fix xstate yarn start

packages/xstate-wallet/package.json, packages/xstate-wallet/src/ui/app.tsx, packages/xstate-wallet/src/ui/application-workflow.tsx, packages/xstate-wallet/src/ui/approve-budget-and-fund-workflow.tsx, packages/xstate-wallet/src/ui/close-ledger-and-withdraw.tsx, packages/xstate-wallet/src/ui/confirm-create-channel-workflow.tsx, packages/xstate-wallet/src/ui/enable-ethereum-workflow.tsx, packages/xstate-wallet/src/ui/factory-reset.tsx, packages/xstate-wallet/src/ui/layout.tsx, packages/xstate-wallet/src/ui/stories/application-workflow.stories.tsx, packages/xstate-wallet/src/ui/stories/channel-id.stories.tsx, packages/xstate-wallet/src/ui/stories/confirm-create-channel-workflow.stories.tsx, packages/xstate-wallet/src/ui/stories/enable-ethereum.stories.tsx, packages/xstate-wallet/src/ui/stories/helpers.tsx, packages/xstate-wallet/src/ui/wallet.tsx
Most of the changes were auto-generated on file save. There are two instance where import/no-unresolved eslint rule had to be disabled.
=> chore: lint xstate-wallet tsx files

packages/xstate-wallet/src/integration-tests/closing.test.ts, packages/xstate-wallet/src/integration-tests/helpers.ts, packages/xstate-wallet/src/integration-tests/running.test.ts, packages/xstate-wallet/src/logger.ts, packages/xstate-wallet/src/store/tests/dexie-store.test.ts, packages/xstate-wallet/src/store/tests/memory-store.test.ts, packages/xstate-wallet/src/workflows/application.ts, packages/xstate-wallet/src/workflows/virtual-defunding-as-hub.ts, packages/xstate-wallet/src/workflows/virtual-defunding-as-leaf.ts
This PR is stacked on top of https://github.com/statechannels/statechannels/pull/3454.
This PR is a series of tweaks to reduce logging noise with xstate unit tests.
=> Calm down xstate tests

packages/nitro-protocol/deployment/deploy-test-contracts.ts
```
Deploying AdjudicatorFactory... (cost estimated to be 688895)
Deploying MasterCopy... (cost estimated to be 3417269)
```
=> [ninja-nitro] record infra deployment costs

packages/nitro-protocol/src/index.ts, packages/nitro-protocol/test/contracts/AssetHolder/adjudicatorAddress.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/claim.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/claimAll.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/computeNewAllocation.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/computeNewAllocationWithGuarantee.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/isExternalDestination.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/setOutcome.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transfer.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transferAll.test.ts, packages/nitro-protocol/test/contracts/ERC20AssetHolder/deposit.test.ts, packages/nitro-protocol/test/contracts/ETHAssetHolder/deposit.test.ts, packages/nitro-protocol/test/contracts/ForceMove/_acceptableWhoSignedWhat.test.ts, packages/nitro-protocol/test/contracts/ForceMove/_isAddressInArray.test.ts, packages/nitro-protocol/test/contracts/ForceMove/_recoverSigner.test.ts, packages/nitro-protocol/test/contracts/ForceMove/_validSignatures.test.ts, packages/nitro-protocol/test/contracts/ForceMove/challenge.test.ts, packages/nitro-protocol/test/contracts/ForceMove/checkpoint.test.ts, packages/nitro-protocol/test/contracts/ForceMove/conclude.test.ts, packages/nitro-protocol/test/contracts/ForceMove/requireValidInput.test.ts, packages/nitro-protocol/test/contracts/ForceMove/respond.test.ts, packages/nitro-protocol/test/contracts/ForceMove/storage.test.ts, packages/nitro-protocol/test/contracts/NitroAdjudicator/concludePushOutcomeAndTransferAll.test.ts, packages/nitro-protocol/test/contracts/NitroAdjudicator/pushOutcome.test.ts, packages/nitro-protocol/test/contracts/NitroAdjudicator/pushOutcomeAndTransferAll.test.ts, packages/nitro-protocol/test/contracts/NullApp/nullApp.test.ts, packages/nitro-protocol/test/contracts/TrivalApp/validTransition.test.ts, packages/nitro-protocol/test/contracts/examples/HashLockedSwap/validTransition.test.ts, packages/nitro-protocol/test/contracts/examples/SingleAssetPayments/validTransition.test.ts, packages/nitro-protocol/test/test-helpers.ts
Rename it, make it synchronous, and add some TSDoc annotations!
This function is 
- poorly named (it's plural, when it shouldn't be)
- marked as async (returns a Promise) unnecessarily
- not self-explanatory (as to what it actually does)
This PR fixes all of these. It's a widely used test helper function, so the changeset is large. But it should be easy to understand the changeset by going commit-by-commit. 
---
=> simplify setupContracts function

packages/nitro-protocol/contracts/ninja-nitro/readme.md
=> [ninja-nitro] add a readme.md

packages/browser-wallet/src/channel-wallet.ts, packages/browser-wallet/src/index.ts, packages/browser-wallet/src/integration-tests/helpers.ts
This PR separates UI from the state-channels-logic code
=> Factor our UI functionality from browser-wallet ChannelWallet

readme.md
This little PR adds instructions for installing postgres on linux and configuring for successfully running our test suites.
---
=> Add linux postgres instructions

packages/nitro-protocol/config/jest/jest.gas-benchmarks.config.js, packages/nitro-protocol/gas-benchmarks/benchmark.test.ts, packages/nitro-protocol/gas-benchmarks/fixtures.ts, packages/nitro-protocol/gas-benchmarks/gas.ts, packages/nitro-protocol/gas-benchmarks/readme.md, packages/nitro-protocol/gas-benchmarks/vanillaSetup.ts, packages/nitro-protocol/package.json
https://www.notion.so/statechannels/Improved-gas-benchmarking-in-nitro-protocol-d14938f9671a48588e6974462e9ffb00
=> Improved gas benchmarking 

packages/nitro-protocol/test/contracts/AssetHolder/claim.test.ts, packages/nitro-protocol/test/contracts/AssetHolder/transfer.test.ts, packages/nitro-protocol/test/contracts/ERC20AssetHolder/deposit.test.ts, packages/nitro-protocol/test/contracts/ForceMove/challenge.test.ts, packages/nitro-protocol/test/contracts/ForceMove/conclude.test.ts, packages/nitro-protocol/test/contracts/NitroAdjudicator/concludePushOutcomeAndTransferAll.test.ts, packages/nitro-protocol/test/test-helpers.ts
Not sure how they got introduced to `master` but this fixes the listing errors causing it to fail.
=> Fix Linting Errors

packages/nitro-protocol/gas-benchmarks/benchmark.test.ts, packages/nitro-protocol/gas-benchmarks/fixtures.ts, packages/nitro-protocol/gas-benchmarks/gas.ts, packages/nitro-protocol/gas-benchmarks/vanillaSetup.ts
=> Add a gas benchmark for the sad path defunding of a directly funded channel

packages/nitro-protocol/gas-benchmarks/benchmark.test.ts
It simply funds someOtherChannel with tokens.
Also remove that step from tests that work with ETH only.
=> introduce addResidualTokenBalance fn

packages/browser-wallet/deployment/deploy.ts, packages/browser-wallet/src/chain.ts, packages/browser-wallet/src/tests-with-chain/chain.test.ts, packages/browser-wallet/src/utils/contract-utils.ts
Gets the browser wallet building and its (unskipped) tests passing.
⚠️ base not master. Towards #3624
=> Update browser wallet to singleton contract architecture

packages/nitro-protocol/test/contracts/MultiAssetHolder/claim.test.ts
⚠️ base not master. Towards #3624
=> add claim.test.ts

packages/nitro-protocol/contracts/MultiAssetHolder.sol, packages/nitro-protocol/gas-benchmarks/gas.ts
... a small refactor to save a little gas.
`yarn test:gas`
=> Remove duplicate call to abi.encode

packages/nitro-protocol/contracts/MultiAssetHolder.sol, packages/nitro-protocol/contracts/interfaces/IMultiAssetHolder.sol, packages/nitro-protocol/gas-benchmarks/gas.ts
Just cleaning up this old bit of wiring that we no longer need.
=> Do not return outcome from transfer method

packages/nitro-protocol/gas-benchmarks/gas.ts, packages/nitro-protocol/hardhat.config.ts, packages/nitro-protocol/package.json, patches/hardhat+2.5.0.patch, yarn.lock
We currently benchmark against the Berlin hardfork, which will become out-of-date (on Ethereum mainnet) soon. The next hardfork is London, and this PR updates the local blockchain used for benchmarking gas so we can get more accurate numbers. 
This is pretty important for any gas optimization work, since this hardfork includes some significant changes to how gas is computed. More information [here](https://medium.com/ethereum-cat-herders/london-upgrade-overview-8eccb0041b41). 
Pre-London, there were generous gas refunds of 15000 gas available for clearing EVM storage slots. These have been reduced to 4800 gas. You can see from the checked-in `gas.ts` file that the transactions that benefit from a refund (the ones that clear all of the funds in the asset holder) have each increased by …
=> Update gas benchmarks to reflect London hardfork

packages/nitro-protocol/contracts/MultiAssetHolder.sol, packages/nitro-protocol/gas-benchmarks/gas.ts
When reviewing the security aspects of this, it is important to understand what changes are made to storage variables. These were some code modifications I made along the way while understanding storage related changes. Some of them come with minor gas savings.
In addition, I re-ordered `_claim` & `_transfer` according to the order in which they are called in `MultiAssetHolder`.
=> Code suggestions

packages/server-wallet/e2e-testing/readme.md, packages/server-wallet/e2e-testing/scripts/load-generator.ts, packages/server-wallet/e2e-testing/wallet-load-node.ts
=> Add readme for stress tests

packages/nitro-protocol/contracts/StatusManager.sol, packages/nitro-protocol/contracts/interfaces/IStatusManager.sol
This silences a compiler warning.
=> add license identifiers

packages/nitro-protocol/test/test-helpers.ts
=> remove defunct test helper

packages/nitro-protocol/tsconfig.json
If you run `npm pack` on master in the nitro-protocol directory, we see the inclusion of lots of stuff we don't need: 
```
npm notice 
npm notice 📦  @statechannels/nitro-protocol@0.17.1
npm notice === Tarball Contents === 
npm notice 1.7kB   contracts/CountingApp.sol                                                              
npm notice 18.7kB  contracts/examples/EmbeddedApplication.sol                                             
npm notice 3.1kB   contracts/examples/HashLockedSwap.sol                                                  
npm notice 3.6kB   contracts/examples/SingleAssetPayments.sol                                             
npm notice 37.3kB  contracts/ForceMove.sol                                                                
npm notice 8.5kB …
```
=> Do not include unecessary files in build output of nitro-protocol

packages/nitro-protocol/contracts/MultiAssetHolder.sol, packages/nitro-protocol/contracts/NitroAdjudicator.sol, packages/nitro-protocol/gas-benchmarks/benchmark.test.ts, packages/nitro-protocol/gas-benchmarks/fixtures.ts, packages/nitro-protocol/gas-benchmarks/gas.ts
fixes #3733 
~warning: these benchmarks do not assert on correct behaviour. While we wait for other tests to do that, these numbers should be taken with a grain of salt. They seem a little too good to be true to me.~
=> fix gas benchmarks
